### PR TITLE
feat(meta): produce sequential number epoch in debug mode

### LINKED ISSUE #3898: meta: produce sequential number epoch in debug mode
e.g. 0, 1, 2, 3, ... instead of physical time, so that debug could be easier.

### PR DESCRIPTION
**Pull request by HuaHuaY**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As the title.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #3898

### CODE REVIEW

**Comment by TennyZhuang** [comment]
This may make many features unavailable on debug mode, e.g. temporal filter, flashback query, weak -1

**Comment by TennyZhuang** [comment]
Don’t do many magic thing in debug mode. If you really want it, please add a feature.

**Comment by skyzh** [comment]
Indeed I opened this issue -> https://github.com/singularity-data/risingwave/issues/3898

Maybe we can make it a feature (or cli flag to enable). I think it would be good for both debugging and testing time-based code path.

**Comment by HuaHuaY** [comment]
How about making `Display::fmt` of `Epoch` prettier instead of adding a feature?

**Comment by BugenZhao** [comment]
As we already encapsulated a struct of `Epoch` for current and previous epoch numbers, I think it's also okay to add a new field of monotonically increasing "epoch sequence" for debugging purposes. The mapping from this `seq` to the epoch number is unnecessary, as we only want to recognize which epoch is later more easily in most cases. 🤣

**Pull request closed without merging**
