### PR TITLE
fix(storage): disable stalled stream protection for aws-sdk-s3

### LINKED ISSUE #16169: bug(storage): "minimum throughput" error causes compaction failure
### Describe the bug

The compaction tasks fail and there are error logs like the following one in the compactor's logs.

### Error message/log

```text
2024-04-05T21:25:41.751263809Z ERROR risingwave_object_store::object: streaming_read_read_bytes failed error=Internal error: streaming error: minimum throughput was specified at 1 B/s, but throughput of 0 B/s was observed
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

https://github.com/awslabs/aws-sdk-rust/blob/924d50e84a83e9af72d6c6d777754e86501b5230/sdk/aws-smithy-runtime/src/client/http/body/minimum_throughput/http_body_0_4_x.rs#L78

### PR DESCRIPTION
**Pull request by MrCroxx**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

aws-sdk-s3 introduced stalled stream protection, which calculates the throughput in a window and raises an error if it is below the threshold. In RW, compactor use stream read to read sstables to be merged, but some iterators may hang for a long time which may triggered the check error.

fix #16169 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by Li0k — APPROVED** [review]

**Comment by yuhao-su** [comment]
Is it expected to have some iterators may hang for a long time?

**Comment by MrCroxx** [comment]
> Is it expected to have some iterators may hang for a long time?

Yes. But the default check window is 1s, which is too short.

**Comment by yuhao-su** [comment]
There are more than one `aws_sdk_s3::config::Builder::from`. Is it enough to dis able this for just one of them?

**Review by yuhao-su — APPROVED** [review]

**Comment by MrCroxx** [comment]
https://buildkite.com/risingwavelabs/pull-request/builds/46609#018eb1c4-9488-4ac2-8bee-09a48aa000e1

cc @wangrunji0408

**Pull request merged**
