### PR TITLE
feat(source): support schemaless debezium json message

### PR DESCRIPTION
**Pull request by waruto210**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

- support schema-less debezium json message

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Connector (sources & sinks)

### Release note

Add a property `debezium_json.schema_include` for creating `debezium_json` source, it's default value is `true`, and the user should set it to `false` if the debezium_json message does not include the schema.

```sql
create materialized source s14 (
  id integer,
  name varchar,
  is_adult bool,
  email varchar,
  PRIMARY KEY (id)
) with (
  connector = 'kafka',
  topic = 'debezium_log_schemaless',
  debezium_json.schema_include = 'false',
  properties.bootstrap.server = '127.0.0.1:29092'
) row format debezium_json;
```

## Refer to a related PR or issue link (optional)
#6094

### CODE REVIEW

**Comment by waruto210** [comment]
@neverchanje please review the interface change.

**Comment by neverchanje** [comment]
I don't think we should provide users an option, especially if we don't use the field at all.

if json["schema"] != null {
  if json.get("payload") == null {
    log.error("invalid debezium json message: {}", json);
    return;
  }
  json = json["payload"]
}
You can address this simply by peaking if there's a field named "schema", if there is, then extract the payload body.

**Comment by waruto210** [comment]
> 

There is a corresponding option `value.converter.schemas.enable` in Debezium Kafka Connect, so it makes sense to let the user provide this option. And implement the logic you wrote would make the code a little bit ugly and harm performance.

**Comment by waruto210** [comment]
> I don't think we should provide users an option, especially if we don't use the field at all.
> 
> ```
> if json["schema"] != null {
>   if json.get("payload") == null {
>     log.error("invalid debezium json message: {}", json);
>     return;
>   }
>   json = json["payload"]
> }
> ```
> 
> You can address this simply by peaking if there's a field named "schema", if there is, then extract the payload body.

There is a corresponding option named `value.converter.schemas.enable` in Debezium Kafka Connect, so it makes sense to let the user provide this option. And implement the logic you wrote would make the code a little bit ugly and harm performance.

**Comment by waruto210** [comment]
> I don't think we should provide users an option, especially if we don't use the field at all.
> 
> ```
> if json["schema"] != null {
>   if json.get("payload") == null {
>     log.error("invalid debezium json message: {}", json);
>     return;
>   }
>   json = json["payload"]
> }
> ```
> 
> You can address this simply by peaking if there's a field named "schema", if there is, then extract the payload body.

In addition, if we want to support avro's schemaless encoding, we also need users to set an option.

**Comment by neverchanje** [comment]
> There is a corresponding option named value.converter.schemas.enable in Debezium Kafka Connect, so it makes sense to let the user provide this option.

It makes sense as a library, but not as a user-facing product.

> And implement the logic you wrote would make the code a little bit ugly and harm performance.

Yeah it will add one check to a field, I believe the overhead will not be too high.

**Comment by tabVersion** [comment]
To make the product simple, I do not agree with the proposal. We can make the parser adapt to the data by adding a state.

**Pull request closed without merging**
