### PR TITLE
fix(cache): fix entry drop in channel

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

as https://github.com/risingwavelabs/risingwave/issues/6617 mentioned, the entry may drop inside `Sender::send` and would not return an `Err` , which would cause a deadlock.
So We do not send entry by channel, even if it would cause another hash-table query.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by BugenZhao** [comment]
Does this mean there'll be no single-flight any more? I'm afraid this will significantly increase the cost of accessing the object store.

**Comment by Little-Wallace** [comment]
> ~Does this mean there'll be no single-flight any more? I'm afraid this will significantly increase the cost of accessing the object store.~

No. But It would increase the cost of accessing the LRU-cache.

**Comment by BugenZhao** [comment]
> But It would increase the cost of accessing the LRU-cache.

Makes sense!

**Review by BugenZhao — APPROVED** [review]
LGTM. Please also fix the benches. :)

**Review by hzxa21 — APPROVED** [review]
LGTM

**Comment by hzxa21** [comment]
I think we also need to merge this fix to the [v0.1.14-rc](https://github.com/risingwavelabs/risingwave/tree/v0.1.14-rc) branch.

**Pull request merged**
