### PR TITLE
fix: quick fix for hummock compile error

### PR DESCRIPTION
**Pull request by nanderstabel**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

as title

## Checklist

~~- [ ] I have written necessary rustdoc comments~~
~~- [ ] I have added necessary unit tests and integration tests~~
[x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#5922

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
LGTM, may directly remove the comments.

**Comment by nanderstabel** [comment]
> LGTM, may directly remove the comments.

Will do 👍

**Comment by skyzh** [comment]
... and I would prefer name the function as `compaction_test_only_xxxxx`, probably people can avoid mistakenly using them.

**Comment by nanderstabel** [comment]
Ok I've changed that as well. @wenym1 can probably come up with a better name later?

**Pull request merged**
