### PR TITLE
fix(metrics): clean streaming actor metrics after dropped (p1)

### PR DESCRIPTION
**Pull request by MrCroxx**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Introduce `ManagedMetricVec<T>` and its wrapper types.

Features:
- Metric label values can be lazily initialized like the original `MetricVec<T>` wrapper types.
- Metric label values can be automatically removed after `ManagedMetricVec<T>` is dropped.

Pros:
- The lifetime of value-labeled metrics can be easily managed.
- The API is similar to the origin wrappers, which can easily replace the origin types with minimal effort.

Cons:
- This implementation relies on some unexported types in lib `rust-prometheus`. So I forked it in my repo and will send a PR to TiKV org to see if they want to merge it.

Notes:

Unlike those in batch tasks, metrics in streaming tasks have much more flexible label types. This makes creating macros like in PR #9378 harder and the readability of the macros is worse. 

Which implementation do you like better? @BugenZhao @ZENOTME @Gun9niR @fuyufjh 

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by MrCroxx** [comment]
@BugenZhao @ZENOTME @Gun9niR @fuyufjh PTAL and feel free to comment.

**Comment by ZENOTME** [comment]
LGTM! 

> So the benefit of using closure is we can use a macro to generate these create_collector_for_xxx?
>> Also we don't need to maintain vector for different metrics label. It make us easy to extend more executor metrics with less code.

Actually the reason of introducing closure and macro is that I can't find a way to maintain vector clearly.

ManagedMetricVec<T> is a smart way to solve this problem. Maybe the batch can use this way too.🤣 Seems it's more clear than closure and macro.@Gun9niR

**Comment by BugenZhao** [comment]
My ideas:

Although there could be `Arc` in an `impl Metric`, let's assume a `Metric`, derived from a `MetricVec` with specified labels, is always being mutually owned by some component in our system.

So what about wrapping the `Metric` instead? Then...
- Since the labels have been filled ahead of time, executors can directly call `inc` on it instead of calling `with_label_values(&[&table_id_str, &actor_id_str])` every time.
- Dropping a wrapped `Metric` cleans up the metric belonging to this label, with `remove_label_values`.

**Comment by Gun9niR** [comment]
Can we make sure the metrics are deleted only after Prometheus collects them?

**Comment by MrCroxx** [comment]
> Can we make sure the metrics are deleted only after Prometheus collects them?

Nice catch. Can be an issue. 🤔

**Comment by Gun9niR** [comment]
> Can we make sure the metrics are deleted only after Prometheus collects them?

This is the most important reason for using a closure, besides enabling macro-generated getters: we need to record the labels associated with each metric. `HashMap<?, Vec<String>>` is not an option, because key type can not be determined. So I think closure is a convenient (but not so efficient and plain) way to keep this information.

**Comment by fuyufjh** [comment]
Hi, any updates? It seems to be inactive for a while

**Comment by MrCroxx** [comment]
> Hi, any updates? It seems to be inactive for a while

Sorry for the delay. I was working on another issue. I'll fix it tomorrow.

**Comment by MrCroxx** [comment]
I solved the problem with a `to_remove` list and self-managedgeneric struct `ManagedMetricVec<T>`, but #9984 made the problem harder in which label-valued can be shared and `to_remove` list is not enough if the user doesn't use it right. I'll refactor this with a `to_remove` reference map to track them.

**Pull request closed without merging**
