### PR TITLE
feat(risedev): deprecate zookeeper & use kraft mode for kafka service

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

...so that one service is reduced when launching Kafka with RiseDev. However, the `zookeeper` service is still kept in `risedev.yml` as a dummy service for the backward compatibility test.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by TennyZhuang** [comment]
ref #3623

**Review by xxchan — APPROVED** [review]
LGTM

**Comment by BugenZhao** [comment]
> the `zookeeper` service is still kept in `risedev.yml` as a dummy service for the backward compatibility test

It started to run without problem but failed likely due to a bug. Opened an issue: https://github.com/risingwavelabs/risingwave/issues/16543

**Comment by kwannoel** [comment]
Is kraft mode backwards compatible? It could break the backwards compatibility test suite.

**Comment by kwannoel** [comment]
> > the `zookeeper` service is still kept in `risedev.yml` as a dummy service for the backward compatibility test
> 
> It started to run without problem but failed likely due to a bug. Opened an issue: #16543

Don't quite get it. So the bug is independent of this PR? But seems it doesn't happen before it.

**Comment by BugenZhao** [comment]
> > > the `zookeeper` service is still kept in `risedev.yml` as a dummy service for the backward compatibility test
> > 
> > 
> > It started to run without problem but failed likely due to a bug. Opened an issue: #16543
> 
> Don't quite get it. So the bug is independent of this PR? But seems it doesn't happen before it.

I don't think replacing zookeeper with kraft could result in any changes to user-facing behavior. 😕

**Comment by kwannoel** [comment]
> > > > the `zookeeper` service is still kept in `risedev.yml` as a dummy service for the backward compatibility test
> > > 
> > > 
> > > It started to run without problem but failed likely due to a bug. Opened an issue: #16543
> > 
> > 
> > Don't quite get it. So the bug is independent of this PR? But seems it doesn't happen before it.
> 
> I don't think replacing zookeeper with kraft could result in any changes to user-facing behavior. 😕

I think it's less of a bug, more like a breaking change to the backwards-compatibility test framework. I'm still thinking of how we can mitigate that.

**Comment by kwannoel** [comment]
I suppose the reason for the breakage is that we do the following in backwards compat test:
1. start cluster in old rw version with kafka (zookeeper)
2. Stop cluster
3. restart cluster in new rw version with kafka (kraft)

**Comment by kwannoel** [comment]
Perhaps one solution is to use kafka in a user-managed way instead for backwards compat test.

**Comment by kwannoel** [comment]
But backwards-compat-test should pass before this gets merged, otherwise we can't catch backwards compat errors after this PR.

**Comment by BugenZhao** [comment]
> So we end up testing compat from kafka zookeeper -> kafka kraft

This makes sense. 👍 It appears that it requires several manual steps for migration, otherwise the data from old Kafka cannot be accessed.

https://docs.confluent.io/platform/current/installation/migrate-zk-kraft.html#step-4-enable-migration-on-the-brokers

**Comment by BugenZhao** [comment]
> Perhaps one solution is to use kafka in a user-managed way instead for backwards compat test.

Actually there's a Kafka service running in the CI environment which can be accessed by `kafka:29093`. It's not a common practices to start Kafka again with RiseDev as far as I know about other CI scripts.

https://github.com/risingwavelabs/risingwave/blob/28c3714e037ad62df5c99859b05bef4d464c9532/ci/docker-compose.yml#L265-L277

Tests that start Kafka with RiseDev:
- `backfill-test.sh`
- `backwwards-compat-tests`

**Comment by BugenZhao** [comment]
> Tests that start Kafka with RiseDev:

I've also had an attempt to change them to use `kafka:29093`, but it then broke `run_local.sh`. I believe we should eventually adopt the idea in https://github.com/risingwavelabs/risingwave/issues/12451#issuecomment-2051861048 to them, however it's not applicable to `backwards-compat-test` since the old version of RiseDev won't support that.

**Comment by kwannoel** [comment]
> I've also had an attempt to change them to use kafka:29093, but it then broke run_local.sh. I believe we should eventually adopt the idea in https://github.com/risingwavelabs/risingwave/issues/12451#issuecomment-2051861048 to them, however it's not applicable to backwards-compat-test since the old version of RiseDev won't support that.

Yeah I think user-managed kafka seems most practical way to support it.

**Comment by xxchan** [comment]
I think the root cause is backwards-compat-tests relies on (different versions of) RiseDev. TBO I feel this is not very good. 😕 A similar issue before is #15448.

Some thoughts:
- We just need to kill and restart RisingWave nodes, but not external services. But one benefit of RiseDev is to start external services locally. Otherwise to run locally we need to manually start them.
- Maybe we can just use the latest RiseDev
  - I think the main concern is old RisingWave cannot be compiled and started by latest RiseDev, e.g., changes in CLI args, compile options. But I think the changes should be very rare though. 
- So another idea is to just use the raw commands e.g., `cargo run`. When there are changes, we can also use different commands for different versions.
- A maybe bigger issue: When we deprecate etcd, how will we test it? Then old versions only support etcd and new versions only support sql 😄

**Comment by xxchan** [comment]
> I've also had an attempt to change them to use `kafka:29093`, but it then broke `run_local.sh`

For the quickest solution, I think sacrificing `run_local` is acceptable.

**Comment by BugenZhao** [comment]
Updated based on #16584. No changes on backwards-compat tests any more. Also removed the dummy service for zookeeper.

**Review by stdrc — APPROVED** [review]
LGTM

**Comment by kwannoel** [comment]
> I think the root cause is backwards-compat-tests relies on (different versions of) RiseDev. TBO I feel this is not very good. 😕 A similar issue before is #15448.
> 
> Some thoughts:
> - We just need to kill and restart RisingWave nodes, but not external services. But one benefit of RiseDev is to start external services locally. Otherwise to run locally we need to manually start them.
> - Maybe we can just use the latest RiseDev
>   - I think the main concern is old RisingWave cannot be compiled and started by latest RiseDev, e.g., changes in CLI args, compile options. But I think the changes should be very rare though. 
> - So another idea is to just use the raw commands e.g., `cargo run`. When there are changes, we can also use different commands for different versions.
> - A maybe bigger issue: When we deprecate etcd, how will we test it? Then old versions only support etcd and new versions only support sql 😄

Changes in CLI options still do happen. Actually when backwards compat tests were initially implemented, they used the latest risedev. After encountering a backwards compat test failure due to this cli options breakage, I switched it to use risedev, with the same version as the RW binary version.

Cargo run also works, but its a lot more manual to switch and maintain the cli options. For backwards compat test with a specific risedev version tagged, we can simply maintain the risedev config. Which is just a few lines.

For sql backend, once we make it default and it is stable, we can switch to test backwards compat between sqlbackend version. Backwards compat between etcd and sqlbackend is too complicated to maintain and its a one off migration.

**Pull request merged**
