### PR TITLE
refactor: migrate all from_to_bytes to value_encoding

### PR DESCRIPTION
**Pull request by waruto210**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

- migrate all `from_to_bytes` to `value_encoding`

## Checklist

- [x] I have written necessary rustdoc comments
~- [ ] I have added necessary unit tests and integration tests~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

#4672

### CODE REVIEW

**Comment by BugenZhao** [comment]
Long expected 🚀🚀🚀

**Comment by waruto210** [comment]
There is one thing to be aware of.
In the implementation of `bytes::Buf`, some assertion is used, so if the bytes buf provided for deserialization is in the wrong format, the program may panic directly.

**Comment by BugenZhao** [comment]
> so if the bytes buf provided for deserialization is in the wrong format, the program may panic directly.

Yes. This is very interesting and I can't find a `try_` interface in `bytes`. Maybe we always need to manually test if `buf.remaining() > size_of::<T>::()` before deserializing? 🤔

**Review by BugenZhao — APPROVED** [review]
LGTM 🥰

**Comment by BugenZhao** [comment]
> > so if the bytes buf provided for deserialization is in the wrong format, the program may panic directly.
> 
> Yes. This is very interesting and I can't find a `try_` interface in `bytes`. Maybe we always need to manually test if `buf.remaining() > size_of::<T>()` before deserializing? 🤔

As we have no way to handle the `Error` if the format is wrong and this shouldn't happen normally, I think directly panicking might also be okay.

**Pull request merged**
