### PR TITLE
feat(udf): show panic message in Rust UDF

### LINKED ISSUE #16125: udf: show panic message in Rust UDF
### Describe the bug

When a Rust UDF panics inside, user can only see a backtrace but not the panic message. It should be printed to help debugging.

### Error message/log

_No response_

### To Reproduce

```sql
dev=> create function int_42() returns int language rust as $$
    fn int_42() -> i32 {
        panic!("gg");
    }
$$;
CREATE_FUNCTION
dev=> select int_42();
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Expr error
  2: error while executing at wasm backtrace:
    0: 0xd31cb - <unknown>!<wasm function 2059>
    1: 0xd2f8b - <unknown>!<wasm function 2050>
    2: 0xd2ebe - <unknown>!<wasm function 2049>
    3: 0xd225e - <unknown>!<wasm function 2037>
    4: 0xd21c4 - <unknown>!<wasm function 2036>
    5: 0xd2895 - <unknown>!<wasm function 2044>
    6: 0xd8276 - <unknown>!<wasm function 2131>
    7: 0x2808 - <unknown>!<wasm function 31>
    8: 0x47f0 - <unknown>!<wasm function 58>
    9: 0x2831 - <unknown>!<wasm function 32>
   10: 0x15b75 - <unknown>!<wasm function 174>
   11: 0x2a51 - <unknown>!<wasm function 33>
   12: 0xe3e1b - <unknown>!<wasm function 2243>
  3: wasm trap: wasm `unreachable` instruction executed
```

### Expected behavior

panic message `gg` should be included in the error message.

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

Current main branch.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR resolves #16125. Previously the stdio of WASM UDF container is inherited from the parent process (i.e. RisingWave), causing the panic messages to be printed in the RisingWave log but not included in the error message. We change this behavior in arrow-udf-wasm v0.2.1 ([code](https://github.com/risingwavelabs/arrow-udf/commit/cbd0dc34c8bccb572c0be3c6398e5d891918b202)). Now stdio is no longer inherited. Instead, we use in-memory files to collect stdout and stderr of user functions. These information will be included as context of error when user function exits abnormally.

```sql
dev=> create function panic() returns int language rust as $$
    fn panic() -> i32 {
        panic!("gg")
    }
$$;
CREATE_FUNCTION
dev=> select panic();
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Expr error
  2: --- stdout

--- stderr
thread '<unnamed>' panicked at src/lib.rs:5:9:
gg
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  3: error while executing at wasm backtrace:
    0: 0xd41f4 - <unknown>!<wasm function 2068>
    1: 0xd3fb4 - <unknown>!<wasm function 2059>
    ...
```

This PR also bumps wasmtime version from 18 to 19.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]

**Comment by wangrunji0408** [comment]
CI failed because it found "panicked at" in the log. However, this is expected in this test case. Should we remove the check or add this case to a whitelist somehow? 😇

**Comment by BugenZhao** [comment]
The multiline error message does not look good enough to me. 😕 Is it possible to somehow extract the panic message from the WASM app, by catching it or overriding the `panic` hook?

**Comment by wangrunji0408** [comment]
> The multiline error message does not look good enough to me. 😕 Is it possible to somehow extract the panic message from the WASM app, by catching it or overriding the `panic` hook?

But I think we should provide the panic context as much as possible for users to debug their code, even through it may not look pretty. Only panic message and no backtrace is not enough. 🤔

**Comment by BugenZhao** [comment]
> > The multiline error message does not look good enough to me. 😕 Is it possible to somehow extract the panic message from the WASM app, by catching it or overriding the `panic` hook?
> 
> But I think we should provide the panic context as much as possible for users to debug their code, even through it may not look pretty. Only panic message and no backtrace is not enough. 🤔

What about providing the details via logs? The error message can be made more concise and precise, while still preserving the necessary details for debugging in the logs.

**Comment by xxchan** [comment]
I feel you are talking about different things. The implementation of this is already "catching the panic message" (it is just stderr (And btw I think this won't work if the udf is compiled to pure wasm without wasi)). The point is we can expose it in different ways (e.g., with methods like `.stderr()`, `.stdout()` for the WasmError. 

If we want prettier error message, maybe we can (at the top level) visit the error chain and use a specialized format. 🤡

**Comment by wangrunji0408** [comment]
What about changing the error message to the following? This way it has a concise reason with enough details. 🤡

```
Caused by these errors (recent errors listed first):
  1: Expr error
  2: user code in wasm exited unexpectedly
--- stdout

--- stderr
thread '<unnamed>' panicked at src/lib.rs:5:9:
gg
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---
  3: error while executing at wasm backtrace:
    0: 0xd41f4 - <unknown>!<wasm function 2068>
    1: 0xd3fb4 - <unknown>!<wasm function 2059>
    ...
```

> What about providing the details via logs? The error message can be made more concise and precise, while still preserving the necessary details for debugging in the logs.

Actually what this PR does is to move details from logs into errors. These are necessary information for users to debug their code, while the logs are for us to debug RisingWave itself.

> The point is we can expose it in different ways (e.g., with methods like .stderr(), .stdout() for the WasmError.

Not all kinds of wasm errors contain stdout & stderr. And the underlying library (arrow-udf-wasm) has provided error in anyhow. 🤡

> And btw I think this won't work if the udf is compiled to pure wasm without wasi

Yes. But we assume that user code is built on our UDF SDK and we do not support other customization.

**Pull request merged**
