### PR TITLE
fix(storage):  fix accessing gcs env credential

### PR DESCRIPTION
**Pull request by wcy-fdu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
as title.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
~~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
~~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by lukeraphael** [comment]
May I check why is `credential path` preferred over `credential`? This requires the credential files to be mounted to the Kubernetes pods.

**Comment by wcy-fdu** [comment]
> May I check why is `credential path` preferred over `credential`? This requires the credential files to be mounted to the Kubernetes pods.

cc @Xuanwo

**Comment by Xuanwo** [comment]
by the way, opendal will load credential from GOOGLE_APPLICATION_CREDENTIALS by default if no credential has been specified. So I believe the code here is not needed.

**Comment by lmatz** [comment]
Plz also make a PR to v0.19.0-RW if we intend to support GCS in the release v0.19, thank you!

**Comment by wcy-fdu** [comment]
Close after gcp test pipeline is done. 
Will reopen this pr if necessary.

**Pull request closed without merging**
