### PR TITLE
fix(risedev): bump kafka version

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title. The old URL is invalid now. Also do not download kafka for e2e without sources.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Review by neverchanje — APPROVED** [review]

**Review by fuyufjh — APPROVED** [review]

**Review by huangjw806 — APPROVED** [review]

**Comment by BugenZhao** [comment]
The speed of `archive.apache.org` is too slow. 😅 I've switched to bump the Kafka version.

**Comment by skyzh** [comment]
Probably you should use some way to force existing users to upgrade. I'll work on a new release of risedev to make things easier.

**Comment by BugenZhao** [comment]
> Probably you should use some way to force existing users to upgrade. I'll work on a new release of risedev to make things easier.

How about including the version number in the directory name?

**Comment by skyzh** [comment]
> > Probably you should use some way to force existing users to upgrade. I'll work on a new release of risedev to make things easier.
> 
> How about including the version number in the directory name?

That's a great idea, better than I thought.

**Pull request merged**
