### PR TITLE
feat(streaming): use refill cache on write policy for streaming hash_…

### PR DESCRIPTION
**Pull request by KeXiangWang**
…join

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Currently, when insert a row in streaming hash join actor, we do not cache it.
In this pr, we start to refill cache when insert a row.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Related PR

https://github.com/risingwavelabs/risingwave/pull/3983

### CODE REVIEW

**Comment by KeXiangWang** [comment]
Here are some points worth mentioning.
 
1. why refilling cache when writing is valuable: 

Assume we have stream A as the left side and stream B as the right side in a join actor.

When join receives a new key from stream A, it needs to read from the table of B to match rows. If we refill the cache when writing, then this read from A will be a cache hit(if not evicted). If we do not refill, we need to read once from the remote storage, which takes a long time.

2. why we do not cache when writing in the past:

The point is that if we want to cache it when inserting a row, we need to first read once from the remote to fetch the previous result and then merge the old result with the new row. Since we still need to read from the remote compared with not refilling, refilling the cache when writing only makes this read happens when writing instead of when matching. And if the newly inserted row is never matched by the keys from another side, this refilling is a waste of memory.

3. why we change our idea now to refill when writing:

As this [PR](https://github.com/risingwavelabs/risingwave/pull/7339) is merged, the bloom filter has a much lower false positive. It means if a key does not exist in the table, the read operation will be finished much more quickly because it has fewer possibilities to read the data block. And the bloom filter is cached in memory. As a result, reading a non-existed key will be almost a memory operation. But reading an existing key is still a remote IO operation. So refilling when writing policy outperforms now.

4. why not make this a configurable policy?

We do not want to expose this to users. It's a burden for users to understand.

5. Does refilling the cache when writing always outperform?

No, it performs well on datasets like nexmark, which has good locality, which means the rows written from one stream will quickly be matched by the keys from another stream. But for some datasets that have no locality, like TPCH, not refilling is better.

For now, since we take nexmark as the main benchmark dataset and streaming datasets usually have some locality, we use the refilling of the cache when writing policy. 

Ideally, we should be able to adjust this policy automatically based on dataset patterns.

**Review by BugenZhao — COMMENTED** [review]
The code logic LGTM!

**Comment by lmatz** [comment]
Sort of confused as `why we change our idea now to refill when writing` seems to not address `this refilling is a waste of memory`. 
I mean the waste is much cheaper due to #7339, but still a waste?

**Comment by KeXiangWang** [comment]
> Sort of confused as `why we change our idea now to refill when writing` seems to not address `this refilling is a waste of memory`. I mean the waste is much cheaper due to #7339, but still a waste?

Yes, it may still waste memory, especially if the inserted key is not matched by the keys from another side, before being evicted. But for dataset like nexmark, the inserted key should be touched quickly. In this secnario, it would not be a waste.

**Review by chenzl25 — APPROVED** [review]
LGTM, thanks for your elaboration.

**Review by hzxa21 — APPROVED** [review]
Thanks for the efforts! LGTM

**Comment by yuhao-su** [comment]
The refilling is most valuable when inserting a join key that does not exist before, and is less useful when the join key already exist. So it would be better is we can have a bloom filter API from storage, so that we can only write then the join key does not exist (in bloom filter). cc @hzxa21  @wenym1

**Comment by lmatz** [comment]
> The refilling is most valuable when inserting a join key that does not exist before, and is less useful when the join key already exist. So it would be better is we can have a bloom filter API from storage, so that we can only write then the join key does not exist (in bloom filter). cc @hzxa21 @wenym1

Good idea, then the entire strategy (refilling only when degree `0 -> 1`) always makes things better, with no downside completely I suppose? (only this bloom filter API call is extra, which is a pure in-memory operation)

**Comment by hzxa21** [comment]
> The refilling is most valuable when inserting a join key that does not exist before, and is less useful when the join key already exist. So it would be better is we can have a bloom filter API from storage, so that we can only write then the join key does not exist (in bloom filter). cc @hzxa21 @wenym1

+1. I will submit a PR for that.

**Review by yuhao-su — APPROVED** [review]

**Comment by BugenZhao** [comment]
> log size is significantly large (2.0M). Please disable unnecessary logs.

**Comment by hzxa21** [comment]
> > The refilling is most valuable when inserting a join key that does not exist before, and is less useful when the join key already exist. So it would be better is we can have a bloom filter API from storage, so that we can only write then the join key does not exist (in bloom filter). cc @hzxa21 @wenym1
> 
> +1. I will submit a PR for that.

https://github.com/risingwavelabs/risingwave/pull/7489

**Pull request merged**
