### PR TITLE
doc(dev-guide): `cargo binstall` -> `cargo install` 

### PR DESCRIPTION
**Pull request by camilesing**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by tabVersion** [comment]
I dont think it is a typo. May take this tool as a reference. https://github.com/cargo-bins/cargo-binstall

**Comment by camilesing** [comment]
> I dont think it is a typo. May take this tool as a reference. https://github.com/cargo-bins/cargo-binstall

Got it. before this I was following the `[How to build and run RisingWave](https://risingwavelabs.github.io/risingwave/build-and-run/intro.html#how-to-build-and-run-risingwave)`, but there is no mention of install `binstall` on macOS. i'll open new MR to fix it.

**Review by xxchan — APPROVED** [review]
I'm a little surprised, since if you hit this, it means you want to build the doc, but you didn't ever try compiling RisingWave. 🤔 (as mentioned by https://github.com/risingwavelabs/risingwave/pull/19057#pullrequestreview-2384891381)

May I ask why do you want to compile it?

But yes I think it's ok to `cargo install` instead of `binstall` here, although the latter is better.

**Comment by camilesing** [comment]
> I'm a little surprised, since if you hit this, it means you want to build the doc, but you didn't ever try compiling RisingWave. 🤔 (as mentioned by [#19057 (review)](https://github.com/risingwavelabs/risingwave/pull/19057#pullrequestreview-2384891381))
> 
> May I ask why do you want to compile it?
> 
> But yes I think it's ok to `cargo install` instead of `binstall` here, although the latter is better.

I just want to try run mdbook on my notebook because I saw on the document that. but I didn't try to compile the project before.

**Pull request merged**
