### PR TITLE
feat(frontend): Align vnode mapping and snapshot epoch

### PR DESCRIPTION
**Pull request by xxhZs**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

We notify the frontend with two steps, update snapshot and update fragment_mapping. They are asynchronous, So we may use inconsistent snapshot and fragment_mapping for query, we will get the wrong result. https://github.com/risingwavelabs/risingwave/issues/5446 . In this pr, Support snapshot and fragment_mapping alignment in frontend.

There are two cases of update order of snapshot and fragment_mapping on the frontend
1. fragment_mapping reaches the frontend before snapshot, we don't need to do anything. Because fragment_mapping being updated means we did a ckpt, we can dispatch this query to any node.
2. snapshot reaches frontend before fragment_mapping, we do something in this pr to ensure consistency

If Meta updates `fragment_mapping`, We will add committed_epoch in notify_fragment_mapping, It will be updated hummock_snapshot_manager's align_epoch(only update in this case). And we will add need_align = true in notify_snapshot.

We add `align_epoch` in `hummock_snapshot_manager` to record the max epoch of update `fragment_mapping`, and `align_epoch_snapshot_map` to record the max snapshot for each align_epoch. We save all snapshots greater than `align_epoch` to map, Instead of updating the snapshot to ensure that the snapshot update is later than the update of fragment_mapping(case2->case1).

And we need to wait for the snapshot to update while we flush

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by BugenZhao** [comment]
> Because fragment_mapping being updated means we did a ckpt, we can dispatch this query to any node.

Before this PR, we may fail to get the epoch of this checkpoint, resulting in reading a barrier (non-checkpoint) with the new mapping, which still leads to problems. 🤔

**Comment by hzxa21** [comment]
@xxhZs Is this PR ready for review now?

**Comment by xxhZs** [comment]
> > Because fragment_mapping being updated means we did a ckpt, we can dispatch this query to any node.
> 
> Before this PR, we may fail to get the epoch of this checkpoint, resulting in reading a barrier (non-checkpoint) with the new mapping, which still leads to problems. 🤔

I think if fragment_mapping is updated at epoch1, it means we did the checkpoint at epoch1. We can query them in storage rather than in memory even if he is a barrier(non-checkpoint). So we can query(epoch < epoch1) in every node.

**Comment by xxhZs** [comment]
> @xxhZs Is this PR ready for review now?

yes,It is

**Comment by fuyufjh** [comment]
> fragment_mapping reaches the frontend before snapshot, we don't need to do anything. Because fragment_mapping being updated means we did a ckpt, we can dispatch this query to any node.

I suppose we hoped to support reading from non-checkpoint barriers correctly with this PR, but it seems not. A read request might be routed to the wrong CN and the CN returns stale data, right?

**Comment by fuyufjh** [comment]
> > > Because fragment_mapping being updated means we did a ckpt, we can dispatch this query to any node.
> > 
> > 
> > Before this PR, we may fail to get the epoch of this checkpoint, resulting in reading a barrier (non-checkpoint) with the new mapping, which still leads to problems. 🤔
> 
> I think if fragment_mapping is updated at epoch1, it means we did the checkpoint at epoch1. We can query them(epoch <= epoch1) in storage rather than in memory even if it is a barrier(non-checkpoint). So we can query(epoch <= epoch1) in every node.

Seems correct. 🤔 I can't find a counter-example, although it looks little weird to me.

**Pull request closed without merging**
