### PR TITLE
feat(explain): use `Distill` for explain

### PR DESCRIPTION
**Pull request by ice1000**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR replaces the main usage of `Display` with `Distill`.

### CODE REVIEW

**Comment by ice1000** [comment]
Regarding the `─ ` diffs and spaces, I think there can be a mode in `pretty-xmlish` to avoid those. Let me think about it.

**Comment by ice1000** [comment]
I've done a reduction from
image
to
image

Very satisfied!!

**Review by stdrc — APPROVED** [review]
Looks very clean to me

**Review by st1page — APPROVED** [review]
LGTM

**Pull request merged**
