### PR TITLE
feat: retry connect to meta until meta online

### LINKED ISSUE #3065: components panic while start cluster using docker compose
**Describe the bug**
When Meta is offline, other components will panic while initialize connection to Meta:

**Expected behavior**
When components start and initialize connection to Meta, it should retry until Meta online rather than panic.

**Additional context**
This bug is reported in our community by starting with `docker-compose.yml`. From the provided log, the compactor node starts before meta-node, but its `depents_on` field already contains meta-node. Need more investigation.

### PR DESCRIPTION
**Pull request by yezizp2012**
## What's changed and what's your intention?

As title. This PR fixes #3065, but we still need to implement gRPC health check protocol mentioned in #41.

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)
- Add the 'user-facing changes' label if your PR contains changes that are visible to users (optional)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
Resolve #3065 #295

### CODE REVIEW

**Review by BowenXiao1999 — COMMENTED** [review]
I remembered that we have retry logic in Frontend/CN when connect to meta?

**Comment by yezizp2012** [comment]
> I remembered that we have retry logic in Frontend/CN when connect to meta?

Nope, only the legacy Frontend does. 😂 Currently, FE/CN will panic when meta is not online.

**Review by BugenZhao — APPROVED** [review]
LGTM.
BTW, I remember the purpose of moving these RPC interfaces into a separate crate is to implement a generic retry strategy for them. Any further idea on this? 🤣

**Comment by yezizp2012** [comment]
> LGTM. BTW, I remember the purpose of moving these RPC interfaces into a separate crate is to implement a generic retry strategy for them. Any further idea on this? 🤣

Not really. 🤣 Well I'm not sure about this. NTFS.

**Pull request merged**
