### PR TITLE
feat(config): deny unitialized `data_directory` and `state_store`

### LINKED ISSUE #9153: Discussion: Should the default data_directory: hummock001 be removed？
Yesterday cloud found a [Risingwave data directory got overwritten](https://www.notion.so/risingwave-labs/Risingwave-data-directory-got-overwritten-eaa78cb886c24fee8fa536f4b5bf122c) issue.

This is because the kernel has changed the configuration, but the cloud has not been modified synchronously, and `data_directory` is not provided, and the kernel will use `hummock001` as the default value, which will cause data overwritten.

This parameter is too important, should the default value be removed to avoid risks?

### PR DESCRIPTION
**Pull request by Gun9niR**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

To support mandatory initialization of a system parameter, developers can specify `None` as the default value in the params declaration macro (`for_all_undeprecated_params`). Then we can utilize `system_params_to_kv` invoked when the cluster is started for the first time to check for uninitialized params.

`ALTER SYSTEM SET data_directory/state_store = DEFAULT;` will also result in an error (though the semantic is wrong as discussed in #8851): 

```
SystemParams error: data_directory does not have a default value
```

Closes #9153 

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- RisingWave cluster configuration changes

### Release note

`--data_directory` and `--state_store` must be specified on CLI of the meta node, or the cluster will fail to start.

</details>

### CODE REVIEW

**Comment by Gun9niR** [comment]
@huangjw806 We might want to update the docs about system params.

```rust
/// Macro input is { field identifier, type, default value }
///
/// Note:
/// - Having `None` as default value means the parameter must be initialized.
macro_rules! for_all_undeprecated_params {
    ($macro:ident
        $(, { $field:ident, $type:ty, $default:expr })*) => {
        $macro! {
            { barrier_interval_ms, u32, Some(1000_u32) },
            { checkpoint_frequency, u64, Some(10_u64) },
            { sstable_size_mb, u32, Some(256_u32) },
            { block_size_kb, u32, Some(64_u32) },
            { bloom_false_positive, f64, Some(0.001_f64) },
            { state_store, String, None },
            { data_directory, String, None },
            { backup_storage_url, String, Some("memory".to_string()) },
            { backup_storage_directory, String, Some("backup".to_string()) },
            { telemetry_enabled, bool, Some(true) },
            $({ $field, $type, $default },)*
        }
    };
}
```

The third column's value being `None` means that the corresponding parameter must be specified from CLI.

**Comment by huangjw806** [comment]
@arkbriar  Please confirm whether the operator needs to be changed synchronously, thank you!

**Review by BugenZhao — APPROVED** [review]
LGTM

**Review by arkbriar — APPROVED** [review]
LGTM

**Comment by arkbriar** [comment]
> Please confirm whether the operator needs to be changed synchronously, thank you!

Sure. AFAIK, the operator should work without any change.

**Review by fuyufjh — APPROVED** [review]

**Pull request merged**
