### PR TITLE
feat(optimizer): support agg group by simplify rule

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Resolve https://github.com/risingwavelabs/risingwave/issues/9578
- Use `first_value` to replace redundant group by key, so that `first_value` could be purged by the following column pruning optimization.

Example:

```sql
before:
select count(*) from sbtest1 group by id, k, c;

use functional dependencies  (id) ==> (k, c)

after:
select count(*) from sbtest1 group by id;
```

## Checklist

- [ ] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by st1page — APPROVED** [review]
Furthermore, will we support that?
```SQL
CREATE TABLE t(v int, k int primary key);
SELECT v, k from t group by k;
ERROR:  QueryError: Invalid input syntax: column must appear in the GROUP BY clause or be used in an aggregate function
```

**Comment by chenzl25** [comment]
> Furthermore, will we support that?
> 
> ```sql
> CREATE TABLE t(v int, k int primary key);
> SELECT v, k from t group by k;
> ERROR:  QueryError: Invalid input syntax: column must appear in the GROUP BY clause or be used in an aggregate function
> ```

To be compatible with PostgreSQL, I think we don't need to support it, although other databases like MySQL support this feature.

**Review by kwannoel — COMMENTED** [review]
> Use first_value to replace redundant group by key, so that first_value could be purged by the following column pruning optimization.

How does column pruning purge the first_value. Seems like it is still present in some of the output plans?

**Comment by stdrc** [comment]
Maybe we need a `any_value` (exists in DuckDB while its semantic is _first non-null value_) or `arbitrary_value` instead of `first_value`. Currently streaming impl of `first_value` requires an order and thus a state table...

**Comment by chenzl25** [comment]
> > Use first_value to replace redundant group by key, so that first_value could be purged by the following column pruning optimization.
> 
> How does column pruning purge the first_value. Seems like it is still present in some of the output plans?

If those columns haven't been used, they could be pruned, however, if they are still being used, they will present.

**Comment by chenzl25** [comment]
> Maybe we need a `any_value` (exists in DuckDB while its semantic is _first non-null value_) or `arbitrary_value` instead of `first_value`. Currently streaming impl of `first_value` requires an order and thus a state table...

Yes, but for each group key, this rule can ensure that there is always one row in the `first_value` state table corresponding to it.

**Comment by stdrc** [comment]
> > Maybe we need a `any_value` (exists in DuckDB while its semantic is _first non-null value_) or `arbitrary_value` instead of `first_value`. Currently streaming impl of `first_value` requires an order and thus a state table...
> 
> Yes, but for each group key, this rule can ensure that there is always one row in the `first_value` state table corresponding to it.

Aren't there `#input rows of each group` rows of the same value?

**Comment by st1page** [comment]
> Yes, but for each group key, this rule can ensure that there is always one row in the first_value state table corresponding to it.

Exactly not :hot_face: there are multiple records in each group
```SQL
CREATE TABLE User{
    id int Primary key,
    name varchar,    
}

CREATE TABLE Events {
    user_id int,
}

SELECT user_id, name, count(*) FROM User 
Join Event On Events.user_id = User.id
Group by user_id, name;
```

**Pull request merged**
