### PR TITLE
feat(expr): support `jsonb_extract_path(_text)` function

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Based on #13110, this PR implements their variadic form functions:

```
jsonb_extract_path ( from_json jsonb, VARIADIC path_elems text[] ) → jsonb
jsonb_extract_path_text ( from_json jsonb, VARIADIC path_elems text[] ) → text
```

by rewriting variadic arguments to array[] in the frontend. e.g.

```
jsonb_extract_path(jsonb, s1, s2) => jsonb_extract_path(jsonb, array[s1, s2])
```

It seems that variadic functions still need special handlings in type inference. We might consider to support such signatures and automate rewrite in the future:

```rust
#[function("jsonb_extract_path(jsonb, variadic varchar[]) -> jsonb")]
```

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [x] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

```
jsonb_extract_path ( from_json jsonb, VARIADIC path_elems text[] ) → jsonb
Extracts JSON sub-object at the specified path. (This is functionally equivalent to the #> operator, but writing the path out as a variadic list can be more convenient in some cases.)
json_extract_path('{"f2":{"f3":1},"f4":{"f5":99,"f6":"foo"}}', 'f4', 'f6') → "foo"

jsonb_extract_path_text ( from_json jsonb, VARIADIC path_elems text[] ) → text
Extracts JSON sub-object at the specified path as text. (This is functionally equivalent to the #>> operator.)
json_extract_path_text('{"f2":{"f3":1},"f4":{"f5":99,"f6":"foo"}}', 'f4', 'f6') → foo
```

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]

**Review by KeXiangWang — APPROVED** [review]
LGTM!

**Comment by xiangjinwu** [comment]
Talking about PostgreSQL, there are two categories of functions that can take a variable number of inputs: a `variadic` function and a variadic-like function...

* `jsonb_extract_path` is a true `variadic` function. In the backend, it is implemented as accepting an array (same as `#>`). But in the frontend, it can be invoked by either `jsonb_extract_path(input, VARIADIC array['foo', 'bar'])` or `jsonb_extract_path(input, 'foo', 'bar')`. In the latter case, the binder collects the rest of input args and puts them in a literal array. In the former case, use of keyword `VARIADIC` suppresses the aforementioned array building behavior.
* `greatest` is just variadic-like. It cannot be invoked with keyword `VARIADIC` and an array `select greatest(variadic array['a', 'b']);`
* `concat`, despite not having `variadic` in its [doc](https://www.postgresql.org/docs/current/functions-string.html), behaves like a true `variadic` function and can be invoked with both syntax.

Now back to RisingWave, we aim to support both syntax eventually. So it is better that `jsonb_extract_path` use the same array-based backend as `#>`. So that we do not need to keep an additional `impl Row` implementation in the future just for backward compatibility.

**Comment by xiangjinwu** [comment]
Sorry for the previous comment. After checking deeper, the PostgreSQL way is:
* `greatest`/`coalesce` are not in `pg_proc` at all and handled specially.
* `concat`/`format` are true `variadic` in [doc](https://www.postgresql.org/docs/current/functions-string.html#:~:text=The%20concat%2C%20concat_ws%20and%20format%20functions%20are%20variadic). Their signature was not declared as `variadic any[]` but `any, ...`, because `any[]` is an invalid. This means it can be invoked with `concat(1, true)` or `concat(variadic array['1', 'true'])` but not `concat(variadic array[1, true])`. Its [backend implementation](https://github.com/postgres/postgres/blob/REL_16_0/src/backend/utils/adt/varlena.c#L5346) has different paths handling `variadic array` and `any, ...`
* `jsonb_extract_path` is declared as `variadic text[]`, supports `jsonb_extract_path('["a", {"b":"c"}]'::jsonb, '1', 'b')` and `jsonb_extract_path('["a", {"b":"c"}]'::jsonb, '1', 'b')` but not `jsonb_extract_path('["a", {"b":"c"}]'::jsonb, 1, 'b')`. Its [backend implementation](https://github.com/postgres/postgres/blob/REL_16_0/src/backend/utils/adt/jsonfuncs.c#L1488) only handles array. However I have not confirmed whether PostgreSQL transformed the args into an array.

Now back to our implementation:
* `impl Row for ListRef` means we accept an array by expanding it to an implementation that handles `, ...` which is the reverse of what PostgreSQL did. I do not have a strong option on which is better, just want to bring it up it is also possible to build a literal array from `, ...` args in frontend.

**Comment by wangrunji0408** [comment]
>  It is better that `jsonb_extract_path` use the same array-based backend implementation as #>.

I see. So it turns out that `jsonb_extract_path` is the identical function of the `#>` operator and this PR should be rewritten to a pure frontend handling.😮

**Comment by xiangjinwu** [comment]
> > It is better that `jsonb_extract_path` use the same array-based backend implementation as #>.
> 
> I see. So it turns out that `jsonb_extract_path` is the identical function of the `#>` operator and this PR should be rewritten to a pure frontend handling.😮

Yes, PostgreSQL resolves `#>` to the `jsonb_extract_path` function.
```
test=# select oprcode from pg_operator where oprname = '#>';
      oprcode       
--------------------
 json_extract_path
 jsonb_extract_path
(2 rows)
```

**Review by xiangjinwu — APPROVED** [review]

**Pull request merged**
