### PR TITLE
fix: Better error message for CREATE SOURCE without connector

### PR DESCRIPTION
**Pull request by gengteng**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

resolve https://github.com/risingwavelabs/risingwave/issues/8792

Improve error message when 'connector' or 'WITH' clause is missing from a CREATE SOURCE statement.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

### Error Message
If the 'connector' field is missing from a CEATE SOURCE statement, the user will get an error message:
```
Protocol error: missing field 'connector'
```
If the 'WITH' clause is missing from a CREATE SOURCE statement, he or she will get an error message:
```
Invalid input syntax: missing WITH clause
```

### CODE REVIEW

**Review by xxchan — APPROVED** [review]
LGTM. Thanks!

**Comment by xxchan** [comment]
One little hint on GitHub (I've changed that): This syntax can close related issue automatically 😄
image

**Comment by gengteng** [comment]
> One little hint on GitHub (I've changed that): This syntax can close related issue automatically 😄 image

Thank you for the reminder. I'll use this syntax when submitting future PRs. 😄

**Comment by xxchan** [comment]
There are compile error. Please update branch and fix that 🙏

**Pull request merged**
