### PR TITLE
feat: use ryu/itoa to cast num to text

### PR DESCRIPTION
**Pull request by curiosityyy**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Use https://github.com/dtolnay/itoa and https://github.com/dtolnay/ryu to do num -> text cast.

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

Ref to https://github.com/risingwavelabs/risingwave/issues/1431 

For https://github.com/risingwavelabs/risingwave/issues/6412, after this pr, still not exactly the same as pg.

For example,
```
pg: 1.2345678901234e+20_f32 -> 1.2345679e+20
ryu: 1.2345678901234e+20_f32 -> 1.2345679e20
pg: 1 -> 1
ryu: 1 -> 1.0
```

And also `Infinity`, but I have handled it.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
https://github.com/risingwavelabs/risingwave/issues/1431

### CODE REVIEW

**Comment by curiosityyy** [comment]
Because `ryu: 1 -> 1.0`, the pr will fail on some e2e test.  Could I fix all the test file and make float number without decimal places to have `.0`?  @xiangjinwu wdyt?

**Comment by xiangjinwu** [comment]
Thanks for your help on this issue.

> Because `ryu: 1 -> 1.0`, the pr will fail on some e2e test. Could I fix all the failed test and make float number without decimal places to have `.0`? @xiangjinwu wdyt?

It seems the ryu crate is not flexible enough to allow us to match PostgreSQL. Maybe the internals exposed by ryu_floating_decimal could be helpful. I also found that PostgreSQL switches to scientific notation at different value from the ryu crate:
|input|PostgreSQL|ryu crate|
|-|-|-|
|1e5::float4|100000|100000.0|
|1e6::float4|1e+06|1000000.0|
|1e12::float4|1e+12|1000000000000.0|
|1e13::float4|1e+13|1e13|
|1e14::float8|100000000000000|100000000000000.0|

Given the goal of diverging from rust std's ToString/Display is to match PostgreSQL, it feels awkward to stay at a position that adds some complexity but still requires modification to test files. But feel free to justify it if the required test modifications are much less than before.

**Comment by curiosityyy** [comment]
> Thanks for your help on this issue.
> 
> > Because `ryu: 1 -> 1.0`, the pr will fail on some e2e test. Could I fix all the failed test and make float number without decimal places to have `.0`? @xiangjinwu wdyt?
> 
> It seems the ryu crate is not flexible enough to allow us to match PostgreSQL. Maybe the internals exposed by ryu_floating_decimal could be helpful. I also found that PostgreSQL switches to scientific notation at different value from the ryu crate:
> 
> input	PostgreSQL	ryu crate
> 1e5::float4	100000	100000.0
> 1e6::float4	1e+06	1000000.0
> 1e12::float4	1e+12	1000000000000.0
> 1e13::float4	1e+13	1e13
> 1e14::float8	100000000000000	100000000000000.0
> Given the goal of diverging from rust std's ToString/Display is to match PostgreSQL, it feels awkward to stay at a position that adds some complexity but still requires modification to test files. But feel free to justify it if the required test modifications are much less than before.

Yeah, I agree with you. If ryu can not bring other benefits, it's not necessary to use it.

**Comment by curiosityyy** [comment]
@xiangjinwu I fix some special cases. And it can pass the ci. 

As I knew, only this case is not compatible with pg. 
input | PostgreSQL | ryu crate
-- | -- | --
1e6::float4 | 1e+06 | 1000000.0

**Comment by curiosityyy** [comment]
I fixed some special cases by string operation. 

And fix a test file which is inconsistent with pg.

image

image

**Review by xiangjinwu — COMMENTED** [review]
Thanks for the update. Could you also attempt enabling some test cases that were commented out in #6410 due to the formatting differences?

For instructions on running these tests:
https://github.com/risingwavelabs/risingwave/tree/main/src/tests/regress

**Comment by curiosityyy** [comment]
> Thanks for the update. Could you also attempt enabling some test cases that were commented out in #6410 due to the formatting differences?
> 
> For instructions on running these tests: https://github.com/risingwavelabs/risingwave/tree/main/src/tests/regress

Have enabled more regress tests.

**Review by xiangjinwu — APPROVED** [review]

**Pull request merged**
