### PR TITLE
fix(meta): expect data dir is empty when creating cluster

### PR DESCRIPTION
**Pull request by Gun9niR**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

As title. Defer system parameter persistence to before starting RPC services, so that if invalid parameters prevent the meta node from starting, they will not be persisted.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment

### Release note

The object store URL identified by `state_store` and `data_directory` must be empty when creating the cluster, or the meta node will refuse to start.

### CODE REVIEW

**Comment by Gun9niR** [comment]
I added a log of system parameters before any check so that we can inspect the log when the cluster is deleted.

**Comment by zwang28** [comment]
Just realize `list` can be expensive while we only want to check if any objects exists 🤔 .

**Comment by Gun9niR** [comment]
> Just realize `list` can be expensive while we only want to check if any objects exists 🤔 .

Then we should write an object to identify this cluster on the first launch.

**Comment by Gun9niR** [comment]
To distinguish the owner of the cluster, we should write a uuid to etcd as the cluster identifier and write a file named as uuid to the object store.

**Comment by CharlieSYH** [comment]
No doc updates for this PR since it's closed.

**Pull request closed without merging**
