### PR TITLE
fix(frontend): `returning` matches desired columns

### PR DESCRIPTION
**Pull request by Eurekaaw**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

`returning` matches desired columns for vanilla table.

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
Let `LogicalInsert`'s schema be the returning schema (rather than its input's schema, for which may misalign with the table's schema). 
This leads to a side effect that the projection afterwards becomes identity, and thus being subject to `ProjectEliminationRule`(credits to @broccoliSpicy, nice catch). Therefore the rule is banned for `project -> dml`  cases.
- Describe any limitations of the current code (optional)
This PR __FAILS__ to solve the problem when the table contains generated columns, and it's banned in the binder phase (it will be tracked by another issue).
- Refer to a related PR or issue link (optional)
#9012 

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
~~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

~~- [ ] My PR **DOES NOT** contain user-facing changes.~~

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- SQL commands, functions, and operators

### Release note
`insert` with `returning` to a table with generated columns will be rejected at the binder phase.

</details>

### CODE REVIEW

**Comment by Eurekaaw** [comment]
@broccoliSpicy PTAL

**Comment by Eurekaaw** [comment]
I find the datachunk written to `dml_manager` in insert executor does not contain columns that will be generated, and thus I don't find a way to yield correct chunk for `returning`. Do you have any suggestions? @yuhao-su

**Comment by Eurekaaw** [comment]
There's another and better design😇

**Comment by yuhao-su** [comment]
> and thus I don't find a way to yield the correct chunk for returning.

Good catch. Let's ban returning an insert with the generated column. After discussing with @st1page , `returning` may not be accurate when inserting a record that pk conflict with existing record.

**Pull request closed without merging**
