### PR TITLE
refactor(optimizer): make ExprVisitor  an object safe trait.

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Related https://github.com/risingwavelabs/risingwave/issues/13510
- To implement ExprVisitable, we need to make ExprVisitor an object safe trait, which means we need to remove the `fn merge`.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by BugenZhao — COMMENTED** [review]
- Is `merge` and `Result` really a good practice of a visitor pattern? As all `visit` methods take `&mut self`, this seems to imply that one should maintain the states or results in `self`. In this way, the signature of `merge` could be like
  ```rust
  fn merge(&mut self, b: Self::Result);
  ```
  Or rather, we should never have a `merge` function?

- Once a method is overridden, users have to duplicate the default implementation there and `merge` does not help us for boilerplate reduction. Will this work somehow related to #13477?

**Comment by chenzl25** [comment]
> Is `merge` and `Result` really a good practice of a visitor pattern?

Although some visitors, such as Has, can easily eliminate the need for merge by using a state, other visitors, like TableScanIoEstimator, might find it challenging to calculate the cost by visiting expressions with the use of only a state, because expressions structure also matters. Therefore, I believe this method still serves a purpose. However, I agree that using &mut self instead of &self for merge would be more appropriate.

**Comment by chenzl25** [comment]
> * Once a method is overridden, users have to duplicate the default implementation there and `merge` does not help us for boilerplate reduction. Will this work somehow related to [optimizer: what's the "correct" form of visitor? #13477](https://github.com/risingwavelabs/risingwave/issues/13477)?

As mentioned above, I think `fn merge` is mainly used to capture the expression structure instead of boilerplate reduction, so maybe we can use another PR to resolve that issue.

**Comment by BugenZhao** [comment]
> However, I agree that using &mut self instead of &self for merge would be more appropriate.

Actually I suggest we either... 🥵
- Make `visit` take `&self`,
- or either remove `merge` but keep `visit` take `&mut self`

**Comment by BugenZhao** [comment]
> However, I agree that using &mut self instead of &self for merge would be more appropriate.

Actually I suggest we either... 🥵
- Make `visit` take `&self`,
- or either remove `merge` but keep `visit` take `&mut self`

**Comment by BugenZhao** [comment]
> However, I agree that using &mut self instead of &self for merge would be more appropriate.

Actually I suggest we either... 🥵
- Make `visit` take `&self`,
- or either remove `merge` but keep `visit` take `&mut self`

**Comment by BugenZhao** [comment]
> However, I agree that using &mut self instead of &self for merge would be more appropriate.

Actually I suggest we either... 🥵
- Make `visit` take `&self`,
- or either remove `merge` but keep `visit` take `&mut self`

**Comment by chenzl25** [comment]
> > However, I agree that using &mut self instead of &self for merge would be more appropriate.
> 
> Actually I suggest we either... 🥵
> 
> * Make `visit` take `&self`,
> * or either remove `merge` but keep `visit` take `&mut self`

I prefer to remove `merge` and return type if we have to.

**Comment by chenzl25** [comment]
> TableScanIoEstimator

But as I mentioned before without a return type and merge function, visitors like `TableScanIoEstimator` could need to maintain a state by itself which is nontrivial.

**Comment by chenzl25** [comment]
cc @BugenZhao I removed the `merge` function right now. PTAL.

**Review by BugenZhao — APPROVED** [review]
LGTM. Thanks for doing this refactoring!

**Review by xxchan — APPROVED** [review]
I revisited #4520 (add return value to visitor) and #5058 (add `merge`). Still has no strong opinion for either way. So rubber stamp.

**Comment by chenzl25** [comment]
> I revisited #4520 (add return value to visitor) and #5058 (add `merge`). Still has no strong opinion for either way. So rubber stamp.

Oh, I have already forgotten that both of them were introduced by myself. 🥵 Now I removed them all.

**Review by st1page — APPROVED** [review]
LGTM

**Pull request merged**
