### PR TITLE
fix: fix connector start in risedev

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by StrikeW** [comment]
Hi, have you tested your modification? Because we don't have ci for risedev, modification should be careful.

**Comment by xxchan** [comment]
> Hi, have you tested your modification? Because we don't have ci for risedev, modification should be careful.

Yes & the change is trivial (changed to the same as playground) & I think breaking risedev isn't too serious 🤡

**Comment by StrikeW** [comment]
duplicate with #8590

**Comment by xxchan** [comment]
> may duplicate with #8590

Not duplicate, but orthogonal. It's still not good to `sh` a `#!/bin/bash` script..

**Comment by StrikeW** [comment]
> > may duplicate with #8590
> 
> Not duplicate, but orthogonal. It's still not good to `sh` a `#!/bin/bash` script..

The reason why I use `sh` is that I encountered an issue in the docker environment which seems it would not work if we simply run it by `./start-service.sh`. But I forget the specific scenario, so maybe we should preserve the `sh` way.

**Review by wenym1 — APPROVED** [review]

**Pull request merged**
