### PR TITLE
feat(frontend): support explain with graphviz visualization in dashboard

### PR DESCRIPTION
**Pull request by lyang24**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
https://github.com/risingwavelabs/risingwave/issues/19542

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

new ui for rendering graphviz output to replace explain distsql. 

image

example usage:
1. run explain (format dot, distsql) xxx and copy the dot output.
2. paste the dot output to dashboard and click parse generate graphviz visualization.

</details>

### CODE REVIEW

**Review by kwannoel — COMMENTED** [review]
We can deprecate all the code related to rendering `explain JSON`, and remove it from the UI as an option, along with its dependencies. `explain (format dot)` is the only option we need. It already provides a graph structure, so all we need to do is let a graphviz library render it. It will save us a lot of code.

**Comment by kwannoel** [comment]
Will try to run it later.

**Comment by kwannoel** [comment]
Screenshot 2024-11-26 at 10 06 47 PM

LGTM, we can also update the naming of this tab. It can render any graphviz output, so we can rename it as `Render Graphviz Dot format`.

**Review by kwannoel — APPROVED** [review]

**Comment by kwannoel** [comment]
I think the screenshot in the release note also should be updated.

**Comment by lyang24** [comment]
> Render Graphviz Dot format

updated the release note and updated title to `Render Graphviz Dot format`

**Pull request merged**
