### PR TITLE
refactor: more row traits

### LINKED ISSUE #6433: Use row trait for state table.
- [x] Use row trait in the arguments. #6404
- [ ] (?) Allow different row types in the return value to avoid collecting an owned row.

### LINKED ISSUE #6735: Utilize `Row` trait in streaming executors.

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Add more row traits in RisingWave.

- Remove most of the deprecated proxies and make `Row2` native for accessing rows.
- Avoid using ITTA in iterator GAT as much as possible to make the analyzer happier.
- Make `Option<impl Row>` a `Row` to simplify group key manipulation.
- Visit all `Row`s and make it generic if possible.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- Close #6433
- Close #6735

### CODE REVIEW

**Comment by wcy-fdu** [comment]
Thanks for your efforts👍 . A lot of files have been changed, I'll review it later.

**Comment by wcy-fdu** [comment]
Thanks for your efforts👍 . A lot of files have been changed, I'll review it later.

**Comment by yuhao-su** [comment]
LGTM! Great work!

**Review by wcy-fdu — APPROVED** [review]
LGTM!

**Review by st1page — APPROVED** [review]

**Pull request merged**
