### PR TITLE
fix(hash agg): don't emit data in HashAgg when stream is paused

### LINKED ISSUE #19117: bug(sink): panic on "should not receive any data after pause"
### Describe the bug

The only compute node panicked on `panicked at src/stream/src/executor/sink.rs:277:21:\nShould not receive any data after pause`.

There're sinks in the cluster. The user was creating multiple `sink into table` at the time.

https://risingwave-labs.slack.com/archives/C034TRPKN1F/p1730175390802129

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

v2.0.2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #19117.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by stdrc** [comment]
* **#19168** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19168?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stdrc and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by st1page — COMMENTED** [review]
Although the modification is simple, we may still need to test to ensure that it does not result in data loss.

🤔 But it seems hard to test in e2e test.

**Comment by fuyufjh** [comment]
I think we need to find out the sources of these watermark events. Because, technically, if there is not incomming events, the watermark won't be updated.

**Comment by stdrc** [comment]
I just realized that `StreamSort` can produce chunks when receiving watermark message. Now I agree that we shouldn't have watermark messages on the stream when the stream is paused.

**Comment by stdrc** [comment]
Superseded by #19199.

**Pull request closed without merging**
