### PR TITLE
fix(integration_tests): datagen timestamp and timestamptz accordingly

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

In #12084 we add stricter check in parsing and forbid **parsing** a string containing timezone info as `timestamp without time zone`. This helps us discover some misuse between `timestamp` vs `timestamptz` in existing integration tests. This PR fixes the failing integration tests ([link](https://buildkite.com/risingwavelabs/integration-tests/builds/272#018a7f32-ee82-4835-9a48-7af90e3b41a6)).

The golang datagen used to contain a single `RwTimestampLayout`. This PR replaces it with `RwTimestamptzLayout` and `RwTimestampNaiveLayout`.
* Most tests are already using `timestamptz`. So there is effectively no change to them.
* Test case `twitter` was using `timestamptz` in json and avro but `timestamp` in proto. This caused the test failure.

Limitations:
* Test cases `ecommerce` and `delivery` (partially removed #11012) are updated to generate `timestamp` as required by their sql query. But seems these tests are not actually executed.
* There are more sink tests refers to `timestamp`. `user_behaviors.event_timestamp` is `timestamptz` in some tests but `timestamp` in others. This may be due to our [tutorial](https://docs.risingwave.com/docs/current/clickstream-analysis/) being [out of sync](https://github.com/risingwavelabs/risingwave-demo/pull/40).

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by StrikeW** [comment]
I build a docker image and test it against the pipeline, but the twitter case still fail. @xiangjinwu 
https://buildkite.com/risingwavelabs/integration-tests/builds/276#018a91a2-4460-4b26-a0e2-4d19fe99f4d5

> meta-node-0  | 2023-09-14T03:04:59.737814838Z  WARN risingwave_meta::barrier: Failed to complete epoch 5074157534773248: Rpc error: gRPC error (Internal error): Actor 27 exit unexpectedly: Executor error: Chunk operation error: Parse error: Can't cast string to timestamp (expected format is YYYY-MM-DD HH:MM:SS[.D+{up to 6 digits}] or YYYY-MM-DD HH:MM or YYYY-MM-DD or ISO 8601 format)

**Comment by xiangjinwu** [comment]
> I build a docker image and test it against the pipeline (RW_IMAGE_VERSION="git-d9222e19862b72c327d5ea778d57fb9487c33963"), but the twitter case still fail. @xiangjinwu https://buildkite.com/risingwavelabs/integration-tests/builds/276#018a91a2-4460-4b26-a0e2-4d19fe99f4d5
> 
> > meta-node-0  | 2023-09-14T03:04:59.737814838Z  WARN risingwave_meta::barrier: Failed to complete epoch 5074157534773248: Rpc error: gRPC error (Internal error): Actor 27 exit unexpectedly: Executor error: Chunk operation error: Parse error: Can't cast string to timestamp (expected format is YYYY-MM-DD HH:MM:SS[.D+{up to 6 digits}] or YYYY-MM-DD HH:MM or YYYY-MM-DD or ISO 8601 format)

The linked failing run is on commit d7a65c150 without changes here. This run against d9222e198 is successful: https://buildkite.com/risingwavelabs/integration-tests/builds/277#018a91bd-c22f-4a22-b49f-1f898372cb8e

The merge queue failure is also irrelevant. It was a 404 in regress test for the following URL:
 http://us-east-2.ec2.archive.ubuntu.com/ubuntu//pool/main/g/glibc/locales_2.35-0ubuntu3.1_all.deb

**Comment by StrikeW** [comment]
That's weird. The integration test pipeline need a docker image to run, I built one based on this PR branch before.

**Comment by xiangjinwu** [comment]
> That's weird. The integration test pipeline need a docker image to run, I built one based on this PR branch before.

The `datagen` in Go is an exception to this rule. It is compiled in every run rather than using prebuilt docker image:

https://github.com/risingwavelabs/risingwave/blob/b1c5ccd03b94c2bf849bc3e603476e3d04cf25e7/integration_tests/ad-ctr/docker-compose.yml#L36-L48

**Pull request merged**
