### PR TITLE
feat(storage): start notification manager when hummock start

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Currently, after we initialize the state store, we then start the observer manager only when our state store is hummock. In other words, our observer manager is only for hummock. Besides, the returned hummock contains an invalid hummock version, and gets ready only after we start the observer manager, which may cause some misuse.

In this PR, we start the observer manager when we initialize hummock, so that we can ensure that the returned hummock is ready to serve read request

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Review by soundOfDestiny — CHANGES_REQUESTED** [review]
I suggest we not merge CN subscriber and risectl subscriber because risectl doesn't do `handle_notification()`

**Comment by soundOfDestiny** [comment]
For example, we need to send CN `HummockVersionDelta`s, but we don't need to send risectl `HummockVersionDelta`s. We can reduce cost here.

**Comment by wenym1** [comment]
> For example, we need to send CN HummockVersionDeltas, but we don't need to send risectl HummockVersionDeltas. We can reduce cost here.

risectl is not a tool we frequently use, especially in production environment. Besides, sending `HummockVersionDeltas` is asynchronous on meta node, and seems do not increase considerable cost. 

If we combine the CN and risectl observer, we can launch the observer when we initialize hummock like what we do in this PR, and don't have to explicitly launch an observer every time after we initialize hummock, which will make the code simpler and more easily maintained. I think this is beneficial compared to the cost increased from sending unused metadata to one more node in a relatively low frequency.

**Review by soundOfDestiny — APPROVED** [review]
ok

**Review by zwang28 — APPROVED** [review]

**Review by Li0k — APPROVED** [review]
Rest LGTM, thanks !

**Pull request merged**
