### PR TITLE
feat(source): enable SASL for Kafka connector

### LINKED ISSUE #4200: Authentication support in Kafka Connector
**Is your feature request related to a problem? Please describe.**
When using Kafka API of Azure Event Hub, we generally use SASL auth. It would be great if RisingWave supports SASL auth options. If it’s already supported, kindly update the docs.

**Describe the solution you'd like**
Add support for  WITH options,
```properties
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=
```
In existing table syntax
```sql
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_abc (
   column1 varchar,
   column2 integer,
)
WITH (
   connector='kafka',
   kafka.topic='demo_topic',
   kafka.brokers='172.10.1.1:9090,172.10.1.2:9090',
   kafka.scan.startup.mode='latest',
   kafka.time.offset='140000000',
   kafka.consumer.group='demo_consumer_name'
)
ROW FORMAT JSON;
```

**Describe alternatives you've considered**
[Flink SQL](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/connectors/table/kafka/)

### PR DESCRIPTION
**Pull request by xx01cyx**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

### Summarize your change 

- Enable SSL when connecting to Kafka.
- Enable SASL authentication for Kafka connector, including SASL/PLAIN, SASL/SCRAM, SASL/GSSAPI and SASL/OAUTHBEARER. Check the meaning of each configuration property [here](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md).

### Describe any limitations of the current code

- SASL/OAUTHBEARER is only supported in unsecured mode, and OIDC is not allowed as well. This is because [rust-rdkafka](https://github.com/fede1024/rust-rdkafka) currently does not have a full support for OAuth based on [librdkafka](https://github.com/edenhill/librdkafka). 
- The large number of SASL properties in `struct KafkaProperties` appears quite tedious. Maybe we can allow `properties.*` to be set by user, [just as what Flink does](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/kafka/):

  > This can set and pass arbitrary Kafka configurations. Suffix names must match the configuration key defined in [Kafka Configuration documentation](https://kafka.apache.org/documentation/#configuration). Flink will remove the "properties." key prefix and pass the transformed key and values to the underlying KafkaClient. For example, you can disable automatic topic creation via 'properties.allow.auto.create.topics' = 'false'.

  However, we must notice that Flink can call Kafka APIs directly, because it is written in Java. If we are to implement `properties.*`, we must align with the [configurations of librdkafka](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md), rather than Kafka itself.

## Checklist

- [x] I have written necessary rustdoc comments
- [x]  I have tested the code manually
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### Types of user-facing changes

* Connector (sources & sinks)

### Release note

Below are the scripts for creating Kafka materialized sources with different security protocols.

```bash
# RisingWave Source 1 -- SSL (w/o SASL)
# Please refer to https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka for details.
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_1 (
   column1 varchar,
   column2 integer,
)                  
WITH (
   connector='kafka',
   kafka.topic='quickstart-events',
   kafka.brokers='localhost:9093',
   kafka.scan.startup.mode='earliest',
   properties.security.protocol='SSL',
   properties.ssl.ca.location='/home/ubuntu/kafka/secrets/ca-cert',
   properties.ssl.certificate.location='/home/ubuntu/kafka/secrets/client_risingwave_client.pem',
   properties.ssl.key.location='/home/ubuntu/kafka/secrets/client_risingwave_client.key',
   properties.ssl.key.password='abcdefgh'
)                                                       
ROW FORMAT JSON;

# RisingWave Source 2 -- SASL/PLAIN (w/o SSL)
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_2 (
   column1 varchar,
   column2 integer,
)                  
WITH (
   connector='kafka',
   kafka.topic='quickstart-events',
   kafka.brokers='localhost:9093',
   kafka.scan.startup.mode='earliest',
   properties.sasl.mechanism='PLAIN',
   properties.security.protocol='SASL_PLAINTEXT',
   properties.sasl.username='admin',
   properties.sasl.password='admin-secret'
)                                                           
ROW FORMAT JSON;

# RisingWave Source 3 -- SASL/SCRAM-SHA-256 (w/o SSL)
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_3 (
   column1 varchar,
   column2 integer,
)                  
WITH (
   connector='kafka',
   kafka.topic='quickstart-events',
   kafka.brokers='localhost:9093',
   kafka.scan.startup.mode='earliest',
   properties.sasl.mechanism='SCRAM-SHA-256',
   properties.security.protocol='SASL_PLAINTEXT',
   properties.sasl.username='admin',
   properties.sasl.password='admin-secret'
)                                                       
ROW FORMAT JSON;

# RisingWave Source 4 -- SASL/SCRAM-SHA-512 (w/o SSL)
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_4 (
   column1 varchar,
   column2 integer,
)                  
WITH (
   connector='kafka',
   kafka.topic='quickstart-events',
   kafka.brokers='localhost:9093',
   kafka.scan.startup.mode='earliest',
   properties.sasl.mechanism='SCRAM-SHA-512',
   properties.security.protocol='SASL_PLAINTEXT',
   properties.sasl.username='admin',
   properties.sasl.password='admin-secret'
)                                                       
ROW FORMAT JSON;

# RisingWave Source 5 -- SASL/GSSAPI (w/o SSL)
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_5 (
   column1 varchar,
   column2 integer,
)                  
WITH (
   connector='kafka',
   kafka.topic='quickstart-events',
   kafka.brokers='localhost:9093',
   kafka.scan.startup.mode='earliest',
   properties.sasl.mechanism='GSSAPI',
   properties.security.protocol='SASL_PLAINTEXT',
   properties.sasl.kerberos.service.name='kafka',
   properties.sasl.kerberos.keytab='/etc/krb5kdc/kafka.client.keytab',
   properties.sasl.kerberos.principal='kafkaclient4@AP-SOUTHEAST-1.COMPUTE.INTERNAL',
   properties.sasl.kerberos.kinit.cmd='sudo kinit -R -kt "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal} || sudo kinit -kt "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}',
   properties.sasl.kerberos.min.time.before.relogin='10000'
)                                                       
ROW FORMAT JSON;

# RisingWave Source 6 -- SASL/OAUTHBEARER (w/o SSL)
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_6 (
   column1 varchar,
   column2 integer,
)                  
WITH (
   connector='kafka',
   kafka.topic='quickstart-events',
   kafka.brokers='localhost:9093',
   kafka.scan.startup.mode='earliest',
   properties.sasl.mechanism='OAUTHBEARER',
   properties.security.protocol='SASL_PLAINTEXT',
   properties.sasl.oauthbearer.config='principal=bob'
)                                                       
ROW FORMAT JSON;

# RisingWave Source 7 -- SASL/PLAIN (w/ SSL)
CREATE MATERIALIZED SOURCE IF NOT EXISTS source_7 (
   column1 varchar,
   column2 integer,
)                  
WITH (
   connector='kafka',
   kafka.topic='quickstart-events',
   kafka.brokers='localhost:9093',
   kafka.scan.startup.mode='earliest',
   properties.sasl.mechanism='PLAIN',
   properties.security.protocol='SASL_SSL',
   properties.sasl.username='admin',
   properties.sasl.password='admin-secret',
   properties.ssl.ca.location='/home/ubuntu/kafka/secrets/ca-cert',
   properties.ssl.certificate.location='/home/ubuntu/kafka/secrets/client_risingwave_client.pem',
   properties.ssl.key.location='/home/ubuntu/kafka/secrets/client_risingwave_client.key',
   properties.ssl.key.password='abcdefgh'
)                                                           
ROW FORMAT JSON;

# Materialized sources for SASL/SCRAM, SASL/GSSAPI and SASL/OAUTHBEARER w/ SSL could be created in the same manner.
```

## Refer to a related PR or issue link (optional)

Fixes #4200

### CODE REVIEW

**Comment by skyzh** [comment]
Looks good. Does ssl on rdkafka bring new dependencies?

**Comment by xx01cyx** [comment]
> Looks good. Does ssl on rdkafka bring new dependencies?

Yes. We need to add `"ssl"` and `"sasl"` to `rdkafka` features in `Cargo.toml` (as below), which requires `libssl-dev` and `libsasl2-dev` installed in Linux.

```rust
rdkafka = { package = "madsim-rdkafka", version = "=0.2.8-alpha", features = ["cmake-build", "ssl", "sasl"] }
```

**Comment by skyzh** [comment]
libssl-dev should be included openssl crate and there's no need for developers to manually install it in package manager. The current situation sounds a little bit weird and I might need to do some investigation before merging.

**Comment by skyzh** [comment]
Should use `ssl-vendored` feature instead of `ssl`, depending on whether `static-link` feature is enabled in RisingWave or not.

**Comment by skyzh** [comment]
The same applies to sasl. Choose gssapi /gssapi-vendored based on whether static-link feature is enabled in RisingWave or not. We expect everything to be statically linked in the release binary, and dynamically linked in development mode.

**Comment by skyzh** [comment]
```
ldd target/debug/risingwave
        linux-vdso.so.1 (0x00007fffdc584000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fbff2c90000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbff2c74000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbff2c54000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbff2b6d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbff2945000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc00018d000)
```

**Review by tabVersion — APPROVED** [review]
LGTM! the pr is exactly what we need

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
risedev image is ready. Let's wait a few days before everyone starts using the new image, and merge this PR.

**Review by TennyZhuang — APPROVED** [review]
Great work!

**Comment by TennyZhuang** [comment]
Please resolve the conflicts 🥰

**Pull request merged**
