### PR TITLE
perf(stream): set `noop_update_hint` when jsonb access exists

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

As noted by a customer, we cannot eliminate the no-op `Update`s if the query is simple extracting fields from a `jsonb` payload. It's very likely that the payload changed but the needed fields are not changed. This PR set the no-op updates hint for such cases.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by BugenZhao — COMMENTED** [review]
Kind of hack to me 🥵

**Comment by stdrc** [comment]
> Kind of hack to me 🥵

Can we make it heuristic? Like, do the compaction at first, if there's no such no-op updates for a while, we can turn off automatically. We can still do compaction from time to time so that we can turn on again.

**Review by st1page — APPROVED** [review]
LGTM. Should we do this for all projects where the output columns do not include all the input columns

**Review by chenzl25 — APPROVED** [review]
Generally LGTM. It seems useful when mongodb source and schemaless kafka source are used,

**Pull request merged**
