### PR TITLE
fix(udf): add `embedded-python-udf` feature and fix dockerfile

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR makes `embedded-python-udf` an optional feature. This feature is not enabled by default so that developers are not required to have Python 3.12 installed. To enable it, you can run `ENABLE_PYTHON_UDF=1 ./risedev d` or `cargo build --features embedded-python-udf`. This feature is enabled in production build.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by fuyufjh — APPROVED** [review]
LGTM

**Comment by BugenZhao** [comment]
My concern is that off-by-default features could be fragile to maintain as most of the developers won't realize its existence. 😕 Fortunately, `check` on CI will run with all features. I hope this can enforce the functionality and quality.

https://github.com/risingwavelabs/risingwave/blob/06e28e8dec8b2f2f2ff16bd32f4bcfd79efeaa85/ci/scripts/check.sh#L24

**Review by xxchan — COMMENTED** [review]
release.sh is not updated 😄

**Comment by xxchan** [comment]
Hmmm, but if we enable it for binary release, users without python3.12 will not be able to start RisingWave. 🤔

**Comment by BugenZhao** [comment]
> Indeed... We should make it static linked.

Strong +1 for this. 🥺

----

Also I think it's okay to make it a default feature.
- It's not a big deal that developers need to install a new build-time dependency.
- If the developer is familiar with `cargo` and `rust-analyzer`, they can set `--no-default-features` to improve DX.
- All existing build scripts work well.

**Pull request merged**
