### PR TITLE
fix: Add check for iceberg test.

### LINKED ISSUE #14673: main-cron: end-to-end iceberg sink v2 test failed
```
  | Executing sql: SELECT * FROM demo_db.demo_table ORDER BY id, v1 ASC
  | Row(id=1, v1=1, v2=50, v3='1-50')
  | Row(id=1, v1=2, v2=2, v3='2-2')
  | Row(id=1, v1=5, v2=2, v3='5-2')
  | Row(id=1, v1=21, v2=2, v3='21-2')
  | Traceback (most recent call last):
  | File "/risingwave/e2e_test/iceberg/main.py", line 116, in <module>
  | verify_result(config,verify_sql,verify_schema,verify_data)
  | File "/risingwave/e2e_test/iceberg/main.py", line 65, in verify_result
  | tc.assertEqual(len(df), len(rows))
  | File "/usr/lib/python3.10/unittest/case.py", line 845, in assertEqual
  | assertion_func(first, second, msg=msg)
  | File "/usr/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
  | raise self.failureException(msg)
  | AssertionError: 4 != 7


```

This frequently occurred in recent tests. Examples above taken from https://buildkite.com/risingwavelabs/main-cron/builds/1539#018d184a-ef9b-4bd3-8fb0-2e4c659e3fda.

cc @liurenjie1024 Would you help to take a look?

### PR DESCRIPTION
**Pull request by liurenjie1024**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Close #14673 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by liurenjie1024** [comment]
cc @StrikeW Could you help to take a look at the cdc error? It reports following in cn log:
2024-01-19T08:25:48.642238088Z ERROR risingwave_stream::task::stream_manager: actor exit with error actor_id=10 error=Executor error: Connector error: MySQL error: Input/output error: Input/output error: can't parse: buf doesn't have enough data

**Comment by StrikeW** [comment]
I checked the log. The case fails in executing the `FLUSH` in `load.slt`.
cdc source, table and iceberg sink (not quite sure) are created successfully before.
```
2024-01-19T08:25:47.086996401Z  INFO risingwave_connector_node: Waiting for keepalive thread to start thread="debezium-mysqlconnector-RW_CDC_1001-change-event-source-coordinator" class="io.debezium.connector.mysql.MySqlStreamingChangeEventSource"
2024-01-19T08:25:47.087560952Z  INFO risingwave_connector_node: Creating thread debezium-mysqlconnector-RW_CDC_1001-binlog-client thread="blc-mysql:3306" class="io.debezium.util.Threads"
2024-01-19T08:25:47.187606448Z  INFO risingwave_connector_node: Keepalive thread is running thread="debezium-mysqlconnector-RW_CDC_1001-change-event-source-coordinator" class="io.debezium.connector.mysql.MySqlStreamingChangeEventSource"
2024-01-19T08:25:48.02996026Z  INFO risingwave_connector_node: Debezium streaming source of RW_CDC_1001 started thread="Thread-1" class="com.risingwave.connector.source.common.DbzSourceUtils"
2024-01-19T08:25:48.030094825Z  INFO risingwave_connector_node: engine#1001 start ok: true thread="Thread-1" class="com.risingwave.connector.source.core.DbzCdcEngineRunner"
2024-01-19T08:25:48.035254309Z  INFO risingwave_connector_node: Start consuming events of table 1001 thread="Thread-1" class="com.risingwave.connector.source.core.JniDbzSourceHandler"
2024-01-19T08:25:48.035328773Z  INFO risingwave_connector::source::cdc::source::reader: cdc connector started source_id=1001
2024-01-19T08:25:48.126703214Z  INFO aws_smithy_runtime::client::identity::cache::lazy: identity cache miss occurred; added new identity (took Ok(61.327Âµs))
2024-01-19T08:25:48.127163905Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:9301
2024-01-19T08:25:48.127385303Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:9301
2024-01-19T08:25:48.173631258Z  INFO risingwave_expr::sig: found 1130 functions
2024-01-19T08:25:48.178072619Z  INFO risingwave_stream::executor::backfill::cdc::cdc_backfill: start cdc backfill upstream_table_id=1003 upstream_table_name="my@db.products" initial_binlog_offset=Some(MySql(MySqlOffset { filename: "binlog.000002", position: 1454 })) current_pk_pos=None is_finished=false snapshot_row_count=0 chunk_size=256
2024-01-19T08:25:48.267867414Z  INFO risingwave_stream::executor::backfill::cdc::cdc_backfill: start cdc backfill loop upstream_table_id=1003 initial_binlog_offset=Some(MySql(MySqlOffset { filename: "binlog.000002", position: 1454 })) current_pk_pos=None
2024-01-19T08:25:48.270162315Z  INFO icelake::catalog: Loading catalog from configs: {"iceberg.table.io.root": "demo", "iceberg.table.io.region": "us-east-1", "iceberg.catalog.type": "storage", "iceberg.table.io.bucket": "icebergdata", "iceberg.catalog.name": "risingwave", "iceberg.table.io.disable_config_load": "true", "iceberg.table.io.secret_access_key": "hummockadmin", "iceberg.table.io.access_key_id": "hummockadmin", "iceberg.table.io.endpoint": "http://127.0.0.1:9301", "iceberg.catalog.risingwave.warehouse": "s3://icebergdata/demo"}
```

**Comment by liurenjie1024** [comment]
cc @StrikeW  
The flush failed because actor failed, and the cp can't finish. The only useful log I can find in cn log is following: 
```
2024-01-19T10:41:56.180091471Z ERROR risingwave_stream::task::stream_manager: actor exit with error actor_id=6 error=Executor error: Connector error: MySQL error: Input/output error: Input/output error: can't parse: buf doesn't have enough data

Backtrace:
   0: capture
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-ext-0.0.11/src/backtrace.rs:30:18
   1: thiserror_ext::ptr::ErrorBox<T,B>::new
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-ext-0.0.11/src/ptr.rs:40:33
   2: <risingwave_stream::executor::error::StreamExecutorError as core::convert::From<E>>::from
             at ./src/stream/src/executor/error.rs:31:35
   3: <T as core::convert::Into<U>>::into
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/convert/mod.rs:757:9
   4: risingwave_stream::executor::error::StreamExecutorError::connector_error
             at ./src/stream/src/executor/error.rs:31:55
   5: <risingwave_stream::executor::error::StreamExecutorError as core::convert::From<risingwave_connector::error::ConnectorError>>::from
             at ./src/stream/src/executor/error.rs:123:9
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/result.rs:1959:27
   7: {coroutine#0}<core::pin::Pin<&mut core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::row::owned_row::OwnedRow, risingwave_connector::error::ConnectorError>> + core::marker::Send), alloc::alloc::Global>>>, risingwave_connector::error::ConnectorError, risingwave_common::row::owned_row::OwnedRow>
             at ./src/stream/src/executor/backfill/utils.rs:597:10
   8: poll_next<risingwave_stream::executor::backfill::utils::iter_chunks::{coroutine_env#0}<core::pin::Pin<&mut core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::row::owned_row::OwnedRow, risingwave_connector::error::ConnectorError>> + core::marker::Send), alloc::alloc::Global>>>, risingwave_connector::error::ConnectorError, risingwave_common::row::owned_row::OwnedRow>, risingwave_common::array::stream_chunk::StreamChunk, risingwave_stream::executor::error::StreamExecutorError>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
   9: {coroutine#0}
             at ./src/stream/src/executor/backfill/cdc/upstream_table/snapshot.rs:77:5
  10: poll_next<risingwave_stream::executor::backfill::cdc::upstream_table::snapshot::{impl#2}::snapshot_read::{coroutine_env#0}, core::option::Option<risingwave_common::array::stream_chunk::StreamChunk>, risingwave_stream::executor::error::StreamExecutorError>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  11: poll_next<futures_async_stream::try_stream::GenTryStream<risingwave_stream::executor::backfill::cdc::upstream_table::snapshot::{impl#2}::snapshot_read::{coroutine_env#0}>, fn(core::result::Result<core::option::Option<risingwave_common::array::stream_chunk::StreamChunk>, risingwave_stream::executor::error::StreamExecutorError>) -> either::Either<core::result::Result<risingwave_stream::executor::Message, risingwave_stream::executor::error::StreamExecutorError>, core::result::Result<core::option::Option<risingwave_common::array::stream_chunk::StreamChunk>, risingwave_stream::executor::error::StreamExecutorError>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:58:26
  12: <rw_futures_util::pausable::Pausable<St> as futures_core::stream::Stream>::poll_next
             at ./src/utils/futures_util/src/pausable.rs:89:13
  13: poll_side<futures_util::stream::stream::map::Map<&mut futures_util::stream::stream::peek::Peekable<core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_stream::executor::Message, risingwave_stream::executor::error::StreamExecutorError>> + core::marker::Send), alloc::alloc::Global>>>, fn(core::result::Result<risingwave_stream::executor::Message, risingwave_stream::executor::error::StreamExecutorError>) -> either::Either<core::result::Result<risingwave_stream::executor::Message, risingwave_stream::executor::error::StreamExecutorError>, core::result::Result<core::option::Option<risingwave_common::array::stream_chunk::StreamChunk>, risingwave_stream::executor::error::StreamExecutorError>>>, rw_futures_util::pausable::Pausable<futures_util::stream::stream::map::Map<futures_async_stream::try_stream::GenTryStream<risingwave_stream::executor::backfill::cdc::upstream_table::snapshot::{impl#2}::snapshot_read::{coroutine_env#0}>, fn(core::result::Result<core::option::Option<risingwave_common::array::stream_chunk::StreamChunk>, risingwave_stream::executor::error::StreamExecutorError>) -> either::Either<core::result::Result<risingwave_stream::executor::Message, risingwave_stream::executor::error::StreamExecutorError>, core::result::Result<core::option::Option<risingwave_common::array::stream_chunk::StreamChunk>, risingwave_stream::executor::error::StreamExecutorError>>>>, risingwave_stream::executor::backfill::cdc::cdc_backfill::{impl#0}::execute_inner::{coroutine#0}::{closure_env#0}<risingwave_storage::monitor::monitored_store::MonitoredStateStore<alloc::boxed::Box<dyn risingwave_storage::store_impl::boxed_state_store::DynamicDispatchedStateStore, alloc::alloc::Global>>>, ()>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/select_with_strategy.rs:220:28
  14: futures_util::stream::select_with_strategy::poll_inner
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/select_with_strategy.rs:243:11
```
```
2024-01-19T10:41:56.56059552Z  INFO risingwave_connector_node: Engine#1001: JNI sender broken detected, stop the engine thread="Thread-1" class="com.risingwave.connector.source.core.JniDbzSourceHandler"
2024-01-19T10:41:56.560703154Z  INFO risingwave_connector_node: Stopping the embedded engine thread="Thread-1" class="io.debezium.embedded.EmbeddedEngine"
2024-01-19T10:41:56.560801687Z  INFO risingwave_connector_node: Waiting for PT5M for connector to stop thread="Thread-1" class="io.debezium.embedded.EmbeddedEngine"
2024-01-19T10:41:56.60142231Z  INFO risingwave_connector_node: Stopping the task and engine thread="rw-dbz-engine-runner-1001" class="io.debezium.embedded.EmbeddedEngine"
2024-01-19T10:41:56.60149364Z  INFO risingwave_connector_node: Stopping down connector thread="rw-dbz-engine-runner-1001" class="io.debezium.connector.common.BaseSourceTask"
Jan 19, 2024 10:41:56 AM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
INFO: threadExecutor is shut down, terminating keepalive thread
```

Is there anything wrong with our slt file for constructing cdc? https://github.com/risingwavelabs/risingwave/blob/e11830ca4352de53952832a5fd7fab926597764f/e2e_test/iceberg/test_case/cdc/load.slt

**Comment by StrikeW** [comment]
I have no idea why Flush causes the error. I will play with the FLUSH locally. The test script is not newly added, it should be fine in the main.

**Comment by liurenjie1024** [comment]
> I have no idea why Flush causes the error. I will play with the FLUSH locally. The test script is not newly added, it should be fine in the main.

Seems unable to reproduce locally

**Comment by StrikeW** [comment]
Or you can use the old syntax instead of the shared mysql source to inject the single cdc table in this case.

**Comment by liurenjie1024** [comment]
> Or you can use the old syntax instead of the shared mysql source to inject the single cdc table in this case.

Is there any doc for this?

**Comment by StrikeW** [comment]
> > Or you can use the old syntax instead of the shared mysql source to inject the single cdc table in this case.
> 
> 
> 
> Is there any doc for this?

https://docs.risingwave.com/docs/current/ingest-from-mysql-cdc/#create-a-table-using-the-native-cdc-connector-in-risingwave

**Review by tabVersion — APPROVED** [review]
the change LGTM, can merge as long as the test passes

**Pull request merged**
