### PR TITLE
feat(optimizer): support expr visitable for plan node

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Resolve https://github.com/risingwavelabs/risingwave/issues/13510
- Support ExprVisitable for each plan node so that there are no plan nodes missed.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by st1page — APPROVED** [review]

**Comment by BugenZhao** [comment]
If I understand correctly, the developers should manually ensure that the implementation is identical to `ExprRewritable`? Although it appears that there is no effective approach for reusing them in Rust.

**Comment by chenzl25** [comment]
> If I understand correctly, the developers should manually ensure that the implementation is identical to `ExprRewritable`? Although it appears that there is no effective approach for reusing them in Rust.

Yes. One is a mutable reference and the other one is an immutable reference.

**Review by xxchan — COMMENTED** [review]
> If we can visit the plan node to check whether we actually need to rewrite exprs we can save CPU cost.

Can you do that together and demonstrate how much improvement it provides? :eyes:

**Comment by chenzl25** [comment]
@xxchan Sure. It can reduce CPU from 2.2% to 0.2% for `inline_now_proc_time`.
Before:
image
After:
image

**Pull request merged**
