### PR TITLE
refactor(array): implement decimal array with primitive array

### LINKED ISSUE #6129: array: implement `DecimalArray` with `PrimitiveArray`
We can implement `PrimitiveType` for `Decimal`, so that the `DecimalArray` can be represented as `PrimitiveArray<Decimal>`. Here're two motivations.

- The code is heavily duplicated.
- We use `Decimal::to_string` when encoding to protobuf. This is really inefficient. 😄
https://github.com/risingwavelabs/risingwave/blob/a3fac7f792a3393e11e8e58c05c3ac0e324cd059/src/common/src/array/decimal_array.rs#L74-L87
- In favor of #6102.

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As explained in #6129.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- Close #6129

### CODE REVIEW

**Review by xxchan — COMMENTED** [review]
I didn't do it because of the encoding. https://github.com/risingwavelabs/risingwave/issues/2190

**Comment by BugenZhao** [comment]
What's the benefit for using the human-readable encoding? 🤔

**Comment by xiangjinwu** [comment]
> What's the benefit for using the human-readable encoding? 🤔

Because there was java frontend and we tried to keep the encoding neutral to libraries on either side (rust_decimal or java BigDecimal). Now that we have a unified ecosystem and it is easier to maintain encoding/decoding at a single place.

**Review by st1page — APPROVED** [review]
LGTM

**Pull request merged**
