### PR TITLE
feat(binder): bind watermark

### LINKED ISSUE #6704: Parse and bind Watermark TVF

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

as tile.
partially blocked by  #6951

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#6704

### CODE REVIEW

**Review by st1page — APPROVED** [review]
generally LGTM.
Btw, I think we can merge the `Relation::WindowTableFunction` and `Relation::Watermark` in the future. And we will have:
- `Relation::TableValueFunction`(current `TableFunction`) which accepts scalars and returns a relation
- `Relation::TableFunction`(current `Relation::WindowTableFunction` and `Relation::Watermark`) which accepts relations and returns a relation
in PG's user-facing conception, all functions can accept relation or scalar. And after the binder, we should distinguish these two cases, which makes the following plan phase easier.
c.c. @TennyZhuang @xiangjinwu @xxchan

**Comment by xxchan** [comment]
@st1page The names don't look good 🤪 BTW, what functions in PG can accept relation?

**Comment by st1page** [comment]
> @st1page The names don't look good zany_face BTW, what functions in PG can accept relation?

agree but I can not give a better name :crying_cat_face: 
Yes, you are right, PG seems can not accept table variables. :thinking:

**Comment by st1page** [comment]
> @st1page The names don't look good zany_face BTW, what functions in PG can accept relation?

c.c. @xxchan 
https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS:~:text=It%20is%20also%20possible%20to%20construct%20an%20array%20from%20the%20results%20of%20a%20subquery.

**Comment by xiangjinwu** [comment]
> > @st1page The names don't look good zany_face BTW, what functions in PG can accept relation?
> 
> c.c. @xxchan https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS:~:text=It%20is%20also%20possible%20to%20construct%20an%20array%20from%20the%20results%20of%20a%20subquery.

The array constructor cannot accept a table name (`t`), but only a subquery (`select * from t`). I also foresee this to be a `SubqueryExpr` rather than a function.

But there is another example in PostgreSQL we do see table name `t` used directly, as a tuple/row/struct type:
```
select t from t;
select array[t, null, t] from t;
select row(2, t, true) from t;
```

**Pull request merged**
