### PR TITLE
fix(udf): fix index-out-of-bound error when string or string list is large.

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

When outputting a large string or string array, Java UDF throws this exception:

```
java.lang.IndexOutOfBoundsException: index: 0, length: 50000 (expected: range(0, 32768))
        at org.apache.arrow.memory.ArrowBuf.checkIndex(ArrowBuf.java:701)
        at org.apache.arrow.memory.ArrowBuf.setBytes(ArrowBuf.java:765)
        at org.apache.arrow.vector.BaseVariableWidthVector.setBytes(BaseVariableWidthVector.java:1251)
        at org.apache.arrow.vector.BaseVariableWidthVector.set(BaseVariableWidthVector.java:1032)
        at com.risingwave.functions.TypeUtils.fillVector(TypeUtils.java:291)
        at com.risingwave.functions.TypeUtils.fillVector(TypeUtils.java:384)
        at com.risingwave.functions.TypeUtils.createVector(TypeUtils.java:188)
        at com.risingwave.functions.ScalarFunctionBatch.evalBatch(ScalarFunctionBatch.java:57)
        at com.risingwave.functions.UdfProducer.doExchange(UdfProducer.java:88)
        ...
```

The reason is that we don't specify **byte capacity** for string vectors and it seems not able to auto resize the buffer. This PR fixes this issue for varchar, bytea, and their array types.

## Checklist

- [ ] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

### CODE REVIEW

**Review by keven-huang — APPROVED** [review]

**Comment by keven-huang** [comment]
LGTM

**Review by xxchan — COMMENTED** [review]
Here's the reference: https://arrow.apache.org/docs/java/vector.html

> It is important that vector is allocated before attempting to read or write, ValueVector “should” strive to guarantee this order of operation: create > allocate > mutate > set value count > access > clear (or allocate to start the process over).

Alternative solution:
> 2) if we are not sure about the vector capacity, we should call the setSafe(index, value) method, which will automatically take care of vector reallocation, if the capacity is not sufficient.

**Review by xxchan — COMMENTED** [review]
I'm wondering whether current solution is efficient, or should we use `setSafe`

**Comment by wangrunji0408** [comment]
> I'm wondering whether current solution is efficient, or should we use `setSafe`

Thanks for your info. I think we have set a precise capacity so `set` should be enough.

**Comment by xxchan** [comment]
I mean I'm not sure which method's overhead is smaller. 🤪 

But anyway

**Comment by wangrunji0408** [comment]
> I mean I'm not sure which method's overhead is smaller. 🤪
> 
> But anyway

Do you mean `setSafe` may be more efficient than "count + preallocate + set"? 🤔

**Comment by xxchan** [comment]
Yes

**Comment by xxchan** [comment]
But I don't care much. Just mention it. 🤪

**Pull request merged**
