### PR TITLE
feat: upgrade tokio version to 1.38.0

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by xxchan** [comment]
Hi, any update? (specifically, any test plan? or it's considered harmless and we can directly merge? https://github.com/risingwavelabs/risingwave/pull/17528#pullrequestreview-2153119218)

**Comment by wenym1** [comment]
> Hi, any update? (specifically, any test plan? or it's considered harmless and we can directly merge? [#17528 (review)](https://github.com/risingwavelabs/risingwave/pull/17528#pullrequestreview-2153119218))

I ran the [sysbench](https://buildkite.com/risingwave-test/sysbench/builds?branch=main) for 2 times (sysbench run #(810, 812)). The test result seems harmless when I have a glance on some bench stats. Later I didn't have bandwidth to continue doing more tests. Feel free to take over if it needs to be prioritized.

**Comment by wenym1** [comment]
Ran the nexmark benchmark. Upgrading the tokio version no significant impact on performance.

image


Full result is [here](http://metabase.risingwave-cloud.xyz/question/2219-nexmark-rw-compare?risingwave_tag_1=nightly-20240807&rw_label_1=medium-1cn-anti-affinity&risingwave_metrics=avg-source-output-rows-per-second&risingwave_tag_2=20240809-tokio-1.38.0&rw_label_2=medium-1cn-anti-affinity-tokio-1.38.0)

**Comment by wenym1** [comment]
Also running a [longevity test](https://buildkite.com/risingwave-test/longevity-test/builds/1743#0191451e-2149-486c-8b46-740df3b4fedf)

**Review by BugenZhao — APPROVED** [review]

**Review by xxchan — APPROVED** [review]
Thank you for driving this!

**Pull request merged**
