### PR TITLE
feat(stream agg): add agg state cache miss ratio metric

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR adds metric to track the cache miss ratio for agg state cache of `min`/`max`/`first_value` and so on, so that we can adjust `extreme_cache_size` config value accordingly.

## Checklist

- [x] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by stdrc** [comment]
* **#18900** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/18900?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stdrc and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by st1page — COMMENTED** [review]
LGTM, would you please send me some context if there is such a case with low cache miss rate? I think it will only happen when there are lots of delete message and I'd like to know it more

**Review by st1page — APPROVED** [review]

**Review by KeXiangWang — APPROVED** [review]
LGTM. 

Is it possible to add some logs/metrics to monitor the amplification rate of agg? Just like for Join amp.

**Comment by stdrc** [comment]
> Is it possible to add some logs/metrics to monitor the amplification rate of agg?

What do you mean by agg amplification? I guess agg only have inner amplification when computing calls like `string_agg`, `array_agg` or `aggregate:`-prefixed UDF.

**Comment by kwannoel** [comment]
> > Is it possible to add some logs/metrics to monitor the amplification rate of agg?
> 
> What do you mean by agg amplification? I guess agg only have inner amplification when computing calls like `string_agg`, `array_agg` or `aggregate:`-prefixed UDF. It's more a redundant computation than amplification.

I think it's more like a metric of the number of group keys being updated. It's not really an amplification per se. It's just called that because of its relation to join amplification. Join amplification can result in a large number of updates.

**Comment by stdrc** [comment]
> He's asking for a metric of the number of group keys being updated.

Then I guess it's already monitored by `Dirty Group Count` metric.

**Pull request merged**
