### PR TITLE
fix(deterministic-test): disable telemetry

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Closes https://github.com/risingwavelabs/risingwave/issues/9661

Disable for flamegraph gen too.

Otherwise in ci this should already be disabled.

## Checklist For Contributors

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [ ] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
I guess this is already achieved by the env var?

https://github.com/risingwavelabs/risingwave/blob/0dc8b251197a857f5682e3d22ce77c6f7770ba98/ci/scripts/common.sh#L6

**Comment by fuyufjh** [comment]
> I guess this is already achieved by the env var?
> 
> https://github.com/risingwavelabs/risingwave/blob/0dc8b251197a857f5682e3d22ce77c6f7770ba98/ci/scripts/common.sh#L6

I thought it was. @kwannoel Can you please confirm it? The telemetry must have logs somewhere I guess...

**Comment by kwannoel** [comment]
It currently is disabled for everything else as long as `ENABLE_TELEMETRY` is set. Just verified it locally with `export ENABLE_TELEMETRY=false`.

I was searching for `TELEMETRY_ENABLED` and couldn't find it 🤦 .

Compute logs:
```
2023-05-08T10:22:03.426048Z  INFO risingwave_compute::server: Telemetry didn't start due to config
```

I guess the real solution is what @BugenZhao mentioned: https://github.com/risingwavelabs/risingwave/issues/9661#issuecomment-1538105448.

Will update this PR.

**Comment by kwannoel** [comment]
Fails because we expect `example.toml` to have static defaults after https://github.com/risingwavelabs/risingwave/pull/9656. I will revert to just using a custom config.toml for deterministic tests.

**Pull request merged**
