### PR TITLE
refactor(batch): fine-grained serving vnode mapping rebalance

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR makes two improvement related to vnode mapping strategy for serving:
1.  rebalance: Inspired by [Straw Buckets](https://github.com/ceph/libcrush/blob/de2e859acd5e52b6db3cf8cde08834e09b8d4ead/crush/mapper.c#LL227C23-L227C23) in Ceph's CRUSH, we uses similar idea to minimize data relocation after addition or removal of serving worker nodes.
2. availability: When a worker node is likely encountering network issue, we **temporarily** mark it as failed, and use a new **temporarily** serving vnode mapping excluding all failed worker nodes. This way, we can achieve high availability of serving cluster. Note that we don't implement auto retry in frontend. So when transient error happens, the first query will fail and any following query will succeed.

#8940

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [ ] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by zwang28** [comment]
Compared with maintaining vnode mapping in meta node, I prefer decentralized method, which is the current implementation for serving:
1. If we go the meta node way, whenever a rebalance is required, we need do it for all mapping for all fragments, and persist it. Persisting streaming vnode mapping has already caused [problems](https://github.com/risingwavelabs/risingwave/issues/7728).
2. Unlike the streaming vnode mapping, which must be followed strictly, serving vnode mapping is just a hint for better data locality. Because we can actually access checkpoint data from any compute nodes.

**Comment by zwang28** [comment]
The core function `map_vnode_for_serving` takes some parallel units, and tries to map all vnodes to them, in a balanced fashion deterministically. As `map_vnode_for_serving` only leads to a **probabilistically** balanced distribution. I run micro bench to illustrate how it perform in practice. Each run of the bench 256 vnodes to n parallel units for 1000 fragments, with random fragment id and random parallel unit id.

The ratio below shows how many given parallel units have been assigned at least one vnode. In a perfect mapping, it should be 100%. Take the worst case of "256 parallel units", 57.8125% roughly means a parallel unit is assigned 2 vnodes, while ideally it should be 1.

256 parallel units:
```
1000 runs
min 148/256 57.8125%
p10 155/256 60.546875%
p50 162/256 63.28125%
p90 168/256 65.625%
max 176/256 68.75%
```

128 parallel units:
```
1000 runs
min 98/128 76.5625%
p10 107/128 83.59375%
p50 111/128 86.71875%
p90 115/128 89.84375%
max 120/128 93.75%
```

**Comment by zwang28** [comment]
The core function `map_vnode_for_serving` takes some parallel units, and maps all vnodes to them deterministically. As `map_vnode_for_serving` only leads to a **probabilistically** balanced distribution, I run micro bench `bench_map_vnode_for_serving` to illustrate how it perform in practice. Each run of the bench maps 256 vnodes to n parallel units for 1000 fragments, with random fragment id and random parallel unit id.

**In short, vnode distribution it produces is not as balanced as expected.**

The ratio below shows how many given parallel units have been assigned at least one vnode. Take the worst case of "256 parallel units", 57.8125% roughly means half of available parallel units are assigned 2 vnodes each on average, and half of available parallel units are not used. But ideally each available parallel unit should be assigned exactly 1 vnode.

256 parallel units:
```
1000 runs
min 148/256 57.8125%
p10 155/256 60.546875%
p50 162/256 63.28125%
p90 168/256 65.625%
max 176/256 68.75%
```

128 parallel units:
```
1000 runs
min 98/128 76.5625%
p10 107/128 83.59375%
p50 111/128 86.71875%
p90 115/128 89.84375%
max 120/128 93.75%
```

64 parallel units:
```
1000 runs
min 59/64 92.1875%
p10 61/64 95.3125%
p50 63/64 98.4375%
p90 64/64 100%
max 64/64 100%
```

**Comment by BugenZhao** [comment]
> * If we go the meta node way, whenever a rebalance is required, we need do it for all mapping for all fragments, and persist it. Persisting streaming vnode mapping has already caused [problems](https://github.com/risingwavelabs/risingwave/issues/7728).

As you've mentioned, the "vnode mapping is just a hint" here. So is it possible that we make it centralized to the meta service but not persisted?
- Once there's some configuration change for the serving nodes in the cluster, the meta node can sense this and broadcast the new mapping.
- If the meta service fails, we can rebuild the mapping from scratch.

**Comment by zwang28** [comment]
> make it centralized to the meta service but not persisted

Make sense. 
Although the mapping rebuilt from scratch may not match exactly with the one before meta fails, the difference should be small.

**Comment by zwang28** [comment]
Replace with #10004

**Pull request closed without merging**
