### PR TITLE
chore(deps): migrate adhoc `@dependabot ignore` commands to `dependabot.yml`

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
> Dependencies can be ignored either by adding them to `ignore` or by using the `@dependabot ignore` command on a pull request opened by Dependabot.
>
> Dependencies ignored by using the `@dependabot ignore` command are stored centrally for each package manager. If you start ignoring dependencies in the `dependabot.yml` file, these existing preferences are considered alongside the `ignore` dependencies in the configuration.
>
> You can check whether a repository has stored `ignore` preferences by searching the repository for `"@dependabot ignore" in:comments`, or by using the `@dependabot show DEPENDENCY_NAME ignore conditions` comment command. If you wish to unblock updates for a dependency ignored this way, re-open the pull request. This clears the `ignore` conditions that were set when the pull request was closed and resumes those Dependabot updates for the dependency. To update the dependency to a newer version, merge the pull request. In pull requests for grouped updates, you can also use the `@dependabot unignore` commands to clear `ignore` settings for dependencies.

Comparison of the two approaches:
* View
  * File: Read the yml file 😃
  * Command: Read the log, or search for `"@dependabot ignore" in:comments` 😞
* Add (ignore)
  * File: Edit the yml file with a PR 😑
  * Command: Comment on the PR, or simply close the PR 😃
* Del (unignore)
  * File: Edit the yml file with a PR 😑
  * Command: Reopen the PR, or comment on (possibly another irrelevant) grouped update PR 😞

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by xxchan** [comment]
I guess we don't need to ignore them for now. 🤡

For new ones we want to ignore in the future, we can do this.

**Comment by xiangjinwu** [comment]
> I guess we don't need to ignore them for now. 🤡
> 
> For new ones we want to ignore in the future, we can do this.

Are you suggesting we simply `unignore` all of them right now (via commenting, as reopening PRs is definitely not an option)?

**Comment by xxchan** [comment]
I'm thinking why to add them? This will not cancel the effect of the ignore commands.

**Comment by xiangjinwu** [comment]
If this PR is merged, my next step would be to `unignore` them from the commands storage, hence the title `migrate`.

**Comment by xxchan** [comment]
I think we can just do the next step first, and add ignore in file later when necessary. In this way, we can revisit whether and why they need to be ignored.

**Comment by xiangjinwu** [comment]
unignored everything from the commands. Let's wait and see which ones shall be added back.

**Pull request closed without merging**
