### PR TITLE
chore(risedev): update the version and script of connector node component

### PR DESCRIPTION
**Pull request by StrikeW**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
Update the version and auto-download script of connector node component. Since the connector node is still private, we release it via another [public repo](https://github.com/risingwavelabs/risingwave-connector-release/).

Currently, only CDC source connectors are released to the repo. Because the size of our sink connectors is quite large (including a 200MB dependency). It will be time-consuming to download such a huge file.

## Checklist

~- [ ] I have written necessary rustdoc comments~
~- [ ] I have added necessary unit tests and integration tests~
~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by fuyufjh** [comment]
From my best understanding, `risedev` is a tool for RisingWave developers like us. So how can I start up a connector process when I develop RW locally?

**Comment by StrikeW** [comment]
> From my best understanding, `risedev` is a tool for RisingWave developers like us. So how can I start up a connector process when I develop RW locally?

Because the connector node repo is private. For internal developers, it is better to clone the private repo and build it by maven. For community developers, I think they can start a docker container for it after we release the docker image of the connector node.

**Comment by StrikeW** [comment]
Any further comments? PTAL, thank you. @fuyufjh @liurenjie1024 @tabVersion

**Comment by fuyufjh** [comment]
> > From my best understanding, `risedev` is a tool for RisingWave developers like us. So how can I start up a connector process when I develop RW locally?
> 
> Because the connector node repo is private. For internal developers, it is better to clone the private repo and build it by maven. For community developers, I think they can start a docker container for it after we release the docker image of the connector node.

It seems to be a really bad experience for community developers...

**Comment by fuyufjh** [comment]
As far as I know, many developers dread Docker in their local laptop, and many community *users* (not developer) actually try RisingWave via `risedev`

**Comment by liurenjie1024** [comment]
I agree that we should keep the original way of downloading the connector node jar in risedev rather than forcing community developers to use docker.

**Comment by StrikeW** [comment]
Got it. Currently the script is outdated, the downloaded jar doesn't match kernel. After I finish refactoring the project layout of connector node, I'll update it.

**Review by tabVersion — APPROVED** [review]
basically LGTM

**Review by fuyufjh — APPROVED** [review]

**Review by liurenjie1024 — APPROVED** [review]
LGTM

**Pull request merged**
