### PR TITLE
fix: Fix task leak when task failed

### PR DESCRIPTION
**Pull request by liurenjie1024**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix scheduler logic to avoid task leak when batch task failed.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

### CODE REVIEW

**Review by chenzl25 — APPROVED** [review]
LGTM

**Review by xx01cyx — APPROVED** [review]
LGTM

**Comment by CharlieSYH** [comment]
@liurenjie1024 This is a bug fix, not a user-facing change. Reply to let me know if this pr contains notable changes other than bug fixes. Currently, release notes do not reflect performance improvement or bug fixes.

**Comment by liurenjie1024** [comment]
> @liurenjie1024 This is a bug fix, not a user-facing change. Reply to let me know if this pr contains notable changes other than bug fixes. Currently, release notes do not reflect performance improvement or bug fixes.

Yes, sorry for wrong label.

**Pull request merged**
