### PR TITLE
chore(ci): rework ci labels used to trigger workflows

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Closes https://github.com/risingwavelabs/risingwave/issues/17182.

Improvements:
1. User has less tags to add now to trigger specific workflows. They no longer need to add labels for the dependent steps.
2. The tags are more straightforward `run-selected` is clearer than `skip-ci`.

See the developer guide for more info, or the labels in this PR.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
Does the `ci/main-cron/run-selected` tag seem to be redundant? (Also a bit counter-intuitive to me)

How about

- `ci/main-cron/run-all` runs all `main-cron` tests
- [`ci/main-cron/foo`, `ci/main-cron/bar`] runs `foo` and `bar`

**Review by huangjw806 — APPROVED** [review]
LGTM!

**Comment by fuyufjh** [comment]
> Just took a look at buildkite's conditional expression support. To support this, we need to check for `ci/main-cron/run-*` inside the PR label, in order to decide whether or not to run the main-cron steps.
> 
> But the conditional expression support is kind of limited. https://buildkite.com/docs/pipelines/conditionals#variable-and-syntax-reference.
> 
> It supports regex, but not for `array`, which is the type of the PR labels in buildkite. For array it only supports `includes`.

I mean, taking `e2e-test-release` as an example, it should be like

```yaml
key: "e2e-test-release"
    command: "ci/scripts/cron-e2e-test.sh -p ci-release -m ci-3streaming-2serving-3fe"
    if: |
      build.pull_request.labels includes "ci/main-cron/run-all"
      || build.pull_request.labels includes "ci/run-e2e-test" 
      || build.env("CI_STEPS") =~ /(^|,)e2e-tests?(,|$$)/
    depends_on:
```

What do you think?

**Comment by fuyufjh** [comment]
Just get to know that there is another condition in [pipeline's setting](https://buildkite.com/risingwavelabs/main-cron/settings/repository): 

```
(build.pull_request.id != null && (build.pull_request.labels includes "ci/main-cron/run-all" || build.pull_request.labels includes "ci/main-cron/run-selected"))  || build.tag != null
```

Thus it seems inevitable to introduce a `run-selected`, because BuildKite doesn't allow to match a value in `Array` via regex.

**Pull request merged**
