### PR TITLE
chore(java-binding): refine stream chunk benchmark

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Previously in the stream chunk benchmark, we generate a stream chunk iterator for each invocation of the benchmark, which affects the accuracy of the measured time of the invocation. In this PR, we change to pre-generate a list of stream chunk to be used in the setup phase, and then in the benchmark method invocation only the iteration on the iterator will be measured.

Besides, for array list benchmark, we change to generate a new row in each loop instead of always reusing a same row. This will be fairer for the stream chunk benchmark.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by yufansong — APPROVED** [review]
LGTM！

**Review by yufansong — COMMENTED** [review]
Wait, I have one question, why we need to move list array construction out of the setup? 
In previous, we construct both array list and stream chunk list in setup. Then call it in each test. 
But now, in each out call the function, for arraylist, it need construct and call get row. But for streamchunk, it seems only need to invoke the jni?

**Comment by wenym1** [comment]
> Wait, I have one question, why we need to move list array construction out of the setup?
In previous, we construct both array list and stream chunk list in setup. Then call it in each test.
But now, in each out call the function, for arraylist, it need construct and call get row. But for streamchunk, it seems only need to invoke the jni?

Here we actually want to compare the cost of constructing a row. If we pre-generate an array list and get its rows, we lost track of the cost of constructing the row, and I think this is unfair for the stream chunk. So in this PR we change to constructing a new row in each loop.

**Comment by yufansong** [comment]
> > Wait, I have one question, why we need to move list array construction out of the setup?
> > In previous, we construct both array list and stream chunk list in setup. Then call it in each test.
> > But now, in each out call the function, for arraylist, it need construct and call get row. But for streamchunk, it seems only need to invoke the jni?
> 
> Here we actually want to compare the cost of constructing a row. If we pre-generate an array list and get its rows, we lost track of the cost of constructing the row, and I think this is unfair for the stream chunk. So in this PR we change to constructing a new row in each loop.

But for streamchunk, in this pr, i think we also construct it in setup. And in each loop we only construct a new JavaBindingRow. Should we only count the construction time of JavaBindingRow, and ignore the construction time of streamchunk?

**Comment by wenym1** [comment]
> But for streamchunk, in this pr, i think we also construct it in setup. And in each loop we only construct a new JavaBindingRow. Should we only count the construction time of JavaBindingRow, and ignore the construction time of streamchunk?

We already did it. The stream chunk iterator is pre-constructed in setup, which is invoked before 10 rounds of stream chunk iterator tests, and it will not be counted in the construction time of row, and in the following 10 rounds of tests, in each loop we only construct and read a row. The behavior is aligned in the array list test, which in each loop also constructs a row and read it.

**Pull request merged**
