### PR TITLE
refactor(batch): set VISIBILITY_MODE to all by default

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

- Add `validate_read_epoch` in `StateStore` trait. `StorageTable` uses it to verify whether any recover occurs during its read. It so, the read result is invalidated and the batch query is aborted. 
- Set VISIBILITY_MODE to all by default.
- ~~Implement try_wait_epoch for non-checkpoint epoch.~~
  - ~~It's necessary because a restarted CN cannot ensure seal_epoch >= uncommitted_read_epoch from batch query.~~
- Temporarily revert FLUSH to always enforce a checkpoint.
  - We will adopt CHECKPOINT in another PR because there will be considerable changes to test scripts.

## Checklist

- [x] I have written necessary rustdoc comments
~~- [ ] I have added necessary unit tests and integration tests~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* SQL commands, functions, and operators

### Release note

Support VISIBILITY_MODE session variable. It's set to ALL by default.

### CODE REVIEW

**Comment by zwang28** [comment]
Need implement try_wait_epoch for current_epoch, because compute node's sealed_epoch is transient (thus recovery test fails).

**Comment by hzxa21** [comment]
> Need implement try_wait_epoch for current_epoch, because compute node's sealed_epoch is transient (thus recovery test fails).

Discussed offline: waiting current epoch to bump on recovery can still cause correctness issue. Consider the following case:
- We have CN [1, 2] and epoch [1, 2, 3] with 
  - epoch 1 as the checkpoint epoch
  - epoch 2 as the non-checkpoint epoch
  - epoch 3 as the recovery epoch
- CN2 restarts after epoch2 and CN1 remains healthy
- While CN2's recovery is still in-progress, frontend holds epoch2 to read from CN1 and CN2
- With try_wait_epoch for current_epoch, CN1 will serve read using data from epoch2 while CN2 will serve read using data from epoch3 (which is equivalent to serving data from epoch1)


@zwang28 also pointed out that the read results from non-restarted CNs on recovery is also non-determinitistic. In the above example, CN1 can serve read using data from epoch2 or epoch3 depending on the progress of the recovery process.

**Comment by zwang28** [comment]
We address the correctness issue https://github.com/risingwavelabs/risingwave/pull/7188#issuecomment-1376718485 as follows:
 - Maintain a `min_current_epoch` in `HummockStorage`.
   - min_current_epoch is initialized as latest MCE.
   - min_current_epoch is set to epoch::MAX whenever `clear_shared_buffer`, before` HummockEvent::Clear` takes effect. It means recovery is in process and no current_epoch read is allowed.
   - min_current_epoch is set to the new epoch whenever a checkpoint is sealed AND min_current_epoch == epoch::MAX. It means a recovery is finished and valid current_epoch starts from the new epoch.
 - Add a `validate_read_epoch`, which requires min_current_epoch <= read_current_epoch <= seal_epoch, otherwise raises error.
 - We call `validate_read_epoch` after `StateStore::get/StateStore::iter` in `StorageTable`, paired with `try_wait_epoch`.
   - Actually we can make `validate_read_epoch` private to `HummockStorage`, and call it just after `HummockStorage::build_read_version_tuple`. But `StateStore::get/StateStore::iter` doesn't know about `HummockReadEpoch` and we'd like to keep the interface unchanged.

Here some examples to show how it works :
epoch_1 is checkpoint
epoch_2 is non-checkpoint
epoch_3 is non-checkpoint
epoch_4 is checkpoint emitted by recovery process

Case 1 compute node that is restarted:  
1. The compute node seals epoch_2. min_current_epoch=[some epoch < epoch_2], seal_epoch=epoch_2
2. The compute node restarted. 
3. The compute node is initilaized with min_current_epoch=epoch_1, seal_epoch=epoch_1.
4. epoch_3 is scheduled by meta.
5. The compute node cannot seal epoch_3 because it's LocalBarrierManager state is not recovered yet.
6. Recovery starts.
7. `clear_storage_buffer` is called. set min_current_epoch to epoch::MAX.
8. The compute node seal epoch_4, set min_current_epoch to 4, seal_epoch to epoch_4.

Any batch query with current_epoch_2 after step 2 will be rejected by `validate_read_epoch`.

Case 2 compute node that is not restarted:
1. The compute node seals epoch_2. min_current_epoch=[some epoch < epoch_2], seal_epoch=epoch_2
2. epoch_3 is scheduled by meta.
3. The compute node seals epoch_3. min_current_epoch=[some epoch < epoch_2], seal_epoch=epoch_3
4. Recovery starts.
5. `clear_storage_buffer` is called. set min_current_epoch to epoch::MAX.
6. The compute node seal epoch_4, set min_current_epoch to 4, seal_epoch to epoch_4.

Any batch query with current_epoch_2 after step 5 will be rejected by `validate_read_epoch`.

**Comment by zwang28** [comment]
A bit surprise that the recovery test doesn't fail, because batch query a restarted compute node with an current epoch < recovery checkpoint's epoch should fail with "cannot read current epoch because read epoch {} > sealed epoch {}".
Notice recovery test will auto retry failed queries for times. I think this hides the failure. Verifying.

**Comment by hzxa21** [comment]
> But currently StateStore::get/StateStore::iter doesn't know about HummockReadEpoch while validate_read_epoch needs it. I prefer to make validate_read_epoch private to HummockStorage, rather than expose it via StateStore trait.

+1. Shall we change the StateStore read interfaces to take HummockReadEpoch instead of u64 then?

**Comment by hzxa21** [comment]
> We address the correctness issue [#7188 (comment)](https://github.com/risingwavelabs/risingwave/pull/7188#issuecomment-1376718485) as follows:
> 
> * Maintain a `min_current_epoch` in `HummockStorage`.
>   
>   * min_current_epoch is initialized as latest MCE.
>   * min_current_epoch is set to epoch::MAX whenever `HummockStorage::clear_shared_buffer`, before `HummockEvent::Clear` takes effect. **It means recovery is in process and no current_epoch read is allowed.**
>   * min_current_epoch is set to the new epoch whenever a checkpoint is sealed AND min_current_epoch == epoch::MAX. **It means recovery is finished and valid current_epoch starts from the new epoch.**
> * Add a `validate_read_epoch`, which requires min_current_epoch <= read_current_epoch <= seal_epoch, otherwise raises error.
> * We call `validate_read_epoch` after `StateStore::get/StateStore::iter` in `StorageTable`, paired with `try_wait_epoch`.
>   
>   * Actually we can make `validate_read_epoch` private to `HummockStorage`, and call it inside `StateStore::get/StateStore::iter` after `HummockStorage::build_read_version_tuple`. But currently `StateStore::get/StateStore::iter` doesn't know about `HummockReadEpoch` while `validate_read_epoch` needs it. I prefer to make `validate_read_epoch` private to `HummockStorage`, rather than expose it via `StateStore` trait. @wenym1
> 
> Here some examples to show how it works :
> 
> epoch_1 is checkpoint epoch_2 is non-checkpoint epoch_3 is non-checkpoint epoch_4 is checkpoint emitted by recovery process
> 
> Case 1 compute node that is restarted:
> 
> 1. The compute node seals epoch_2. min_current_epoch=[some epoch <= epoch_1], seal_epoch=epoch_2
> 2. The compute node is restarted.
> 3. The compute node is initialized with min_current_epoch=epoch_1, seal_epoch=epoch_1.
> 4. epoch_3 is scheduled by meta.
> 5. The compute node cannot seal epoch_3 because its actors are not recovered yet.
> 6. Recovery starts.
> 7. `clear_storage_buffer` is called. set min_current_epoch to epoch::MAX.
> 8. The compute node seal epoch_4, set min_current_epoch to 4, seal_epoch to epoch_4.
> 
> Any batch query with epoch_2 after step 2 will be rejected by `validate_read_epoch`.
> 
> * For step 2 - step 6, the error message will be "cannot read current epoch because read epoch {} > sealed epoch {}".
> * For step 7 and above, the error message will be "cannot read current epoch because read epoch {} < min current epoch {}".
> 
> Case 2 compute node that is not restarted:
> 
> 1. The compute node seals epoch_2. min_current_epoch=[some epoch <= epoch_1], seal_epoch=epoch_2
> 2. epoch_3 is scheduled by meta.
> 3. The compute node seals epoch_3. min_current_epoch=[some epoch <= epoch_1], seal_epoch=epoch_3
> 4. Recovery starts.
> 5. `clear_storage_buffer` is called. set min_current_epoch to epoch::MAX.
> 6. The compute node seal epoch_4, set min_current_epoch to 4, seal_epoch to epoch_4.
> 
> Any batch query with epoch_2 after step 5 will be rejected by `validate_read_epoch`.
> 
> @hzxa21 PTAL


Good idea. Overall looks good and it enlights me to think of a potential issue and an improvement:

### Issue
IIUC, under this proposal, it is possible that we reject a read even when there is no recovery due to async notification of epoch updates. Consider the following example:
```
epoch_1 is non-checkpoint
epoch_2 is checkpoint
```
1. FE uses `epoch_1` for a batch read
2. CN seals `epoch_2` and bumps `min_current_epoch` to `epoch_2`
3. Batch read issued by 1 reaches the CN. `validate_read_epoch` fails because `read_epoch = epoch_1 < min_current_epoch = epoch_2`.


### Improvement
To solve the above issue, we can simply avoid updating `min_current_epoch` on every checkpoint. The update rules become:
- Set `min_current_epoch = MCE` and `sealed_epoch = MCE` on CN bootup.
- Set `min_current_epoch = MAX` when recovery is in-progress (before `clear_storage_buffer`).
- Set `min_current_epoch = sealed_epoch` only on sealing the recovery epoch (guaranteed to happen after `clear_storage_buffer`).

Let's see whether there is any pitfall and continue the discussion next week.

**Comment by zwang28** [comment]
> Set min_current_epoch = sealed_epoch only on sealing the recovery epoch (guaranteed to happen after clear_storage_buffer).

Yes, this's what I mean by

> min_current_epoch is set to the new epoch whenever a checkpoint is sealed AND min_current_epoch == epoch::MAX.

**Comment by hzxa21** [comment]
> > Set min_current_epoch = sealed_epoch only on sealing the recovery epoch (guaranteed to happen after clear_storage_buffer).
> 
> Yes, this's what I mean by
> 
> > min_current_epoch is set to the new epoch whenever a checkpoint is sealed AND min_current_epoch == epoch::MAX.

Ah I see. I misunderstood. Make sense.

**Comment by zwang28** [comment]
> A bit surprise that the recovery test doesn't fail, because batch query a restarted compute node with a current epoch < recovery checkpoint's epoch should fail.

Verified it's just because recovery test doesn't trigger any case that read current epoch < min_current_epoch or read current epoch > sealed_epoch, i.e. `validate_read_epoch` never fails.

**Review by hzxa21 — APPROVED** [review]
Rest LGTM. Thanks for the PR!

**Comment by zwang28** [comment]
> > A bit surprise that the recovery test doesn't fail, because batch query a restarted compute node with a current epoch < recovery checkpoint's epoch should fail.
> 
> Verified it's just because recovery test doesn't trigger any case that read current epoch < min_current_epoch or read current epoch > sealed_epoch, i.e. `validate_read_epoch` never fails.

After merging main, the recovery test triggers both "current epoch < min_current_epoch" failure and "current epoch > sealed_epoch" failure as expected.
Fixing the recovery test.

**Comment by zwang28** [comment]
> Shall we change the StateStore read interfaces to take HummockReadEpoch instead of u64 then

I suggest to address this refactor in another PR. Likely lots test cases need to be touched.

**Pull request merged**
