### PR TITLE
feat: replace icelake Transform with iceberg

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
remove icelake in frontend and sink

https://github.com/risingwavelabs/risingwave/issues/17548

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by xxchan** [comment]
* **#18625** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/18625?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @xxchan and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by stdrc — APPROVED** [review]
lgtm

**Comment by xxchan** [comment]
😟
```
--- STDERR:              risingwave_planner_test::planner_test_runner sink ---
  | thread '<unnamed>' panicked at src/connector/src/connector_common/iceberg/mock_catalog.rs:279:26:
  | called `Result::unwrap()` on an `Err` value: FeatureUnsupported => Can't create table with partition spec now
 

<br class="Apple-interchange-newline">
```

**Review by chenzl25 — COMMENTED** [review]
We have an expression [IcebergTransform](https://github.com/risingwavelabs/risingwave/blob/c6db8013319c4f540f9b2c93fc1671472e3757b2/src/expr/impl/src/scalar/external/iceberg.rs#L34) which use icelake as an implementation. Can we use iceberg-rust mixed with it?

**Comment by chenzl25** [comment]
One known issue with partition is that if the table's partition changes later, we cannot write the partition value based on the expression used when creating the sink. Instead, we should use Iceberg's hidden partition capability to calculate it ourselves.

**Comment by xxchan** [comment]
> We have an expression [IcebergTransform](https://github.com/risingwavelabs/risingwave/blob/c6db8013319c4f540f9b2c93fc1671472e3757b2/src/expr/impl/src/scalar/external/iceberg.rs#L34) which use icelake as an implementation. Can we use iceberg-rust mixed with it?

This is already changed together in the PR



> One known issue with partition is that if the table's partition changes later, we cannot write the partition value based on the expression used when creating the sink. Instead, we should use Iceberg's hidden partition capability to calculate it ourselves.

I’m aware of this issue. Let’s just do the simple “translation” first, and fix logic issue later

**Review by chenzl25 — APPROVED** [review]
LGTM, thanks!

**Comment by xxchan** [comment]
It needs more work in iceberg-rs. I'm focused on releasing shared source now, and will continue later.

**Pull request merged**
