### PR TITLE
feat(optimizer): Only accept scalar subquery can guarantee at most one row at compile time

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- In this PR, we only accept scalar subquery can guarantee at most one row in compile time for batch and stream.
- Batch scalar subquery can support runtime detection later.
- Planner always convert subquery to `Apply`
- Use `MaxOneRowEliminateRule` to eliminate max one row restriction from `Apply`.
- Use `ApplyToJoinRule` to convert an uncorrelated `Apply` to `Join`.
- `max_one_row` of `Apply` means if the subquery produces more than one result we have to report an error.
- For streaming, ~~the only way to eliminate the `max_one_row` of correlated `Apply` is through scalar agg.~~ we also rely on `MaxOneRowEliminateRule` to eliminate max one row restriction.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#5019

### CODE REVIEW

**Comment by likg227** [comment]
> > For streaming, the only way to eliminate the max_one_row of correlated Apply is through scalar agg.

Also, User can add a `order by ... limit 1` as a workaround.  

However, we didn't support TopN in correlated subquery because it can not be unnested.......

**Comment by chenzl25** [comment]
> 

Yes, It seems `Apply` is impossible to push down through `Limit` and `TopN`.

**Comment by chenzl25** [comment]
> > For streaming, the only way to eliminate the max_one_row of correlated Apply is through scalar agg.
> 
> Also, User can add a `order by ... limit 1` as a workaround.

Another way to eliminate the max_one_row is using predicate like `pk = xxx`

**Review by likg227 — APPROVED** [review]
LGTM 
please take a look @xiangjinwu

**Pull request merged**
