### PR TITLE
fix(stream): Simple Agg Row Count is Not 0 for 0 rows

### PR DESCRIPTION
**Pull request by jon-chuang**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
Group agg should not have row, simple agg should have `count(*)` 0

## Checklist

- [X] I have written necessary rustdoc comments
- [X] I have added necessary unit tests and integration tests
- [X] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [X] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [X] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [X] My PR **DOES NOT** contain user-facing changes.

## Related
Fixes: https://github.com/risingwavelabs/risingwave/issues/4954

### CODE REVIEW

**Comment by lmatz** [comment]
how about adding an e2e test?

**Review by fuyufjh — COMMENTED** [review]
LGTM

**Comment by jon-chuang** [comment]
> how about adding an e2e test?

Done

**Review by richardchien — APPROVED** [review]
LGTM!

**Pull request merged**
