### PR TITLE
refactor: lower log info when a field does not exists

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

resolve https://github.com/risingwavelabs/risingwave/issues/15525

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
> > I don't see how the change is beneficial. What advantage do users gain from lowering the level? Just "less scary"? 😄
> 
> Yes, because a user complains. I think the parser has to report if sth goes wrong but less important.

_An_ user complains but what about the _majority of others_? Prior to this PR, they could easily identify the logs that require their attention by filtering the lines with the predicate `level = WARN`. Now their experiences are sacrificed just for the few edge cases mentioned in #15525.

**Comment by tabVersion** [comment]
> > > I don't see how the change is beneficial. What advantage do users gain from lowering the level? Just "less scary"? 😄
> > 
> > 
> > Yes, because a user complains. I think the parser has to report if sth goes wrong but less important.
> 
> _A_ user complains but what about the _majority of others_? Prior to this PR, they could easily identify the logs that require their attention by filtering the lines with the predicate `level = WARN`. Now their experiences are sacrificed just for the few edge cases.

I do not strongly hold for the pr, @fuyufjh proposed the idea on the meeting. Shall we discuss a bit more here?

> Personally I don't find this PR reasonable, while still +1 for the original approach proposed in #15525. cc @xiangjinwu

I think the #15525 talks about it is expected to have NULL field in json encode, and #16191 is related to a (maybe wrong) impl in parser when handling delete event.

**Comment by xxchan** [comment]
If we really want this way, at least we can provide a prefix for this log e.g., risingwave_connector::parser::missing_field, so that users can turn off it on their own.

**Comment by stdrc** [comment]
> If we really want this way, at least we can provide a prefix for this log e.g., risingwave_connector::parser::missing_field, so that users can turn off it on their own.

+1, or provide some config so that user can choose to enable (if they care about it) or disable such logs.

**Pull request closed without merging**
