### PR TITLE
feat(frontend): support explain distsql

### PR DESCRIPTION
**Pull request by Flpha0830**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
Support explain distsql in the handler to output JSON-formatted distributed plan information. Eg. 
```
create table t1(v1 int);
explain (type distsql) select * from t1;

                 QUERY PLAN                 
--------------------------------------------
 {
   "root_stage_id": 0,
   "stages": {
     "1": {
       "root": {
         "plan_node_id": 17,
         "plan_node_type": "BatchSeqScan",
         "schema": [
           {
             "dataType": {
               "typeName": "INT32",
               "isNullable": true
             },
             "name": "t1.v1"
           }
         ],
         "children": [],
         "source_stage_id": null
       },
       "parallelism": 4,
       "exchange_info": {
         "mode": "SINGLE"
       }
     },
     "0": {
       "root": {
         "plan_node_id": 18,
         "plan_node_type": "BatchExchange",
         "schema": [
           {
             "dataType": {
               "typeName": "INT32",
               "isNullable": true
             },
             "name": "t1.v1"
           }
         ],
         "children": [],
         "source_stage_id": 1
       },
       "parallelism": 1,
       "exchange_info": {
         "mode": "SINGLE"
       }
     }
   },
   "child_edges": {
     "1": [],
     "0": [
       1
     ]
   },
   "parent_edges": {
     "0": [],
     "1": [
       0
     ]
   }
 }
(59 rows)
```

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by chenzl25** [comment]
Please give it an example by planner test. BTW, what about the streaming part? (like `explain (distsql) create materialized view`)

**Comment by st1page** [comment]
> Please give it an example by planner test. BTW, what about the streaming part? (like `explain (distsql) create materialized view`)
- maybe we should change planner test use explain instead of call the function directly at first( in other PRs)
- we will not handle streaming query in this PR and still ban it(return a error to user)

**Comment by Flpha0830** [comment]
> Please give it an example by planner test. BTW, what about the streaming part? (like `explain (distsql) create materialized view`)

I've updated the description with an example. For the planner test, Maybe we could address this subsequently (in other PRs)

**Review by chenzl25 — APPROVED** [review]
LGTM

**Pull request merged**
