### PR TITLE
fix(dynamic filter): load from state on vnode change

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

load from state on vnode change

## Checklist

- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
#6461

### CODE REVIEW

**Comment by BugenZhao** [comment]
https://github.com/risingwavelabs/risingwave/pull/6415 👀

**Comment by soundOfDestiny** [comment]
> #6415 👀

There is no contradiction or duplicate.
#6415 invalids all cache and this PR makes up missing cache.
this PR can be based on #6415

**Comment by BugenZhao** [comment]
Sounds good!

**Comment by BugenZhao** [comment]
Sounds good!

**Comment by soundOfDestiny** [comment]
> Sounds good!



> Sounds good!

just rebased

**Comment by jon-chuang** [comment]
We may also like to join all the `add_vnode_range` futures. It may not be so easy as we need to take ownership of the cache to insert. So one can either:
1. buffer into a temporary BTreeMap or vec first and then merge it with existing or empty BTreeMap in the cache. 
2. Have a per-vnode lock to mutate an immutable reference to an entry

I'll leave it up to you whether to do in this PR or create an issue and new PR for this.

Rest LGTM, let me know what you decide and I'll approve if ready.

**Comment by soundOfDestiny** [comment]
> We may also like to join all the `add_vnode_range` futures. It may not be so easy as we need to take ownership of the cache to insert. So one can either:
> 
> 1. buffer into a temporary BTreeMap or vec first and then merge it with existing or empty BTreeMap in the cache.
> 2. Have a per-vnode lock somehow
> 
> I'll leave it up to you whether to do in this PR or create an issue and/or new PR for this.
> 
> Rest LGTM, let me know what you decide and I'll approve if ready.

Let's buffer first as we want to parallel.
What about a new PR for this?

**Comment by jon-chuang** [comment]
Sure, sounds good.

**Comment by jon-chuang** [comment]
> We should definitely buffer into a temporary BTreeMap

Actually, to my understanding, the range will be returned in order as the iterator is in-order for each vnode. Actually, if that is the case, we should actually put some comments in the `StateTable` interface to be clear about it.

**Review by jon-chuang — COMMENTED** [review]
LGTM

**Review by jon-chuang — APPROVED** [review]
LGTM

**Pull request merged**
