### PR TITLE
fix(ctl): scan table

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Several fixes to make ctl scan work.

- Fix hummock local version initialization.
- Fix StateTable initialization.
- Fix StateTable::compute_vnode assertion, which fails due to usage of StateTable::iter in ctl. This PR uses StorageTable and a committed epoch from local version.

## Checklist

- ~~[ ] I have written necessary rustdoc comments~~
- ~~[ ] I have added necessary unit tests and integration tests~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by BugenZhao** [comment]
> TODO: fix StateTable::compute_vnode assertion. Currently it fails due to usage of StateTable::iter in ctl.

Should we use `StorageTable` for scanning, as we won't write into it? cc @st1page @wcy-fdu

**Comment by wcy-fdu** [comment]
> > TODO: fix StateTable::compute_vnode assertion. Currently it fails due to usage of StateTable::iter in ctl.
> 
> Should we use `StorageTable` for scanning, as we won't write into it? cc @st1page @wcy-fdu

`StorageTable` need to `wait_epoch`, does this matter?
If not, using `StorageTable` make sense to me.

**Comment by BugenZhao** [comment]
> `StorageTable` need to `wait_epoch`, does this matter?

I'm afraid it does. IIRC, we've no version logic here and simply use `u64::MAX` as the epoch. 😢

**Review by st1page — APPROVED** [review]
LGTM, and sorry for not approving earlier.

**Review by BugenZhao — APPROVED** [review]

**Pull request merged**
