### PR TITLE
chore: Adjust default large query memory

### PR DESCRIPTION
**Pull request by liurenjie1024**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Related #13506 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [x] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [x] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by chenzl25** [comment]
IIRC, this PR https://github.com/risingwavelabs/risingwave/pull/13558/files will deprecate this configuration.

**Comment by liurenjie1024** [comment]
> IIRC, this PR #13558 will deprecate this configuration.

I think they are not conflicting. #13558 will fix this in each executor, and we can merge this first to solve the potential oom issue.

**Review by lmatz — APPROVED** [review]

**Comment by lmatz** [comment]
just bump to see if reviewers agree with merging this PR?
the backfill/batch scan perf is still blocked by this OOM issue

**Comment by liurenjie1024** [comment]
CC @chenzl25 @hzxa21 @Little-Wallace

**Review by chenzl25 — APPROVED** [review]

**Pull request merged**
