### PR TITLE
test: add tpch/nexmark tests for shared kafka source

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
- Note: for planner tests, I just make sure they can be generated. Haven't checked all the plans yet.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by xxchan** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19589?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#19589** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19589?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19589?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#19578** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19578?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by BugenZhao** [comment]
Previously we don't have nexmark source test on CI, even for non-shared source?

**Comment by xxchan** [comment]
We have `connector='nexmark'` tests, no Kafka tests.

**Comment by xxchan** [comment]
I had thought CI covered many cases, so didn't add many tests for shared source. But it turns out there are very few tests for Kafka. Most streaming tests are based on tables.

**Review by st1page — APPROVED** [review]
Interesting, I have a feeling that no one has thought of generating data in e2e test with risingwave sink before

**Comment by xxchan** [comment]
> Interesting, I have a feeling that no one has thought of generating data in e2e test with risingwave sink before

I learned from @kwannoel

**Review by BugenZhao — APPROVED** [review]

**Comment by xxchan** [comment]
### Merge activity

* **Nov 28, 1:32 AM GMT+8**: [Graphite](https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19589) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Pull request merged**
