### PR TITLE
fix(connector): avoid long-lived tracing span

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

When `tracing-opentelemetry` layer is on, long-lived tracing span will accumulate all events in memory, and eventually lead to OOM. See https://github.com/risingwavelabs/risingwave/issues/14424.

This PR introduces a new `instrument_with` to create a new tracing span for every item polled and replaces the existing problematic ones. Fortunately, only source parser is affected.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by StrikeW — COMMENTED** [review]
LGTM, interesting OOM issue.

**Review by xxchan — APPROVED** [review]
LGTM

1. Can we run a test with the excessive parser logs to see the improvement?
2. Is this use case general/reasonable enough and can be contributed upstream?

**Comment by BugenZhao** [comment]
Will run a test asynchronously. 😄

**Comment by BugenZhao** [comment]
> Will run a test asynchronously. 😄

https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2830

**Comment by BugenZhao** [comment]
> > Will run a test asynchronously. 😄
> 
> [buildkite.com/risingwave-test/nexmark-benchmark/builds/2830](https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2830)

Benchmark succeeded. Workflow failed because of GitHub. 😄

**Pull request merged**
