### PR TITLE
chore(config): make enable_managed_cache default to true

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
Although no decision has been made for #5676, `enable_managed_cache` is the same across different `risedev` settings, 
so this PR moves it to `src/config/risingwave.toml` and makes it default to true. 

Make `managed_cache` tested in each daily test.

## Checklist

- [x] I have written necessary rustdoc comments
- ~[ ] I have added necessary unit tests and integration tests~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Review by yuhao-su — APPROVED** [review]

**Comment by yuhao-su** [comment]
Seems the test is failing. I'll do some fix before merge this.,

**Comment by yuhao-su** [comment]
The deterministic test panic in tikv jemalloc. I suspect it's because we used a `tikv_jemalloc_ctl` in managed lru.

```
stack backtrace:
--
  | 0: rust_begin_unwind
  | at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:575:5
  | 1: core::panicking::panic_fmt
  | at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panicking.rs:65:14
  | 2: core::result::unwrap_failed
  | at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/result.rs:1791:5
  | 3: core::result::Result<T,E>::expect
  | at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/result.rs:1070:23
  | 4: std::thread::local::LocalKey<T>::with
  | at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:422:9
  | 5: clock_gettime
  | at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.9/src/sim/time/system_time.rs:48:25
  | 6: nstime_get
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/nstime.c:192:2
  | 7: nstime_update_impl
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/nstime.c:268:2
  | 8: _rjem_je_nstime_init_update
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/nstime.c:280:2
  | 9: _rjem_je_pac_maybe_decay_purge
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/pac.c:505:2
  | 10: arena_decay_impl
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/arena.c:439:24
  | 11: arena_decay_dirty
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/arena.c:459:9
  | 12: _rjem_je_arena_decay
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/arena.c:485:6
  | 13: tcache_destroy
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/tcache.c:826:2
  | 14: tsd_do_data_cleanup
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/tsd.c:382:2
  | 15: _rjem_je_tsd_cleanup
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/tsd.c:408:3
  | 16: _rjem_je_tsd_cleanup
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/tsd.c:388:1
  | 17: <unknown>
  | 18: <unknown
```

**Comment by fuyufjh** [comment]
tikv-jemalloc panicked when calling `nstime_get` from `madsim`

```
  | 5: clock_gettime
  | at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.9/src/sim/time/system_time.rs:48:25
  | 6: nstime_get
  | at /risingwave/target/sim/ci-sim/build/tikv-jemalloc-sys-687a57ab160ed187/out/build/src/nstime.c:192:2
  | 7: nstime_update_impl
```

cc. @wangrunji0408

**Comment by wangrunji0408** [comment]
It seems that jemalloc was trying to get time which was then intercepted by madsim. However this happened during the exit phase when TLS was cleaned up, so it panicked when madsim tried to access them.

This should be a problem in madsim and I'll try to fix it.

**Review by yuhao-su — APPROVED** [review]

**Pull request merged**
