### PR TITLE
refactor: always insert a exchange singleton on top dml

### PR DESCRIPTION
**Pull request by BowenXiao1999**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Currently only a demo and I'm not sure whether which way we should do. 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by BowenXiao1999** [comment]
After #4708, now we are able to distribute dml by faciliate it as MPP. However, according to #3269 , I'm working on to execute root fragment of MPP in FE, while Insert / Update / Delete now can not execute in FE (?), so I plan to hack and insert a Exchange Singleton. This PR shows what will be, I think the dirty is controllable for now.

cc @chenzl25 @liurenjie1024 @st1page @fuyufjh , What's your opinion?

**Comment by liurenjie1024** [comment]
LGTM

**Comment by chenzl25** [comment]
+1

**Comment by fuyufjh** [comment]
> I plan to hack and insert a Exchange Singleton on dml to solve this.

I would like to leave the top node distributed and support this kind of plan in scheduler

**Comment by BowenXiao1999** [comment]
> > I plan to hack and insert a Exchange Singleton on dml to solve this.
> 
> I would like to leave the top node distributed and support this kind of plan in scheduler

Update / Delete / Insert can be distributed if we support it, Add a singleton exchange will not change that, cuz previously we use `get_data` exchange service RPC to fetch results, now we add a exchange locally and no network cost introduced.

if Update / Delete / Insert is distributed, we still need a root singleton to get merged reported results. If currently we do not want to add this singleton, then we can not execute it in FE, unless we hack in scheduler that "unlike DQL, this kind of query (DML) will schedule root fragment in CN ", which I think may be more dirty.

**Comment by st1page** [comment]
LGTM

**Comment by fuyufjh** [comment]
> > > I plan to hack and insert a Exchange Singleton on dml to solve this.
> > 
> > 
> > I would like to leave the top node distributed and support this kind of plan in scheduler
> 
> Update / Delete / Insert can be distributed if we support it, Add a singleton exchange will not change that, cuz previously we use `get_data` exchange service RPC to fetch results, now we add a exchange locally and no network cost introduced.
> 
> if Update / Delete / Insert is distributed, we still need a root singleton to get merged reported results. If currently we do not want to add this singleton, then we can not execute it in FE, unless we hack in scheduler that "unlike DQL, this kind of query (DML) will schedule root fragment in CN ", which I think may be more dirty.

OK, make sense to me

**Review by liurenjie1024 — APPROVED** [review]

**Comment by BowenXiao1999** [comment]
Seems like encounter some problems relates to e2e, construct a minimal example in #4788. May wait to see any progress.

**Comment by liurenjie1024** [comment]
Still not working? I think @wangrunji0408 has resolved the issue in madsim?

**Comment by wangrunji0408** [comment]
> Still not working? I think @wangrunji0408 has resolved the issue in madsim?

Yes. But this looks like a new problem in parallel e2e:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/frontend/src/handler/dml.rs:50:29
```

**Comment by BowenXiao1999** [comment]
> > Still not working? I think @wangrunji0408 has resolved the issue in madsim?
> 
> Yes. But this looks like a new problem in parallel e2e:
> 
> ```
> thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/frontend/src/handler/dml.rs:50:29
> ```

I will take a look at this. Tested success locally.

**Comment by liurenjie1024** [comment]
I think we may need to add some flush commands in parallel e2e to support dml.

**Comment by BowenXiao1999** [comment]
> Still not working? I think @wangrunji0408 has resolved the issue in madsim?

The root cause of this problem is: #4947 .  Errors may happen after QueryResultFetcher starts to work. I think can add a if-statement to workaround this.

**Comment by skyzh** [comment]
removed can-merge as it's a draft

**Pull request merged**
