### PR TITLE
fix: udf error ui

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by lmatz — APPROVED** [review]

**Review by xxchan — COMMENTED** [review]
Why CI didn’t prevent the regression? Is this a flaky test..?

**Comment by stdrc** [comment]
> Why CI didn’t prevent the regression? Is this a flaky test..?

I believe this can be caused by CI infra's network configuration change.

**Comment by stdrc** [comment]
> Why CI didn’t prevent the regression? Is this a flaky test..?

Another CI test produced the old message: https://buildkite.com/risingwavelabs/pull-request/builds/56040#01916e22-fdda-4a17-aea8-bbd6e32453b0

I guess this is related to the network setup of the spot instance allocated for the CI pipeline.

Is it possible to support only to check the first several lines of the error message in sqllogictest?

**Comment by xxchan** [comment]
https://github.com/risinglightdb/sqllogictest-rs#:~:text=single%20line%20error%20message

**Comment by stdrc** [comment]
> https://github.com/risinglightdb/sqllogictest-rs?tab=readme-ov-file#extension-run-a-querystatement-that-should-fail-with-the-expacted-error-message
> 
> yes

You mean using the regex match syntax?

**Comment by StrikeW** [comment]
This fix is not stable.
https://buildkite.com/risingwavelabs/pull-request/builds/56065#01916eab-d82b-4a03-8edf-cc6ab0baa0ac

**Pull request merged**
