### PR TITLE
fix(test): fix recovery test case

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

To fix https://buildkite.com/risingwavelabs/main-cron/builds/2310#018ec8bd-ae19-4e05-9ec2-5ab7fcf40698.

After #16211, we find flush is missing in a test case.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by kwannoel — APPROVED** [review]
Thanks!

**Review by yezizp2012 — APPROVED** [review]
LGTM, However, this is too error-prone . If we forget to add flush when adding slt tests in the future, there is still a chance that e2e tests including recovery tests can pass. It may be exposed later in other PRs or main-cron.

**Comment by wangrunji0408** [comment]
Indeed. Then should we add auto `RW_IMPLICIT_FLUSH` back? or keep the current dynamic-zeroing strategy?

**Comment by yezizp2012** [comment]
> Indeed. Then should we add auto `RW_IMPLICIT_FLUSH` back? or keep the current dynamic-zeroing strategy?

Let's keep it. If we find more cases in remaining tests, then we need to add `RW_IMPLICIT_FLUSH` back.

**Pull request merged**
