### PR TITLE
feat(streaming): support append-only min/max for more types

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

To support more nexmark extended queries. I've verified in Postgres that these types work with `min` and `max`.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- #6994

### CODE REVIEW

**Comment by richardchien** [comment]
Better to add some e2e tests?

**Review by st1page — APPROVED** [review]
LGTM

**Comment by BugenZhao** [comment]
Added. PTAL.

**Review by lmatz — APPROVED** [review]
LGTM

**Review by richardchien — APPROVED** [review]
LGTM

**Pull request merged**
