### PR TITLE
K8s workflow

### PR DESCRIPTION
**Pull request by CAJan93**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This is an attempt to simplify the k8s workflow. Ideally I want to have one command e.g. `make meta` which builds meta, packages it and deploys it in my local kind cluster. 

I will also add caches for the target dir. This way we avoid building from scratch, which is really slow 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by CAJan93** [comment]
Original build takes several hours 

Compiling, Containerising and deploying the same code (completely from cache) takes 

```
make k8s-all  9.54s user 46.01s system 14% cpu 6:28.14 total
```

**Comment by CAJan93** [comment]
Original build takes several hours 

Compiling, Containerising and deploying the same code (completely from cache) takes 

```
make k8s-all  9.54s user 46.01s system 14% cpu 6:28.14 total
```

Adding a test log-line to `src/meta/src/lib.rs` takes 

```
???
```

**Comment by skyzh** [comment]
Sorry but I'm not in favor of introducing too much complexity into the development workflow. I think we can work out the same thing by adding support for starting multiple etcd + multiple meta-node to risedev, so that all developers can work on HA settings with their familiar environment.

**Comment by skyzh** [comment]
But I would be happy to get `build.sh` merged. It seems more manageable than before.

**Comment by CAJan93** [comment]
I agree with you. This does not seem to be the right way forward.

**Pull request closed without merging**
