### PR TITLE
feat(metrics): add actor id and fragment id into udf metrics

### PR DESCRIPTION
**Pull request by yufansong**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
Proposed in #14199, add `actor_id` and `fragment_id`as label into udf metrics. 
When go through batch logic, these two lables will be empty "".
When go through streaming logic, it will use corresponding actor id and fragment id.
The prometheus result looks like below:
image

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by chenzl25 — COMMENTED** [review]
Do we really need actor-level metrics? Previously, actor-level metrics caused prometheus OOM, so we use fragment-level instead.

**Review by wangrunji0408 — COMMENTED** [review]
Passing actor and fragment info everywhere looks too intrusive. 🥵
cc @BugenZhao Is it possible to put them in a global context and provide a static function to retrieve them?

**Comment by yufansong** [comment]
> Do we really need actor-level metrics? Previously, actor-level metrics caused prometheus OOM, so we use fragment-level instead.

Can u share me more details about why actor-level metrics will cause prometheus OOM. Does is because of too much metrics? Is this prometheus meaning kernel promehteus or cloud promehteus?

For me, it is fine for me to remove the `actor id` label to avoid prometheus OOM problem. What do you think @wangrunji0408  ?

**Comment by yufansong** [comment]
> Passing actor and fragment info everywhere looks too intrusive. 🥵

Agree, but currently didn't figure out a better way to achieve it. Welcome any suggestions.

> Is it possible to put them in a global context and provide a static function to retrieve them?

I find each `ExecutorBuilder` and `ExprBuilder` will have their own customzied `actor_id` and `fragment_id` store in `ExecutorParams`. Wonder how can we retrival those customzied info from a global context?

**Comment by chenzl25** [comment]
> > Do we really need actor-level metrics? Previously, actor-level metrics caused prometheus OOM, so we use fragment-level instead.
> 
> Can u share me more details about why actor-level metrics will cause prometheus OOM. Does is because of too much metrics? Is this prometheus meaning kernel promehteus or cloud promehteus?
> 

The cloud promehteus.
Related issue: https://github.com/risingwavelabs/risingwave/issues/12381

**Comment by wangrunji0408** [comment]
> For me, it is fine for me to remove the actor id label to avoid prometheus OOM problem. What do you think @wangrunji0408 ?

I'm okay with it.

> I find each `ExecutorBuilder` and `ExprBuilder` will have their own customzied `actor_id` and `fragment_id` store in `ExecutorParams`. Wonder how can we retrival those customzied info from a global context? 

For example, we can store them in a [task-local variable](https://docs.rs/tokio/latest/tokio/task/struct.LocalKey.html). This is feasible since we spawn a task for each actor.

**Comment by yufansong** [comment]
Close. Finished in #15391 .

**Pull request closed without merging**
