### PR TITLE
fix: deprecate `SinkPayloadFormat`

### LINKED ISSUE #15662: Deprecate `SinkPayloadFormat`

### LINKED ISSUE #15950: connector: Deprecate JSON payload format
Follow-ups of #10047

Time to remove

- `sink_payload_format`
- `ConnectorParams`
- config: `connector_rpc_sink_payload_format`

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Closes #15950
Closes #15662

The `Json` sink format has been deprecated and never used any more.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by wenym1 — APPROVED** [review]
LGTM.

Not sure if the `SinkPayloadFormat` is being used in java for some integration test. If CI passes, it's fine. If not passed, we may either remove the related CI test, or preserve the proto field and use `STREAM_CHUNK` anyway in the rust code.

**Comment by fuyufjh** [comment]
> LGTM.
> 
> Not sure if the `SinkPayloadFormat` is being used in java for some integration test. If CI passes, it's fine. If not passed, we may either remove the related CI test, or preserve the proto field and use `STREAM_CHUNK` anyway in the rust code.

Thanks for reminding me. Let me try to remove the Java code as well.

**Comment by fuyufjh** [comment]
@wenym1 I have cleaned the code in Java as well. Would you like to take a look?

As we have discussed in Slack, I disabled the test case `testOnNext_writeValidation` in CI pipeline. The context are recorded in the comments.

By the way, I still think it's better to use Java to decode the `StreamChunk` protobuf into array of values, in order to eliminate Java-native code call overhead. Let me create an issue for it saperately.

**Review by wenym1 — APPROVED** [review]
LGTM

**Pull request merged**
