### PR TITLE
refactor(meta): prefixed auto full GC

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

After introducing time travel, there is expected to be much more objects in object store. To reduce the overhead associated with scanning the entire data direcoty during auto full GC, this PR refines auto full GC by adding a rotational prefix when listing objects.

Note that the path to an object within a cluster can either be `data_dir/shard_id/object_name` or `data_dir/object_name`, depending on the specific configuration settings. The setting is not straightforward to obtain. So by default this fine-grain auto full GC is not enabled. It should be set later accordingly.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by hzxa21** [comment]
> To reduce the overhead associated with scanning the entire data direcoty during auto full GC, this PR refines auto full GC by adding a rotational prefix when listing objects.

I am a little bit confused about the motivation. The overhead is the same before and after this PR. In other words, the number files needed to be listed is the same. This PR uses the prefix to do pagination and reduces the items per list request. Are we concerned that listing many files in one shot will make the list request timeout more easily?

**Comment by zwang28** [comment]
> Are we concerned that listing many files in one shot will make the list request timeout more easily?

Yes. It also aims to avoid an excessively large list result, which impacts RPC size and memory footprint adversely.
The "RPC size" refers to the compactor returns the list result to meta node (alternatively we can make meta node do the list instead).

**Comment by hzxa21** [comment]
> > Are we concerned that listing many files in one shot will make the list request timeout more easily?
> 
> Yes. It also aims to avoid an excessively large list result, which impacts RPC size and memory footprint adversely. The "RPC size" refers to the compactor returns the list result to meta node (alternatively we can make meta node do the list instead).

I see. I think this PR cannot solve the issue completely because:
- For object store backend with no prefixes, this PR is not effective
- For object store backend with prefixes, the number of files returned by each list request is still unbounded

Also, it requires manual configuration to make this PR work as expected.

Based on that, I think it is better to use the native pagination mechanism provided by the object store backends. Basically we can bound the number of files to be listed per list request accurately and continue from what we left off in the next round by providing the start key for listing. For example, aws s3 supports `continuation-token` in its list [API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax). Implementation wise, we can store the key in memory in a structure similar to `FullGcPrefixManager`

**Comment by zwang28** [comment]
> For object store backend with no prefixes, this PR is not effective

This PR implements 2 rotations: path prefix and file name prefix. For object store backend with no prefixes, file name prefix will still help.

**Comment by zwang28** [comment]
>  Basically we can bound the number of files to be listed per list request accurately and continue from what we left off in the next round by providing the start key for listing.

I will adopt this idea, using the `start-after` parameter which has been supported by opendal.

**Pull request closed without merging**
