### PR TITLE
feat(telemetry): record cloud hosted UUID

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

https://github.com/risingwavelabs/risingwave-cloud/pull/8212 related pr from cloud side

the pr adjust telemetry behavior: use cloud UUID if provided, use it as trackingID

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
Is it possible to unify the cloud & kernel UUIDs? Saying, don't generated any UUIDs when a cloud UUID is provided

**Comment by fuyufjh** [comment]
> > Is it possible to unify the cloud & kernel UUIDs? Saying, don't generated any UUIDs when a cloud UUID is provided
> 
> I don't think so. Since we initially track clusters with tracking_id for telemetry, such migration may take some effort and seem unnecessary. The requirement here is to track the behavior from cloud hosted clusters, I don't see a strong motivation to migrate to the cloud UUID. We still need to accept reports from on-perm clusters.

I feel you might need to explain again and again to everything that cloud UUID is not telemetry UUID. Unifying them is the easiest way to avoid this burden.

Also, I said "when a cloud UUID is provided". As the cloud UUID is passed via environment variable, I think it should be easy to write such an if-else.

**Comment by tabVersion** [comment]
current behavior: 

* set cloud UUID as `trackingID` if the ENV is set
* the telemetry backend does not distinguish its own trackingID and cloud UUID
* the cluster count on the telemetry should be affect for at most 48h, we may over count the clusters.

**Comment by fuyufjh** [comment]
Hi, is it ready for review?

**Comment by fuyufjh** [comment]
I think it's probably better to modify the code of generating a tracking ID, such as

https://github.com/risingwavelabs/risingwave/blob/84b7b9444c794886b40970212c9181545249e948/src/common/src/telemetry/report.rs#L68

Otherwise, the "wrong" tracking ID is still stored in `TELEMETRY_TRACKING_ID` and it's prone to be misused.

**Review by fuyufjh — APPROVED** [review]

**Pull request merged**
