### PR TITLE
fix: load pk from the downstream instead of Risingwave

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

as title, query pk from jdbc at runtime and concat sql
if no pk is provided, will concat all columns for sql

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
~~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
~~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by wenym1 — COMMENTED** [review]
Generally LGTM. 

Can we have some unit test to use derby jdbc driver to validate the feature? 

And it seems that most CI is not running for this PR.

**Comment by tabVersion** [comment]
> Can we have some unit test to use derby jdbc driver to validate the feature?

unit test is not proper in this case. prefer use CI instead. 

> And it seems that most CI is not running for this PR.

code changes to connector_node/ will not trigger the main ci.

**Comment by tabVersion** [comment]
encountered a concurrent committing bug. here is the log

```
2023-03-15 07:28:23,423 INFO  [main] connector.ConnectorService:46 - Server started, listening on 50051
2023-03-15 07:28:23,451 INFO  [main] connector.ConnectorService:53 - Prometheus metrics server started, listening on 50052
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-11] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-0] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-9] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-8] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-10] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-4] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-5] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-12] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-6] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-14] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-13] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,421 INFO  [grpc-default-executor-15] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,456 INFO  [grpc-default-executor-1] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,456 INFO  [grpc-default-executor-3] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,456 INFO  [grpc-default-executor-2] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,457 INFO  [grpc-default-executor-7] connector.JDBCSink:71 - detected pk []
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-5] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread19',2)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-1] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread17',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-2] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment53',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-15] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment79',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-3] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread34',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-0] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment48',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment90',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-10] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment86',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-14] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread45',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-8] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread64',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-9] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread5',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-6] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment26',1)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-13] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread55',2)
2023-03-15 07:28:41,490 INFO  [grpc-default-executor-4] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment9',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-14] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment33',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-9] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('user74',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-15] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread6',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-13] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread23',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-5] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('user17',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-1] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread61',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-6] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread22',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread70',1)
2023-03-15 07:28:41,499 INFO  [grpc-default-executor-4] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread43',1)
2023-03-15 07:28:41,500 INFO  [grpc-default-executor-13] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread51',1)
2023-03-15 07:28:41,500 INFO  [grpc-default-executor-1] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread69',1)
2023-03-15 07:28:41,500 INFO  [grpc-default-executor-0] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread32',1)
2023-03-15 07:28:41,500 INFO  [grpc-default-executor-6] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread50',2)
2023-03-15 07:28:41,500 INFO  [grpc-default-executor-15] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread91',1)
2023-03-15 07:28:41,501 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread90',1)
2023-03-15 07:28:41,501 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread98',1)
2023-03-15 07:28:41,503 INFO  [grpc-default-executor-1] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread81',1)
2023-03-15 07:28:42,294 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread31',1)
2023-03-15 07:28:42,296 INFO  [grpc-default-executor-1] connector.JDBCSink:163 - update delete condition: target_id = ? AND target_count = ? on values [thread70, 1]
2023-03-15 07:28:42,297 INFO  [grpc-default-executor-1] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: UPDATE target_count SET target_id = 'thread70',target_count = 2 WHERE target_id = 'thread70' AND target_count = 1
2023-03-15 07:28:43,294 INFO  [grpc-default-executor-15] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread100',1)
2023-03-15 07:28:43,294 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread75',1)
2023-03-15 07:28:44,295 INFO  [grpc-default-executor-15] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment23',1)
2023-03-15 07:28:44,295 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread13',1)
2023-03-15 07:28:45,295 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('comment88',1)
2023-03-15 07:28:45,296 INFO  [grpc-default-executor-15] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread28',1)
2023-03-15 07:28:46,294 INFO  [grpc-default-executor-15] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread58',1)
2023-03-15 07:28:46,294 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('user19',1)
2023-03-15 07:28:47,294 INFO  [grpc-default-executor-15] connector.JDBCSink:163 - update delete condition: target_id = ? AND target_count = ? on values [thread100, 1]
2023-03-15 07:28:47,295 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread85',1)
2023-03-15 07:28:47,295 INFO  [grpc-default-executor-15] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: UPDATE target_count SET target_id = 'thread100',target_count = 2 WHERE target_id = 'thread100' AND target_count = 1
2023-03-15 07:28:48,294 INFO  [grpc-default-executor-7] connector.JDBCSink:163 - update delete condition: target_id = ? AND target_count = ? on values [thread58, 1]
2023-03-15 07:28:48,294 INFO  [grpc-default-executor-9] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('user47',1)
2023-03-15 07:28:48,295 INFO  [grpc-default-executor-7] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: UPDATE target_count SET target_id = 'thread58',target_count = 2 WHERE target_id = 'thread58' AND target_count = 1
2023-03-15 07:28:49,295 INFO  [grpc-default-executor-9] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread30',1)
2023-03-15 07:28:49,295 INFO  [grpc-default-executor-6] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread88',1)
2023-03-15 07:28:50,294 INFO  [grpc-default-executor-9] connector.JDBCSink:163 - update delete condition: target_id = ? AND target_count = ? on values [thread30, 1]
2023-03-15 07:28:50,294 INFO  [grpc-default-executor-6] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO target_count (target_id,target_count) VALUES ('thread27',1)
2023-03-15 07:28:50,295 INFO  [grpc-default-executor-9] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: UPDATE target_count SET target_id = 'thread30',target_count = 2 WHERE target_id = 'thread30' AND target_count = 1
2023-03-15 07:28:51,294 INFO  [grpc-default-executor-10] connector.JDBCSink:163 - update delete condition: target_id = ? AND target_count = ? on values [comment48, 1]
2023-03-15 07:28:51,295 INFO  [grpc-default-executor-10] connector.JDBCSink:218 - Executing statement: com.mysql.cj.jdbc.ClientPreparedStatement: UPDATE target_count SET target_id = 'comment48',target_count = 2 WHERE target_id = 'comment48' AND target_count = 1
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-13] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-8] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-11] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-3] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-6] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-5] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-2] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-14] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-0] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,296 INFO  [grpc-default-executor-4] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,300 INFO  [grpc-default-executor-8] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,302 INFO  [grpc-default-executor-4] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,302 INFO  [grpc-default-executor-13] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,302 INFO  [grpc-default-executor-6] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,302 INFO  [grpc-default-executor-5] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,302 INFO  [grpc-default-executor-0] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,302 INFO  [grpc-default-executor-3] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,302 INFO  [grpc-default-executor-14] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,303 INFO  [grpc-default-executor-11] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,303 INFO  [grpc-default-executor-2] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,304 INFO  [grpc-default-executor-2] connector.JDBCSink:233 - doing sync
2023-03-15 07:28:51,307 INFO  [grpc-default-executor-2] connector.JDBCSink:242 - sync success
2023-03-15 07:28:51,310 ERROR [grpc-default-executor-10] connector.SinkStreamObserver:188 - sink task error:
io.grpc.StatusRuntimeException: INTERNAL
        at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.49.0.jar:1.49.0]
        at com.risingwave.connector.JDBCSink.write(JDBCSink.java:221) ~[risingwave-sink-jdbc-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:146) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:35) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262) [grpc-stub-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:332) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:315) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.49.0.jar:1.49.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

exec-10 is trying to update `('comment48', 1)` to `('comment48', 2)` but exec-0 just insert `('comment48', 1)` in the same epoch. and the two exec commit at the same time, leading to a commit failure. 

FYI, the source and mv look like 

```sql
CREATE SOURCE user_behaviors (
    user_id VARCHAR,
    target_id VARCHAR,
    target_type VARCHAR,
    event_timestamp TIMESTAMPTZ,
    behavior_type VARCHAR,
    parent_target_type VARCHAR,
    parent_target_id VARCHAR
) WITH (
    connector = 'kafka',
    topic = 'user_behaviors',
    properties.bootstrap.server = 'message_queue:29092',
    scan.startup.mode = 'earliest'
) ROW FORMAT JSON;

CREATE MATERIALIZED VIEW target_count AS
SELECT
    target_id,
    COUNT(*) AS target_count
FROM
    user_behaviors
GROUP BY
    target_id;
```

besides there are no exchange op before sink 

```
dev=> explain CREATE SINK target_count_mysql_sink
FROM
    target_count WITH (
        connector = 'jdbc',
        jdbc.url = 'jdbc:mysql://mysql:3306/mydb?user=root&password=123456',
        table.name = 'target_count'
    );
                                          QUERY PLAN
-----------------------------------------------------------------------------------------------
 StreamSink { type: upsert, columns: [target_id, target_count], pk: [target_count.target_id] }
 └─StreamTableScan { table: target_count, columns: [target_id, target_count] }
(2 rows)
```

**Comment by tabVersion** [comment]
resolve #8482

**Review by wenym1 — APPROVED** [review]
LGTM!

**Pull request merged**
