### PR TITLE
feat(storage): fill missing columns with null for replicated state_table

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

```
upstream -> arrangement backfill
```

The records from upstream will undergo column pruning before reaching arrangement backfill.

We want to replicate these records. They must match local state store's schema, so that they can be merged with committed data.

So we just fill pruned columns with null values to support this. This handles the write path.

The read path has previously been handled in #13622 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by kwannoel** [comment]
I will add some type-safety for methods which replicated state table can use in a separate PR, to avoid excessive refactor. You may see https://github.com/risingwavelabs/risingwave/issues/10225. It is tracked there.

**Review by chenzl25 — COMMENTED** [review]
LGTM. Do we have an e2e test case using arrangement backfill to test whether the null filling works well.

**Comment by kwannoel** [comment]
https://github.com/risingwavelabs/risingwave/blob/4fa341cd36f572ae6eda5e7cc79072fda79e227a/src/stream/src/executor/backfill/arrangement_backfill.rs#L375-L376

**Review by chenzl25 — APPROVED** [review]

**Comment by BugenZhao** [comment]
So we'll not adopt the "mixed encoding" approach, right? 👀 Is there any discussion about this?

**Comment by kwannoel** [comment]
> So we'll not adopt the "mixed encoding" approach, right? 👀 Is there any discussion about this?

Nope, after I thought about it, I think filling with `NULL` is also not too complex, and it's details can be encapsulated by the state table. So it won't make arrangement backfill more complex.

I opt for this approach instead, so we don't have to do runtime checks on the encoding type.

**Pull request merged**
