### PR TITLE
refactor: allow modification of the query mode

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR permits to set the runtime parameter `query_mode` gloablly. Sometimes it's helpful to easily alter this parameter globally for queries sent from a client process, which otherwise need code change and rebuild for client process.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by BugenZhao — COMMENTED** [review]
May I know why it was previously set to `NO_ALTER_SYS`?

**Comment by zwang28** [comment]
> May I know why it was previously set to `NO_ALTER_SYS`?

We've discussed offline and agreed NO_ALTER_SYS is not necessary.

@yuhao-su

**Review by hzxa21 — APPROVED** [review]

**Comment by WanYixian** [comment]
> query_mode

Hello @lmatz, so shall we clarify this as global in the [doc](https://docs.risingwave.com/operate/view-configure-runtime-parameters#how-to-view-runtime-parameters:~:text=these%20materialized%20views.-,query_mode,-auto)? or keep it as it is

**Comment by WanYixian** [comment]
> It seems our documentation and the runtime parameter system table do not differentiate if a parameter can be set globally or not at the moment. I thought all can be `alter system set`

Hello @lmatz, so shall we clarify this as global in the [doc](https://docs.risingwave.com/operate/view-configure-runtime-parameters#how-to-view-runtime-parameters:~:text=these%20materialized%20views.-,query_mode,-auto)? or keep it as it is

**Pull request merged**
