### PR TITLE
feat: support custom kafka group id prefix

### LINKED ISSUE #17657: allow custom kafka consumer group id
follow up of https://github.com/risingwavelabs/risingwave/pull/16111

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

fix #17657
follow up of #16111

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [x] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

Add new config `group.id.prefix` for Kafka source.

See comment on the code for doc.

</details>

### CODE REVIEW

**Review by tabVersion — COMMENTED** [review]
the impl LGTM, is there a request to customize the prefix?

**Comment by xxchan** [comment]
There were some from time to time. To clean the backlog.

**Review by fuyufjh — APPROVED** [review]

**Comment by pjpringlenom** [comment]
I raised a similar request for pulsar connector consumer id prefix on slack.

**Comment by xxchan** [comment]
> I raised a similar request for pulsar connector consumer id prefix on slack.

I see @tabVersion is doing it: #18377

**Pull request merged**
