### PR TITLE
feat(frontend): support AS OF syntax

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Related issue: https://github.com/risingwavelabs/risingwave/issues/15846
- Support `Support FOR [SYSTEM_TIME | SYSTEM_VERSION] AS OF [STRING | NUMBER]` syntax.
- Unify the temporal join syntax `Support FOR SYSTEM_TIME AS OF PROCTIME()`.
- Later, we could use this syntax to support time travel for Iceberg sources, tables and materialized views.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by kwannoel** [comment]
Could we have some planner tests? Thanks! And also need update release note since it's user-facing.

**Review by kwannoel — APPROVED** [review]

**Comment by chenzl25** [comment]
> Could we have some planner tests? Thanks! And also need update release note since it's user-facing.

Actually, it is not a user-facing in this PR, because I ban the possible way to use `AS OF` for table scan and source. We will turn it on in the following PR

**Comment by kwannoel** [comment]
Ignore the earlier comment, this is just syntax change, so it will just get rejected as an error if we add planner test. We can add it subsequently once we add the backend side.

Wonder if we have some docs for time travel query within RW.

**Comment by chenzl25** [comment]
> Ignore the earlier comment, this is just syntax change, so it will just get rejected as an error if we add planner test. We can add it subsequently once we add the backend side.
> 
> Wonder if we have some docs / RFC for time travel query within RW.
> 
> LGTM!

It would be used to iceberg source first, since iceberg source currently only support COW read, we need to give users a way to specify a specific snapshot so that RisingWave can read it.

**Comment by hengm3467** [comment]
@chenzl25 Looks like there's no need to update the documentation, right? Thanks.

**Comment by chenzl25** [comment]
> @chenzl25 Looks like there's no need to update the document, right? Thanks.

Yes, no need to update the documentation for the current PR.
Only after we use this syntax for iceberg and then we need to update the document. https://github.com/risingwavelabs/risingwave/pull/15866

**Pull request merged**
