### PR TITLE
fix(sink): fix starrocks doris and clickhouse decimal

### PR DESCRIPTION
**Pull request by xxhZs**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
Previously we would report an error when insert ck doris starrocks nan inf -inf, now we have made the change
in clickhouse ,if clickhouse is nullable, will insert null. If not, we will insert 0.
in doris/storrocks, if decimal is out of bounds or inf -inf nan, we insert null.

Due to the starrocks update, we removed some of the calibration logic for decimal

The reason for the change is that 
1. previously we needed precision to make precision corrections, e.g. if we had a 1.123456 and starrocks had a precision of 3, we would need to convert it to 1.123 first, but recent versions of starrocks have been able to convert it automatically, so it doesn't require us to do this (doris is still required)

2. Regarding the maximum number of bits, as long as the maximum number of bits is exceeded, there is no way for us to insert into the downstream. Previously, we would judge the number of bits because we wanted to report the error ahead of time, but then we found out that there is no point in doing so, so we remove this logic

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [x] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

Previously we would report an error when insert ck doris starrocks nan inf -inf, now we have made the change
in clickhouse ,if clickhouse is nullable, will insert null. If not, we will insert 0.

</details>

### CODE REVIEW

**Comment by wenym1** [comment]
> in clickhouse ,if clickhouse is nullable, will insert null. If not, we will insert 0.
> in doris/storrocks, if decimal is out of bounds or inf -inf nan, we insert null.

Intuitively this might work, but I am not sure if this will be too implicit for users. Did you check how flink connector handle these cases?

**Comment by lmatz** [comment]
could you add tests for these edge cases in the integration tests? Thanks!

**Comment by wenym1** [comment]
> Due to the starrocks update, we removed some of the calibration logic for decimal

Is the change only compatible to the latest version of starrocks? Does it work on some previous versions of starrocks? If not we may add in our document and release note to notify users to be careful with the upgrade.

**Review by wenym1 — APPROVED** [review]
Generally LGTM.

Can you paste some links from starrocks and doris about the related changes in the PR to explain the reason for removing the decimal config map from starrocks and changing the decimal config map from (u8, u8) to u8 for doris?

**Comment by xxhZs** [comment]
> > Due to the starrocks update, we removed some of the calibration logic for decimal
> 
> Is the change only compatible to the latest version of starrocks? Does it work on some previous versions of starrocks? If not we may add in our document and release note to notify users to be careful with the upgrade.

test with 2.5.18 -> laster(The versions we support), No problem

**Pull request merged**
