### PR TITLE
feat(frontend): support alter source refresh schema for shared source

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
follow up of #19649  (#19063). basically the same

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by xxchan** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19740?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#19740** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19740?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19740?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#19649** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19649?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#19650** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19650?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#18935** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/18935?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#19630** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19630?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by BugenZhao — APPROVED** [review]

**Comment by xxchan** [comment]
### Merge activity

* **Dec 11, 3:05 PM GMT+8**: [Graphite](https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19740) rebased this pull request as part of a merge.

**Comment by xiangjinwu** [comment]
https://buildkite.com/risingwavelabs/pull-request/builds/64241#0193b9e7-fcdd-43e5-9618-93b6866b6b30
```
e2e_test/source_inline/kafka/protobuf/alter_source_shared.slt .. [FAILED]
failed to run `e2e_test/source_inline/kafka/protobuf/alter_source_shared.slt`
Caused by:
    query result mismatch:
    [SQL] SELECT COUNT(*), MAX(age), MIN(age), SUM(age) FROM mv_user_more;
    [Diff] (-expected|+actual)
    -   25	104	0	510
    +   0 NULL NULL NULL
    at e2e_test/source_inline/kafka/protobuf/alter_source_shared.slt:74
```

**Comment by xxchan** [comment]
I think this is the same issue as https://github.com/risingwavelabs/risingwave/issues/19681#issuecomment-2532183002

**Pull request merged**
