### PR TITLE
perf(storage): upgrade foyer to spawn fetch block in dedicated runtime

### PR DESCRIPTION
**Pull request by MrCroxx**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Try to reduce foyer hybrid cache latency.

https://github.com/MrCroxx/foyer/pull/557

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by hzxa21** [comment]
Thanks for the quick PR. Shall we test this and confirm this is the root cause of the latency issue before merging?

**Comment by MrCroxx** [comment]
> Thanks for the quick PR. Shall we test this and confirm this is the root cause of the latency issue before merging?

Yep, I'm building the docker for it. Let me convert the PR to draft first.

**Comment by MrCroxx** [comment]
p90 main vs pr
image
image
p99 main vs pr
image
image

**Comment by MrCroxx** [comment]
Looks works.

**Review by hzxa21 — APPROVED** [review]
LGTM. Do we need to release foyer 0.9.3 for this feat?

**Review by Li0k — APPROVED** [review]

**Comment by MrCroxx** [comment]
> LGTM. Do we need to release foyer 0.9.3 for this feat?

Yep. Let me merge the PR in the foyer side and bump version.

**Comment by MrCroxx** [comment]
image

@wangrunji0408 RJGG, need `fn handle(&self) -> &Handle` for `Runtime` in *madsim*. 🥵

**Comment by wangrunji0408** [comment]
GG

**Comment by MrCroxx** [comment]
```bash
RUST_BACKTRACE=1 RUST_LOG=INFO ./risedev sslt --profile ci-sim -- --kill-rate=1.0 --kill "e2e_test/streaming/**/*.slt"
```

image

```
2022-05-03T20:19:33.885569Z ERROR risingwave_storage::hummock::event_handler: LocalInstanceGuard Drop SendError error=channel closed table_id=1 instance_id=6
2022-05-03T20:19:33.885569Z ERROR risingwave_storage::hummock::event_handler: LocalInstanceGuard Drop SendError error=channel closed table_id=5 instance_id=5
2022-05-03T20:19:33.885571Z ERROR node{id=11 name="compute-3"}:task{id=1542}: risingwave_stream::task::stream_manager: actor exit with error actor_id=13 error=Executor error: exchange channel from remote upstream actor 16 closed unexpectedly: gRPC request failed: Unknown error: error reading a body from connection: broken pipe
2022-05-03T20:19:33.885572Z  WARN node{id=5 name="meta-2"}:task{id=130}: risingwave_meta::barrier::rpc: get error from response stream node=WorkerNode { id: 4, r#type: ComputeNode, host: Some(HostAddress { host: "192.168.3.2", port: 5688 }), state: Running, parallel_units: [ParallelUnit { id: 2, worker_node_id: 4 }, ParallelUnit { id: 3, worker_node_id: 4 }], property: Some(Property { is_streaming: true, is_serving: true, is_unschedulable: false }), transactional_id: Some(2), resource: Some(Resource { rw_version: "1.9.0-alpha", total_memory_bytes: 134127427584, total_cpu_cores: 2 }), started_at: Some(1651609140) } err=gRPC request to stream service failed: Unknown error: error reading a body from connection: broken pipe
2022-05-03T20:19:33.885572Z  INFO node{id=5 name="meta-2"}:task{id=130}: risingwave_meta::barrier::rpc: no inflight barrier no node. Ignore error node=WorkerNode { id: 4, r#type: ComputeNode, host: Some(HostAddress { host: "192.168.3.2", port: 5688 }), state: Running, parallel_units: [ParallelUnit { id: 2, worker_node_id: 4 }, ParallelUnit { id: 3, worker_node_id: 4 }], property: Some(Property { is_streaming: true, is_serving: true, is_unschedulable: false }), transactional_id: Some(2), resource: Some(Resource { rw_version: "1.9.0-alpha", total_memory_bytes: 134127427584, total_cpu_cores: 2 }), started_at: Some(1651609140) }
2022-05-03T20:19:33.885574Z ERROR node{id=9 name="compute-1"}:task{id=1564}: risingwave_stream::task::stream_manager: actor exit with error actor_id=19 error=Executor error: exchange channel from remote upstream actor 4 closed unexpectedly: gRPC request failed: Unknown error: error reading a body from connection: broken pipe
2022-05-03T20:19:33.885574Z ERROR node{id=11 name="compute-3"}:task{id=2184}: risingwave_stream::task::stream_manager: actor exit with error actor_id=21 error=actor exited unexpectedly

Backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.86/src/error.rs:83:36
   1: risingwave_stream::executor::actor::Actor<C>::run_consumer::{{closure}}
             at ./src/stream/src/executor/actor.rs:217:39
   2: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/future/maybe_done.rs:62:56
   3: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}::{{closure}}::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/macros/join.rs:126:24
   4: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/future/poll_fn.rs:58:9
   5: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}::{{closure}}
             at ./src/stream/src/executor/actor.rs:170:17
   6: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:391:31
   7: tokio::task::task_local::LocalKey<T>::scope_inner
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:217:19
   8: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:387:19
   9: risingwave_expr::expr_context::expr_context_scope::{{closure}}
             at ./src/expr/core/src/expr_context.rs:35:65
  10: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:391:31
  11: tokio::task::task_local::LocalKey<T>::scope_inner
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:217:19
  12: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:387:19
  13: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}
             at ./src/stream/src/executor/actor.rs:178:10
  14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/map.rs:55:37
  15: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:391:31
  16: tokio::task::task_local::LocalKey<T>::scope_inner
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:217:19
  17: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:387:19
  18: await_tree::root::TreeRoot::instrument::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.2.1/src/root.rs:43:34
  19: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/either.rs:109:32
  20: core::ops::function::FnOnce::call_once
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/ops/function.rs:250:5
  21: tokio_metrics::task::instrument_poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-metrics-0.3.1/src/task.rs:2530:15
  22: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-metrics-0.3.1/src/task.rs:2430:9
  23: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:391:31
  24: tokio::task::task_local::LocalKey<T>::scope_inner
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:217:19
  25: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:387:19
  26: madsim::sim::task::Spawner::spawn_inner::{{closure}}::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/task/mod.rs:638:28
  27: <async_task::runnable::Builder<M>::spawn_local::Checked<F> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:455:26
  28: async_task::raw::RawTask<F,T,S,M>::run
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17
  29: async_task::runnable::Runnable<M>::run
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18
  30: madsim::sim::task::Executor::run_all_ready::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/task/mod.rs:280:59
  31: std::panicking::try::do_call
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:552:40
  32: std::panicking::try
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:516:19
  33: std::panic::catch_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panic.rs:146:14
  34: madsim::sim::task::Executor::run_all_ready
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/task/mod.rs:280:17
  35: madsim::sim::task::Executor::block_on
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/task/mod.rs:240:13
  36: madsim::sim::runtime::Runtime::block_on
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/runtime/mod.rs:129:9
  37: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/runtime/builder.rs:141:35
  38: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/sys_common/backtrace.rs:155:18
  39: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/thread/mod.rs:528:17
  40: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panic/unwind_safe.rs:272:9
  41: std::panicking::try::do_call
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:552:40
  42: std::panicking::try
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:516:19
  43: std::panic::catch_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panic.rs:146:14
  44: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/thread/mod.rs:527:30
  45: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/ops/function.rs:250:5
  46: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/alloc/src/boxed.rs:2020:9
  47: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/alloc/src/boxed.rs:2020:9
  48: std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/sys/pal/unix/thread.rs:108:17
  49: <unknown>
  50: <unknown>


2022-05-03T20:19:33.885575Z ERROR node{id=9 name="compute-1"}:task{id=1087}: risingwave_stream::task::stream_manager: actor exit with error actor_id=5 error=Executor error: exchange channel from remote upstream actor 9 closed unexpectedly: gRPC request failed: Unknown error: error reading a body from connection: broken pipe
2022-05-03T20:19:33.885576Z ERROR node{id=11 name="compute-3"}:task{id=2185}: risingwave_stream::task::stream_manager: actor exit with error actor_id=22 error=actor exited unexpectedly

```

**Comment by MrCroxx** [comment]
```
thread '<unnamed>' panicked at /home/mrcroxx/github/risingwavelabs/risingwave/src/tests/simulation/src/slt.rs:413:33:
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:72:14
   2: risingwave_simulation::slt::run_slt_task::{{closure}}
             at ./src/tests/simulation/src/slt.rs:413:33
   3: risingwave_simulation::main::{{closure}}::{{closure}}::{{closure}}
             at ./src/tests/simulation/src/main.rs:268:84
   4: madsim::sim::task::Spawner::spawn_inner::{{closure}}::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/task/mod.rs:638:28
   5: <async_task::runnable::Builder<M>::spawn_local::Checked<F> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:455:26
   6: async_task::raw::RawTask<F,T,S,M>::run
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17
   7: async_task::runnable::Runnable<M>::run
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18
   8: madsim::sim::task::Executor::run_all_ready::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/task/mod.rs:280:59
   9: std::panicking::try::do_call
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:552:40
  10: std::panicking::try
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:516:19
  11: std::panic::catch_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panic.rs:146:14
  12: madsim::sim::task::Executor::run_all_ready
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/task/mod.rs:280:17
  13: madsim::sim::task::Executor::block_on
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/task/mod.rs:240:13
  14: madsim::sim::runtime::Runtime::block_on
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/runtime/mod.rs:129:9
  15: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.29/src/sim/runtime/builder.rs:141:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
context: node=14 "client", task=719 (spawned at /home/mrcroxx/github/risingwavelabs/risingwave/src/tests/simulation/src/cluster.rs:613:21)
note: run with `MADSIM_TEST_SEED=1717603843457124093` environment variable to reproduce this error
```

**Comment by MrCroxx** [comment]
cc @wangrunji0408 Seems something wrong with madsim. This PR run `fetch()` in the runtime of foyer.

**Comment by MrCroxx** [comment]
Fixed! Thanks, @wangrunji0408 !!! 🥰

**Pull request merged**
