### PR TITLE
feat: remove deno UDF

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

To unblock dependency updates e.g., #17544,  #13695.

We can revert this to bring it back after https://github.com/risingwavelabs/arrow-udf/issues/38 is resolved.

~~This is not a breaking change since it's only used in CI.~~ Well, it's actually already enabled in production, but is not documented. So I think it's still fine.

https://github.com/risingwavelabs/risingwave/blob/8984ae23ff59ef841a385c968cd20176c84ed9ef/docker/Dockerfile#L73

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
> Well, it's actually already enabled in production

You mean it was built in our previous release binaries? 🥵

**Review by fuyufjh — APPROVED** [review]
LGTM

**Comment by xxchan** [comment]
> > Well, it's actually already enabled in production
> 
> You mean it was built in our previous release binaries? 🥵

Yes. (I thought I proposed only enabling it in CI, but it seems not enforced.)

**Comment by xxchan** [comment]
Just tested with latest docker image that it is indeed enabled.
```
> docker run -it --pull=always -p 4566:4566 -p 5691:5691 risingwavelabs/risingwave:latest single_node

dev=> CREATE FUNCTION gcd(a int, b int) RETURNS int LANGUAGE javascript RUNTIME deno AS $$
    if(a == null || b == null) {
        return null;
    }
    while (b != 0) {
        let t = b;
        b = a % b;
        a = t;
    }
    return a;
$$;
CREATE_FUNCTION
```

**Review by wangrunji0408 — APPROVED** [review]

**Comment by xxchan** [comment]
cc @bakjos, sorry for removing this feature. If you still need Deno UDF (in the short term), you can still use RisingWave 1.10, or you can revert this PR in your branch. In the long term, we can bring it back after https://github.com/risingwavelabs/arrow-udf/issues/38 is resolved.

**Pull request merged**
