### PR TITLE
fix(cdc): check duplicated `server.id` for mysql cdc

### PR DESCRIPTION
**Pull request by WillyKidd**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- disallow duplicate `user.id` for mysql cdc
- throw error in validate if duplicated

## Checklist For Contributors

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
~~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
~~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

### CODE REVIEW

**Review by StrikeW — COMMENTED** [review]
Please add unit test for it.

**Comment by tabVersion** [comment]
correct me if I am wrong, `user.id` is a user-specified property, so the checking process is better on the frontend or meta?

**Comment by WillyKidd** [comment]
Sorry I forgot about this pr 🤣🤣
Currently I couldn't find a method to check whether `server.id` is duplicated or not...and what I wrote in this pr doesn't work..
Maybe we have to rely on the user to ensure that it is unique

**Comment by tabVersion** [comment]
> Sorry I forgot about this pr 🤣🤣
> 
> Currently I couldn't find a method to check whether `server.id` is duplicated or not...and what I wrote in this pr doesn't work..
> 
> Maybe we have to rely on the user to ensure that it is unique

What happens if the user id duplicates

**Pull request closed without merging**
