### PR TITLE
build: dynamic link openssl & zstd

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

To speed up full debug build

Also add some notes for workspace-config/hack

OpenSSL
- macOS Ventura ships 3.3.6. No need to brew install (actually it doesn't work, needs further config envvar)
- It's controlled in workspace-config. No need to force it in connector. Not sure why it's changed in connnector.

## Checklist For Contributors

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [ ] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by xxchan** [comment]
Hmmm, should we then dynamically link bzip2, rdkafka, ... 🤡

**Comment by xxchan** [comment]
Do we want to use dylib for debug build in CI? 🤪

**Review by BugenZhao — APPROVED** [review]
So it turns out some crates make static-link optional by features and others make dynamic-link optional, then the feature unification makes it hard to make any of both default? 🤡

**Comment by BugenZhao** [comment]
> Do we want to use dylib for debug build in CI? 🤪

What do you mean by "dylib"? 👀

**Comment by xxchan** [comment]
> > Do we want to use dylib for debug build in CI? 🤪
> 
> What do you mean by "dylib"? 👀

dynamic linking. Currently in CI build we force rw-static-link

**Comment by BugenZhao** [comment]
> Currently in CI build we force rw-static-link

Oops. I guess we can have a try.

**Comment by xxchan** [comment]
Only 2m10s now. >30s less :p

(But why uploading & showing sccache stats take so long.

image

**Pull request merged**
