### PR TITLE
feat(optimizer): support table function to project set rule

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
- Convert `LogicalTableFunction` to `LogicalProjectSet` by `TableFunctionToProjectSetRule`.
- We need a type alignment between them because `LogicalProjectSet` return one column with struct type instead of multiple columns like `LogicalTableFunction`.
- After this PR, we can support SQLs like the below one for batch and streaming.

```sql
select *, (select sum(i) from (select unnest(x) i) Q ) as sum_x, (select sum(i) from (select unnest(y) i) Q ) as sum_y from t;
```

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by st1page — COMMENTED** [review]
Do we still need `TableFunction` operator?

**Review by wangrunji0408 — APPROVED** [review]
LGTM!

I'm also feeling that `TableFunction` operator can be abandoned.
Another concern is about performance. I guess there will be regression after switching `TableFunction` to `ProjectSet`, because the former is a simple wrapper over table function expression, while the latter has to iterate rows and rebuild the chunk. Maybe we can add optimizations for 1-column-case in `ProjectSet` in the future.

**Review by xxchan — COMMENTED** [review]
> I'm also feeling that TableFunction operator can be abandoned.
>
> Another concern is about performance.

Actually I had thought we should merge `LogicalTableFunction` to `LogicalValues` 🤔️

https://github.com/risingwavelabs/risingwave/blob/2719c648f20579eed4a54d5d94c4eb446364209b/src/frontend/src/planner/relation.rs#L122-L134

**Comment by chenzl25** [comment]
> > I'm also feeling that TableFunction operator can be abandoned.
> > Another concern is about performance.
> 
> Actually I had thought we should merge `LogicalTableFunction` to `LogicalValues` 🤔️
> 
> https://github.com/risingwavelabs/risingwave/blob/2719c648f20579eed4a54d5d94c4eb446364209b/src/frontend/src/planner/relation.rs#L122-L134

In order to unnest the `LogicalTableFunction`, we need to let `LogicalApply` pass through it which means they cannot be the leaves node all the time. Still need to extract table functions from `LogicalValues`.

**Comment by xxchan** [comment]
You are right, I didn't notice `from (select f(x)))` is correlated subquery and not a constant 🥵🤪

**Pull request merged**
