### PR TITLE
feat(optimizer): improve inline now proc time

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Related issue https://github.com/risingwavelabs/risingwave/issues/13459 https://github.com/risingwavelabs/risingwave/issues/13510
- Avoid rewrite of `InlineNowProcTime` for plan nodes if there are no now() and proctime().
- Performance comparison https://github.com/risingwavelabs/risingwave/pull/13587#issuecomment-1822568243

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by xxchan — DISMISSED** [review]

**Comment by BugenZhao** [comment]
Actually I'm wondering why this could improve the performance. It appears that a no-op call of `rewrite_exprs_recursive` will still lead to performance overhead of cloning and allocation, which is far from ideal. In this PR, we manually add a visitor dual for a rewriter to avoid calling `rewrite` as much as possible. However, the developers still have to make sure they're identical, just like what we talked in https://github.com/risingwavelabs/risingwave/pull/13587#issuecomment-1822303190.

I'm considering whether it's possible to reduce the overhead of `rewrite`...

- We already have `has_rewritable_expr` to reduce the calls.
https://github.com/risingwavelabs/risingwave/blob/d37b87bf641655d775f72997a268d6e881541e6d/src/frontend/src/optimizer/plan_node/expr_rewritable.rs#L26-L28
 Is it possible to make it specific to different rewriters? This will somehow be similar to https://doc.rust-lang.org/stable/std/error/struct.Request.html#method.would_be_satisfied_by_ref_of.

- When expressions not actually be rewritten, `rewrite_exprs` should be able to directly return itself without cloning. This can be achieved with `Cow`.
https://github.com/risingwavelabs/risingwave/blob/d37b87bf641655d775f72997a268d6e881541e6d/src/frontend/src/optimizer/plan_node/logical_project.rs#L172-L180

- Similarly when inputs not changed, `clone_with_inputs` should be able to directly return itself without cloning.  This can be achieved with `Rc::ptr_eq`.
https://github.com/risingwavelabs/risingwave/blob/d37b87bf641655d775f72997a268d6e881541e6d/src/frontend/src/optimizer/plan_node/mod.rs#L300

- There is no need to allocate a `Vec<ExprImpl>` or clone the expression when rewriting them.
https://github.com/risingwavelabs/risingwave/blob/d37b87bf641655d775f72997a268d6e881541e6d/src/frontend/src/optimizer/plan_node/generic/project.rs#L55-L63

Take this for an example, a more efficient version should be...

```rust
        for expr in self.exprs.iter_mut() {
            *expr = r.rewrite_expr(std::mem::replace(expr, ExprImpl::Dummy));
        }
```

where no allocation will be done if there's no actual rewriting.

**Review by BugenZhao — COMMENTED** [review]
This PR LGTM to achieve goal #13459.

**Comment by st1page** [comment]
> * When expressions not actually be rewritten, `rewrite_exprs` should be able to directly return itself without cloning. This can be achieved with `Cow`.
>   https://github.com/risingwavelabs/risingwave/blob/d37b87bf641655d775f72997a268d6e881541e6d/src/frontend/src/optimizer/plan_node/logical_project.rs#L172-L180


I guess we can achieve it with passing the Arc<Self>

```SQL
use std::rc::Rc;
pub trait ExprRewritable {
    fn rewrite_exprs(self: Rc<Self>) -> Rc<dyn ExprRewritable>;
}

struct Proj {
    a: i32
}

impl ExprRewritable for Proj {
    fn rewrite_exprs(self: Rc<Self>) -> Rc<dyn ExprRewritable> {
        if self.a == 1 {
            return Rc::new(Proj{ a: 2});
        } else {
            return self
        }
    }

}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ad2cde81ff455d7589f93d9832780355

**Comment by chenzl25** [comment]
> Actually I'm wondering why this could improve the performance. It appears that a no-op call of rewrite_exprs_recursive will still lead to performance overhead of cloning and allocation, which is far from ideal. 

Good idea. Maybe we can refactor it in the future if necessary. 

> In this PR, we manually add a visitor dual for a rewriter to avoid calling rewrite as much as possible. 
 However, the developers still have to make sure they're identical, just like what we talked in https://github.com/risingwavelabs/risingwave/pull/13587#issuecomment-1822303190.

I think letting developers make sure they're identical in our cases seems trivial. It is not too painful to work with it at this moment.

**Review by BugenZhao — APPROVED** [review]

**Pull request merged**
