### PR TITLE
refactor(type): introduce `Timestampz` type

### PR DESCRIPTION
**Pull request by wangrunji0408**
Signed-off-by: Runji Wang <wangrunji0408@163.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR introduces `Timestampz` type as a wrapper over the original `i64`, as well as the corresponding `TimestampzArray` and `TimestampzArrayBuilder`. It makes a 1-1 mapping between SQL data types and Rust types, removes the ambiguity of i64 value -> int64 or timestampz. Thus `ToText` and `ToBinary` can be called without specifying the data type.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by xiangjinwu** [comment]
> Thus `ToText` and `ToBinary` can be called without specifying the data type.

This may not be the right direction to go, although a 1-1 mapping does feel cleaner at first glance.

There are basically 2 different designs:
* `Scalar/Datum` contains enough sql-typing information, and can derive its corresponding `DataType`.
* `Scalar/Datum` only contains arbitrary binary data, whose proper interpretation depends on its accompanying `DataType`.

In our current implementation, `ScalarImpl` is not `[u8]` but an `enum`. So it does feel closer to the former design than the latter. However, this may just be a side effect of rust tagged union (aka enum):
* Matching against `enum` is easier to use than reinterpreting `[u8]`.
* The extra tagging bits inside `enum ScalarImpl` happen to contain enough information as `enum DataType`.

My concern is, as our `DataType` becomes complex later, the tagging bits inside `ScalarImpl` won't be enough, and we still need to take the latter design that passes `ScalarImpl` and `DataType` together.

**Comment by jon-chuang** [comment]
Do beware of: https://github.com/risingwavelabs/risingwave/pull/7067 added to merge train.

**Comment by wangrunji0408** [comment]
@xiangjinwu Thanks for the explanation! I'll revert this part.

**Comment by wangrunji0408** [comment]
Closed as it will encourage ignoring data types that leads to misinterpretation. Will reopen it when we find a proper solution.

**Pull request closed without merging**
