### PR TITLE
build: debug=1 -> "line-tables-only"

### LINKED ISSUE #9107: Use `debug=line-tables-only`
`debuginfo=1` still contains debug info. `line-tables-only` can be much smaller. I tested that it's 1.4G -> 844M

See https://github.com/rust-lang/rust/pull/109808/files#diff-6e9a08e032c83ccfc4b967a192b6d38c932eaaf6a153027bd79365830e4d7139

Wait for cargo's support https://github.com/rust-lang/cargo/pull/11958

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
close #9107

tested:
- `ci-dev` 1.4G -> 764M (zstd compressed CI artifact 204M -> 130M)
- `release` 1.3G -> 761M 

## Checklist For Contributors

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [ ] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]

**Comment by fuyufjh** [comment]
@xxchan 

`debug = "line-tables-only"` caused [heap profiling](https://github.com/risingwavelabs/risingwave/blob/252f72ee56ec1a215ee62e68834540747fa9c44e/docs/memory-profiling.md) failed to print the crate name of a function:

image


As described in Rust docs:

> * `line-tables-only`: line tables only. Generates the minimal amount of debug info for backtraces with filename/line number info, but not anything else, i.e. no variable or function parameter info.

Perhaps the crate information is excluded as well :(

We may either 1) use different compile option for profiling and release, or, 2) use the same one so that we are able to run profiling directly in users' cluster. I prefer 2 slightly. What do you think?


------------

*In addition:*

I tried to use `--lines` options of `jeprof` and it indeed can show filename and line numbers. But unluckly this cannot be used together with flamegraph (`--collapsed --lines` not work)

```
     0.0   0.0% 100.0%      0.5   0.0% push /home/ubuntu/risingwave/src/stream/src/cache/managed_lru.rs:180
     0.0   0.0% 100.0%      0.5   0.0% push_back /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/h2-0.3.18/src/proto/streams/buffer.rs:44
     0.0   0.0% 100.0%      1.0   0.0% push_front (inline) /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/collections/vec_deque/mod.rs:1633
     0.0   0.0% 100.0%      1.0   0.0% push_internal_level (inline) /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/collections/btree/node.rs:594
     0.0   0.0% 100.0%      8.7   0.0% put /home/ubuntu/.cargo/git/checkouts/lru-rs-b0d90f175c30fd68/cb2d7c7/src/lib.rs:311
     0.0   0.0% 100.0%      8.7   0.0% put /home/ubuntu/risingwave/src/stream/src/cache/managed_lru.rs:126
```

**Comment by xxchan** [comment]
I will take a look

**Comment by xxchan** [comment]
Agree to go back to `debug = 1`, although the decrease in binary size looks really cool 🥹. It doesn't matter that much now. BTW, I'm not sure what's the common practice for debuginfo in production.

**Comment by xxchan** [comment]
BTW, it seems turning off `lto` can also fix it, but of course we won't do that. 😅

**Comment by fuyufjh** [comment]
> Agree to go back to `debug = 1`, although the decrease in binary size looks really cool 🥹. It doesn't matter that much now. BTW, I'm not sure what's the common practice for debuginfo in production.

As far as I know, C++ application usually keeps all debug information with binary, but Rust has so many options and I don't know which one to use as well. 

But what I can say for sure is that our CI pipelines e.g. benchmark relies on release build. Our CI pipeline only distinguishes between `release` and `debug`, and we don't want to introduce another kind of build.

**Pull request merged**
