### PR TITLE
chore(build): bump toolchain to 2022-10-27

### LINKED ISSUE #5977: Tracking: bump compiler toolchain to 1.65
PR: https://github.com/risingwavelabs/risingwave/pull/5119

Blocked by:

- [x] https://github.com/rust-lang/rust/issues/101465
- [x] https://github.com/rust-lang/rust/issues/101750
- [x] https://github.com/rust-lang/rust/issues/103423

### PR DESCRIPTION
**Pull request by BugenZhao**
Co-Authored-By: xxchan <xxchan22f@gmail.com>
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR is mostly a replication of https://github.com/risingwavelabs/risingwave/pull/5119. We use a workaround for zip_order_key to make it compile.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

close #5977

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]

**Comment by skyzh** [comment]
@MrCroxx I've workaround the file cache lifetime problem. You should fix it if you have time later.

**Review by xxchan — APPROVED** [review]

**Comment by wangrunji0408** [comment]
@BugenZhao Any idea why building simulation timed out on CI? 🥵

**Comment by BugenZhao** [comment]
> @BugenZhao Any idea why building simulation timed out on CI? 🥵

Nope. 🥺 Does it mean we should write code really carefully after this PR? 🥵

**Comment by wangrunji0408** [comment]
Building `nexmark_chaos.rs` become extremely slow in the new toolchain. Need help from rustc experts 🆘

**Comment by skyzh** [comment]
Thanks for identifying 🤣

**Comment by BugenZhao** [comment]
> Building `nexmark_chaos.rs` become extremely slow in the new toolchain. Need help from rustc experts 🆘

There shouldn't be much black magic inside. Perhaps const generic?

**Comment by skyzh** [comment]
Probably yes. Also why don't we merge hello, nexmark_chaos, nexmark_q4 into one single binary?

**Comment by BugenZhao** [comment]
That's okay. But I think there's no problem to separate integrated tests into multiple files? 🤣

**Comment by BugenZhao** [comment]
Still don't think we should get this merged before the compiler fixes the issue. It's abnormal to put such effort or attention on these hacks while programming. 🤔

**Comment by skyzh** [comment]
> Still don't think we should get this merged before the compiler fixes the issue. It's abnormal to put such effort or attention on these hacks while programming. 🤔

I think it's more like we are abusing the type system. Sometimes we just insert random `'a` at some random place and we even don't know why it works.

**Comment by BugenZhao** [comment]
Agree on some storage stuffs, but it makes little sense on such a simple integrated test. 🤣

**Comment by skyzh** [comment]
> Agree on some storage stuffs, but it makes little sense on such a simple integrated test. 🤣

This is something I've been fixing before. All interfaces exposed by lib and not needed for inlining should have BoxFuture. Otherwise it will be recompiled in every binary. Let's see if it improves compile speed.

**Comment by skyzh** [comment]
I feel like it's also a bug of lifetime inference. FnMut seems to be the root cause for slow integration test compile. Will reproduce later. Let's workaround it first.

**Comment by skyzh** [comment]
Removing `impl<ToString>` and `impl<IntoIterator>` seem to fix everything.

**Comment by BugenZhao** [comment]
> Removing `impl<ToString>` and `impl<IntoIterator>` seem to fix everything.

This is unreasonable. 🤣🤣 There should be tons of occurrences in well-known library crates of them.

**Pull request merged**
