### PR TITLE
chore: add telemetry reminder if meeting `type/feature`

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by cyliu0** [comment]
Replaced the `pull_request_target` with `pull_request` to test the code. Refer to https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. This event allows your workflow to do things like label or comment on pull requests from forks. Avoid using this event if you need to build or run code from the pull request.

And the github-actions bot label `type/feature` won't trigger this workflow. Refer to https://github.com/peaceiris/actions-label-commenter?tab=readme-ov-file#work-with-other-auto-label-actions
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

**Review by hzxa21 — APPROVED** [review]
Generally LGTM.

I found that ~30% of the PRs are labeled as `type/feature`. I am not sure how effective the reminder can be if only a portion of them requires adding telemetry. I think reminder from the reviewers is still required.

**Review by fuyufjh — APPROVED** [review]
Thanks!

**Comment by tabVersion** [comment]
> > Generally LGTM.
> > I found that ~30% of the PRs are labeled as `type/feature`. I am not sure how effective the reminder can be if only a portion of them requires adding telemetry. I think reminder from the reviewers is still required.
> 
> How about `user-facing-changes + type/feature`? which restricts to the features that really matters to users.

Just `user-facing-changes` seems okay. Telemetry focus mainly on user-facing PRs. 
The action may not have the ability to handle AND logic within labels.

**Pull request merged**
