### PR TITLE
fix(batch): fix local execute query stuck

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- ~~For local execution, the LOCAL_EXECUTE_BUFFER_SIZE is not large enough which would cause stuck.~~
- Spawns a future for local execution to avoid query stuck

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#5499

### CODE REVIEW

**Comment by lmatz** [comment]
how about making it a configurable parameter in 'src/config/risingWave.toml'?

There are several examples in the '[streaming.developer]' subsection

**Comment by chenzl25** [comment]
> streaming.developer

I am still thinking about whether our local execution has run in a correct way. The producer keep producing data until buffer filled up while consumer has no idea.

**Comment by chenzl25** [comment]
> > streaming.developer
> 
> I am still thinking about whether our local execution has run in a correct way. The producer keep producing data until buffer filled up while consumer has no idea.

I think I catch the bug.

**Review by lmatz — APPROVED** [review]
LGTM! Seems to be the same bug as https://github.com/risingwavelabs/risingwave-legacy/pull/1215/files😂

**Pull request merged**
