### PR TITLE
fix(stream agg): fix cache filling to avoid relying on `row_count`

### PR DESCRIPTION
**Pull request by richardchien**
Signed-off-by: Richard Chien <stdrc@outlook.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Previously we have an in-memory `row_count` variable maintained by `apply_batch`, and the value is restored from `row_count` column in result table. However, the problem is that, when filters are applied on some agg calls (especially different filters for different calls), the count maintained by `apply_batch` will be inconsistent with the `row_count` column. So we decided to remove the use of `row_count` in state caches.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

https://github.com/risingwavelabs/risingwave/issues/7394

### CODE REVIEW

**Review by st1page — APPROVED** [review]
LGTM. about the name, how about `TopNStateCache` and `SortedStateCache`?

**Review by BugenZhao — APPROVED** [review]
LGTM. I'm actually not sure whether this reduces the performance or improves the performance (as there seems unnecessary to add the `RowCount` agg call for streaming?). 😄

**Review by soundOfDestiny — APPROVED** [review]
lgtm

**Comment by richardchien** [comment]
> I'm actually not sure whether this reduces the performance or improves the performance (as there seems unnecessary to add the `RowCount` agg call for streaming? so we don't need to maintain it). 😄

Ideally we don't need to maintain `row_count` column, but we did it anyway. `row_count` column is still used in `build_changes`, and problem still exists (#7412) so we can't remove it for now. Need some discussion to reach a consensus on #7412.

**Pull request merged**
