### PR TITLE
feat: package dashboard artifact in docker image

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Previously when using RisingWave via docker, dashboard artifact is proxied to GitHub, so it's not accessible without internet connection. This PR adds dashboard artifact to the docker image and use the local one.

### Types of user-facing changes

- Installation and deployment
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by lmatz — APPROVED** [review]

**Comment by xxchan** [comment]
FIXME: 
image

**Comment by xxchan** [comment]
https://buildkite.com/risingwavelabs/docker/builds/13428#01869925-958e-4829-aa4f-e6de9a158c1e

tested locally 
```
docker run -it -p 4566:4566 -p 5691:5691 ghcr.io/risingwavelabs/risingwave:870f32ae3b157e5f1c6e32f579957b44bd82925c-aarch64 playground 


```

**Comment by xxchan** [comment]
We‘d better build dashboard in Dockerfile instead of downloading from GitHib 🤣

**Comment by BugenZhao** [comment]
Oh. This reminds me that I introduced the Monaco editor for the await-tree dump in #8330 and it requires additional assets from CDN. 😢 Maybe we should get rid of this as well.

**Comment by xxchan** [comment]
@BugenZhao Couldn’t it be packaged? (static link🤪)

**Comment by BugenZhao** [comment]
> @BugenZhao Couldn’t it be packaged? (static link🤪)

Not deep dived yet. Next time for sure!

**Pull request merged**
