### PR TITLE
feat: support for displaying sinks in the pg_class system table

### PR DESCRIPTION
**Pull request by idx0-dev**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Support for displaying sinks in the `pg_class` system table. The `relkind` of Sink relation type is `'s'`.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
 #7577

### CODE REVIEW

**Comment by tabVersion** [comment]
will this pr print sink in relations displayed in \t

psql=> \t

**Comment by yezizp2012** [comment]
> will this pr print sink in relations displayed in \t
> 
> 
> 
> psql=> \t

No I guess. The relkind of 's' is not a standard kind in PostgreSQL. So it's should not be included in any sqls of '\t', '\d' or others.

**Review by yezizp2012 — APPROVED** [review]

**Review by tabVersion — APPROVED** [review]

**Comment by tabVersion** [comment]
any updates?

**Comment by tabVersion** [comment]
close for no activity.

**Pull request closed without merging**
