### PR TITLE
chore: use a stable version instead of latest

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

`latest` is confusing. It does not necessarily give the true latest version of the image.

When users try to use `docker compose` to bring up the Risingwave cluster, it may start a stale one and has bugs.

https://www.risingwave.dev/docs/current/risingwave-trial/?method=docker-compose
To avoid a random version, either doc or this repo needs to be updated at the time of release.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by wcy-fdu — APPROVED** [review]

**Comment by fuyufjh** [comment]
Oops. This broke 

https://github.com/risingwavelabs/risingwave/blob/aceb8659680e2aef0ac5a8bbf0d75989f257dd3b/ci/scripts/integration-tests.sh#L45

**Comment by wcy-fdu** [comment]
> Oops. This broke
> 
> https://github.com/risingwavelabs/risingwave/blob/aceb8659680e2aef0ac5a8bbf0d75989f257dd3b/ci/scripts/integration-tests.sh#L45

Should we revert this PR?

**Comment by fuyufjh** [comment]
It's okay. I'm fixing it.

**Comment by fuyufjh** [comment]
Will be fixed by 8aa274c25e1a2da71147b0397e95f53460bd77c2

**Pull request merged**
