### PR TITLE
fix: assert fail when migrating singleton fragment

### LINKED ISSUE #6768: scale: cannot migrate singleton fragment
Unfortunately, we have no coverage for singleton fragments in the scaling chaos test. 🥵 And it seems the capability for migrating singleton fragment has been broken after some changes: we'll panic on assertion here:

https://github.com/risingwavelabs/risingwave/blob/9e749bd5d98606a8cd4b5e199f9da233ef750f91/src/meta/src/stream/scale.rs#L253-L262

Full logs here: https://buildkite.com/risingwavelabs/pull-request/builds/13320#0184e701-84ba-4d26-91d3-ce94501f7af6

I'll add more tests in #6758.

### PR DESCRIPTION
**Pull request by shanicky**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Fix #6768 

This PR skips the vnode rebalance of the Singleton distribution from the upper layer, thus preventing an already existing assert from failing.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
#6768

### CODE REVIEW

**Comment by BugenZhao** [comment]
Looks like the hash mapping field is set for the singleton inner side of the dynamic filter? 🤔

https://buildkite.com/risingwavelabs/pull-request/builds/13499#0184f279-ad93-46a9-b3a1-5e7b944dcb2a

**Comment by shanicky** [comment]
> Looks like the hash mapping field is set for the singleton inner side of the dynamic filter? 🤔
> 
> https://buildkite.com/risingwavelabs/pull-request/builds/13499#0184f279-ad93-46a9-b3a1-5e7b944dcb2a


It looks like this, for q102's DAG, `DynamicFilter` Fragment will have both types of upstream Dispatcher: `Hash` and `Broadcast`. According to the current semantics of `RescheduleCommand`, we can only update both Dispatchers through one Barrier, but the update of these two Dispatchers is different, `Hash` needs to update downstream actors and mapping, while Broadcast does not need to update mapping, so maybe that assert can be skipped when Dispatcher is `Broadcast`
🤔

**Comment by shanicky** [comment]
We currently appear to have 3 (4?) Dispatcher types, may be combined in multiple ways in the case of `DynamicFilter`,and it feels like the assert here will prevent many combinations

**Comment by BugenZhao** [comment]
Makes sense. I'll give it a try. 🤔

**Review by BugenZhao — APPROVED** [review]
LGTM!

**Pull request merged**
