### PR TITLE
fix: faster lru watermark to avoid OOM

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- check and update watermark more frequently.
- hash join evict cache more frequently.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by yuhao-su** [comment]
Maybe use https://github.com/singularity-data/risingwave/blob/7b0f2d21d278013faca232d399d0366352b240e0/src/common/src/collection/estimate_size.rs#L20 we maintained?

**Comment by yuhao-su** [comment]
I didn't see any OOM loops in the recent longevity tests. I think we can merge this change.

**Comment by liurenjie1024** [comment]
Have you run mv on mv on this branch?

**Comment by yuhao-su** [comment]
> Have you run mv on mv on this branch?

I use the same load in longevity test. I think it has mv on mv work load?

**Comment by lmatz** [comment]
> > Have you run mv on mv on this branch?
> 
> I use the same load in the longevity test. I think it has mv on mv workload?

It seems that each time the queries are different in the longevity tests, we can run multiple ones to be more confident.


And how about also e2e performance tests: https://buildkite.com/risingwave-test/nexmark-benchmark for all nexmark queries once?

**Comment by lmatz** [comment]
Is it tested?

**Comment by liurenjie1024** [comment]
> Is it tested?

You mean performance test or ci?

**Comment by lmatz** [comment]
both? let's say longevity test more important

**Pull request merged**
