### PR TITLE
chore: enable info logging by default for release build

### PR DESCRIPTION
**Pull request by hzxa21**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Enable info logging by default to avoid missing logs in release build

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
IIRC, we've applied something like [this](https://docs.rs/tracing/latest/tracing/level_filters/index.html#compile-time-filters)?

**Comment by hzxa21** [comment]
> IIRC, we've applied something like [this](https://docs.rs/tracing/latest/tracing/level_filters/index.html#compile-time-filters)?

We have enabled [release_max_level_info](https://github.com/risingwavelabs/risingwave/blob/415b0701fc59915b818e2b2e30c0682e8cb472d0/src/utils/workspace-config/Cargo.toml#L21) but IIUC it just means that we DEBUG/TRACE logs will not be included in the binary. It doesn't mean that all INFO level logs will be printed out in the runtime if we don't set the leve filter (or set RUST_LOG=info) accordingly. 

In fact, when debugging a production issue, we found that some critical info/warn logs are missing and we didn't notice that these logs are turned off by default for release build, which has distracted the debugging process...

**Review by TennyZhuang — APPROVED** [review]

**Review by BugenZhao — APPROVED** [review]
LGTM. Maybe it's also time for us to cleanup these lines...

https://github.com/risingwavelabs/risingwave/blob/83de0116d5576080d17b783edb8aae3fb9d70461/src/utils/runtime/src/lib.rs#L49-L61

**Comment by hzxa21** [comment]
> LGTM. Maybe it's also time for us to cleanup these lines...
> 
> https://github.com/risingwavelabs/risingwave/blob/83de0116d5576080d17b783edb8aae3fb9d70461/src/utils/runtime/src/lib.rs#L49-L61

Based on the documentation of `configure_risingwave_targets_fmt`, it seems to be used for enable TRACE logs. Why do we instead use it for INFO/DEBUG logs? If we don't have a specific reason, I can remove them in this PR as well.

**Comment by lmatz** [comment]
> We have enabled [release_max_level_info](https://github.com/risingwavelabs/risingwave/blob/415b0701fc59915b818e2b2e30c0682e8cb472d0/src/utils/workspace-config/Cargo.toml#L21) but IIUC it just means that we DEBUG/TRACE logs will not be included in the binary.

which means setting `RUST_LOG=debug` does not work for a release build? 
then https://github.com/risingwavelabs/kube-bench/pull/100/files will have no effect I suppose, right?

**Comment by BugenZhao** [comment]
> then [risingwavelabs/kube-bench#100 (files)](https://github.com/risingwavelabs/kube-bench/pull/100/files) will have no effect I suppose, right?

I guess so... 🤔

**Comment by lmatz** [comment]
in chaos mesh test, we want to have the debug log and considering the chaos test may fail much more frequently than others......

**Comment by hzxa21** [comment]
Created #9401 for further discussions.

**Pull request merged**
