### PR TITLE
feat(test): more chaos when killing nodes in recovery test

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Previously in recovery test we would pick some nodes and kill them **at the same time**. This PR messes up this process by making each node be killed and restarted **at a random order**. And for each kind of nodes (CN/FE/meta/compactor), any number (0-all) of them might be killed at a time.

This PR also bumps madsim-tonic version, to add interceptor support for #6466.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
https://github.com/madsim-rs/madsim/pull/91

### CODE REVIEW

**Comment by wangrunji0408** [comment]
Now we get another bunch of errors. 🤣
https://buildkite.com/risingwavelabs/pull-request/builds/13137#_

**Comment by yezizp2012** [comment]
> Now we get another bunch of errors. 🤣 cc @yezizp2012 https://buildkite.com/risingwavelabs/pull-request/builds/13137#0184d1ef-405a-4afa-b92e-08531fe9b3e1

Took a quick look, they were all same problems as I fixed in #6687 . 🥵  panic of unwrap everywhere.

**Comment by yezizp2012** [comment]
> Now we get another bunch of errors. 🤣 cc @yezizp2012 https://buildkite.com/risingwavelabs/pull-request/builds/13137#0184d1ef-405a-4afa-b92e-08531fe9b3e1

I tried to fix these panics in #6709 , and tested it under the changes in your branch. The recovery test passed with kill-rate=1.0 but I'm not sure if they were just lucky runs. 🥵

**Comment by wangrunji0408** [comment]
Is this OK to merge? 👀 @yezizp2012

**Comment by yezizp2012** [comment]
> Is this OK to merge? 👀 @yezizp2012

LGTM. Let's give it another try and merge it if passed. 🥵

**Review by yezizp2012 — APPROVED** [review]
LGTM

**Pull request merged**
