### PR TITLE
ci: fix cron invalid workflow

### LINKED ISSUE #2304: ci: main cron job never runs
https://github.com/singularity-data/risingwave/actions/workflows/main-cron.yml

Seems always failure.

cc @tabVersion may take a look?

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)

Close #2304

### CODE REVIEW

**Comment by TennyZhuang** [comment]
https://github.com/singularity-data/risingwave/actions/runs/2270362072

manual trigger

**Comment by TennyZhuang** [comment]
image
It seems that ec2-c do nothing :(

**Comment by TennyZhuang** [comment]
You can add ec2-c back while you add connector tests later :(

**Review by skyzh — APPROVED** [review]
Would you please also help change the `permissions` of `main-cron.yml` to

```
permissions:
  id-token: write
  contents: write
```

**Comment by TennyZhuang** [comment]
https://github.com/singularity-data/risingwave/actions/runs/2270629634

**Pull request merged**
