### PR TITLE
fix(batch, source): Propagate user errors

### PR DESCRIPTION
**Pull request by jon-chuang**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
Error for user batch source error.

Question: should we propagate backtrace?

Previous behaviour: silently ignore. Now:
```
dev=> create source s2 (v1 int, v2 varchar) with (
  connector = 'kafka',
  topic = 'kafka_1_partition_topic',
  properties.bootstrap.server = '127.0.0.1:29092',
  scan.startup.mode = 'earliest'
) row format json;
CREATE_SOURCE
dev=> ^C
dev=> ^C
dev=> select * from s2;
ERROR:  QueryError: Internal(Protocol error: ExpectedObjectContent at character 1 ('e')
Stack backtrace:
   0: anyhow::kind::Adhoc::new
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.69/src/kind.rs:70:36
   1: <risingwave_batch::error::BatchError as core::convert::From<risingwave_common::error::RwError>>::from
             at ./src/batch/src/error.rs:67:18
   2: risingwave_batch::task::task_execution::BatchTaskExecution<C>::run::{{closure}}
             at ./src/batch/src/task/task_execution.rs:522:44
   3: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
   4: risingwave_batch::task::task_execution::BatchTaskExecution<C>::async_execute::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/batch/src/task/task_execution.rs:393:21
   5: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-metrics-0.1.0/src/task.rs:2365:19
   6: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   7: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
   8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
   9: tokio::runtime::task::core::Core<T,S>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  10: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  12: std::panicking::try::do_call
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  13: __rust_try
  14: std::panicking::try
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  15: std::panic::catch_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  16: tokio::runtime::task::harness::poll_future
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  17: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  18: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  19: tokio::runtime::task::raw::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  20: tokio::runtime::task::raw::RawTask::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  21: tokio::runtime::task::LocalNotified<S>::run
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:394:9
  22: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  23: tokio::runtime::coop::with_budget
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
  24: tokio::runtime::coop::budget
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
  25: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  26: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  27: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  28: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
  29: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  30: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  31: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/task.rs:42:21
  32: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  33: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  34: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  35: tokio::runtime::task::core::Core<T,S>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  36: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  38: std::panicking::try::do_call
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  39: __rust_try
  40: std::panicking::try
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  41: std::panic::catch_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  42: tokio::runtime::task::harness::poll_future
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  43: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  44: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  45: tokio::runtime::task::raw::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  46: tokio::runtime::task::raw::RawTask::poll
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  47: tokio::runtime::task::UnownedTask<S>::run
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:431:9
  48: tokio::runtime::blocking::pool::Task::run
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:159:9
  49: tokio::runtime::blocking::pool::Inner::run
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:511:17
  50: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/jonch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:469:13
  51: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys_common/backtrace.rs:121:18
  52: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/thread/mod.rs:560:17
  53: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  54: std::panicking::try::do_call
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  55: __rust_try
  56: std::panicking::try
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  57: std::panic::catch_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  58: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/thread/mod.rs:559:30
  59: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/ops/function.rs:250:5
  60: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/boxed.rs:1988:9
  61: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/boxed.rs:1988:9
  62: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys/unix/thread.rs:108:17
  63: start_thread
             at ./nptl/./nptl/pthread_create.c:442:8
  64: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81)
```
## Checklist For Contributors

- [X] I have written necessary rustdoc comments
- [X] I have added necessary unit tests and integration tests
- [X] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [X] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [X] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [X] My PR **DOES NOT** contain user-facing changes.

## Related
Closes: https://github.com/risingwavelabs/risingwave/issues/8232

### CODE REVIEW

**Comment by jon-chuang** [comment]
Seems the kafka source tests are producing EOF issue: 
```
thread '<unnamed>' panicked at 'query failed: db error: ERROR: QueryError: Internal(Protocol error: Eof at character 0
```
Is this expected? @tabVersion

**Comment by tabVersion** [comment]
> Seems the kafka source tests are producing EOF error:
> 
> ```
> thread '<unnamed>' panicked at 'query failed: db error: ERROR: QueryError: Internal(Protocol error: Eof at character 0
> ```
> 
> Is this expected? @tabVersion
> 
> Perhaps it's simply a test generation issue? Could we fix it so that it does not produce this EOF?

We only deliver necessary info to users and, absolutely, not full backtrace.
I don't get how the panic is produced, can you share the topic contents?

**Comment by jon-chuang** [comment]
> I don't get how the panic is produced, can you share the topic contents?

This was produced by the deterministic simulation tests https://buildkite.com/risingwavelabs/pull-request/builds/19271#0186d84a-07af-4cab-9c5b-28b8428ec29a

**Comment by wangrunji0408** [comment]
Looks like a bug in the mock. I'll fix it soon.

**Comment by wangrunji0408** [comment]
It turns out that we were feeding an empty message to Kafka topic. I've fixed it in the simulation code. Not related to madsim.

**Review by tabVersion — APPROVED** [review]

**Pull request merged**
