### PR TITLE
feat(connector): add nats integration test

### PR DESCRIPTION
**Pull request by yufansong**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

Add integration test for nats source/sink. 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by StrikeW** [comment]
You may need to add `query.sql` and `data_check` files, please refer to the `ci/scripts/integration-tests.sh` for the steps of integration test.

**Comment by StrikeW** [comment]
Hi @yufansong, do you plan to go on this work?

**Comment by yufansong** [comment]
> Hi @yufansong, do you plan to go on this work?

Oh, almost forget this one. I can continue this one in next week. Currently busy with some more urgent task. Thanks for remind. @StrikeW

**Comment by yufansong** [comment]
> You may need to add `query.sql` and `data_check` files, please refer to the `ci/scripts/integration-tests.sh` for the steps of integration test.

@StrikeW I have checked the `ci/scripts/integration-tests.sh` logic. Currently I test it manually by running the `run_demo.py`, `check_data.py` and `clean_demos.py`. Is there anything I need to test?

**Comment by StrikeW** [comment]
> > You may need to add `query.sql` and `data_check` files, please refer to the `ci/scripts/integration-tests.sh` for the steps of integration test.
> 
> @StrikeW I have checked the `ci/scripts/integration-tests.sh` logic. It can run correctly in `run_demo.py`, `check_data.py` and `clean_demos.py`. Is there anything I need to test?
> 
> But I didn't directly run the `ci/scripts/integration-tests.sh` locally because of some env parameter configuration. Is there any way to run it directly?

You can build a docker image against your branch then trigger the integration test pipeline manually from buildkite and specify your image via the `RW_IMAGE` parameter.

**Comment by yufansong** [comment]
> > > You may need to add `query.sql` and `data_check` files, please refer to the `ci/scripts/integration-tests.sh` for the steps of integration test.
> > 
> > 
> > @StrikeW I have checked the `ci/scripts/integration-tests.sh` logic. It can run correctly in `run_demo.py`, `check_data.py` and `clean_demos.py`. Is there anything I need to test?
> > But I didn't directly run the `ci/scripts/integration-tests.sh` locally because of some env parameter configuration. Is there any way to run it directly?
> 
> You can build a docker image against your branch then trigger the integration test pipeline manually from buildkite and specify your image via the `RW_IMAGE` parameter.

Yeah, I test it in buildkite intergration-test workflow and the [result](https://buildkite.com/risingwavelabs/integration-tests/builds/517#018c7017-34ee-4cec-abae-3b80c29c7c12) is correct.

**Review by tabVersion — APPROVED** [review]
basically LGTM, are there related tests in CI?

**Comment by yufansong** [comment]
> basically LGTM, are there related tests in CI?
@tabVersion I manually trigger the test [here ](https://buildkite.com/risingwavelabs/integration-tests/builds/517#018c7017-34ee-4cec-abae-3b80c29c7c12)

**Pull request merged**
