### PR TITLE
feat(meta): support sql meta store backup and restoration

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR adds support for sql meta store backup and restoration.
- serde_json is used to serde sea_orm types. Previously I meant to use bincode, but it turned out bincode cannot serde sea_orm types correctly.
- meta backup e2e test is enabled for sql meta store.

Known issue:
- `sea_orm::IsolationLevel::Serializable` is used when creating a metadata backup. However, sea_orm only raise warning when it's not supported by backend (e.g. sqlite). I think it's fine as long as the sql backend in production supports `sea_orm::IsolationLevel::Serializable`.
- Newly added metadata model by default is not included in backup. We need a reminder for it, similar to the `MetadataModelMarker` for etcd meta store.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by BugenZhao — COMMENTED** [review]
May I ask why don't we directly dump the meta store database as the backup? This seems to be much easier and less error-prone to implement.

**Comment by zwang28** [comment]
> May I ask why don't we directly dump the meta store database as the backup? This seems to be much easier and less error-prone to implement.

A metadata backup includes [meta store database snapshot] + [SSTs required by this snapshot, which is not stored in meta store database]. It's necessary to ensure these two pieces are consistent.

> dump the meta store database as the backup
By `dump` do you mean `select * from` or tools like `pg_dump`?

**Comment by BugenZhao** [comment]
> It's necessary to ensure these two pieces are consistent.

This is true. If I understand it correctly, a synchronization mechanism between the meta store and the object store is required when doing backup.

However, once they have been synchronized (say that a "snapshot" is captured), it doesn't seem to matter whether we query different kinds of entities one by one, or directly dump all data from the database without actual knowledge of the data itself.

> we must always restore the [next Hummock SST id] metadata from the latest backup rather than the speficied one

Hmm, this is a bit counterintuitive to me. I always thought backup-restore was majorly the same as a bootstrap recovery during restart. 😕

> The problem with the latter is, besides the above-mentioned one, it's not universal for other SQL backend.

Agree but I guess it just requires a layer of abstraction, though I'm not sure whether there's existing solution with `sea-orm` or `sqlx`.

**Comment by zwang28** [comment]
> we must always restore the [next Hummock SST id] metadata from the latest backup rather than the speficied one

> Hmm, this is a bit counterintuitive to me. I always thought backup-restore was majorly the same as a bootstrap recovery during restart. 😕

To be more specific, say there're backups B1={ [ SST0 ], next_SST_ID=1 }, B2={ [ SST0, SST1 ], next_SST_ID=2 }.
When restoring B1, the next_SST_ID should be max next_SST_ID of from all B*, i.e. next_SST_ID=2 in this case.
Otherwise, if next_SST_ID=1, the new SST1* written by the restored cluster will overwrite the old SST1 used by B2, which actually makes B2 invalid.

**Comment by yezizp2012** [comment]
> To be more specific, say there're two backups B1={ [ SST0 ], next_SST_ID=1 }, B2={ [ SST0, SST1 ], next_SST_ID=2 }.
When restoring B1, the next_SST_ID should be max next_SST_ID of from all B*, i.e. next_SST_ID=2 from B2 in this case.
Otherwise, if set next_SST_ID=1, the new SST1* written by the restored cluster will overwrite the old SST1 used by B2, which actually makes B2 invalid.

If it is restored to the previous version, will the object id be affected? If the allocated table id has been used before In some newer backups.

**Comment by zwang28** [comment]
> > To be more specific, say there're two backups B1={ [ SST0 ], next_SST_ID=1 }, B2={ [ SST0, SST1 ], next_SST_ID=2 }.
> > When restoring B1, the next_SST_ID should be max next_SST_ID of from all B*, i.e. next_SST_ID=2 from B2 in this case.
> > Otherwise, if set next_SST_ID=1, the new SST1* written by the restored cluster will overwrite the old SST1 used by B2, which actually makes B2 invalid.
> 
> If it is restored to the previous version, will the object id be affected? If the allocated table id has been used before In some newer backups.

No it won't be affected. Because any changes after restoration are kept in SSTs with id >= max(next_SST_ID), which is not used by any backups.

**Review by yezizp2012 — APPROVED** [review]
It's indeed a little bit error-prone to handle all tables case by case. We might need another similar mechanism like using `for_all_metadata_models`. Let's merge it first to support backup, Later, let's see if we can integrate any other external tools to avoid this problem.

**Comment by zwang28** [comment]
I'll merge this PR first, to make a sql backup available in the coming release.

> May I ask why don't we directly dump the meta store database as the backup? This seems to be much easier and less error-prone to implement.

> Later, let's see if we can integrate any other external tools to avoid this problem.

This is absolutely a better solution,  but there're some details to handle, as mentioned in https://github.com/risingwavelabs/risingwave/pull/16384#issuecomment-2073933516. We can implement it as a new backup format in the future.

@yezizp2012 @BugenZhao

**Pull request merged**
