### PR TITLE
feat(dashboard): add plan overview based on d3-dag

### PR DESCRIPTION
**Pull request by xxchan**
Signed-off-by: xxchan <37948597+xxchan@users.noreply.github.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by BugenZhao** [comment]
Any preview? Or the same as the previous version? 🤩

**Comment by skyzh** [comment]
image

The sidebar is nearly complete. You can select a fragment from the sidebar, and the connected edges will be highlighted.

@BugenZhao

**Comment by st1page** [comment]
good work! btw, what will be at the right part? a complete stream plan graph or just the plan nodes in the selected fragment? 
I prefer a complete graph. And when the user selects a fragment, the part will be high-light. What do you think

**Review by mikechesterwang — APPROVED** [review]
LSTM!

**Comment by skyzh** [comment]
> good work! btw, what will be at the right part? a complete stream plan graph or just the plan nodes in the selected fragment?
> I prefer a complete graph. And when the user selects a fragment, the part will be high-light. What do you think

Yes, that's the plan.

**Pull request merged**
