### PR TITLE
fix(frontend): avoid panic when querying log store internal table

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix https://github.com/risingwavelabs/risingwave/issues/14429

Now the query will return error instead of panic
```
dev=> select * from __internal_s_3_sink_1003;
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Scheduler error
  2: distribution key [4] must be a subset of primary key [0, 1]
```

In this PR, we allow returning error in some frontend methods instead of panic directly.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
Hmmm, it's better than panic, but is it possible to allow selecting from sink's internal table?

This error doesn't make sense to me/users because it's not the fault of this `select` statement.

**Comment by wenym1** [comment]
> but is it possible to allow selecting from sink's internal table?

I just inspected our codebase. We have many codes that are based on the assumption that the dist key is a subset of primary key. The panic comes from breaking the assumption in log store's internal table. Therefore, to allow selecting from the log store's internal table, we will need a great amount of work to refactor our code to break the assumption, and this is not trivial. Given that this is a special internal table and users are not expected to often query from it, it's not worthwhile to support this small case with great amount of work. Personally I think the best solution is just to avoid panic and report error. To be more user-friendly, we can change to a more reasonable error message such as `distribution key is not a subset of primary key. You are probably querying a special sink internal table`.

**Comment by st1page** [comment]
> > but is it possible to allow selecting from sink's internal table?
> 
> I just inspected our codebase. We have many codes that are based on the assumption that the dist key is a subset of primary key. The panic comes from breaking the assumption in log store's internal table. Therefore, to allow selecting from the log store's internal table, we will need a great amount of work to refactor our code to break the assumption, and this is not trivial. Given that this is a special internal table and users are not expected to often query from it, it's not worthwhile to support this small case with great amount of work. Personally I think the best solution is just to avoid panic and report error. To be more user-friendly, we can change to a more reasonable error message such as `distribution key is not a subset of primary key. You are probably querying a special sink internal table`.

Can we add an vnode column in the logstore's state table to use the `tableCatalog::vnode_idx`?

**Comment by fuyufjh** [comment]
> Can we add an vnode column in the logstore's state table to use the `tableCatalog::vnode_idx`?

Same idea. Store `vnode` as a separated column and use it as dist key & PK of this table. It may look similar with the state table of LocalAgg.

**Review by st1page — APPROVED** [review]
LGTM, because it fixes the panic of the FE though does not fix the issue https://github.com/risingwavelabs/risingwave/issues/14429
We will do https://github.com/risingwavelabs/risingwave/issues/14503 in the later PR.

**Review by hzxa21 — APPROVED** [review]
LGTM

**Pull request merged**
