### PR TITLE
test: Disable kill when create.

### PR DESCRIPTION
**Pull request by liurenjie1024**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

`create table as` is also not atomic in our system, so we should avoid killing in determined test.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Review by wangrunji0408 — APPROVED** [review]

**Comment by yezizp2012** [comment]
We still need to verify the correctness of other create DDLs like `CREATE TABLE/MATERIALIZED VIEW` etc. Let's disable kill only for `CREATE TABLE AS`.

**Comment by BugenZhao** [comment]
> We still need to verify the correctness of other create DDLs like `CREATE TABLE/MATERIALIZED VIEW` etc. Let's disable kill only for `CREATE TABLE AS`.

+1. Disable killing on all creates decreases the coverage a lot.

**Comment by liurenjie1024** [comment]
> > We still need to verify the correctness of other create DDLs like `CREATE TABLE/MATERIALIZED VIEW` etc. Let's disable kill only for `CREATE TABLE AS`.
> 
> +1. Disable killing on all creates decreases the coverage a lot.

Yes, I've updated to disable `create table as` only.

**Review by yezizp2012 — APPROVED** [review]
LGTM

**Pull request merged**
