### PR TITLE
fix(test): handle `RETURNING` correctly in recovery test

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

We also need to match `Record::Query` for DMLs.

In this PR, we also
- skip `FLUSH` as we always enable `IMPLICIT_FLUSH`,
- only forward logs to the file and print the test case file name in the console.

After #7470 gets merged, we should be able to enable `dml_returning.slt.part`.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- #7470
- #7461

### CODE REVIEW

**Comment by BugenZhao** [comment]
image
It's interesting that the log is printed after a while (7:11 vs 7:17). 🤔

**Review by wangrunji0408 — APPROVED** [review]
LGTM

**Comment by BugenZhao** [comment]
```
2022-12-03T04:13:43.001197Z ERROR node{id=5 name="frontend-2"}:task{id=590828}: risingwave_frontend::session: failed to handle sql:
CREATE TABLE test (a INTEGER, b INTEGER);:
Catalog error: table with name test exists
2022-12-03T04:13:43.007658Z ERROR node{id=11 name="client"}:task{id=995}: risingwave_simulation::slt: failed to run test: statement failed: db error: ERROR: QueryError: Catalog error: table with name test exists
[SQL] CREATE TABLE test (a INTEGER, b INTEGER);
at e2e_test/batch/./duckdb/./join/inner/test_join.slt.part:9
at e2e_test/batch/./duckdb/all.slt.part:4
at e2e_test/batch/distribution_mode.slt:9

retry after 1s
2022-12-03T04:13:44.007658Z  INFO node{id=11 name="client"}:task{id=995}: sqllogictest::runner: testing record=Statement { loc: Location { file: "e2e_test/batch/./duckdb/./join/inner/test_join.slt.part", line: 9, upper: Some(Location { file: "e2e_test/batch/./duckdb/all.slt.part", line: 4, upper: Some(Location { file: "e2e_test/batch/distribution_mode.slt", line: 9, upper: None }) }) }, conditions: [], expected_error: None, sql: "CREATE TABLE test (a INTEGER, b INTEGER);", expected_count: None }
2022-12-03T04:13:44.017208Z ERROR node{id=5 name="frontend-2"}:task{id=590828}: risingwave_frontend::session: failed to handle sql:
CREATE TABLE test (a INTEGER, b INTEGER);:
Catalog error: table with name test exists
2022-12-03T04:13:44.025673Z  INFO node{id=11 name="client"}:task{id=995}: sqllogictest::runner: testing record=Statement { loc: Location { file: "e2e_test/batch/./duckdb/./join/inner/test_join.slt.part", line: 12, upper: Some(Location { file: "e2e_test/batch/./duckdb/all.slt.part", line: 4, upper: Some(Location { file: "e2e_test/batch/distribution_mode.slt", line: 9, upper: None }) }) }, conditions: [], expected_error: None, sql: "INSERT INTO test VALUES (11, 1), (12, 2), (13, 3);", expected_count: None }
2022-12-03T04:13:44.035775Z ERROR node{id=5 name="frontend-2"}:task{id=590828}: risingwave_frontend::session: failed to handle sql:
INSERT INTO test VALUES (11, 1), (12, 2), (13, 3);:
Bind error: INSERT has more target columns than expressions
thread '<unnamed>' panicked at 'failed to run test after retry 0 times: statement failed: db error: ERROR: QueryError: Bind error: INSERT has more target columns than expressions
[SQL] INSERT INTO test VALUES (11, 1), (12, 2), (13, 3);
at e2e_test/batch/./duckdb/./join/inner/test_join.slt.part:12
at e2e_test/batch/./duckdb/all.slt.part:4
at e2e_test/batch/distribution_mode.slt:9
', /risingwave/src/tests/simulation/src/slt.rs:116:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:64:14
   2: risingwave_simulation::slt::run_slt_task::{{closure}}
             at ./src/tests/simulation/src/slt.rs:116:33
   3: risingwave_simulation::main::{{closure}}::{{closure}}::{{closure}}
             at ./src/tests/simulation/src/main.rs:182:57
   4: async_task::raw::RawTask<F,T,S>::run
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/raw.rs:511:20
   5: madsim::sim::task::Executor::run_all_ready
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/task.rs:209:17
   6: madsim::sim::task::Executor::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/task.rs:159:13
   7: madsim::sim::runtime::Runtime::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/runtime/mod.rs:124:9
   8: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/runtime/builder.rs:128:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: run with `MADSIM_TEST_SEED=14` environment variable to reproduce this error
      and make sure `MADSIM_CONFIG_HASH=1AD2E4ABC41F3553`
```
😕

**Comment by Eurekaaw** [comment]
> ```
> 2022-12-03T04:13:43.001197Z ERROR node{id=5 name="frontend-2"}:task{id=590828}: risingwave_frontend::session: failed to handle sql:
> CREATE TABLE test (a INTEGER, b INTEGER);:
> Catalog error: table with name test exists
> 2022-12-03T04:13:43.007658Z ERROR node{id=11 name="client"}:task{id=995}: risingwave_simulation::slt: failed to run test: statement failed: db error: ERROR: QueryError: Catalog error: table with name test exists
> [SQL] CREATE TABLE test (a INTEGER, b INTEGER);
> at e2e_test/batch/./duckdb/./join/inner/test_join.slt.part:9
> at e2e_test/batch/./duckdb/all.slt.part:4
> at e2e_test/batch/distribution_mode.slt:9
> 
> retry after 1s
> 2022-12-03T04:13:44.007658Z  INFO node{id=11 name="client"}:task{id=995}: sqllogictest::runner: testing record=Statement { loc: Location { file: "e2e_test/batch/./duckdb/./join/inner/test_join.slt.part", line: 9, upper: Some(Location { file: "e2e_test/batch/./duckdb/all.slt.part", line: 4, upper: Some(Location { file: "e2e_test/batch/distribution_mode.slt", line: 9, upper: None }) }) }, conditions: [], expected_error: None, sql: "CREATE TABLE test (a INTEGER, b INTEGER);", expected_count: None }
> 2022-12-03T04:13:44.017208Z ERROR node{id=5 name="frontend-2"}:task{id=590828}: risingwave_frontend::session: failed to handle sql:
> CREATE TABLE test (a INTEGER, b INTEGER);:
> Catalog error: table with name test exists
> 2022-12-03T04:13:44.025673Z  INFO node{id=11 name="client"}:task{id=995}: sqllogictest::runner: testing record=Statement { loc: Location { file: "e2e_test/batch/./duckdb/./join/inner/test_join.slt.part", line: 12, upper: Some(Location { file: "e2e_test/batch/./duckdb/all.slt.part", line: 4, upper: Some(Location { file: "e2e_test/batch/distribution_mode.slt", line: 9, upper: None }) }) }, conditions: [], expected_error: None, sql: "INSERT INTO test VALUES (11, 1), (12, 2), (13, 3);", expected_count: None }
> 2022-12-03T04:13:44.035775Z ERROR node{id=5 name="frontend-2"}:task{id=590828}: risingwave_frontend::session: failed to handle sql:
> INSERT INTO test VALUES (11, 1), (12, 2), (13, 3);:
> Bind error: INSERT has more target columns than expressions
> thread '<unnamed>' panicked at 'failed to run test after retry 0 times: statement failed: db error: ERROR: QueryError: Bind error: INSERT has more target columns than expressions
> [SQL] INSERT INTO test VALUES (11, 1), (12, 2), (13, 3);
> at e2e_test/batch/./duckdb/./join/inner/test_join.slt.part:12
> at e2e_test/batch/./duckdb/all.slt.part:4
> at e2e_test/batch/distribution_mode.slt:9
> ', /risingwave/src/tests/simulation/src/slt.rs:116:33
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:575:5
>    1: core::panicking::panic_fmt
>              at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:64:14
>    2: risingwave_simulation::slt::run_slt_task::{{closure}}
>              at ./src/tests/simulation/src/slt.rs:116:33
>    3: risingwave_simulation::main::{{closure}}::{{closure}}::{{closure}}
>              at ./src/tests/simulation/src/main.rs:182:57
>    4: async_task::raw::RawTask<F,T,S>::run
>              at ./.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/raw.rs:511:20
>    5: madsim::sim::task::Executor::run_all_ready
>              at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/task.rs:209:17
>    6: madsim::sim::task::Executor::block_on
>              at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/task.rs:159:13
>    7: madsim::sim::runtime::Runtime::block_on
>              at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/runtime/mod.rs:124:9
>    8: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
>              at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/runtime/builder.rs:128:35
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> note: run with `MADSIM_TEST_SEED=14` environment variable to reproduce this error
>       and make sure `MADSIM_CONFIG_HASH=1AD2E4ABC41F3553`
> ```
> 
> 
>     
>  
>   
> 
> 😕

seems like "test" is created again before being dropped?

**Comment by BugenZhao** [comment]
> seems like "test" is created again before being dropped?

This is recovery test and it seems the atomicity of creation of this table `test` is broken.

**Comment by BugenZhao** [comment]
It succeeded after updating the branch. 😄 Let's try to merge it.

**Comment by BugenZhao** [comment]
@mergifyio requeue

**Pull request merged**
