### PR TITLE
fix(test): replay SET statements after recovery

### LINKED ISSUE #8285: Replay set statements for the recovery test after recovering
It seems `deterministic simulation e2e, ci-3cn-2fe-3meta, recovery, batch` runs slower than before.

_Originally posted by @chenzl25 in https://github.com/risingwavelabs/risingwave/issues/8274#issuecomment-1451376344_

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR fixes the session context loss problem in recovery test. 
It will record all SET statements and replay them on reconnection.

resolve #8285

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

### CODE REVIEW

**Review by zwang28 — APPROVED** [review]
LGTM

**Review by chenzl25 — APPROVED** [review]
LGTM!

**Comment by yezizp2012** [comment]
The recovery test was timeout due to hang by a slow query after recovery, the execution seems to be blocked in frontend?
```
2022-09-12T12:42:49.817072Z  WARN node{id=7 name="frontend-1"}:task{id=499613}: risingwave_frontend::session: slow query has been running for another 60s sql_str="SELECT 1 UNION SELECT 1"
2022-09-12T12:42:54.250396Z  INFO node{id=8 name="frontend-2"}:task{id=524286}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2998361418170368 with RPC
2022-09-12T12:43:04.127906Z  INFO node{id=7 name="frontend-1"}:task{id=524916}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2998362139066368 with RPC
2022-09-12T12:43:04.250396Z  INFO node{id=8 name="frontend-2"}:task{id=524943}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2998362139066368 with RPC
2022-09-12T12:43:14.250396Z  INFO node{id=8 name="frontend-2"}:task{id=525593}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2998362859962368 with RPC
2022-09-12T12:43:24.127906Z  INFO node{id=7 name="frontend-1"}:task{id=526229}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2998363580858368 with RPC
2022-09-12T12:43:24.250396Z  INFO node{id=8 name="frontend-2"}:task{id=526258}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2998363580858368 with RPC
2022-09-12T12:43:34.127906Z  INFO node{id=7 name="frontend-1"}:task{id=526888}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2998364301754368 with RPC
2022-09-12T12:43:44.250396Z  INFO node{id=8 name="frontend-2"}:task{id=527557}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2998365022650368 with RPC
2022-09-12T12:43:49.817072Z  WARN node{id=7 name="frontend-1"}:task{id=499613}: risingwave_frontend::session: slow query has been running for another 60s sql_str="SELECT 1 UNION SELECT 1"
```

**Comment by BugenZhao** [comment]
> The recovery test was timeout and the scaling test failed 🥵 . Cc  @BugenZhao 

Will investigate it tomorrow. 🥵

**Comment by zwang28** [comment]
> The recovery test was timeout

As `SET VISIBILITY_MODE TO checkpoint; ` has been removed in this PR, `Cannot read when cluster is under recovery` error is expected behavior, and is fine as long as the batch query eventually succeeds before reaching the max retry in the test.

**Comment by BugenZhao** [comment]
> `Cannot read when cluster is under recovery` error is expected behavior

There's no recovery in scaling test but this error still happens. 🤔

**Comment by yezizp2012** [comment]
I think we can also remove `session_timezone.slt` from `KILL_IGNORE_FILES` now.

**Comment by zwang28** [comment]
> > `Cannot read when cluster is under recovery` error is expected behavior
> 
> There's no recovery in scaling test but this error still happens. 🤔

Despite the poor/inaccurate message, it reflects the fact that when a compute node is with no actor, [barrier won't be sent to it](https://github.com/risingwavelabs/risingwave/blob/075d50a4938bab239b09fadb5b5e5f1963db6139/src/meta/src/barrier/mod.rs#L697) and consequently hummock's seal epoch never increase. But I expect the batch query shouldn't visit that compute node either. I'll confirm tomorrow.

**Pull request merged**
