### PR TITLE
refactor(fragmenter): remove unneeded struct, prepare for rewrite

### PR DESCRIPTION
**Pull request by ice1000**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

+ Removed struct `StreamFragmenter`
+ Publicize `BuildFragmentGraphState` at crate level for future refactoring

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

Not really needed -- the change list is pretty much the documentation (and it's just three lines!)

## Refer to a related PR or issue link (optional)

#3684

### CODE REVIEW

**Comment by ice1000** [comment]
> Merging [#5064](https://codecov.io/gh/risingwavelabs/risingwave/pull/5064?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=risingwavelabs) (https://github.com/risingwavelabs/risingwave/commit/2f1de83909e85e42920988e14c11c081e714e84d) into [main](https://codecov.io/gh/risingwavelabs/risingwave/commit/b20ad0b6aaf405e3a36197bbf0becb0d20978704?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=risingwavelabs) (https://github.com/risingwavelabs/risingwave/commit/b20ad0b6aaf405e3a36197bbf0becb0d20978704) will decrease coverage by 0.03%.

How dare you! I didn't change any function body nontrivially

**Review by st1page — DISMISSED** [review]
LGTM

**Review by st1page — APPROVED** [review]
LGTM

**Comment by ice1000** [comment]
```
e2e_test/streaming/extreme_null.slt                          .. [FAILED]
--
  |  
  | failed to run `e2e_test/streaming/extreme_null.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] insert into t values (interval '1' minute, timestamp '2001-02-16 20:38:40', 'abc', date '2001-02-16');
  | at e2e_test/streaming/extreme_null.slt:66
  |  
  |  
  | e2e_test/streaming/struct_table.slt                          .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/struct_table.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] insert into st values(1,(1,(1,3)));
  | at e2e_test/streaming/struct_table.slt:13
  |  
  |  
  | e2e_test/streaming/project_set.slt                           .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/project_set.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] insert into tweet values ('#1 #2 abaaba'), ('ss #1 ggg #risingwave');
  | at e2e_test/streaming/project_set.slt:33
  |  
  |  
  | e2e_test/streaming/append_only.slt                           .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/append_only.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] drop table t4
  | at e2e_test/streaming/append_only.slt:90
  |  
  |  
  | e2e_test/streaming/non_strict_mode.slt                       .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/non_strict_mode.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] drop materialized view mv_filter_is_null;
  | at e2e_test/streaming/non_strict_mode.slt:60
  |  
  |  
  | e2e_test/streaming/tpch_snapshot.slt                         .. [BEGIN]
  | \| e2e_test/streaming/../tpch/create_tables.slt.part            .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/tpch_snapshot.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] CREATE TABLE supplier (
  | s_suppkey  INTEGER,
  | s_name VARCHAR,
  | s_address VARCHAR,
  | s_nationkey INTEGER,
  | s_phone VARCHAR,
  | s_acctbal NUMERIC,
  | s_comment VARCHAR,
  | PRIMARY KEY (s_suppkey)
  | );
  | at e2e_test/streaming/../tpch/create_tables.slt.part:1
  | at e2e_test/streaming/tpch_snapshot.slt:1
  |  
  |  
  | e2e_test/streaming/order_by.slt                              .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/order_by.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] drop table t1
  | at e2e_test/streaming/order_by.slt:54
  |  
  |  
  | e2e_test/streaming/basic.slt                                 .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/basic.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] drop materialized view mv3
  | at e2e_test/streaming/basic.slt:96
  |  
  |  
  | e2e_test/streaming/time_window.slt                           .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/time_window.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] create materialized view mv_hop as
  | select * from hop(t1, created_at, interval '15' minute, interval '30' minute);
  | at e2e_test/streaming/time_window.slt:19
  |  
  |  
  | e2e_test/streaming/selective_agg.slt                         .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/selective_agg.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] drop materialized view mv2;
  | at e2e_test/streaming/selective_agg.slt:33
  |  
  |  
  | e2e_test/streaming/string_agg.slt                            .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/string_agg.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] create materialized view mv3 as select string_agg(a, '' order by b) filter (where c != 0) as res from t;
  | at e2e_test/streaming/string_agg.slt:16
  |  
  |  
  | e2e_test/streaming/mv_on_mv.slt                              .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/mv_on_mv.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: Rpc error: gRPC status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  | [SQL] create materialized view m8 as select sum(v1) as sum_v1 from m6 group by v2;
  | at e2e_test/streaming/mv_on_mv.slt:83
  |  
  |  
  | e2e_test/streaming/time_window_join.slt                      .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/time_window_join.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: transport error
  | [SQL] CREATE MATERIALIZED VIEW mv_window_join AS
  | SELECT L.num AS L_Num, L.id AS L_Id, R.num AS R_Num, R.id AS R_Id,
  | COALESCE(L.window_start, R.window_start) AS window_start,
  | COALESCE(L.window_end, R.window_end) AS window_end
  | FROM TUMBLE(left, row_time, interval '5' minute) AS L
  | FULL JOIN
  | TUMBLE(right, row_time, interval '5' minute) AS R
  | ON L.num = R.num AND L.window_start = R.window_start AND L.window_end = R.window_end;
  | at e2e_test/streaming/time_window_join.slt:15
  |  
  |  
  | e2e_test/streaming/demo/twitter.slt                          .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/demo/twitter.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: transport error
  | [SQL] CREATE TABLE twitter (
  | data STRUCT < created_at TIMESTAMP,
  | id VARCHAR,
  | text VARCHAR,
  | lang VARCHAR >,
  | author STRUCT < created_at TIMESTAMP,
  | id VARCHAR,
  | name VARCHAR,
  | username VARCHAR >,
  | );
  | at e2e_test/streaming/demo/twitter.slt:1
  |  
  |  
  | e2e_test/streaming/join.slt                                  .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/join.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: transport error
  | [SQL] create materialized view mv4 as select t7.v1, t7.v2, t7.v3, t8.v1 as v10, t8.v2 as v20, t8.v3 as v30 from t7 FULL JOIN t8 ON t7.v1=t8.v1;
  | at e2e_test/streaming/join.slt:77
  |  
  |  
  | e2e_test/streaming/tpch_upstream.slt                         .. [BEGIN]
  | \| e2e_test/streaming/../tpch/create_tables.slt.part            .. [FAILED]
  |  
  | failed to run `e2e_test/streaming/tpch_upstream.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: transport error
  | [SQL] CREATE TABLE supplier (
  | s_suppkey  INTEGER,
  | s_name VARCHAR,
  | s_address VARCHAR,
  | s_nationkey INTEGER,
  | s_phone VARCHAR,
  | s_acctbal NUMERIC,
  | s_comment VARCHAR,
  | PRIMARY KEY (s_suppkey)
  | );
  | at e2e_test/streaming/../tpch/create_tables.slt.part:1
  | at e2e_test/streaming/tpch_upstream.slt:1
```

So I crashed the tests by moving some functions?

**Comment by ice1000** [comment]
image
image

How can both of these happen at the same time

**Comment by BugenZhao** [comment]
> image image
> 
> How can both of these happen at the same time

A bug described in #4861

**Pull request merged**
