### PR TITLE
fix: missing specified meta backend for backwards compat test config

### LINKED ISSUE #16794: flaky test: backwards compat test: Data directory is already used by another cluster
### Describe the bug

https://buildkite.com/risingwavelabs/main-cron/builds/2476#018f7b8d-91cf-4682-b155-e7d063ab089a
https://buildkite.com/risingwavelabs/main-cron/builds/2508#018f8222-a713-4548-8aea-758fdf0046cc

### Error message/log

```text
thread 'rw-main' panicked at src/meta/node/src/server.rs:488:6:
called `Result::unwrap()` on an `Err` value: ObjectStore(Internal error: Data directory is already used by another cluster with id "20b6ee2c-c632-4ffa-96fb-c37ea3ead75e", path hummock_001/cluster_id/0.)
stack backtrace:
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #16794 .

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by xxchan — APPROVED** [review]
❤️

**Comment by kwannoel** [comment]
Pushed another commit, looks like the test still fails, since older version's risedev doesn't know how to handle `meta-backend` setting.

**Comment by yezizp2012** [comment]
> Pushed another commit to fix it, looks like the test still fails, since older version's risedev doesn't know how to handle `meta-backend` setting.

Thx, LGTM!

**Comment by yezizp2012** [comment]
🥵 Found that https://github.com/risingwavelabs/risingwave/pull/16662 is not included in release-1.9. The config is not the root cause I think. Will take a further look.

**Pull request merged**
