### PR TITLE
chore: use original tpch

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

reference: https://github.com/dragansah/tpch-dbgen/tree/master/tpch-queries

```
Test #17 (id: tpch_q17) failed, SQL:
select
  sum(l_extendedprice) / 7.0 as avg_yearly
from
  lineitem,
  part,
  (select l_partkey as agg_partkey, 0.2 * avg(l_quantity) as avg_quantity from lineitem group by l_partkey) part_agg
where
  p_partkey = l_partkey
  and p_brand = 'Brand#13'
  and p_container = 'JUMBO PKG'
  and l_quantity < avg_quantity;

Error: unexpected stream_error: Not supported: streaming nested-loop join
HINT: The non-equal join in the query requires a nested-loop join executor, which could be very expensive to run. Consider rewriting the query to use dynamic filter as a substitute if possible.
See also: https://github.com/risingwavelabs/rfcs/blob/main/rfcs/0033-dynamic-filter.md
```

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by st1page — APPROVED** [review]
LGTM, Thanks!
So, just to verify, does we support all original tpch queries now?

**Comment by lmatz** [comment]
no, q17 not yet, need to rewrite manully

**Comment by lmatz** [comment]
And some queries without `order by` cannot be followed by `limit` statement in the streaming context. But this is ok

**Review by TennyZhuang — APPROVED** [review]

**Comment by st1page** [comment]
> no, q17 not yet, need to rewrite manually
> 
> therefore, cannot merge yet

I guess it is acceptable let us maintain the original query in the comments. 

https://github.com/apache/impala/blob/master/testdata/workloads/tpch/queries/tpch-q17.test
https://doris.apache.org/docs/dev/benchmark/tpch/

I even find the "rewritten query" is in the TPC-H's doc 🤔 
image

http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v2.17.1.pdf

**Pull request merged**
