### PR TITLE
feat(frontend): Acosd function

### PR DESCRIPTION
**Pull request by CAJan93**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Implement the `Acosd` function. This implementation is slightly different from the PSQL implementation. I do not return an error on `acosd(Inf)`, but instead return `NaN`. Also returns `NaN` when inout is out of range.

- [Tracking Issue](https://github.com/risingwavelabs/risingwave/issues/8806) 
- [PSQL implementation](https://github.com/postgres/postgres/blob/REL_15_2/src/backend/utils/adt/float.c)

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

`acosd` trigonometric function implementation.

### Release note

Add `acosd` function, which calculates the inverse acos in degrees. 

</details>

### CODE REVIEW

**Comment by CAJan93** [comment]
@xiangjinwu Sorry, I completely forgot about this one. Does this LGTY?

**Comment by xiangjinwu** [comment]
> @xiangjinwu Sorry, I completely forgot about this one. Does this LGTY?

No worries. We received no requests from customers needing trigonometric functions 😂

**Comment by CAJan93** [comment]
> No worries. We received no requests from customers needing trigonometric functions 😂

Guess so 😂 Was still nice to work on the kernel side for a while.

**Comment by CAJan93** [comment]
No idea why we get these imprecisions. Doing everything just like the PG implementation. Maybe it is a difference between Rust and C? 

For now I will hardcode these cases. I feel like it is not wort putting more energy into this. 

```
SELECT x,
       tand(x),
       tand(x) IN ('-Infinity'::float8,-1,0,
                   1,'Infinity'::float8) AS tand_exact,
       cotd(x),
       cotd(x) IN ('-Infinity'::float8,-1,0,
                   1,'Infinity'::float8) AS cotd_exact
FROM (VALUES (0), (45), (90), (135), (180),
      (225), (270), (315), (360)) AS t(x);
2024-06-27T17:28:44.720818Z ERROR risingwave_regress_test::schedule: Diff:
-  x  |   tand    | tand_exact |   cotd    | cotd_exact
------+-----------+------------+-----------+------------
-   0 |         0 | t          |  Infinity | t
-  45 |         1 | t          |         1 | t
-  90 |  Infinity | t          |         0 | t
- 135 |        -1 | t          |        -1 | t
- 180 |         0 | t          | -Infinity | t
- 225 |         1 | t          |         1 | t
- 270 | -Infinity | t          |         0 | t
- 315 |        -1 | t          |        -1 | t
- 360 |         0 | t          |  Infinity | t
+  x  |        tand         | tand_exact |        cotd         | cotd_exact
+-----+---------------------+------------+---------------------+------------
+   0 |                   0 | t          |            Infinity | t
+  45 |  1.0000000000000002 | f          |  0.9999999999999998 | f
+  90 |            Infinity | t          |                   0 | t
+ 135 | -1.0000000000000002 | f          | -0.9999999999999998 | f
+ 180 |                   0 | t          |           -Infinity | t
+ 225 |  1.0000000000000002 | f          |  0.9999999999999998 | f
+ 270 |           -Infinity | t          |                   0 | t
+ 315 | -1.0000000000000002 | f          | -0.9999999999999998 | f
+ 360 |                   0 | t          |            Infinity | t
```

**Comment by CAJan93** [comment]
Shall we merge it @xiangjinwu ? 😁 If we really don't need the function at the moment I'd suggest to close the PR.

**Comment by xiangjinwu** [comment]
> Shall we merge it @xiangjinwu ? 😁 If we really don't need the function at the moment I'd suggest to close the PR.

I am looking at several avro issues recently 🥵

**Comment by CAJan93** [comment]
> I am looking at several avro issues recently 🥵

No worries. I think this is low priority 😁

**Review by xiangjinwu — APPROVED** [review]

**Pull request merged**
