### PR TITLE
chore(deps): bump dependencies

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao 2 <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by skyzh** [comment]
Shall we ignore the precision error of `parser::json_parser::tests::test_json_parser`? cc @tabVersion @waruto210

**Comment by waruto210** [comment]
> 

I think it can be ignored.

**Comment by waruto210** [comment]
> > 
> 
>

**Comment by waruto210** [comment]
> Shall we ignore the precision error of `parser::json_parser::tests::test_json_parser`? cc @tabVersion @waruto210

I think it can be ignored.

**Comment by skyzh** [comment]
I'll fix that

**Comment by TennyZhuang** [comment]
Why part of the common deps are managed by workspace.dependencies, while others by hakari?

**Review by liurenjie1024 — APPROVED** [review]
LGTM

**Pull request merged**
