### PR TITLE
test(recovery): add recovery test for nexmark stream

### PR DESCRIPTION
**Pull request by wangrunji0408**
Signed-off-by: Runji Wang <wangrunji0408@163.com>

I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR adds a new recovery test for nexmark stream. It creates a nexmark source and mviews of queries, then randomly injects node failures to trigger recovery, and verifies the query results at the end. Compared to the existing recovery test, it focuses on the correctness of streams rather than ad-hoc queries.

~~This test is currently failing. @BugenZhao @yezizp2012 Please help take a look and find out the reason. 🥵~~
It turned out that the waiting time is not enough to make sure the stream is finished.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by wangrunji0408** [comment]
Found a new problem: the results from debug mode and release mode are different. 😇

See https://github.com/risingwavelabs/risingwave/pull/7623/commits/ab880b042d0acded7a9cb08ede613a4063fb52c5#diff-cf792a35091cf054806e811b40496421d97aa9aa8d6feab582a381c7d954b711

**Comment by BugenZhao** [comment]
> Found a new problem: the results from debug mode and release mode are different. 😇
> 
> See [ab880b0#diff-cf792a35091cf054806e811b40496421d97aa9aa8d6feab582a381c7d954b711](https://github.com/risingwavelabs/risingwave/commit/ab880b042d0acded7a9cb08ede613a4063fb52c5#diff-cf792a35091cf054806e811b40496421d97aa9aa8d6feab582a381c7d954b711)

Do you mean `ci-release` or `release`? That is, optimization or `debug_assertions`? 🤔

**Comment by wangrunji0408** [comment]
I used `release`.

**Review by BugenZhao — APPROVED** [review]

**Review by yezizp2012 — APPROVED** [review]

**Comment by zwang28** [comment]
I ran build-simulation.sh then deterministic-scale-test.sh with ab4093258771dff3be0c29dcdb25d2c470858dd2, but results  no failure. However the CI in this PR fails. 🤔

**Comment by BugenZhao** [comment]
Seems we should extend the time on the main branch again. 🥵

**Pull request merged**
