### PR TITLE
style(connector): avoid Arc<String>

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

It's always meaningless to use `Arc<String>`, use `Arc<str>` instead.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Review by BugenZhao — COMMENTED** [review]
Conversion from `String` to `Arc<str>` may lead to an allocation. 🤪 We should make sure this is infrequent.

**Review by tabVersion — COMMENTED** [review]
I am still a little confused, elements contained in Arc are immutable. Why using `Arc<String>` is misleading?

**Comment by TennyZhuang** [comment]
We may need another deref for `Arc<String>`

`Arc<str>`: `ptr -> (strong, weak, data)`
`Arc<String>`: `ptr -> (strong, weak, (ptr -> data, len, cap))`

**Comment by TennyZhuang** [comment]
`str` is similar to `[T]`
`&str` is similar to `&[T]`
`String` is similar to `Vec`

So `Arc<String>` need two deref operations to get the `data`, but `Arc<str>` only need one.

**Review by tabVersion — APPROVED** [review]
lgtm

**Pull request merged**
