### PR TITLE
perf(hash join): parallel fetch cache in hash join

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

parallel fetch cache in hash join
While a chunk arrives, in `eq_join_oneside`, this PR will call `side_match.ht.fetch_cached_state` parallel for cache miss keys in chunk.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by yuhao-su** [comment]
Could you also do some test to show how the performance increase?

**Comment by fuyufjh** [comment]
> Could you also do some test to show how the performance increase?

NexMark Q4 may be a good case

**Comment by soundOfDestiny** [comment]
I have tried various queries but benchmark result upsets

**Comment by Little-Wallace** [comment]
I think most of keys in the same state would query the same sst file. If this file is missed cache, all querys would block on the same IO request and it may cause performance regression

**Comment by soundOfDestiny** [comment]
> I think most of keys in the same state would query the same sst file. If this file is missed cache, all querys would block on the same IO request and it may cause performance regression

I have the same opinion and discussed with @hzxa21  last week.

**Comment by BugenZhao** [comment]
> all querys would block on the same IO request and it may cause performance regression

Interesting. But I'm curious why there'll be an obvious performance regression here?

**Comment by hzxa21** [comment]
> > all querys would block on the same IO request and it may cause performance regression
> 
> Interesting. But I'm curious why there'll be an obvious performance regression here?

+1. If CPU is not saturated, concurrent I/O theoritically should help. Let's try using paralleism=1 and see how it performs. Also, we can also measure how many keys are processed and operator cache miss per chunk.

**Comment by hzxa21** [comment]
> I think most of keys in the same state would query the same sst file. If this file is missed cache, all querys would block on the same IO request and it may cause performance regression

Based on our current key encoding `[table_id, vnode, key]`, even in the same executor, IMO locality of different keys is weak since the vnode of different keys can be totally different. However, if cache miss mostly happens on overlapping L0 SSTs, the above sceanrio makes sense (i.e. different keys of different vnodes written by the same CN lands on the same SST block). Maybe we should have a metrics for per level cache miss rate?

**Pull request closed without merging**
