### PR TITLE
fix: remove message name parameter for avro schema

### PR DESCRIPTION
**Pull request by waruto210**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

I checked the code for the version where this parameter was first introduced and found that it was never used, it was probably just copied from `ProtobufSchema`. 

It is strange to let the user specify the message name for a avro schema, so we should remove it.

## Checklist For Contributors

~- [ ] I have written necessary rustdoc comments~
~- [ ] I have added necessary unit tests and integration tests~
~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).~
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

~- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.~

## Documentation

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Connector (sources & sinks)
- SQL commands, functions, and operators

### Release note

```SQL
statement ok
create table s9 with (
  connector = 'kafka', 
  topic = 'avro_topic',
  properties.bootstrap.server = '127.0.0.1:29092',
  scan.startup.mode = 'earliest'
) row format avro 
row schema location 'http://xxx/xxx-schema.avsc'
```

</details>

### CODE REVIEW

**Review by tabVersion — APPROVED** [review]
as avro constraints the message's top level must be a `record`, there are no other ways to interpret payloads. So we remove the `message name` design

**Review by hzxa21 — APPROVED** [review]
> It is strange to let the user specify the message name for a avro schema, so we should remove it.

I had the same question before. LGTM!

**Comment by hengm3467** [comment]
@waruto210 This change applies to all sources (Pulsar, Kinesis, etc). Correct?

**Comment by waruto210** [comment]
> @waruto210 This change applies to all sources (Pulsar, Kinesis, etc). Correct?

Yes, applied to all sources that support avro row format.

**Pull request merged**
