### PR TITLE
fix: collect actor sender in actor creation

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Currently, the barrier sender of actors are registered via a channel in the local barrier manager. This happens in the process of creating actors. It may happen that the register sender request is handled after the actors have been created and spawned. However, after the actors have been created and spawned, the meta node will start injecting barrier. If the register sender request is handled after the inject barrier request, the inject barrier request will fail at `sender not found` like in https://github.com/risingwavelabs/risingwave/issues/15703. We try to prevent this by using a biased select like the following
```
select! {
    biased;
    register_sender = register_sender_rx.recv() => {...}
    inject_barrier = inject_barrier_rx.recv() => {...}
}
```

Intuitively this should work, because the register sender request is added to the channel before actor creation finished, and inject barrier request is sent after actor creation. When we do biased select, we always poll the register sender channel before the inject barrier channel, and then we should have ensured that the sender is registered successfully before injecting barrier. However, https://github.com/risingwavelabs/risingwave/issues/15703 still happened.

Looking into the code of tokio mpsc channel, we can see that it's using memory order `AcqRel` rather than `SeqCst ` maybe out of performance issue. However, when using `AcqRel`, we can only ensure that the memory order on a single channel is consistent, which means in a single channel if event A is sent before event B, event A must be received before event B. However, we cannot ensure that if event A is sent to channel A before event B is sent to channel B, in another thread event A must be visible in channel A before event B is visible in channel B. As an example, the following code can panic after several iteration.
```
use std::collections::HashSet;
use std::thread::{sleep, spawn};
use std::time::Duration;
use tokio::select;
use tokio::sync::mpsc;

#[tokio::main]
async fn main() {
    let (tx1, mut rx1) = mpsc::unbounded_channel();
    let (tx2, mut rx2) = mpsc::unbounded_channel();
    let _thread_handle = spawn(move || {
        let mut i = 0_usize;
        loop {
            // for any i, tx1 is sent before tx2.
            tx1.send(i).unwrap();
            tx2.send(i).unwrap();
            i += 1;
            sleep(Duration::from_micros(10));
        }
    });
    let mut set = HashSet::new();
    loop {
        select! {
            biased;
            first = rx1.recv() => {
                set.insert(first.unwrap());
            },
            second = rx2.recv() => {
                let i = second.unwrap();
                // since for any i, tx1 is sent before tx2, and the select is biased to rx1
                // we used to expect that for any i, we will receive i from rx1 before rx2.
                assert!(set.remove(&i), "{}", i);
            }
        }
    }
}
```

Hence, we cannot guarantee that the register sender request is handled before inject barrier request simply via biased select.

In this PR, we change to store the register the sender in a struct shared via `Arc<Mutex<_>>`. After actor creation, the registered sender will be taken out and register in the worker loop before spawn the actor and notify finish of actor creation.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by yezizp2012 — APPROVED** [review]
LGTM, I think we need to cherry pick it into release 1.8.

**Comment by BugenZhao** [comment]
Apart from introducing the shared context back, can we make `register_send` an async function and await on an `oneshot` channel to ensure the sender is registered when it returns?

**Comment by wenym1** [comment]
> Apart from introducing the shared context back, can we make `register_send` an async function and await on an `oneshot` channel to ensure the sender is registered when it returns?

Currently it works, but I am worried that this may introduce potential deadlock easily in our future development. Awaiting on the oneshot channel depends on the worker loop to handle the request, and it blocks actor creation. But the worker loop manages actor creation and polls the finish of actor creation to do further work. This can be dangerous, and may introduce implicit deadlock by accidence.

**Review by hzxa21 — APPROVED** [review]
LGTM. Good catch

**Pull request merged**
