### PR TITLE
fix: always retry on connection error

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

In this case, UDF can be part of join key, so their call to UDF server must never fail, otherwise it will lead to inconsistent error and the MV will need to be recreated.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
Noticed that the target branch is `wkx/jindo-hotfix-udf-call-timeout` 👀 Then LGTM

Generally, we don't have a perfect solution yet. The best known solution to me is to introduce a `MaterializeProjectExec` to run (non-deterministic) UDFs.

**Comment by kwannoel** [comment]
> Noticed that the target branch is `wkx/jindo-hotfix-udf-call-timeout` 👀 Then LGTM
> 
> Generally, we don't have a perfect solution yet. The best known solution to me is to introduce a `MaterializeProjectExec` to run (non-deterministic) UDFs.

It cannot really help this case as well. Since if we materialize the result to a `NULL`, subsequently, we also need to update the result, otherwise always returning `NULL` for some inputs, means we are always returning incorrect results.

**Comment by BugenZhao** [comment]
> otherwise always returning NULL for some inputs, means we are always returning incorrect results.

This is true, but I believe it's more like a trade-off between correctness and availability. Strictly speaking, returning `NULL` for an arithmetic expressoin that should fail with overflowing is also "incorrect". There seems to be no better choice. 😕

**Review by KeXiangWang — APPROVED** [review]
LGTM , looks like it's the current most appropriate choice to guarantee availability for them. I'm also considering that whether we can add support of cancelling a request on both client and server sides. In their cases, the functions are totally idempotent. If we find a request takes too long we can cancel it and retry it on another server, which improve availability while guarantee the correctness.

**Pull request merged**
