### PR TITLE
feat(optimizer,batch): optimize batch two phase limit/topn

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Optimize batch two phase limit/topn, if the input's distribution is singleton. Resolve https://github.com/risingwavelabs/risingwave/issues/8793.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by Eurekaaw** [comment]
This pr itself looks ok, but does it solve your problem as expected? @xxchan

**Comment by xxchan** [comment]
> This pr itself looks ok, but does it solve your problem as expected?

I don't know. 🤣 Just reported a finding. The solution in my mind was sth like checking distribution before generating 2 phase limit. Since this problem isn't too critical, I don't have any preference for solutions. (Maybe it's also ok to no fix it..)

**Comment by st1page** [comment]
c.c. @BugenZhao we can rewrite the rule with https://github.com/risingwavelabs/risingwave/pull/9237 later

**Comment by ZENOTME** [comment]
> The solution in my mind was sth like checking distribution before generating 2 phase limit. Since this problem isn't too critical, I don't have any preference for solutions. (Maybe it's also ok not to fix it..)

+1. I find that we will create a new limit anytime and then enforce it to satisfy single distribution. Can we create a new limit only if we find the input of original limit can't satisfy single distribution🤔?

**Comment by chenzl25** [comment]
> > The solution in my mind was sth like checking distribution before generating 2 phase limit. Since this problem isn't too critical, I don't have any preference for solutions. (Maybe it's also ok not to fix it..)
> 
> +1. I find that we will create a new limit anytime and then enforce it to satisfy single distribution. Can we create a new limit only if we find the input of original limit can't satisfy single distribution🤔?

You are right. Let me check the distribution before enforcing two phase limit.

**Review by Eurekaaw — APPROVED** [review]
LGTM

**Pull request merged**
