### PR TITLE
fix(optimizer): move `NOW` and `PROCTIME` inlining to optimization phase

### LINKED ISSUE #9572: bug: `PROCTIME` in source won't work in streaming and batch query
... performs a source-select, where the `PROCTIME` is unhandled to be rewritten to a constant. That's why we get the error of `Context not found` since by default we extract the timestamp from the current epoch value, which is only valid in streaming execution.

_Originally posted by @BugenZhao in https://github.com/risingwavelabs/risingwave/issues/9540#issuecomment-1534155805_

```
dev=> CREATE SOURCE t3 (v INT, t timestamptz as proctime()) WITH (
    connector = 'datagen',
    fields.v.kind = 'sequence',
    fields.v.start = '1',
    fields.v.end  = '10',
    datagen.rows.per.second='15',
    datagen.split.num = '1'
) ROW FORMAT JSON;
CREATE_SOURCE

dev=> select * from t3;
ERROR:  QueryError: Expr error: Context not found
```

Related: #9571

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

See #9572 for the background. To resolve this problem, this PR removes the logic for handling or rewriting `NOW` and `PROCTIME` from the binder, and uses an expression rewriter instead.

By selecting from a source in a batch query, the `PROCTIME` has the same semantics with `NOW`.

Close #9572.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by soundOfDestiny — APPROVED** [review]
LGTM. great!

**Review by st1page — APPROVED** [review]
LGTM

**Comment by BugenZhao** [comment]
Oops, `PROCTIME` from generated columns only appears after `LogicalSource::to_batch` so logical optimization does not cover this. Possible solutions:

- do it after `to_batch`, which potentially prevents some other logical optimizations
- do it twice
- `impl ExprRewritable for LogicalSource`, which requires binding the expressions from catalog ahead of time (preferred)

**Review by chenzl25 — APPROVED** [review]
LGTM

**Pull request merged**
