### PR TITLE
test: add negative tests for kafka source auth

### PR DESCRIPTION
**Pull request by neverchanje**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

To add some negative tests for the authentication of Kafa source.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

### CODE REVIEW

**Comment by tabVersion** [comment]
it is kinda strange to test SSL/SASL options on a unencrypted broker

**Comment by tabVersion** [comment]
image
risedev starts server in a plaintext manner and it can never response to a SSL request.
If you want to test it on a local broker, may try to add SSL protocol on listeners.

**Comment by tabVersion** [comment]
ping @neverchanje will continue on this?

**Comment by neverchanje** [comment]
No 😅 I forget about this.

**Pull request closed without merging**
