### PR TITLE
fix(config): use total_memory_available_bytes for opts not config

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
#6536,

~https://github.com/risingwavelabs/risingwave/pull/6762/files/a1017ad8b581d2d32132ab6407036734275fe978#r1052906636~

Let's remove this option.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by fuyufjh** [comment]
https://github.com/risingwavelabs/risingwave/pull/6762/files#r1052925483

> Please remove this option. Available memory is specified to each CN machine so it has been moved to command-line argument --total-memory-bytes. See #6767

**Comment by yuhao-su** [comment]
should we use the `total_memory_available_bytes` as `default_total_memory_bytes`?

**Review by sixletters — APPROVED** [review]
LGTM!

**Review by yuhao-su — APPROVED** [review]
LGTM

**Pull request merged**
