### PR TITLE
feat: add await tree for opendal object store

### PR DESCRIPTION
**Pull request by wcy-fdu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
as title

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
Interesting. Can you elaborate more? What extra info does it provide additional to the spans we attached in `MonitoredObjectStore`?

https://github.com/risingwavelabs/risingwave/blob/468f7ec14f7e53d7c4d4af965eace50bf1d2fde7/src/object_store/src/object/mod.rs#L584

**Comment by wcy-fdu** [comment]
> Interesting. Can you elaborate more? What extra info does it provide additional to the spans we attached in `MonitoredObjectStore`?
> 
> https://github.com/risingwavelabs/risingwave/blob/468f7ec14f7e53d7c4d4af965eace50bf1d2fde7/src/object_store/src/object/mod.rs#L584

Recently we are debugging https://github.com/risingwavelabs/risingwave/issues/15209, and found that the await tree of compactor node is a bit less:
```
--- Compactor Traces ---
>> Compaction Task 50708-0
Compaction Task 50708 Split 0  [1843.496s]
  compact [!!! 1843.496s]
    compact_and_build_sst [!!! 1843.496s]
      rewind [!!! 1843.496s]
        object_store_streaming_read_read_bytes [!!! 1843.456s]

>> Compaction Task 51832-0
Compaction Task 51832 Split 0  [1062.498s]
  compact [!!! 1062.498s]
    compact_and_build_sst [!!! 1062.498s]
      add_full_key [!!! 1061.768s]
        object_store_streaming_upload_write_bytes [!!! 1061.768s]
```

and OpenDAL provide AwaitTreeLayer, which will show the interfaces in it's operator. With this await tree layer enabled, we will get these info right behind RisingWave's own trace file.

The bug is fixed, but it's still worth adding it and not complicated.

**Comment by zwang28** [comment]
> and OpenDAL provide AwaitTreeLayer, which will show the interfaces in it's operator level. With this await tree layer enabled, we will get these info right behind RisingWave's own trace file.

Can you give an example file of OpenDAL's await tree?

**Review by fuyufjh — APPROVED** [review]
LGTM. Do you think it needs to run a benchmark before merging?

**Review by Li0k — APPROVED** [review]
+1， testing to get await-tree file before merge

**Pull request closed without merging**
