### PR TITLE
feat(meta): Add disable_checkpoint configuration

### PR DESCRIPTION
**Pull request by xxhZs**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***
After https://github.com/risingwavelabs/risingwave/pull/4966, We support decouple barrier and checkpoint.
 And in this pr, We add a configuration item (`unsafe_disable_checkpoint`) to turn off sending checkpoints by frequency.
If `unsafe_disable_checkpoint = true`, we will send only the barrier(checkpoint = false) except for configuration changes 
May be useful for testing

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* RisingWave cluster configuration changes

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by hzxa21** [comment]
Just curious, in which testing sceanrios will we turn off checkpoint?

**Comment by xxhZs** [comment]
> 
Currently need to test the correctness of querying data without checkpoint.

**Comment by hzxa21** [comment]
> > 
> 
> Currently need to test the correctness of querying data without checkpoint.

If this is just for test and `disable_checkpoint` will not be used in production, can we just set `checkpoint_frequency` to usize::MAX to disable checkpoint in the related tests?

**Comment by hzxa21** [comment]
Discussed offline. This config is not only useful for testing but also in the ETL use cases (See #4392). I think it is fine to add this config then.

**Comment by xxhZs** [comment]
> Discussed offline. This config is not only useful for testing but also in the ETL use cases (See #4392). I think it is fine to add this config then.

This pr is not perfected, I will make some changes

**Pull request closed without merging**
