### PR TITLE
feat: eliminate adjacent no-op updates for agg with empty agg call

### LINKED ISSUE #17030: non-append-only distinct may output adjacent noop updates
Using `DISTINCT` on a non-append-only relation will generate a plan like this:

```
dev=> create table t (v int);
CREATE_TABLE

dev=> explain create materialized view mv as select distinct v from t;
                                         QUERY PLAN                                         
--------------------------------------------------------------------------------------------
 StreamMaterialize { columns: [v], stream_key: [v], pk_columns: [v], pk_conflict: NoCheck }
 └─StreamProject { exprs: [t.v] }
   └─StreamHashAgg { group_key: [t.v], aggs: [count] }
     └─StreamExchange { dist: HashShard(t.v) }
       └─StreamTableScan { table: t, columns: [v, _row_id] }
(5 rows)
```

If we insert an existing value into the table, we'll still get a chunk with adjacent noop updates in `StreamMaterialize`.

```
2024-05-30T17:04:40.659745+08:00 DEBUG   rw-streaming actor{otel.name="Actor 27" actor_id=27 prev_epoch=6542110140137472 curr_epoch=6542110205739008}:executor{otel.name="Materialize 1B00000004"}:executor{otel.name="Project 1B00000003"}:executor{otel.name="HashAgg 1B00000002"}: events::stream::message::chunk: 
+----+-----+-------+
|    | t.v | count |
+----+-----+-------+
| U- | 233 | 1     |
| U+ | 233 | 2     |
+----+-----+-------+
 cardinality=2 capacity=2
2024-05-30T17:04:40.659848+08:00 DEBUG   rw-streaming actor{otel.name="Actor 27" actor_id=27 prev_epoch=6542110140137472 curr_epoch=6542110205739008}:executor{otel.name="Materialize 1B00000004"}:executor{otel.name="Project 1B00000003"}: events::stream::message::chunk: 
+----+-----+
|    | t.v |
+----+-----+
| U- | 233 |
| U+ | 233 |
+----+-----+
 cardinality=2 capacity=2
```

If the output is further used as a dimension table in `Join`, the noop update will cause an amplification **per-row**, resulting in extremely high latency. Note that this does not only happen on `DISTINCT`, `LATERAL JOIN` could also generate a plan like this.

----

This is mainly because we add an extra `row_count` agg-call for internal use, which is then stripped with the following `Project`. We are missing the optimization here:

https://github.com/risingwavelabs/risingwave/blob/bb6d16b8406e81684559cd60793b80ca7c60685d/src/stream/src/executor/aggregation/agg_group.rs#L72-L74

Also, if there's no column-pruning dispatchers (typically in MV on MV), we'll also miss the optimization in https://github.com/risingwavelabs/risingwave/pull/14652.

https://github.com/risingwavelabs/risingwave/blob/bb6d16b8406e81684559cd60793b80ca7c60685d/src/stream/src/executor/dispatch.rs#L758-L765

Following the idea of #10949, I'm considering whether we should apply the optimization to `Project`s, or at least specifically the `Project` in the case of this issue.

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

See background in #17030. Close #17030.

Introduced a flag named `noop_update_hint` on `StreamProject` indicating...

> Whether there are likely no-op updates in the output chunks, so that eliminating them with `StreamChunk::eliminate_adjacent_noop_update` could be beneficial.

and only enable it on the one following `HashAgg` with empty agg call set, which usually happens in queries with semantics of deduplication.

This reduces the need for always calling `eliminate` on the output, resulting in minimal performance overhead.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by chenzl25 — APPROVED** [review]
LGTM, interesting insight~

**Review by stdrc — APPROVED** [review]
LGTM!

**Review by fuyufjh — COMMENTED** [review]
I can understand the motivation, but why it's done in `ProjectExecutor`? In my mind `Project` means evaluating expression - 1 row in, 1 row out. This PR seems to add some irrelevant logic to `Project`.

**Comment by stdrc** [comment]
> I can understand the motivation, but why it's done in `ProjectExecutor`? In my mind `Project` means evaluating expression - 1 row in, 1 row out. This PR seems to add some irrelevant logic to `Project`.

We can consider `Project`s as convenient hook points to do such no-op updates elimination, because they naturally pervade the whole query.😄

**Pull request merged**
