### PR TITLE
chore(streaming): rewrite nexmark q5 to benefit from common sub-plan sharing

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Reorder `GROUP BY window_start, bid.auction` into `GROUP BY bid.auction, window_start`, so that we can share a large sub-plan.
- Theoretically, the ordering in group-by clause doesn't matter, however, in our LogicalAgg implementation, we store them in a `vec` so the ordering matter in terms of common sub-plan detection.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

#7343

### CODE REVIEW

**Review by lmatz — APPROVED** [review]
LGTM

**Comment by chenzl25** [comment]
> > however, in our LogicalAgg implementation, we store them in a vec so the ordering matter in terms of common sub-plan detection.
> 
> Will we change it to a data structure where order does not matter in the future?

Not quite sure whether other components rely on the ordering provided by the `vec`.

**Comment by chenzl25** [comment]
Do we need to rewrite the SQL in the longevity test? @lmatz

**Comment by lmatz** [comment]
Yes, but no worries, I will update it in the risingwave-test and kube-bench

**Comment by BugenZhao** [comment]
> Theoretically, the ordering in group-by clause doesn't matter, however, in our LogicalAgg implementation, we store them in a vec so the ordering matter in terms of common sub-plan detection.

Does this mean that extracting common plan node with `Eq` is too strict? It'll be nice if we can share Agg in this case with a Project automatically inserted.

**Comment by chenzl25** [comment]
> > Theoretically, the ordering in group-by clause doesn't matter, however, in our LogicalAgg implementation, we store them in a vec so the ordering matter in terms of common sub-plan detection.
> 
> Does this mean that extracting common plan node with `Eq` is too strict? It'll be nice if we can share Agg in this case with a Project automatically inserted.

Actually, I prefer to replace the group-by `vec` with a`bitmap`.

**Comment by BugenZhao** [comment]
> Actually, I prefer to replace the group-by `vec` with a`bitmap`.

Interesting! And we may add different `Project`s atop of the shared `Agg`, right?

**Comment by chenzl25** [comment]
> > Actually, I prefer to replace the group-by `vec` with a`bitmap`.
> 
> Interesting! And we may add different `Project`s atop of the shared `Agg`, right?

Yep.

**Pull request merged**
