### PR TITLE
fix(storage): incorrect row op of "insert then update"

### LINKED ISSUE #3887: storage: enable sanity check on hash join
Currently, it doesn't call update interface, which might cause problems for the storage layer.

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Check the code for details.

The sanity check for HashJoin is also enabled correctly.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- #4997
- #3085
- #4588
- Close #3887

### CODE REVIEW

**Review by wcy-fdu — APPROVED** [review]
LGTM! Thanks for this fix

**Review by skyzh — APPROVED** [review]
LGTM, thanks!

**Comment by wcy-fdu** [comment]
related to https://github.com/risingwavelabs/risingwave/pull/3085/files#diff-444707333048cb99ef65e5fbbb1d59db6fb6437096c3d7958ee4c6769b1084d8
cc @yuhao-su

**Review by yuhao-su — APPROVED** [review]

**Comment by BugenZhao** [comment]
Note: the `update` is only used by `HashJoin`, so it tends to be not relevant to #4861.

**Pull request merged**
