### PR TITLE
fix(streaming): reorganize output of hop window

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

As explained in https://github.com/risingwavelabs/risingwave/issues/10495#issuecomment-1619370490. This PR reorganizes the output of the hop window executor to group multiple output rows of a single input row together to avoid `Update` interfering with each other.

Previous:
```
dev=> create table t1 (k int primary key, ts timestamp);
CREATE_TABLE
dev=> create materialized view mv as select * from hop(t1, ts, interval '10' minute, interval '30' minute);
CREATE_MATERIALIZED_VIEW
dev=> insert into t1 values (1, '2021-01-01 10:15:00');
INSERT 0 1
dev=> select * from t1;
 k |         ts          
---+---------------------
 1 | 2021-01-01 10:15:00
(1 row)

dev=> select * from mv;
 k |         ts          |    window_start     |     window_end      
---+---------------------+---------------------+---------------------
 1 | 2021-01-01 10:15:00 | 2021-01-01 09:50:00 | 2021-01-01 10:20:00
 1 | 2021-01-01 10:15:00 | 2021-01-01 10:00:00 | 2021-01-01 10:30:00
 1 | 2021-01-01 10:15:00 | 2021-01-01 10:10:00 | 2021-01-01 10:40:00
(3 rows)

dev=> update t1 set ts = '2021-01-01 10:25:00' where k = 1;
UPDATE 1
dev=> select * from mv;
 k |         ts          |    window_start     |     window_end      
---+---------------------+---------------------+---------------------
 1 | 2021-01-01 10:15:00 | 2021-01-01 10:00:00 | 2021-01-01 10:30:00 <- 😨
 1 | 2021-01-01 10:15:00 | 2021-01-01 10:10:00 | 2021-01-01 10:40:00 <- 😨
 1 | 2021-01-01 10:25:00 | 2021-01-01 10:20:00 | 2021-01-01 10:50:00
(3 rows)
```

Now:
```
 k |         ts          |    window_start     |     window_end      
---+---------------------+---------------------+---------------------
 1 | 2021-01-01 10:25:00 | 2021-01-01 10:00:00 | 2021-01-01 10:30:00
 1 | 2021-01-01 10:25:00 | 2021-01-01 10:10:00 | 2021-01-01 10:40:00
 1 | 2021-01-01 10:25:00 | 2021-01-01 10:20:00 | 2021-01-01 10:50:00
```

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by st1page — APPROVED** [review]

**Comment by st1page** [comment]
maybe we should do this https://github.com/risingwavelabs/risingwave/issues/10730 :thinking:

**Comment by BugenZhao** [comment]
> maybe we should do this #10730 🤔

Yeah, mentioned as an alternative solution. https://github.com/risingwavelabs/risingwave/issues/10495#issuecomment-1619438377

Not sure which approach is better.

**Comment by kwannoel** [comment]
Do all materialized views in our system expect to have unique pk? Seems like it is hard to guarantee it. In this case I guess that's why we have to use `Insert` and `Delete`, since we don't have unique keys?

**Comment by st1page** [comment]
> > maybe we should do this #10730 🤔
> 
> Yeah, mentioned as an alternative solution. [#10495 (comment)](https://github.com/risingwavelabs/risingwave/issues/10495#issuecomment-1619438377)
> 
> Not sure which approach is better.

Oh I think this PR is ok, I just thinking if there is further issues when we shuffled by time column in the downstream. headache, think about it later :hot_face:

**Comment by st1page** [comment]
> Do all materialized views in our system expect to have unique pk? Seems like it is hard to guarantee it. In this case I guess that's why we have to use `Insert` and `Delete`, since we don't have unique keys?

That is guaranteed by stream key derivation which in optimizer's `logic_rewrite_for_stream`
https://zhuanlan.zhihu.com/p/633094455

**Review by zwang28 — APPROVED** [review]

**Review by TennyZhuang — APPROVED** [review]

**Comment by BugenZhao** [comment]
Benchmarking...

https://buildkite.com/risingwave-test/nexmark-benchmark/builds/1379#01892043-4d7f-42aa-ab68-68922dd6f75c

**Pull request merged**
