### PR TITLE
chore: expose hyper client connect socket address debug log

### LINKED ISSUE #14207: print the connecting IP whenever possible for better diagnosis into network issues
```
2023-12-26T06:56:37.992865433Z ERROR pgwire::pg_protocol: error when process message error=Failed to run the query: Scheduler error: gRPC request failed: Unknown error: transport error error.sources=[Scheduler error: gRPC request failed: Unknown error: transport error, Scheduler error: gRPC request failed: Unknown error: transport error, gRPC request failed: Unknown error: transport error, transport error, connection error: host unreachable, host unreachable]
```

One user reported this. We are not sure what led to this error yet, but it is likely to be some network glitch caused by environmental issues or possibly even the cloud vendor. Haven't seen this error before.

The `host unreachable` error makes it unclear to tell which host it is, which makes it harder to debug.

### PR DESCRIPTION
**Pull request by MrCroxx**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

#14207 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by lmatz — APPROVED** [review]
We will have all the debug! logs in this file: https://github.com/hyperium/hyper/blob/master/src/proto/h2/client.rs?

**Comment by MrCroxx** [comment]
> We will have all the debug! logs in this file: [hyperium/hyper@`master`/src/proto/h2/client.rs](https://github.com/hyperium/hyper/blob/master/src/proto/h2/client.rs?rgh-link-date=2023-12-27T06%3A43%3A23Z)?

You mean [hyperium/hyper@`0.14.x`/src/client/connect/http.rs](https://github.com/hyperium/hyper/blob/0.14.x/src/client/connect/http.rs) ?

**Comment by lmatz** [comment]
You are right, didn't realize we are using `v0.14.x`

**Review by arkbriar — APPROVED** [review]
LGTM!

**Pull request merged**
