### PR TITLE
fix(meta): fix cpu core limit check query

### LINKED ISSUE #18113: nightly-20240819 compute node crash
### Describe the bug

image

https://grafana.test.risingwave-cloud.xyz/explore?schemaVersion=1&panes=%7B%22yfd%22:%7B%22datasource%22:%22PE59595AED52CF917%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22ch-benchmark-pg-cdc-daily-20240819%5C%22,%20component%3D%5C%22compute%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PE59595AED52CF917%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1

https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/359#01916ca8-8e38-47d7-8235-08c6a5ea0308

### Error message/log

```text
2024-08-19T22:08:09.746758142Z ERROR risingwave_rpc_client::meta_client: failed to register worker, exiting... error=failed to add worker node: gRPC request to meta service failed: Internal error: Query Error: error returned from database: operator does not exist: character varying = integer
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

nightly-20240819

### Additional context

https://github.com/risingwavelabs/rw-commits-history?tab=readme-ov-file#nightly-20240819

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

`enum` is stored as string instead of number with sea-orm. Resolve #18113.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by yezizp2012 — APPROVED** [review]

**Comment by BugenZhao** [comment]
Not sure why it was not covered by the e2e-single-node-tests in https://github.com/risingwavelabs/risingwave/pull/18022.

**Comment by yezizp2012** [comment]
> Not sure why it was not covered by the e2e-single-node-tests in #18022.

Oh, I know why. Single node uses `Sqlite`, which allows string and int comparison. 🥵

**Comment by BugenZhao** [comment]
> > Not sure why it was not covered by the e2e-single-node-tests in #18022.
> 
> Oh, I know why. Single node uses `Sqlite`, which allows string and int comparison. 🥵

So `sea-orm` or `sea-query` does not completely erase the difference between backends. 🥵 Perhaps we need to consider testing against all supported backends in CI.

**Comment by yezizp2012** [comment]
> > > Not sure why it was not covered by the e2e-single-node-tests in #18022.
> > 
> > 
> > Oh, I know why. Single node uses `Sqlite`, which allows string and int comparison. 🥵
> 
> So `sea-orm` or `sea-query` does not completely erase the difference between backends. 🥵 Perhaps we need to consider testing against all supported backends in CI.

Yes, I will switch all CI tests for PR to `sqlite` recently and we can test all backends in `main-cron` job.

**Pull request merged**
