### PR TITLE
feat(common): introduce ArrayBuilder and Array for Int256/Uint256 

### PR DESCRIPTION
**Pull request by shanicky**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Note that this PR does not implement `int256/uint256` types for Arrow and will be implemented in a later PR.

In addition, `HashKeySerDe` cannot be implemented for non-primitive types.

### Summary
🧮🚀🔑

This pull request adds support for 256-bit integer types as scalars and arrays in the `src/common` crate. It implements the conversion, serialization, and hashing of these types using the `ethnum`, `Arrow`, and `protobuf` libraries. It also adds tests and enums for these types. The purpose of this pull request is to enable the RisingWave platform to handle Ethereum data and logic more efficiently.

> _`Int256Array`_
> _New type for Ethereum_
> _Spring of big numbers_

### Walkthrough
*  Add `Int256Array` and `Uint256Array` types and their builders to store and manipulate 256-bit integers using the `ethnum` crate ([link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-2b302a0fdfb8a9f50e8c9b0ba4ce80a917b1e30b05eab979be8c9adc0d770382R32), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-2b302a0fdfb8a9f50e8c9b0ba4ce80a917b1e30b05eab979be8c9adc0d770382R70-R72), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-2b302a0fdfb8a9f50e8c9b0ba4ce80a917b1e30b05eab979be8c9adc0d770382R345-R346), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-2b302a0fdfb8a9f50e8c9b0ba4ce80a917b1e30b05eab979be8c9adc0d770382R384-R395), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-84c57d493a4069a8a3611014d0e3cc59238f764600205efd0394c53e618b3c34R1-R206))
*  Implement conversion of `Int256Array` and `Uint256Array` types to and from `arrow::array::ArrayRef` types using the `From` trait ([link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-2b23b6b129c6f9cf9789bfc6e08c0ee15da6579d3655b609c9f63e0b5b4cb7c3R440-R441))
*  Implement serialization and deserialization of `Int256Array` and `Uint256Array` types to and from protobuf using the `Array` trait and the `ArrayType` enum ([link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-ac8e6d38f431921d3cd3deb802124f19ae8c7e459f83e7991602102ff24694ffR102-R103), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-2b302a0fdfb8a9f50e8c9b0ba4ce80a917b1e30b05eab979be8c9adc0d770382L61-R62), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-2b302a0fdfb8a9f50e8c9b0ba4ce80a917b1e30b05eab979be8c9adc0d770382R716-R717), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-973fd95cbf6f8e31d33005dde05504c5db5652a3b7f13a7d9e114add1feb1bf4L22-R26), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-973fd95cbf6f8e31d33005dde05504c5db5652a3b7f13a7d9e114add1feb1bf4R72-R98))
*  Implement `HashKeySerDe` trait for `Int256Ref` and `Uint256Ref` types to enable their use as hash keys ([link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-d0ee107bce648d0743d32eed11034a9f0cead3657d1d819e1f41def1ed03c24cR40), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-d0ee107bce648d0743d32eed11034a9f0cead3657d1d819e1f41def1ed03c24cR369-R392))
*  Implement `RandValue` trait for `Int256` and `Uint256` types to enable random value generation for testing ([link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-b4c2aabd2e24330e67771d0ec5ca2fc8995b5e35883468c64590b0d9ef167c3fR30), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-b4c2aabd2e24330e67771d0ec5ca2fc8995b5e35883468c64590b0d9ef167c3fR122-R137))
*  Add convenience and functionality methods for `Int256`, `Uint256`, `Int256Ref`, and `Uint256Ref` types, such as converting to and from bytes, returning size and array type, and accessing inner fields ([link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-973fd95cbf6f8e31d33005dde05504c5db5652a3b7f13a7d9e114add1feb1bf4L31-R41), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-973fd95cbf6f8e31d33005dde05504c5db5652a3b7f13a7d9e114add1feb1bf4R72-R98), [link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-973fd95cbf6f8e31d33005dde05504c5db5652a3b7f13a7d9e114add1feb1bf4R104-R117))
*  Make `num256` module public and expose its types to the rest of the crate ([link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-eaafd1f1b7bcfbb3f1f1a20e2064755bdd0867314889c0150ccb19e9f00dddf2L50-R50))
*  Add an empty line to improve readability and formatting ([link](https://github.com/risingwavelabs/risingwave/pull/8989/files?diff=unified&w=0#diff-2b23b6b129c6f9cf9789bfc6e08c0ee15da6579d3655b609c9f63e0b5b4cb7c3R423))

This pull request includes changes to `data.proto` file to add support for `Int256` and `Uint256` data types. The builder and array types for these data types are implemented in `num256_array.rs`. Additionally, this PR adds support for the serialization and deserialization of these data types in `HashKeySerDe`. Several other files have been updated to incorporate these data types.

## Checklist For Contributors

~- [ ] I have written necessary rustdoc comments~
~- [ ] I have added necessary unit tests and integration tests~
~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~
~- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)~

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
I suggest using `PrimitiveArray` to avoid code duplication, but not sure whether we may omit the `Box` there. 👀

**Comment by shanicky** [comment]
> I suggest using `PrimitiveArray` to avoid code duplication, but not sure whether we may omit the `Box` there. 👀

I tried using primitives directly, but the primitive item type requires scalar and scalarref to be the same, which makes it impossible to use box because box does not satisfy the copy of scalarref. Do you have any alternative solutions? 🥺

**Comment by shanicky** [comment]
> I suggest using `PrimitiveArray` to avoid code duplication, but not sure whether we may omit the `Box` there. 👀

I'm trying to replace the `Copy` restriction in `ScalarRef` with `Clone` in the [PR](https://github.com/risingwavelabs/risingwave/pull/9021). If a type already implemented `Copy`, there would be no performance loss. However, I'm unsure if this would cause other issues, such as with the `AsPrimitive` requirement for `Copy`. Therefore, I suggest that we start by implementing this approach with non-primitive types first and then decide whether to extend it to primitive types later.

**Review by lmatz — APPROVED** [review]
As the two new data types will be first considered as `experimental feature` for a while, it's fine to further optimize it later. 

The duplicated code seems associated with int256/uint256 modules only, I suppose it's not a big deal. We may re-consider later when we make them stable.

LGTM

**Pull request merged**
