### PR TITLE
chore: upgrade to openjdk17 in dockerfile 

### PR DESCRIPTION
**Pull request by StrikeW**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

as title.

Test build: https://buildkite.com/risingwavelabs/docker/builds/15879

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by huangjw806** [comment]
Let's upgrade it here too.
https://github.com/risingwavelabs/risingwave/blob/main/docker/Dockerfile.hdfs#L6

**Comment by StrikeW** [comment]
> Let's upgrade it here too. https://github.com/risingwavelabs/risingwave/blob/main/docker/Dockerfile.hdfs#L6

done.

**Review by huangjw806 — APPROVED** [review]

**Review by wenym1 — APPROVED** [review]
Just curious what's the motivation for the upgrade? Will we deprecate the support on java 11?

**Comment by StrikeW** [comment]
> Just curious what's the motivation for the upgrade? Will we deprecate the support on java 11?

We encounter SIGSEGV in a customer tenant in the cloud, and suspect that openjdk 11 could be one of the [reason](https://github.com/risingwavelabs/risingwave/pull/16765#discussion_r1601118987), so try to bump the jdk version to reduce the probability.

[Here](https://risingwave-labs.slack.com/archives/C03DFGV6L2W/p1717034563923459) is some discussion.

**Review by kwannoel — APPROVED** [review]

**Comment by kwannoel** [comment]
Thanks!

**Pull request merged**
