### PR TITLE
feat(streaming): introduce new source executor

### PR DESCRIPTION
**Pull request by xx01cyx**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This is the first step of the new DML design.

### Summarize your change

Introduce new source executor. It differs from the current one in following ways:
1. The streaming source (`SourceExecutorV2.stream_source_core`) becomes optional. That is to say, it is possible that a new source executor has no external connector. Under this circumstance, the new source executor's only responsibility is to receive and forward barrier messages.
2. The new source executor will not generate row id for data. This will be done in `RowIdGenerateExecutor` (to be implemented).

### Describe any limitations of the current code 

`Datagen` is used to mock external connector in UT now. A better approach will be introducing a mock connector only for testing. (#6427)

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Related Issue

#5949

### CODE REVIEW

**Comment by StrikeW** [comment]
Is this PR related to the _Unify the materialized source and table_ RFC?

**Comment by xx01cyx** [comment]
> Is this PR related to the Unify the materialized source and table RFC?

Yes. The tracking issue is [here](https://github.com/risingwavelabs/risingwave/issues/5949).

**Review by tabVersion — APPROVED** [review]
generally LGTM

**Review by st1page — APPROVED** [review]
LGTM

**Pull request merged**
