### PR TITLE
feat(expr): add short circuit checker in `is_const`

### LINKED ISSUE #15724: consider short-circuit when constant folding
```SQL
dev=> create table t(x int);
CREATE_TABLE
dev=> select true OR 'abc'::int > 10;
 ?column?
----------
 t
(1 row)

dev=> select true OR 'abc'::int > x from t;
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Expr error
  2: Parse error: integer invalid digit found in string
```

So for the first expression, RW's optimizer can identify the whole expression as a constant expression and evaluate it when generating the plan, in this case the short-circuit evaluation will take effect.
But for the second expression, the optimizer does not consider it as a whole constant value due to the presence of the variable `x`. But it will identify the `'abc::int'` as a constant expression and evaluate it separately.

### PR DESCRIPTION
**Pull request by xzhseh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

close #15724.

note that for short circuit check to be true, we only consider the first input of a `Or / And`, otherwise the semantic will not be preserved, as shown below.

## Checklist

- [x] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by st1page — COMMENTED** [review]
add some planner test cases?

**Review by chenzl25 — APPROVED** [review]
LGTM

**Review by st1page — APPROVED** [review]

**Review by TennyZhuang — APPROVED** [review]

**Comment by TennyZhuang** [comment]
Not necessary to fix in the PR. Just a question: Does CASE WHEN handled correctly in the PR?

**Comment by xzhseh** [comment]
> Not necessary to fix in the PR. Just a question: Does CASE WHEN handled correctly in the PR?

It depends on which pattern of `case-when` expression.
For pattern like `true or (case when ...)` or `false and (case when ...)`, it should be handled correctly.

**Review by BugenZhao — COMMENTED** [review]
I think the main issue is that the code logic for determining if an `ExprImpl` can be constant-folded differs from the actual evaluation process for folding it.

So I'm considering if it's possible to merge `is_const` and `fold_const` into a single step, that is:

- Provide another implementation of `build_from_prost` that rejects any other expressions except for `Literal` and `FunctionCall`.

- Call that to build the expression. If there's an error, we say that the expression cannot be folded.

- Call `eval_row` on the built expression, which will utilize short-circuiting.

**Comment by xzhseh** [comment]
> I think the main issue is that the code logic for determining if an `ExprImpl` can be constant-folded differs from the actual evaluation process for folding it.
> 
> So I'm considering if it's possible to merge `is_const` and `fold_const` into a single step, that is:
> 
> * Provide another implementation of `build_from_prost` that rejects any other expressions except for `Literal` and `FunctionCall`.
> * Call that to build the expression. If there's an error, we say that the expression cannot be folded.
> * Call `eval_row` on the built expression, which will utilize short-circuiting.

Then presumably the current `try_fold_const` could be a wrapper function that contains the new constant-folding function - to avoid large refactor.

**Pull request merged**
