### PR TITLE
fix(meta): unregister table from Hummock after catalog change

### LINKED ISSUE #15144: bug: inconsistency table info between catalog and hummock in meta node
### Describe the bug

We've encountered this bug several times:
1. Compactor nodes keep failing task because [inconsistency table info between catalog and hummock manager](https://github.com/risingwavelabs/risingwave/blob/be30f20e2c14b5d12efd5b33a4ac9e537602fc37/src/storage/src/hummock/compactor/compactor_runner.rs#L340).
2. After restarting meta node, the issue is gone. It works due to the [rectification process](https://github.com/risingwavelabs/risingwave/blob/be30f20e2c14b5d12efd5b33a4ac9e537602fc37/src/meta/src/hummock/manager/compaction_group_manager.rs#L152) during meta node startup.

In meta node, whenever a table is remove from catalog, it must [notify hummock manager](https://github.com/risingwavelabs/risingwave/blob/be30f20e2c14b5d12efd5b33a4ac9e537602fc37/src/meta/src/hummock/manager/compaction_group_manager.rs#L382) as well. Otherwise it could lead to the issue above. So I suspect there is a corner case that doesn't follow this rule, during dropping a stream job.

### Error message/log

_No response_

### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Before this PR tables are unregistered from Hummock either after the drop-stream-job barrier succeeds or during recovery. However there is a corner case that can cause a deadlock situation:
1. The cluster encounters backpressure originating from Hummock. So the earliest barrier becomes stuck. It is expected to be resolved via Hummock compaction.
2. User drops the table. Meta removes the table from catalog immediately on receiving the drop command. But Hummock manager won't remove the table until the barrier finishes, which is stuck already.
3. At the moment, compaction task related to this dropped table will always fail due to **the inconsistency between catalog and Hummock**. So the backpressure will never recover. It's a deadlock situation. Neither the barrier or the compaction can make any progress.

This PR fixes it by make Hummock drop tables immediately after catalog have done that.

close #15144

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by zwang28** [comment]
I bring back `LocalNotification::UnregisterTablesFromHummock ` to avoid ref HummockManager in catalog mgr. @wenym1

**Comment by zwang28** [comment]
One problem with this PR is, by removing dropped tables from Hummock before barrier is finished, the on-going barrier may fail due to being unable to find expected row from Hummock. It already causes failure in `e2e_test/streaming/aggregate/hdr_approx_percentile.slt`.

**Comment by wenym1** [comment]
> Blocking: one problem with this PR is, by removing dropped tables from Hummock before barrier is finished, the on-going barrier may fail (or inconsistent stream panic) due to being unable to find the expected row from Hummock. It already causes failure in `e2e_test/streaming/aggregate/hdr_approx_percentile.slt`.

May i ask in the current main branch, in what scenario will we forget to unregister the table? Currently we will unregister the table at the end of drop and cancel streaming job command, and we will purge all tables that are not in catalog. Did we have some commands left and didn’t unregister the table for these command?

**Comment by zwang28** [comment]
> > Blocking: one problem with this PR is, by removing dropped tables from Hummock before barrier is finished, the on-going barrier may fail (or inconsistent stream panic) due to being unable to find the expected row from Hummock. It already causes failure in `e2e_test/streaming/aggregate/hdr_approx_percentile.slt`.
> 
> May i ask in the current main branch, in what scenario will we forget to unregister the table? Currently we will unregister the table at the end of drop and cancel streaming job command, and we will purge all tables that are not in catalog. Did we have some commands left and didn’t unregister the table for these command?

Pls check the deadlock scenario in the PR description.

**Pull request closed without merging**
