### PR TITLE
fix(postgres-cdc): ssl.mode value backward compatibility

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

We changed the setting `ssl.mode` from `require` to `required` etc

If we don't want an upgrade script to modify user meta data, I guess keep both value should be fine

p.s.
For MySQL source, we require the value to be required, the alias require only as a backward compatibility for postgres.
So no need to write additional code for MySQL.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by StrikeW** [comment]
1.8 doesn't release this feature, do we need to backward compatible?

**Comment by yuhao-su** [comment]
> 1.8 doesn't release this feature, do we need to backward compatible? For users used nightly version we can let them recreate the sources.

Ahh I did see this been cherry picked in v1.8

**Review by StrikeW — APPROVED** [review]
LGTM to have alias, btw the 1.8 doc doesn't listed this feature.

**Comment by yuhao-su** [comment]
> LGTM to have alias, btw the 1.8 doc doesn't listed this feature.

Hmm I'm not sure in this case. Let's wait for @neverchanje 's comment

**Comment by StrikeW** [comment]
> > LGTM to have alias, btw the 1.8 doc doesn't listed this feature.
> 
> Hmm I'm not sure in this case. Let's wait for @neverchanje 's comment

There is a problem, actually the alias e.g. `require` cannot work for MySQL, MySQL needs the value to be `required`. I think we better should not allow the alias. Otherwise we need additional code for MySQL.

**Comment by yuhao-su** [comment]
>  I think we better should not allow the alias. Otherwise we need additional code for MySQL.

Ok. I'll close this pr.

**Comment by yuhao-su** [comment]
> I think we better should not allow the alias. Otherwise we need additional code for MySQL.

Ok. I'll close this pr.

**Comment by fuyufjh** [comment]
Discussed in [Slack](https://risingwave-labs.slack.com/archives/C078FMP8G9K/p1718758576982059)

**Comment by fuyufjh** [comment]
Discussed in [Slack](https://risingwave-labs.slack.com/archives/C078FMP8G9K/p1718758576982059)

**Comment by StrikeW** [comment]
> There is a problem, actually the alias e.g. `require` cannot work for MySQL, MySQL needs the value to be `required`. I think we better should not allow the alias. Otherwise we need additional code for MySQL.

For MySQL source, we require the value to be `required`, the alias `require` only as a backward compatibility for postgres.
So no need to write additional code for MySQL.

**Pull request merged**
