### PR TITLE
refactor(object store): OpenDAL write concurrent = 256

### PR DESCRIPTION
**Pull request by wcy-fdu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
In OpenDAL's implementation, if currency > part numbers, the `FinishMultipartUpload` operation incurs  two IO operations: the first round waits for `task.execute`, and the second waits for all tasks in the batch to complete.
In our scenario, the file in object store has a soft limit of 256MB, and the default part size is 16MB. Therefore, to avoid redundant IO, all parts should be uploaded in parallel, just like the AWS SDK. This PR adjusts the concurrency to 32(at most 512MB file size).

The longevity test passed.
image

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by wcy-fdu** [comment]
Longevity test pass on the new concurrency(256):
image

**Review by Li0k — COMMENTED** [review]
Thansk for the test, i have question:
1. Have you tested increasing the upload part size to reduce concurrency?
2. Pr description has Typo 32 -> 256

**Comment by wcy-fdu** [comment]
Nexmark perf test result:  the performance of (q0 and q13) have decreased, and the performance of (q3 15 17 q12 q101 q102) have increased. 
image

http://metabase.risingwave-cloud.xyz/question/2219-nexmark-rw-compare?risingwave_tag_1=opendal-0.49&rw_label_1=opendal-0.49-0921&risingwave_metrics=avg-source-output-rows-per-second&risingwave_tag_2=nightly-20240919&rw_label_2=daily

**Comment by wcy-fdu** [comment]
> Thansk for the test, i have question:
> 
> 1. Have you tested increasing the upload part size to reduce concurrency?
> 2. Pr description has Typo 32 -> 256

Let me briefly introduce the background of this PR: We found that in OpenDAL, streaming uploads result in an additional IO when the part number exceeds concurrency, which increases the probability of timeouts. Therefore, the aim of this PR is to avoid this situation by making concurrency approach unlimited. What you mentioned about increasing part size can indeed achieve this, but I prefer to directly increase concurrency because
- our maximum file size is about 256MB, meaning that concurrency values above 16 are effectively the same as 16(I think 16 is acceptable, not too high).
- before OpenDAL 0.47, we used unlimited settings, and we haven't encountered OOM issues during this round longevity test.
- change concurrency to "unlimit" is aligned with the AWS SDK.

**Comment by hzxa21** [comment]
> Nexmark perf test result: the performance of (q0: -8.5% and q13 -3%) have decreased

Can you try re-run the q0 perf test with this PR? It is surprised that a query with almost no object store I/O can differ that much with the change of this PR.

**Comment by wcy-fdu** [comment]
> > Nexmark perf test result: the performance of (q0: -8.5% and q13 -3%) have decreased
> 
> Can you try re-run the q0 perf test with this PR? It is surprised that a query with almost no object store I/O can differ that much with the change of this PR.

Just rerun the two queries(q0 and q13) with degraded performance, and this time the performance of q13 has not decreased, while that of q0 has decreased slightly(about -1.2% from 128.3 to 126.9).
I will check the reason tomorrow, but personally I feel this decrease is fine.
image

metabase: http://metabase.risingwave-cloud.xyz/question/2219-nexmark-rw-compare?risingwave_tag_1=opendal-0.49&rw_label_1=opendal-0.49-0922-q0q13&risingwave_metrics=avg-source-output-rows-per-second&risingwave_tag_2=nightly-20240919&rw_label_2=daily

**Review by hzxa21 — APPROVED** [review]
The rerun result looks good.

LGTM.

**Comment by wcy-fdu** [comment]
> The rerun result looks good.

I took a quick look at the q0 monitoring and found nothing abnormal. This 1.2% drop should be an error. So we can merge this PR. Thank you @hzxa21  for helping locate the root cause.
concurrency=256  https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1727009162000&orgId=1&to=1727009947000&var-datasource=VictoriaMetrics&var-namespace=nexmark-kafka-benchmark-20240922-122656
concurrency=8 https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=VictoriaMetrics&from=1726763091000&to=1726763871000&var-namespace=nexmark-bs-0-14-daily-20240919

**Pull request merged**
