### PR TITLE
chore(test): add more nexmark queries into source test

### LINKED ISSUE #6809: Add more nexmark queries into the end-to-end source test
https://github.com/risingwavelabs/risingwave/blob/main/e2e_test/source/basic/nexmark_endless.slt#L3-L4
We were worried that the end-to-end source test would take too much time. (any idea about how much more time exactly?)

SCR-20221208-w6k

From the figure above, we can roughly tolerate another 5 min before the end-to-end source test becomes the bottleneck.

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
#6809, end-to-end source test currently is not the bottleneck of the entire CI.

~Just add all of the stateful nexmark queries we supported now.~
Not all, but the representative the same 12 queries used for daily performance test and performance dashboard.

## Checklist

- [x] ~I have written necessary rustdoc comments~
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
closes #6809

### CODE REVIEW

**Comment by tabVersion** [comment]
any update?

**Comment by lmatz** [comment]
> any update?

Should work now, maybe timeout is still not large enough, let's see.

**Comment by lmatz** [comment]
split into 4 files just for the sake of my eyes,
thinking we will use some template language such as jinja to maintain all the SQLs just like code, e.g. DRY.

**Comment by lmatz** [comment]
end-to-end source test still not the bottleneck

SCR-20221219-o7k

**Review by tabVersion — APPROVED** [review]
LGTM

**Pull request merged**
