### PR TITLE
fix: cherry-pick #13078 and #13046

### LINKED ISSUE #13093: cherrypick fix(object_store): fix a corner case with retry (#13078) to branch v1.3-rc
Cherry picking \#13078 onto branch v1.3-rc

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

close #13093

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by wangrunji0408 — APPROVED** [review]

**Comment by zwang28** [comment]
@kwannoel 

I encountered a fuzzing test error, which I believe was not caused by this PR. Has it been fixed in main branch?

```
2022-08-24T01:04:16.275573Z ERROR node{id=7 name="frontend-1"}:task{id=606}:process_query_msg_one_stmt{session_id=0 stmt=CREATE MATERIALIZED VIEW m10 AS SELECT TIMESTAMP '2022-04-19 10:04:39' AS col_0, (approx_count_distinct(hop_0.c13) FILTER(WHERE false) + hop_0.c3) AS col_1, hop_0.c4 AS col_2, internal_last_seen_value(DISTINCT (hop_0.c13 + hop_0.c10)) FILTER(WHERE CAST((INT '321') AS BOOLEAN)) AS col_3 FROM hop(alltypes2, alltypes2.c11, INTERVAL '61', INTERVAL '61') AS hop_0 WHERE hop_0.c1 GROUP BY hop_0.c11, hop_0.c4, hop_0.c6, hop_0.c1, hop_0.c14, hop_0.c3}: risingwave_frontend::session: failed to handle sql:
CREATE MATERIALIZED VIEW m10 AS SELECT TIMESTAMP '2022-04-19 10:04:39' AS col_0, (approx_count_distinct(hop_0.c13) FILTER(WHERE false) + hop_0.c3) AS col_1, hop_0.c4 AS col_2, internal_last_seen_value(DISTINCT (hop_0.c13 + hop_0.c10)) FILTER(WHERE CAST((INT '321') AS BOOLEAN)) AS col_3 FROM hop(alltypes2, alltypes2.c11, INTERVAL '61', INTERVAL '61') AS hop_0 WHERE hop_0.c1 GROUP BY hop_0.c11, hop_0.c4, hop_0.c6, hop_0.c1, hop_0.c14, hop_0.c3:
Bind error: failed to bind expression: internal_last_seen_value(DISTINCT (hop_0.c13 + hop_0.c10)) FILTER(WHERE CAST((INT '321') AS BOOLEAN))

Caused by:
  Invalid input syntax: DISTINCT, ORDER BY or FILTER is only allowed in aggregation functions, but `internal_last_seen_value` is not an aggregation function
2022-08-24T01:04:16.275573Z  INFO node{id=7 name="frontend-1"}:task{id=606}: pgwire_query_log: mode=(simple query) session=0 status=err time=0ms sql=CREATE MATERIALIZED VIEW m10 AS SELECT TIMESTAMP '2022-04-19 10:04:39' AS col_0, (approx_count_distinct(hop_0.c13) FILTER(WHERE false) + hop_0.c3) AS col_1, hop_0.c4 AS col_2, internal_last_seen_value(DISTINCT (hop_0.c13 + hop_0.c10)) FILTER(WHERE CAST((INT '321') AS BOOLEAN)) AS col_3 FROM hop(alltypes2, alltypes2.c11, INTERVAL '61', INTERVAL '61') AS hop_0 WHERE hop_0.c1 GROUP BY hop_0.c11, hop_0.c4, hop_0.c6, hop_0.c1, hop_0.c14, hop_0.c3
2022-08-24T01:04:16.275573Z ERROR node{id=7 name="frontend-1"}:task{id=606}: pgwire::pg_protocol: error when process message error=QueryError: Bind error: failed to bind expression: internal_last_seen_value(DISTINCT (hop_0.c13 + hop_0.c10)) FILTER(WHERE CAST((INT '321') AS BOOLEAN))

Caused by:
  Invalid input syntax: DISTINCT, ORDER BY or FILTER is only allowed in aggregation functions, but `internal_last_seen_value` is not an aggregation function
2022-08-24T01:04:16.280404Z  INFO node{id=14 name="client"}:task{id=605}: risingwave_sqlsmith::runner: [UNEXPECTED ERROR]: Error {
    kind: Db,
    cause: Some(
        DbError {
            severity: "ERROR",
            parsed_severity: None,
            code: SqlState(
                EXX000,
            ),
            message: "QueryError: Bind error: failed to bind expression: internal_last_seen_value(DISTINCT (hop_0.c13 + hop_0.c10)) FILTER(WHERE CAST((INT '321') AS BOOLEAN))\n\nCaused by:\n  Invalid input syntax: DISTINCT, ORDER BY or FILTER is only allowed in aggregation functions, but `internal_last_seen_value` is not an aggregation function",
            detail: None,
            hint: None,
            position: None,
            where_: None,
            schema: None,
            table: None,
            column: None,
            datatype: None,
            constraint: None,
            file: None,
            line: None,
            routine: None,
        },
    ),
}
```

**Comment by kwannoel** [comment]
Didnt see this before. Looks like a regression perhaps. Taking a look.

**Comment by kwannoel** [comment]
`internal_last_seen_value` should not be used. I guess it still works in latest `main`. Let me ban it.

**Comment by kwannoel** [comment]
> `internal_last_seen_value` should not be used. I guess it still works in latest `main`. Let me ban it.

Building new snapshot https://buildkite.com/risingwavelabs/generate-sqlsmith-snapshots-weekly/builds/129

**Pull request merged**
