### PR TITLE
chore(common): move rows to a separate directory

### PR DESCRIPTION
**Pull request by yuhao-su**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
as title

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by fuyufjh** [comment]
We had some offline discussions. This PR aims to prepare for an abstraction of different **Rows**: RowRef, Row(Vec<Datum>), the in-memory Row, etc...

I think we should be cautious about this because it will introduce another trait and will cause more structs to be generic.

**Comment by yuhao-su** [comment]
It's debatable whether that is an overdesign. It is true that such change will add a generic on `eval_row` and `StateTable`.

We can discuss more details later.

**Comment by BugenZhao** [comment]
> I think we should be cautious about this because it will introduce another trait and will cause more structs to be generic.

I think that the row trait will be mainly used for passing arguments to functions, instead of storing a generic one (or type-erased one) somewhere: the use case for each operator should be concrete, not to speak of that we agree that randomly-accessiable row is very inefficient for memory usage. #5094, #5137


> It is true that such change will add a generic on eval_row and StateTable.

Coming back in a month, the StateTable has become raw-bytes based. 😄

**Comment by fuyufjh** [comment]
Inactive

**Pull request closed without merging**
