### PR TITLE
feat: remove watermark buffer in state table

### LINKED ISSUE #14014: make `WatermarkBufferByEpoch<const PERIOD: usize>`'s `PERIOD` as a virable
Currently, as the title, we have
https://github.com/risingwavelabs/risingwave/blob/420577906aa3ee39d4ba07589eb08a255a7a8156/src/stream/src/common/table/watermark.rs#L42

And it makes the constant period a part of the type `DefaultWatermarkBufferStrategy`.
It is especially annoying when we want to test the executor with no watermark buffer.

### PR DESCRIPTION
**Pull request by hzxa21**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

We have fully switched to using the table vnode watmerk for state cleaning and deprecate the range tombstones in storage.  With that, eagerly performing range delete will not put excessive pressure on storage so the streaming watermark buffer in state table can be removed.

After this PR, we can expect the range delete based on streaming watermark will take effect immediately for state table reads.

close #14014 
## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by st1page** [comment]
close #14014

**Review by wenym1 — APPROVED** [review]
LGTM!

**Comment by hzxa21** [comment]
I suspect the e2e test failure is caused by https://github.com/risingwavelabs/risingwave/issues/17711, which can cause a row that is already been deleted by the watermark state cleaning to be deleted from the left state table of dynamic filter.

Discussed with @stdrc offline. @stdrc will pick this PR to https://github.com/risingwavelabs/risingwave/pull/17816 to fix the issue.

**Comment by stdrc** [comment]
Changes moved to #17816.

**Pull request closed without merging**
