### PR TITLE
fix: dedup join key in degree table

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Deduplicate columns in HashJoin's degree table. Check the `ch_benchmark.yaml` for example.

**Limitation**: Note that this only applies to values. For the key, the columns are still duplicated, e.g. `primary key: [ $0 ASC, $1 ASC, $0 ASC ]`. This is because the `HashJoin` executor assumes that the join key is always the first (second, third...) columns in state/degree table's PK. As a result, fixing that may require additional work, such as passing a `join_key_columns_in_state_table` in proto.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by BugenZhao — APPROVED** [review]
LGTM.

Since I'm not an expert in optimizer, I'm not sure whether there could be any potential issues similar to https://github.com/risingwavelabs/risingwave/issues/7698#issuecomment-1423785603.

**Comment by yuhao-su** [comment]
You may also need to fix the `dk_indices_in_jk` for degree table

**Comment by fuyufjh** [comment]
> You may also need to fix the `dk_indices_in_jk` for degree table

I think not. Neither distribution key nor join key were affected. Let me add some test cases.

**Comment by yuhao-su** [comment]
> Neither distribution key nor join key were affected. Let me add some test cases.

You are right. I guess what really need to be fixed is exector code. e.g. this https://github.com/singularity-data/risingwave/blob/9cd7f6486e659af72857aef7ac27247305e880c0/src/stream/src/executor/managed_state/join/mod.rs#L79

**Comment by fuyufjh** [comment]
> > Neither distribution key nor join key were affected. Let me add some test cases.
> 
> You are right. I guess what really need to be fixed is exector code. e.g. this https://github.com/singularity-data/risingwave/blob/9cd7f6486e659af72857aef7ac27247305e880c0/src/stream/src/executor/managed_state/join/mod.rs#L79

Seems no problem. `order_key` is projected with `state_order_key_indices`, which is from `order_key_indices`, which is from `degree_table.pk_indices().to_vec()`

**Pull request closed without merging**
