### PR TITLE
fix(ci): disable LTO for `ci-release` to resolve build timeout in main-cron

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

image

30 min is barely enough for the `cargo build` command, but sometimes it timeouts due to the fluctuation and other phases.

https://buildkite.com/risingwavelabs/main-cron/builds/1559#018d1d50-28d4-4f64-8175-e842dd03e634

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by xxchan — COMMENTED** [review]
We may consider turn off `lto` for `ci-release`

**Review by xxchan — APPROVED** [review]
rubber stamp

**Comment by BugenZhao** [comment]
Have a try: https://buildkite.com/risingwavelabs/main-cron/builds/1562#018d2054-8b11-40c2-80b0-ecc4546da7ee

**Comment by BugenZhao** [comment]
> Have a try: [buildkite.com/risingwavelabs/main-cron/builds/1562#018d2054-8b11-40c2-80b0-ecc4546da7ee](https://buildkite.com/risingwavelabs/main-cron/builds/1562#018d2054-8b11-40c2-80b0-ecc4546da7ee)

Wow, so fast after disabling LTO. 😄

image

**Pull request merged**
