### PR TITLE
fix(cmd_all): immediately exit if `idle_exit_secs` is set, and meta node has stopped

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Close https://github.com/risingwavelabs/risingwave/issues/16323

Tested locally with:
```
RW_SINGLE_NODE_MAX_IDLE_SECS=10 cargo run --bin risingwave playground
```

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by BugenZhao — COMMENTED** [review]
What about moving it out of the `MetaOpts` and making it an option only used by standalone mode?

**Comment by kwannoel** [comment]
> What about moving it out of the `MetaOpts` and making it an option only used by standalone mode?

The idle manager is in meta node and that requires more refactoring. Leave an issue to track it: https://github.com/risingwavelabs/risingwave/issues/16370

**Comment by tabVersion** [comment]
> What about moving it out of the `MetaOpts` and making it an option only used by standalone mode?

The fix LGTM. 
IIRC, the reason why we added this parameter is to prevent ram pile-up in playground mode. Do we still need it in standalone mode?

**Comment by kwannoel** [comment]
> > What about moving it out of the `MetaOpts` and making it an option only used by standalone mode?
> 
> The fix LGTM. IIRC, the reason why we added this parameter is to prevent ram pile-up in playground mode. Do we still need it in standalone mode?

I'm not sure... Defer to @mikechesterwang . We can merge this in first and close the bug.

**Comment by mikechesterwang** [comment]
> > > What about moving it out of the `MetaOpts` and making it an option only used by standalone mode?
> > 
> > 
> > The fix LGTM. IIRC, the reason why we added this parameter is to prevent ram pile-up in playground mode. Do we still need it in standalone mode?
> 
> I'm not sure... Defer to @mikechesterwang . We can merge this in first and close the bug.

currently I'm using `/usr/bin/timeout` to force the container to stop. If we could use `idle timeout`, we can set a longer retention time and also reduce the idle time.

**Review by fuyufjh — APPROVED** [review]
Acceptable to me. Anyway this is only used in playground.

**Pull request merged**
