### PR TITLE
feat: support DISTINCT ON in batch query

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR adds `DISTINCT ON` support to batch query.

- In parser, the `select.distinct` field is changed from boolean to an enum `Distinct`.
- In binder, `Distinct` will be transformed to a new enum `BoundDistinct`.
- In planner, the `DISTINCT ON` will be planned to a `LogicalAgg` node **before** projection.
  - the group list is the expressions being distincted on.
  - the aggregations is all other expressions in the select list, with a new `first_value` agg.
  - the `first_value` agg will keep the first non-null value it has seen.
- In expr module, it adds a new `first` aggregator. So far the batch query works.

Note that even we keep the first value in aggregation, the output value of `SELECT` is still unpredictable if no `ORDEY BY` is specified on that column:

```sql
v1 v2
-----
1  2
4  3
4  2
1  3

select distinct on(v1) v2 from t order by v1;
---- 
2
3
----
3
2
----
2
2
----
3
3
# all of them are valid
```

If `ORDER BY` is specified on `v2`, the output **should be** predictable (`2 2`). But this feature is hard to implement on the streaming side (according to @TennyZhuang). So currently it is left unimplemented and the `ORDER BY v2` will be just **ignored**.

In the future PR I'll add a new `first_value` aggregation state to stream executor, in order to support `DISTINCT ON` in materialized view.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

* SQL commands, functions, and operators

### Release note

(Not fully implemented. I will fill this part in the future PR.)

## Refer to a related PR or issue link (optional)
part of #4617

### CODE REVIEW

**Comment by chenzl25** [comment]
FYI, using over window can express predictable result for deduplication.  #5282

**Comment by TennyZhuang** [comment]
> FYI, using over window can express predictable result for deduplication. #5282

Yes, but I guess `DISTINCT ON` is more friendly to users.

**Review by chenzl25 — APPROVED** [review]
LGTM. I think for batch query with distinct on. We can use `SortAgg` to implement it in the future. Using `SortAgg` we can provide a predictable result when `order by` is specified.

**Comment by chenzl25** [comment]
Finally, it would be great if a planner test of `distinct on` can be added.😁

**Pull request merged**
