### PR TITLE
refactor(meta): only retry on error when creating meta client

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Once we successfully initialize the meta client, we are sure that there's no connection issue with the meta service.

Based on this, we only need to wrap the initialization step within `Retry`, while directly throw any error occurred in subsequent steps like `add_worker_node` and `get_system_params`. This eliminates the need for handling errors based on their variants.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
* **#18049** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/18049?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @BugenZhao and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yezizp2012 — APPROVED** [review]
LGTM, but found something weird in e2e:
```
2024-08-15T05:56:55.221041949Z ERROR risingwave_rpc_client::meta_client: failed to register worker, exiting... error=failed to add worker node: gRPC request to meta service failed: Operation is not implemented or not supported: 
```

**Comment by BugenZhao** [comment]
> but found something weird in e2e:

Yeah. 😕 Might be because we always boot the follower service first, then the leader service after shutting it down. The race case here need to be tolerated and retried.

**Comment by BugenZhao** [comment]
Updated to ensure we are connecting to the leader service by returning from `GrpcMetaClient::new`. Let's see whether it works.

**Comment by BugenZhao** [comment]
Will try another approach 😕

**Pull request closed without merging**
