### PR TITLE
refactor: error handling in system param

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Don't use `RwError`;
Use `ok_or_else` to avoid unnecesary error creation.

To some extent mitigate #6205...

### CODE REVIEW

**Review by BugenZhao — APPROVED** [review]
I've checked the clippy rules and there seems no rule about this. 🤔 The only related rule is an inverse one of `unnecessary_lazy_evaluations`.

**Comment by xxchan** [comment]
> I've checked the clippy rules and there seems no rule about this. 🤔 The only related rule is an inverse one of `unnecessary_lazy_evaluations`.

https://rust-lang.github.io/rust-clippy/master/#or_fun_call

**Comment by BugenZhao** [comment]
> https://rust-lang.github.io/rust-clippy/master/#or_fun_call

Oh. It's `allow` by default. 🤔🥵

**Comment by xxchan** [comment]
IIRC it was warn by default, but now it becomes allow. It may be because it has too many issues: https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+or_fun_call

**Pull request merged**
