### PR TITLE
perf(agg): merge common agg calls

### LINKED ISSUE #12305: enhancement(optimizer): merge common aggregation functions
> Discussed with @st1page 

For example,

```
select avg(x) a, sum(x) s, count(x) c from t;
```

will be executed as 

```
select expr1 / expr2, s, c from 
  (select sum(x) as expr1, count(x) as expr2, sum(x) s , count(x) c from t);
```

Here, the two `sum(x)` and two `count(x)` can be simply reused.

Another example is NexMark Q15

https://github.com/risingwavelabs/risingwave/blob/0259125649a7494e4d58d83f1c8f7d5d1d3cdd7f/src/frontend/planner_test/tests/testdata/output/nexmark_source.yaml#L1126

```
StreamHashAgg [append_only] {
  group_key: [$expr1, bidder, auction, flag],
  aggs: [
    count, 
    count filter((price < 10000:Int32)), 
    count filter((price >= 10000:Int32) AND (price < 1000000:Int32)), 
    count filter((price >= 1000000:Int32)),
    count filter((price < 10000:Int32)), 
    count filter((price >= 10000:Int32) AND (price < 1000000:Int32)), 
    count filter((price >= 1000000:Int32)),
    count filter((price < 10000:Int32)), 
    count filter((price >= 10000:Int32) AND (price < 1000000:Int32)), 
    count filter((price >= 1000000:Int32))] 
```

Obviously the 9 `count` agg functions can be merged to 3, so that we reduce the aggregation state size to 1/3.

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Previously we have duplication check in `LogicalAggBuilder::push_agg_call`, but that doesn't work for `Agg` node directly created by optimizer rules. This PR adds an `AggCallMergeRule` to eliminate duplicated agg calls.

This fixes #12305.

## Checklist

- [x] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [x] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by wangrunji0408 — APPROVED** [review]
LGTM

**Review by st1page — APPROVED** [review]

**Comment by stdrc** [comment]
Waiting for benchmark: https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2192

**Review by chenzl25 — APPROVED** [review]
LGTM

**Comment by stdrc** [comment]
> Waiting for benchmark: [buildkite.com/risingwave-test/nexmark-benchmark/builds/2192](https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2192)

Benchmark result shows a big degradation🤡, and I fixed it in recent 2 commits.

Starting a fresh benchmark...

**Comment by stdrc** [comment]
Benchmark results (rightmost is this PR):

Q15:

截屏2023-10-09 18 27 55

Q16:

截屏2023-10-09 18 31 47

Q15 has an increase to some extend, while Q16 faces slight degradation. I have no idea why🤔, maybe the bottleneck is not on those duplicated agg calls and the degradation is just a normal fluctuation.

**Comment by st1page** [comment]
Q15's plan does not changes :thinking:

**Comment by stdrc** [comment]
> Q16's plan does not changes 🤔

I'm not sure if the bench pipeline is running q16 with `split_distinct_agg` and `force_two_phase_agg` on or not. But q15 is confirmed by Jianwei.

**Comment by stdrc** [comment]
> > Q16's plan does not changes 🤔
> 
> I'm not sure if the bench pipeline is running q16 with `split_distinct_agg` and `force_two_phase_agg` on or not. But q15 is confirmed by Jianwei.

The Q16 is ran with `split_distinct_agg = false` and `force_two_phase_agg = false`, then it's explained.

**Pull request merged**
