### PR TITLE
fix(stream):hash join: check degree & row iterator have same length

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Otherwise it will lead to more confusing errors.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by st1page — APPROVED** [review]

**Review by st1page — APPROVED** [review]
Maybe also open the debug assert to assert? In case they have the same cardinality but different pks..
```
 debug_assert_eq!(
                    pk1, pk2,
                    "mismatched pk in degree table: pk1: {pk1:?}, pk2: {pk2:?}",
                );
```

**Review by BugenZhao — APPROVED** [review]

**Review by yuhao-su — APPROVED** [review]
LGTM. Also ok to wrap it in a zip_eq.

BTW, this previous impl is to drop unmatched keys. https://github.com/risingwavelabs/risingwave/pull/6159/files#diff-6e4d3950cf84ab354e5daa96879a733b1842693d1a6951773adbbb5abdd5f8dcL24-L29

**Comment by fuyufjh** [comment]
> Maybe also open the debug assert to assert? In case they have the same cardinality but different pks..
> 
> ```
>  debug_assert_eq!(
>                     pk1, pk2,
>                     "mismatched pk in degree table: pk1: {pk1:?}, pk2: {pk2:?}",
>                 );
> ```

Yeah, I have considered this. I guess @yuhao-su chose `debug_assert_eq` because of concerning about the performance cost of comparing these two byte arrays, right? On the other hand, the probability of encountering inconsistencies on both sides while having an equal number of rows is very low, I think

**Comment by fuyufjh** [comment]
Let me hold the PR until the storage bugs being fixed... Otherwise it will only cause more panics.

**Review by yuhao-su — APPROVED** [review]

**Pull request merged**
