### PR TITLE
fix: support kafka sink for struct and list type 

### LINKED ISSUE #7072: kafka sink: panicked at `itertools: .zip_eq()`
### Describe the bug

commit: 21e12ea2878e5597f05ee14aace56f84b67bdca5

```
CREATE SOURCE nexmark (
  event_type BIGINT,
  person STRUCT<"id" BIGINT,
                "name" VARCHAR,
                "email_address" VARCHAR,
                "credit_card" VARCHAR,
                "city" VARCHAR,
                "state" VARCHAR,
                "date_time" TIMESTAMP,
                "extra" VARCHAR>,
  auction STRUCT<"id" BIGINT,
                 "item_name" VARCHAR,
                 "description" VARCHAR,
                 "initial_bid" BIGINT,
                 "reserve" BIGINT,
                 "date_time" TIMESTAMP,
                 "expires" TIMESTAMP,
                 "seller" BIGINT,
                 "category" BIGINT,
                 "extra" VARCHAR>,
  bid STRUCT<"auction" BIGINT,
             "bidder" BIGINT,
             "price" BIGINT,
             "channel" VARCHAR,
             "url" VARCHAR,
             "date_time" TIMESTAMP,
             "extra" VARCHAR>
) WITH (
    connector = 'nexmark',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
```

```
create sink nexmark_sink
as select * from nexmark with (
    kafka.brokers = '127.0.0.1:9092',
    kafka.topic = 'nexmark',
    format = 'append_only',
    connector = 'kafka'
);
```

LOG:
```
   0: std::panicking::begin_panic
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:607:12
   1: <itertools::zip_eq_impl::ZipEq<I,J> as core::iter::traits::iterator::Iterator>::next
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/zip_eq_impl.rs:48:13
   2: risingwave_connector::sink::kafka::datum_to_json_object
             at ./src/connector/src/sink/kafka.rs:374:47
   3: risingwave_connector::sink::kafka::record_to_json
             at ./src/connector/src/sink/kafka.rs:398:21
```

[compute-node-5688.log](https://github.com/risingwavelabs/risingwave/files/10306501/compute-node-5688.log)

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context
enable DEBUG LOG: 
```
2022-12-27T07:13:15.681606Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Int64, Int64(2)
2022-12-27T07:13:15.681606Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Int64, Int64(1)
2022-12-27T07:13:15.681618Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Struct(StructType { fields: [Int64, Int64, Int64, Varchar, Varchar, Timestamp, Varchar], field_names: ["auction", "bidder", "price", "channel", "url", "date_time", "extra"] }), Struct(Some(Int64(1000)), Some(Int64(1001)), Some(Int64(461574)), Some(Utf8("channel-1315")), Some(Utf8("https://www.nexmark.com/wwwv/sxm/hikr/item.htm?query=1&channel_id=996147200")), Some(NaiveDateTime(NaiveDateTimeWrapper(2022-12-27T07:13:14.860))), Some(Utf8("iugddyabokogelsfvrrroebiavelhnnxdxbefjnktsbsgvxcnhpsvqcpq")))
2022-12-27T07:13:15.681623Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Struct(StructType { fields: [Int64, Varchar, Varchar, Int64, Int64, Timestamp, Timestamp, Int64, Int64, Varchar], field_names: ["id", "item_name", "description", "initial_bid", "reserve", "date_time", "expires", "seller", "category", "extra"] }), Struct(Some(Int64(1000)), Some(Utf8("sbeimyckhspxpmpeeuqm")), Some(Utf8("gvseirycizmyesblucotqllwnexpjnmleygtxdduleovagzygzgleacqfvawalfwlfaimlzupsxpmexeufltsibzopargshhlkpp")), Some(Int64(595843)), Some(Int64(691876)), Some(NaiveDateTime(NaiveDateTimeWrapper(2022-12-27T07:13:14.853))), Some(NaiveDateTime(NaiveDateTimeWrapper(2022-12-27T07:13:15.185))), Some(Int64(1000)), Some(Int64(12)), Some(Utf8("uamacidfvaipnenhviwwavjfvbpbucvfkxqygfeowbwtosrufnpiznlnvdyxjugfkolqozsatlutklowfvzbhyfzzywptzehmmwjtmmssqrheaubbyogocydtzvhcqrdebvgzpgdbnfrgfgpeekmimaasrosvnhjafwzjzsiisiojknnuwmiedvlhsbfmnmbgceohwobbxagbtucgaelkohpksyktwgdqdlunjkvghuencafwgauxmoetfcyttjsxcrpvqlmuapiyewovcxldrnaybyxgbnptzkuugubkhihhbyreysolqguhxuruxafdmwwecypdlhrazsnox")))
thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at 'itertools: .zip_eq() reached end of one iterator before the otheritertools: .zip_eq() reached end of one iterator before the other', ', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/zip_eq_impl.rs/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/zip_eq_impl.rs::2022-12-27T07:13:15.681652Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Int64, Int64(2)
```

### PR DESCRIPTION
**Pull request by tabVersion**
Signed-off-by: tabVersion <tabvision@bupt.icu>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

**This section will be used as the commit message. Please do not leave this empty!**

fix type matches for struct and list in kafka sink

& add struct and list test cases in ut
& add script command for compress test cases into zip file

## Checklist

~~- [ ] I have written necessary rustdoc comments~~
~~- [ ] I have added necessary unit tests and integration tests~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)

resolve #7072

### CODE REVIEW

**Review by lmatz — APPROVED** [review]

**Comment by lmatz** [comment]
how about adding some e2e tests in the `kafka.slt`

**Comment by CAJan93** [comment]
How does this relate to https://github.com/risingwavelabs/risingwave/pull/7022?

**Comment by tabVersion** [comment]
> how about adding some e2e tests in the kafka.slt

It is on progress

**Comment by tabVersion** [comment]
> How does this relate to #7022?

My mistake. It is #7072

**Pull request merged**
