### PR TITLE
fix: extract decimal correctly when bytes len >= 5

### PR DESCRIPTION
**Pull request by xuefengze**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
Correctly handle the situation when the length of bytes is greater than 4.
defore:
`1.1234567891` -> `18848476.8633979091`
after:
`1.1234567891` -> `1.1234567891`

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by tabVersion — APPROVED** [review]
LGTM, thanks for the fix

**Comment by xuefengze** [comment]
[test_decimal_truncate](https://github.com/risingwavelabs/risingwave/blob/main/src/connector/src/parser/unified/avro.rs#L482) test failed. Is `4.557430887741865791` the correct result?
https://buildkite.com/risingwavelabs/pull-request/builds/40741

**Comment by tabVersion** [comment]
> [test_decimal_truncate](https://github.com/risingwavelabs/risingwave/blob/main/src/connector/src/parser/unified/avro.rs?rgh-link-date=2024-01-26T05%3A26%3A24Z#L482) test failed. Is `4.557430887741865791` the correct result? [buildkite.com/risingwavelabs/pull-request/builds/40741](https://buildkite.com/risingwavelabs/pull-request/builds/40741)

The test result is generated by prev logic, feel free to change it as long as you make it correct.

**Comment by xiangjinwu** [comment]
> > [test_decimal_truncate](https://github.com/risingwavelabs/risingwave/blob/main/src/connector/src/parser/unified/avro.rs?rgh-link-date=2024-01-26T05%3A26%3A24Z#L482) test failed. Is `4.557430887741865791` the correct result? [buildkite.com/risingwavelabs/pull-request/builds/40741](https://buildkite.com/risingwavelabs/pull-request/builds/40741)
> 
> The test result is generated by prev logic, feel free to change it as long as you make it correct.

I would suggest to obtain the correct expected output from other official avro libraries, for example python or java.

**Pull request merged**
