### PR TITLE
revert: feat(stream): make Project expr evaluation concurrent (#14558)

### LINKED ISSUE #14828: perf: source throughput & barrier latency of longevity-test is worse than before
> Summarized from Sack thread: https://risingwave-labs.slack.com/archives/C034TRPKN1F/p1706079713814969

## Background

The recent failures of longevity test all nexmark (8 sets of nexmark queries) with 10k throughput), including

- https://github.com/risingwavelabs/risingwave/issues/14736
- https://github.com/risingwavelabs/risingwave/issues/14712
- https://github.com/risingwavelabs/risingwave/issues/14613

In short, in the past we can pass the test, but recently, it sometimes OOMed. This indicates that RW consume a bit more memory with same workload.

#### 1. Barrier latency became higher

As we know, the barrier latency is an important cause of OOM.

Before: before

After: after

#### 2. Source throughput became lower

The source throughput went down from 6.21 MB/s to 4.x ~ 5.x MB/s

- `nightly-20231225` 6.18 MB/s (18277 rows/s)  [BuildKite](https://buildkite.com/risingwave-test/longevity-test/builds/872)   [Grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20231225-150220&from=1703525911587&to=1703560610000)
- `nightly-20240122` 15109 rows/s (5.10 MB/s) **(-18% even when q6-group-top1 was EXCLUDED)** [BuildKite](https://buildkite.com/risingwave-test/longevity-test/builds/980)   [Grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=usrlngvty-20240124-085008&from=1706086766000&to=1706130105000)

## Code History

:white_check_mark: **nightly-20240107**  https://buildkite.com/risingwave-test/longevity-test/builds/891
Source throughput: 6.21 MB/s  18400 rows/s
Commit: a01a30dece65f0391210c1a60e6ef17d4270581a

:x: **nightly-20240108** https://buildkite.com/risingwave-test/longevity-test/builds/895
Source throughput: 3.57 MB/s  10566 rows/s
Commit: 414c6ec1c05e3d13aa4842d30624c13b83b9692c

~~Comparing: https://github.com/risingwavelabs/risingwave/compare/a01a30dece65f0391210c1a60e6ef17d4270581a...414c6ec1c05e3d13aa4842d30624c13b83b9692c~~ (see next comment)

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Revert #14558 to fix #14828.

Found by comparing

- [`nightly-20240115-fix-compaction`](https://buildkite.com/risingwave-test/longevity-test/builds/1001) 5.20 MB/s ⚠️
image
image

- [`nightly-20240115-fix-compaction-revert-14558`](https://buildkite.com/risingwave-test/longevity-test/builds/1010) 6.52 MB/s ✅
image
image

------------

Verifying on latest nightly build. So far so good.

- [`nightly-20240129`](https://buildkite.com/risingwave-test/longevity-test/builds/1008) Running
- [`nightly-20240129-revert-14558` (2 hour)](https://buildkite.com/risingwave-test/longevity-test/builds/1011) 6.43 MB/s ✅
- [`nightly-20240129-revert-14558` (12 hour)](https://buildkite.com/risingwave-test/longevity-test/builds/1012) Running

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]

**Comment by TennyZhuang** [comment]
The computation of Project is lightweight enough, so even after we use chunk, the overhead of `buffered` still can’t be ignored.

Will try some generic tricks to split the codes.

**Comment by fuyufjh** [comment]
> The computation of Project is lightweight enough, so even after we use chunk, the overhead of `buffered` still can’t be ignored.
> 
> Will try some generic tricks to split the codes.

I suppose the concurrent optimization is majorly for UDF, right? Is it possible to apply to the UDF functions only?

Btw, if we finally decide to work on `UdfProject` (or `MaterializedProject`), this optimization should be there.

**Comment by wangrunji0408** [comment]
> I suppose the concurrent optimization is majorly for UDF, right? Is it possible to apply to the UDF functions only?

Yes. This can be done by analyzing protobuf expressions to determine whether they contain UDFs. We can apply concurrency only when there are UDF expressions. But I still feel it's a bit hacky. 

> Btw, if we finally decide to work on `UdfProject` (or `MaterializedProject`), this optimization should be there.

Agree. Or `MaterializedFunction` if we want to allow UDFs everywhere. 🤔

**Comment by BugenZhao** [comment]
I suspect that the issue is not related to CPU performance, but rather due to the polling strategy of `TryBufferedWithFence` (mostly ported from `Buffered` I think).

We'll try to buffer as more "ready" chunks from upstream as possible, before doing the evaluation (and in most cases without UDF, this procedure is sequential). This could possibly lead to increased latency.

https://github.com/risingwavelabs/risingwave/blob/ce808ba849ac39c5211a3bac505947be2ba18091/src/utils/futures_util/src/buffered_with_fence.rs#L79-L92

**Pull request merged**
