### PR TITLE
fix(storage): lock table may cause deadlock and block iter

### PR DESCRIPTION
**Pull request by Little-Wallace**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
Fix https://github.com/risingwavelabs/risingwave/issues/13943
## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by st1page — APPROVED** [review]

**Review by Li0k — APPROVED** [review]

**Comment by hzxa21** [comment]
Can you explain how the deadlock happens in the PR description?

**Comment by Little-Wallace** [comment]
> Can you explain how the deadlock happens in the PR description?

I do not understand, but the trace stack show that it hung on lock-table.

**Comment by MrCroxx** [comment]
> > Can you explain how the deadlock happens in the PR description?
> 
> I do not understand, but the trace stack show that it hung on lock-table.

Is there a await tree dump?

**Comment by chenzl25** [comment]
Related issue https://github.com/risingwavelabs/risingwave/issues/13932

**Comment by chenzl25** [comment]
Just have tested a backfill on a table with only 1 parallelism and it succeeds, so it is a deadlock between different parallelism.

**Review by MrCroxx — APPROVED** [review]

**Review by chenzl25 — COMMENTED** [review]
We should hold the lock before calling the `notified`, otherwise, no one would drop the guard when the future is dropped in that await point.
```rust
        let lock = LockGuard {
            key,
            locks: self.locks.clone(),
        };
        if let Some(notify) = notify {
            notify.notified().await;
        }
        return lock
```

**Comment by st1page** [comment]
> > > Can you explain how the deadlock happens in the PR description?
> > 
> > 
> > I do not understand, but the trace stack show that it hung on lock-table.
> 
> Is there a await tree dump?

https://risingwave-labs.slack.com/archives/C069B78AXDW/p1702439327854279

**Pull request merged**
