### PR TITLE
feat(stream): concurrent fetch for temporal join (take 2)

### LINKED ISSUE #13974: perf: temporal join look up concurrently
https://github.com/risingwavelabs/risingwave/blob/783442dc3cb3f7dc713e76a58df8c691e973fd66/src/stream/src/executor/temporal_join.rs#L435

### PR DESCRIPTION
**Pull request by TennyZhuang**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Previous try: Close #14666 

Close #13974 

Rework without any rust tricks :)

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by TennyZhuang** [comment]
```yaml
CreatedAt: "2023-01-31T07:12:52.702476Z"
DeletedAt: null
ID: 2
UpdatedAt: "2023-02-10T06:32:34.128656Z"
compactor-node-instance:
  CreatedAt: "2022-12-02T03:27:31.615859Z"
  DeletedAt: null
  ID: 2
  UpdatedAt: "2022-12-02T03:27:31.615859Z"
  cpu-num: 8
  description: 8 CPUs and 16GB Mem
  mem-size-gb: 16
  name: 8C16G
  nic-bandwidth: 10
compactor-node-num: 1
compute-node-instance:
  CreatedAt: "2022-12-02T03:27:31.615859Z"
  DeletedAt: null
  ID: 2
  UpdatedAt: "2022-12-02T03:27:31.615859Z"
  cpu-num: 8
  description: 8 CPUs and 16GB Mem
  mem-size-gb: 16
  name: 8C16G
  nic-bandwidth: 10
compute-node-num: 1
description: Testbed with 1 8C16G instances
frontend-node-instance:
  CreatedAt: "2022-12-02T03:27:31.615859Z"
  DeletedAt: null
  ID: 2
  UpdatedAt: "2022-12-02T03:27:31.615859Z"
  cpu-num: 8
  description: 8 CPUs and 16GB Mem
  mem-size-gb: 16
  name: 8C16G
  nic-bandwidth: 10
frontend-node-num: 1
meta-node-instance:
  CreatedAt: "2022-12-02T03:27:31.615859Z"
  DeletedAt: null
  ID: 2
  UpdatedAt: "2022-12-02T03:27:31.615859Z"
  cpu-num: 8
  description: 8 CPUs and 16GB Mem
  mem-size-gb: 16
  name: 8C16G
  nic-bandwidth: 10
meta-node-num: 1
name: medium-1cn
rising-wave-config: |
  [storage]
  block_cache_capacity_mb = 2048
  meta_cache_capacity_mb = 512
  compactor_memory_limit_mb = 2560
  shared_buffer_capacity_mb = 2048
```

Perf test result:

q13: 877,779.52rows/s -> 883,290.01rows/s

**Comment by TennyZhuang** [comment]
15115-q13-benchmark

No performance downgrade.

Due to the good locality of nexmark, we can't see a performance improvement.

**Comment by st1page** [comment]
> Due to the good locality of nexmark, we can't see a performance improvement.

https://github.com/risingwavelabs/risingwave/issues/15124

**Review by chenzl25 — APPROVED** [review]
LGTM

**Comment by TennyZhuang** [comment]
image

When the dimensional table (10k records, q13) is all in memory, this PR did not bring significant performance loss (within the fluctuation range).
When the dimensional table (1b records, q13) experiences high cache misses, this PR brought a fivefold performance improvement.

I believe merging it is worthwhile.

**Review by BugenZhao — APPROVED** [review]

**Pull request merged**
