### PR TITLE
fix(metrics): fix metrics barrier_latency_avg

### PR DESCRIPTION
**Pull request by wcy-fdu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Close https://github.com/risingwavelabs/risingwave/issues/18535

Previously, if the barrier latency was discontinuous, such as when running Nexmark benchmark with different queries, multiple barrier_latency_avg measurements would be displayed, see
image

This pr fix this, use avg to show only one metrics during all time periods:
image

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
> Previously, if the barrier latency was discontinuous, such as when running Nexmark benchmark with different queries, multiple barrier_latency_avg measurements would be displayed, see

I didn't understand... Why there can be multiple series of `meta_barrier_duration_seconds`? This metric is kept in `MetaMetrics`, which is kept in `GLOBAL_META_METRICS` as a singleton, so I suppose there should be always one metrics, unless the Meta node restarts.

**Comment by wcy-fdu** [comment]
> > Previously, if the barrier latency was discontinuous, such as when running Nexmark benchmark with different queries, multiple barrier_latency_avg measurements would be displayed, see
> 
> I didn't understand... Why there can be multiple series of `meta_barrier_duration_seconds`? This metric is kept in `MetaMetrics`, which is kept in `GLOBAL_META_METRICS` as a singleton, so I suppose there should be always one metrics, unless the Meta node restarts.


I also find it strange. I found that this problem always exists in our Nexmark benchmark: the barrier number is discontinuous, and the barrier latency is also discontinuous, causing many `barrier_latency_avg` metrics.
image


The current modification does not change the value of this metric, but only eliminates the redundancy of multiple displays.
image

I don't know why, but it works.

**Comment by fuyufjh** [comment]
> the barrier number is discontinuous, and the barrier latency is also discontinuous, causing many `barrier_latency_avg` metrics.

AFAIK, discontinuous metrics won't cause a metric to split into multiple. As you can observe from your screenshots, the blue lines keep being blue even with some breakings, until something happens and new line starts with another color.

**Comment by fuyufjh** [comment]
This PR seems to address a different issue other than https://github.com/risingwavelabs/risingwave/issues/18535.  See https://github.com/risingwavelabs/risingwave/issues/18535#issuecomment-2425522392 for the cause of #18535.

Can you please provide the source link of the screenshot in the PR description?

image

I guess it's caused by some recover or restarts. Want to confirm it.

**Comment by wcy-fdu** [comment]
> This PR seems to address a different issue other than #18535. See [#18535 (comment)](https://github.com/risingwavelabs/risingwave/issues/18535#issuecomment-2425522392) for the cause of #18535.
> 
> Can you please provide the source link of the screenshot in the PR description?
> 
> image
> I guess it's caused by some recover or restarts. Want to confirm it.

https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=VictoriaMetrics&var-namespace=longcmkf-20241020-190243&from=1729451197000&to=1729466205000

And the buildkite link    https://buildkite.com/risingwave-test/chaos-mesh/builds/1108

**Comment by wcy-fdu** [comment]
> I guess it's caused by some recover or restarts.

Oh you are right, recovery happened 5 times, and their are 6 `barrier_latency_avg`.

**Comment by fuyufjh** [comment]
> > I guess it's caused by some recover or restarts.
> 
> May be related, in the [first link](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=VictoriaMetrics&var-namespace=longcmkf-20241020-190243&from=1729451197000&to=1729466205000), the recovery happened 5 times, and their are 6 `barrier_latency_avg`. But in [another link](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=VictoriaMetrics&var-namespace=longcmkf-20241020-194205&from=1729453550000&to=1729472355000), the number of recoveries does not match the number of metrics.

The case of [another link] is because of the IP of instance changes due to Pod restart, thus, Prometheus considers these as different timeseries.

Screenshot 2024-10-21 at 17 00 12

**Comment by wcy-fdu** [comment]
> > > I guess it's caused by some recover or restarts.
> > 
> > 
> > May be related, in the [first link](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=VictoriaMetrics&var-namespace=longcmkf-20241020-190243&from=1729451197000&to=1729466205000), the recovery happened 5 times, and their are 6 `barrier_latency_avg`. But in [another link](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=VictoriaMetrics&var-namespace=longcmkf-20241020-194205&from=1729453550000&to=1729472355000), the number of recoveries does not match the number of metrics.
> 
> The case of [another link] is because of the IP of instance changes due to Pod restart, thus, Prometheus considers these as different timeseries.
> 
> Trick: set `Legand=Auto` to view the full labels of a timeseries.
> 
> Screenshot 2024-10-21 at 17 00 12

I see, so this is expected.
let's close this pr.

**Pull request closed without merging**
