### PR TITLE
fix(agg): fix `first_value` and `last_value` to not ignore NULLs

### LINKED ISSUE #18927: different result from mv and ad hoc query, may related to `last_value`
```
create table t1(
    id bigint primary key,
    uid bigint,
    value bigint,
    ts bigint
);
insert into t1 values(1, 1, null, 1),(2, 1, 2, 2),(3, 1, 3, 3);
flush;
select
    uid,
    last_value(case when ts=2 then value else null end order by ts) as lv
from t1
group by uid;
 uid | lv
-----+----
   1 |  2
(1 row)
create materialized view mv1 as
select
    uid,
    last_value(case when ts=2 then value else null end order by ts) as lv
from t1
group by uid;
select * from mv1;
 uid | lv
-----+----
   1 |
(1 row)
```

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

To align behavior with PG, we should not ignore NULLs when computing `first_value` and `last_value`.

This PR affects batch aggregate, batch over window. Also, a previous PR #19233 has already changed the behavior of streaming over window to the correct one.

Fixes #18927.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by stdrc** [comment]
* **#19275** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19275?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stdrc and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by st1page — APPROVED** [review]

**Review by BugenZhao — APPROVED** [review]
Is this considered a breaking change? Do we use them internally as well?

**Comment by stdrc** [comment]
The initial fix is not correct for `first_value` because of the internal mechanism of `aggregate` macro. Later commits introduced a new `shortcurcuit_if` macro argument so that `first_value` can be implemented via immediate shortcurcuiting.

**Comment by stdrc** [comment]
Superseded by #19332

**Pull request closed without merging**
