### PR TITLE
feat(stream): read exactly 1 row if no snapshot read per barrier for arrangement backfill

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

The main idea is: https://github.com/risingwavelabs/risingwave/pull/12780.

If there's a large number of tombstones, backfill snapshot read takes a long time to read an actual record. When barrier comes, the tombstone iterator's progress is dropped. Then backfill's snapshot read will stall and be unable to make progress. 

So we just make sure per barrier we read at least 1 record, to avoid the stall scenario.

As to why 1 row instead of 1 chunk, you can see #14544. See the closed issue for more details: https://github.com/risingwavelabs/risingwave/issues/14077

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by kwannoel** [comment]
snapshot read
Screenshot 2024-01-30 at 11 21 23 AM

snapshot read + upstream (arrangement backfill)
Screenshot 2024-01-30 at 11 21 43 AM

snapshot read + upstream (no shuffle backfill)
Screenshot 2024-01-30 at 11 21 54 AM

**Comment by BugenZhao** [comment]
Could you please also fill the PR body?

**Comment by kwannoel** [comment]
> Could you please also fill the PR body?

Updated, sorry about that.

**Comment by BugenZhao** [comment]
IIUC this is similar to #14544 but for the arrangement backfill. Would you show that in the PR title?

**Review by chenzl25 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
