### PR TITLE
refactor(frontend): simplify condition by merging lower bound and upper bound 

### PR DESCRIPTION
**Pull request by ZENOTME**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

1. complete the `TODO: simplify bounds:` in condition:
    - merge lower bound and upper bound 
    - filter eq conds using lower bound and upper bound
2. try to refine the split_to_scan_ranges by seperate out subprocess from it. ( Not sure whether it's a positive refine. I try make it look more tiny because I think its original len is so long to impact the readbility.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by chenzl25** [comment]
Are you still working on this? @ZENOTME

**Comment by ZENOTME** [comment]
> Are you still working on this? @ZENOTME

Yes, I think it has completed🤔. But I have long time not to touch on it seem it didn't have no progress. I can take a review later.

**Comment by ZENOTME** [comment]
ready for review @chenzl25

**Review by chenzl25 — COMMENTED** [review]
LGTM. Much clearer than before.

**Review by chenzl25 — APPROVED** [review]
LGTM

**Pull request merged**
