### PR TITLE
fix(direct cdc): use `time.precision.mode=connect`

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

According to Debeizum docs,

- `adaptive_time_microseconds` or `adaptive`: using either millisecond, microsecond, or nanosecond precision values based on the database column’s type.
- `connect` always represents time and timestamp values using Kafka Connect’s built-in representations for Time, Date, and Timestamp, which use millisecond precision regardless of the database columns' precision.

Our implementation simply inherits the implementation of [Kafka Connect's JsonConverter](https://github.com/a0x8o/kafka/blob/master/connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java)

https://github.com/risingwavelabs/risingwave/blob/c364ef3f35723ce7032c92a469831b0ab4dcf8c5/java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzJsonConverter.java#L34-L38

Thus, we should use `time.precision.mode=connect` accordingly.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
Notice that the solution only works for direct CDC. For those who use a self-deployed Debezium -> Kafka -> RW, we have to provide an option to adjust the parsing behavior for each column. Let me create another issue for that.

**Comment by fuyufjh** [comment]
@StrikeW Can you confirm the code path of CDC V2? I remember in that case the Rust json parser will be used.

**Comment by StrikeW** [comment]
> @StrikeW Can you confirm the code path of CDC V2? I remember in that case the Rust json parser will be used.

Tested this branch with `1972-01-01 00:00:00` value in upstream, and can ingest correctly (backfill and incremental).
image

**Review by StrikeW — APPROVED** [review]

**Comment by StrikeW** [comment]
> connect always represents time and timestamp values using Kafka Connect’s built-in representations for Time, Date, and Timestamp, which use millisecond precision regardless of the database columns' precision.

This seems only true for postgres, for mysql `Time` still represent with micro seconds.

image

**Comment by fuyufjh** [comment]
> If we really want to enforce to milliseconds, I think we have to implement a `CustomConverter` (e.g. https://github.com/risingwavelabs/risingwave/blob/main/java/connector-node/risingwave-source-cdc/src/main/java/com/risingwave/connector/cdc/debezium/converters/DatetimeTypeConverter.java) to manually handle those temporal data types.

It sounds reasonable to parse `Time` (instead of `timestamp`) in microseconds because we got enough bits. 

It sounds like this will be a bug? Did we ever test `time` column for MySQL CDC v1 & v2?

Btw, @StrikeW The approval was lost after you second review. Can you pls approve again?

**Review by StrikeW — APPROVED** [review]

**Comment by StrikeW** [comment]
> It sounds like this will be a bug? Did we ever test time column for MySQL CDC v1 & v2? If it's a bug, let's fix it.

We have done some tests before and have specify the limitation in the doc.

image

**Pull request merged**
