### PR TITLE
feat: support more types for canal json

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

copilot:summary

copilot:walkthrough

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
~~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
~~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by tabVersion** [comment]
resolve #9416

**Review by fuyufjh — APPROVED** [review]
LGTM but need some tests

**Comment by tabVersion** [comment]
> LGTM but need some tests

yes, I am working on some jsonb samples

**Comment by tabVersion** [comment]
kinda strange that TiCDC does not work with `json` type column but leaves no error message.

```sql
create table temp (
    `id` int primary key,
    `json` JSON,
);

insert into temp values (1, '{"a": 1, "b": 2}'), (2, '{"a": 3, "c": 4}');
```

I added the above table to `risingwave/integration_tests/tidb-cdc-sink/tidb_create_tables.sql` and all tables stopped replication. 
may need more time for investigation

**Pull request merged**
