### PR TITLE
perf(bloom filter): replace bloom filter with xor filter

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

same as #7834 

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by lmatz — APPROVED** [review]

**Review by hzxa21 — APPROVED** [review]

**Comment by hzxa21** [comment]
maybe we need this fix: https://github.com/risingwavelabs/risingwave/pull/8036

**Comment by soundOfDestiny** [comment]
> maybe we need this fix: #8036

I found that several minutes ago 😢

**Comment by soundOfDestiny** [comment]
> maybe we need this fix: #8036

I also found that several minutes ago 😢

**Comment by hzxa21** [comment]
@lmatz Seems like we cannot merge to the rc branch via the normal pipeline. Do we need to manually push to the rc branch?

**Comment by lmatz** [comment]
> @lmatz Seems like we cannot merge to the rc branch via the normal pipeline. Do we need to manually push to the rc branch?

It should be able to merge instead of manually pushing to the rc branch. For the recent several branches, we did merge. Not sure what has been changed.

If it really cannot, let's merge it (bypass branch protections). 👌

**Comment by soundOfDestiny** [comment]
> > @lmatz Seems like we cannot merge to the rc branch via the normal pipeline. Do we need to manually push to the rc branch?
> 
> It should be able to merge instead of manually pushing to the rc branch. For the recent several branches, we did merge. Not sure what has been changed.
> 
> If it really cannot, let's merge it (bypass branch protections). 👌

license header check freezes 😢 (that in main branch does not freeze)

**Comment by lmatz** [comment]
I see, thanks for pointing it out, 
no worries, I will keep an eye on it

**Comment by lmatz** [comment]
As the iceberg sink test cannot finish due to too much time spent on downloading, let's merge this first. It should have nothing to do with the sink.

**Comment by soundOfDestiny** [comment]
c.c. @sumittal Tests on release-v0.1.17 should include this recent PR. I feel very sorry to bring you inconvenience.

**Pull request merged**
