### PR TITLE
feat(parser): use PROCTIME() instead of NOW() for the process time temporal join

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Since we have already supported `PROCTIME()`, we can use it to represent the `NOW()` of the process time temporal join syntax. This syntax makes more sense. `NOW()` will be kept for backward compatibility.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [ ] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- SQL commands, functions, and operators

### Release note

- Use `FOR SYSTEM_TIME AS OF PROCTIME()` instead of `FOR SYSTEM_TIME AS OF NOW()` to represent the process time temporal join.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
`PROCTIME()` is still ambigious insude a SQL query. It's hard to tell when exactly an expression is executed. For example, `select proctime() from a,b where a.k=b.k`, the `proctime()` here can be either evaluated before or after `join`, which result in different timestamp. Thus, I always recommend to use `PROCTIME()` only in Source. (cc. @yuhao-su )

For this case, I think Flink's syntax is the most clear one: `FOR SYSTEM_TIME AS OF table1.proctime` where `table1.proctime` refers to a column defined in Source. 

Actually either `FOR SYSTEM_TIME AS OF NOW()` or `FOR SYSTEM_TIME AS OF PROCTIME()` looks good to me, but I can't say the later one is better than the previous one.

**Review by fuyufjh — APPROVED** [review]

**Comment by yuhao-su** [comment]
> For example, select proctime() from a,b where a.k=b.k, the proctime() here can be either evaluated before or after join.

Agree.

**Comment by yuhao-su** [comment]
Flink allow this query
```sql
SELECT
    B.bidder,
    count(*) as bid_count,
    TUMBLE_START(B.p_time, INTERVAL '10' SECOND) as starttime,
    TUMBLE_END(B.p_time, INTERVAL '10' SECOND) as endtime
FROM (SELECT *, PROCTIME() as p_time FROM bid) B
```

It add a `proctime()` column to the `bid` source

**Comment by chenzl25** [comment]
> I think `PROCTIME()` is still ambigious inside a SQL query. It's hard to tell when exactly an expression is executed. For example, `select proctime() from a,b where a.k=b.k`, the `proctime()` here can be either evaluated before or after `join`, which result in different timestamp. Thus, I always recommend to use `PROCTIME()` only in Source. (cc. @yuhao-su )
> 
> 
> 
> For this case, I think Flink's syntax is the most clear one: `FOR SYSTEM_TIME AS OF table1.proctime` where `table1.proctime` refers to a column defined in Source. 
> 
> 
> 
> Actually either `FOR SYSTEM_TIME AS OF NOW()` or `FOR SYSTEM_TIME AS OF PROCTIME()` looks good to me, but I can't say the later one is better than the previous one.

If we consider it as a batch query we can see the differences. For system_time as of now() should be same as regular join.

**Comment by fuyufjh** [comment]
> If we consider it as a batch query we can see the differences. For system_time as of now() should be same as regular join.

Yes, right. `PROCTIME()` sounds better than `now()` in this case.

**Pull request merged**
