### PR TITLE
chore: bump `tonic` to v0.12

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

See https://github.com/risingwavelabs/risingwave/issues/13695.

This PR bumps `tonic` to v0.12, `prost` to 0.13, `http` and `hyper` to v1 in relevant modules. There are still indirect dependencies on `tonic` v0.10 and v0.11 due to external dependencies, as described in the issue. Mark them with `TODO(http-bump)` and leave them to future work.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by fuyufjh — APPROVED** [review]
There seems no logic changes. LGTM as long as the tests can pass

**Comment by BugenZhao** [comment]
Currently blocked due to a panic in simulation test. See #17920.

**Comment by wenym1** [comment]
The previous panic should have been fixed in https://github.com/risingwavelabs/risingwave/pull/17955

**Comment by BugenZhao** [comment]
e2e-sink-test now consistently hangs here:

https://github.com/risingwavelabs/risingwave/blob/8d8c1360ce36ca919a7f784ed5fe1a4fac9bbb41/e2e_test/sink/kafka/avro.slt#L189-L196

I find that by disabling `SCHEMA_REGISTRY_DEBUG` here, this issue is gone.

https://github.com/risingwavelabs/risingwave/blob/8d8c1360ce36ca919a7f784ed5fe1a4fac9bbb41/ci/docker-compose.yml#L269

The only difference is that there won't be backtraces from the schema registry in the error message.

```diff
failed to validate sink: config error: all request confluent registry all timeout, req path ["subjects", "test-rw-sink-upsert-avro-err-key", "versions", "latest"], urls http://schemaregistry:8082/
	confluent schema registry error 40401: Subject 'test-rw-sink-upsert-avro-err-key' not found. io.confluent.rest.exceptions.RestNotFoundException: Subject 'test-rw-sink-upsert-avro-err-key' not found.
- io.confluent.rest.exceptions.RestNotFoundException: Subject 'test-rw-sink-upsert-avro-err-key' not found.
-	at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.subjectNotFoundException(Errors.java:78)
-	at io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource.getSchemaByVersion(SubjectVersionsResource.java:154)
-	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
```

Following this insight, I suppose it's because we always encode the `ServerError` in gRPC (HTTP2) headers (#13282), and there's an outstanding issue where `tonic 0.12` will hang forever when the header size exceeds some limit.

https://github.com/risingwavelabs/risingwave/blob/8d8c1360ce36ca919a7f784ed5fe1a4fac9bbb41/src/error/src/tonic.rs#L68-L71

Upstream issues:
- https://github.com/hyperium/tonic/issues/1834
- https://github.com/hyperium/hyper/issues/3724

**Pull request merged**
