### PR TITLE
feat(metrics): add upstream fragment id in `actor_in_record_cnt`

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

As title.

Due to #13948, use `GenericCounterVec` instead of `LabelGuardedIntCounterVec` for now.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

### CODE REVIEW

**Comment by wenym1** [comment]
I seem to know the cause of https://github.com/risingwavelabs/risingwave/issues/13948. 

Here we use `with_label_values` in each time we report the metrics, in which case the value returned from `with_label_values` is dropped immediately. From the view of label guarded metrics, the label is dropped immediately and will not be used as label. After the metric is collected, the counter will be deleted because the label is not used anymore. The counter is recreated in our next time of calling `with_label_values` to report the count.

The recommended way to is call `with_label_values` at the beginning of the stream and save the return metric variable, and later when we report the metrics, we use the saved variable instead of calling with_label_values every time. This is also recommended for the raw GenericCounterVec, because there is a lock in the GenericCounterVec, and each time we call with_label_values on it, we need to acquire the lock, which may affect the performance.

**Comment by fuyufjh** [comment]
> I seem to know the cause of #13948.
> 
> Here we use `with_label_values` in each time we report the metrics, in which case the value returned from `with_label_values` is dropped immediately. From the view of label guarded metrics, the label is dropped immediately and will not be used as label. After the metric is collected, the counter will be deleted because the label is not used anymore. The counter is recreated in our next time of calling `with_label_values` to report the count.
> 
> The recommended way to is call `with_label_values` at the beginning of the stream and save the return metric variable, and later when we report the metrics, we use the saved variable instead of calling with_label_values every time. This is also recommended for the raw GenericCounterVec, because there is a lock in the GenericCounterVec, and each time we call with_label_values on it, we need to acquire the lock, which may affect the performance.


Oh, that makes sense! Thanks for the explanation!


I just randomly checked several other usages of `with_label_values` in streaming module, and none of them follow the "recommended way" 🤣 Let's open a separated issue and fix them step by step.


`> risingwave/src/stream $ ag -C with_label_values`

<details>




```
67-            .metrics
68-            .stream_memory_usage
69:            .with_label_values(&[
70-                &metrics_info.table_id,
71-                &metrics_info.actor_id,
--
77-            .metrics
78-            .lru_evicted_watermark_time_ms
79:            .with_label_values(&[
80-                &metrics_info.table_id,
81-                &metrics_info.actor_id,

src/common/log_store_impl/kv_log_store/mod.rs
80-        let executor_id = format!("{}", writer_param.executor_id);
81-        let sink_id = format!("{}", sink_param.sink_id.sink_id);
82:        let storage_write_size = metrics.kv_log_store_storage_write_size.with_label_values(&[
83-            executor_id.as_str(),
84-            connector,
--
87-        let storage_write_count = metrics
88-            .kv_log_store_storage_write_count
89:            .with_label_values(&[executor_id.as_str(), connector, sink_id.as_str()]);
90-
91-        const READ_PERSISTENT_LOG: &str = "persistent_log";
92-        const READ_FLUSHED_BUFFER: &str = "flushed_buffer";
93-
94:        let persistent_log_read_size = metrics.kv_log_store_storage_read_size.with_label_values(&[
95-            executor_id.as_str(),
96-            connector,
--
99-        ]);
100-        let persistent_log_read_count =
101:            metrics.kv_log_store_storage_read_count.with_label_values(&[
102-                executor_id.as_str(),
103-                connector,
--
106-            ]);
107-
108:        let flushed_buffer_read_size = metrics.kv_log_store_storage_read_size.with_label_values(&[
109-            executor_id.as_str(),
110-            connector,
--
113-        ]);
114-        let flushed_buffer_read_count =
115:            metrics.kv_log_store_storage_read_count.with_label_values(&[
116-                executor_id.as_str(),
117-                connector,

src/task/stream_manager.rs
727-                            metrics
728-                                .actor_memory_usage
729:                                .with_label_values(&[&actor_id_str, &fragment_id_str])
730-                                .set(bytes as i64);
731-
--
751-                        metrics
752-                            .actor_execution_time
753:                            .with_label_values(&[&actor_id_str])
754-                            .set(task_metrics.total_poll_duration.as_secs_f64());
755-                        metrics
756-                            .actor_fast_poll_duration
757:                            .with_label_values(&[&actor_id_str])
758-                            .set(task_metrics.total_fast_poll_duration.as_secs_f64());
759-                        metrics
760-                            .actor_fast_poll_cnt
761:                            .with_label_values(&[&actor_id_str])
762-                            .set(task_metrics.total_fast_poll_count as i64);
763-                        metrics
764-                            .actor_slow_poll_duration
765:                            .with_label_values(&[&actor_id_str])
766-                            .set(task_metrics.total_slow_poll_duration.as_secs_f64());
767-                        metrics
768-                            .actor_slow_poll_cnt
769:                            .with_label_values(&[&actor_id_str])
770-                            .set(task_metrics.total_slow_poll_count as i64);
771-                        metrics
772-                            .actor_poll_duration
773:                            .with_label_values(&[&actor_id_str])
774-                            .set(task_metrics.total_poll_duration.as_secs_f64());
775-                        metrics
776-                            .actor_poll_cnt
777:                            .with_label_values(&[&actor_id_str])
778-                            .set(task_metrics.total_poll_count as i64);
779-                        metrics
780-                            .actor_idle_duration
781:                            .with_label_values(&[&actor_id_str])
782-                            .set(task_metrics.total_idle_duration.as_secs_f64());
783-                        metrics
784-                            .actor_idle_cnt
785:                            .with_label_values(&[&actor_id_str])
786-                            .set(task_metrics.total_idled_count as i64);
787-                        metrics
788-                            .actor_scheduled_duration
789:                            .with_label_values(&[&actor_id_str])
790-                            .set(task_metrics.total_scheduled_duration.as_secs_f64());
791-                        metrics
792-                            .actor_scheduled_cnt
793:                            .with_label_values(&[&actor_id_str])
794-                            .set(task_metrics.total_scheduled_count as i64);
795-                        tokio::time::sleep(Duration::from_secs(1)).await;

src/executor/aggregation/distinct.rs
87-                .metrics
88-                .agg_distinct_total_cache_count
89:                .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
90-                .inc();
91-            // TODO(yuhao): avoid this `contains`.
--
97-                    .metrics
98-                    .agg_distinct_cache_miss_count
99:                    .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
100-                    .inc();
101-                // load from table into the cache
--
197-            .metrics
198-            .agg_distinct_cached_entry_count
199:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
200-            .set(self.cache.len() as i64);
201-        self.cache.evict();

src/executor/receiver.rs
123-                self.metrics
124-                    .actor_input_buffer_blocking_duration_ns
125:                    .with_label_values(&[
126-                        &actor_id_str,
127-                        &fragment_id_str,
--
138-                        self.metrics
139-                            .actor_in_record_cnt
140:                            .with_label_values(&[
141-                                &actor_id_str,
142-                                &fragment_id_str,

src/executor/exchange/input.rs
166-                    metrics
167-                        .exchange_frag_recv_size
168:                        .with_label_values(&[&up_fragment_id, &down_fragment_id])
169-                        .inc_by(bytes as u64);
170-

src/executor/dispatch.rs
70-                        self.metrics
71-                            .actor_output_buffer_blocking_duration_ns
72:                            .with_label_values(&[
73-                                &self.actor_id_str,
74-                                &self.fragment_id_str,
--
88-                        self.metrics
89-                            .actor_output_buffer_blocking_duration_ns
90:                            .with_label_values(&[
91-                                &self.actor_id_str,
92-                                &self.fragment_id_str,
--
100-                self.metrics
101-                    .actor_out_record_cnt
102:                    .with_label_values(&[&self.actor_id_str, &self.fragment_id_str])
103-                    .inc_by(chunk.cardinality() as _);
104-            }
--
114-                        self.metrics
115-                            .actor_output_buffer_blocking_duration_ns
116:                            .with_label_values(&[
117-                                &self.actor_id_str,
118-                                &self.fragment_id_str,

src/executor/monitor/streaming_stats.rs
1049-    ) -> SinkMetrics {
1050-        let label_list = [identity, connector, sink_id_str];
1051:        let sink_commit_duration_metrics = self.sink_commit_duration.with_label_values(&label_list);
1052-        let connector_sink_rows_received = self
1053-            .connector_sink_rows_received
1054:            .with_label_values(&[connector, sink_id_str]);
1055-
1056-        let log_store_latest_read_epoch = self
1057-            .log_store_latest_read_epoch
1058:            .with_label_values(&label_list);
1059-
1060-        let log_store_latest_write_epoch = self
1061-            .log_store_latest_write_epoch
1062:            .with_label_values(&label_list);
1063-
1064-        let log_store_first_write_epoch = self
1065-            .log_store_first_write_epoch
1066:            .with_label_values(&label_list);
1067-
1068:        let log_store_write_rows = self.log_store_write_rows.with_label_values(&label_list);
1069:        let log_store_read_rows = self.log_store_read_rows.with_label_values(&label_list);
1070-
1071-        let label_list = [identity, sink_id_str];
1072-        let iceberg_file_appender_write_qps = self
1073-            .iceberg_file_appender_write_qps
1074:            .with_label_values(&label_list);
1075-        let iceberg_file_appender_write_latency = self
1076-            .iceberg_file_appender_write_latency
1077:            .with_label_values(&label_list);
1078-
1079-        SinkMetrics {

src/executor/wrapper/trace.rs
57-                            .streaming_metrics
58-                            .executor_row_count
59:                            .with_label_values(&[&actor_id_str, &fragment_id_str, &info.identity])
60-                            .inc_by(chunk.cardinality() as u64);
61-                    }

src/executor/sink.rs
211-                            .streaming_metrics
212-                            .sink_input_row_count
213:                            .with_label_values(&[&sink_id_str, &actor_id_str, &fragment_id_str])
214-                            .inc_by(c.capacity() as u64);
215-
--
270-                            .streaming_metrics
271-                            .sink_input_row_count
272:                            .with_label_values(&[&sink_id_str, &actor_id_str, &fragment_id_str])
273-                            .inc_by(chunk.capacity() as u64);
274-

src/executor/source/source_executor.rs
140-        self.metrics
141-            .source_split_change_count
142:            .with_label_values(
143-                &self
144-                    .get_metric_labels()
--
522-                                self.metrics
523-                                    .source_row_per_barrier
524:                                    .with_label_values(&[
525-                                        self.actor_ctx.id.to_string().as_str(),
526-                                        self.stream_source_core
--
599-                            self.metrics
600-                                .source_output_row_count
601:                                .with_label_values(
602-                                    &self
603-                                        .get_metric_labels()

src/executor/source/fs_source_executor.rs
392-                        self.metrics
393-                            .source_row_per_barrier
394:                            .with_label_values(&[
395-                                self.actor_ctx.id.to_string().as_str(),
396-                                self.stream_source_core.source_id.to_string().as_ref(),
--
445-                    self.metrics
446-                        .source_output_row_count
447:                        .with_label_values(&[
448-                            self.stream_source_core.source_id.to_string().as_ref(),
449-                            self.stream_source_core.source_name.as_ref(),

src/executor/barrier_align.rs
110-                            metrics
111-                                .join_barrier_align_duration
112:                                .with_label_values(&[&actor_id, &fragment_id, "right"])
113-                                .observe(start_time.elapsed().as_secs_f64());
114-                            break;
--
136-                            metrics
137-                                .join_barrier_align_duration
138:                                .with_label_values(&[&actor_id, &fragment_id, "left"])
139-                                .observe(start_time.elapsed().as_secs_f64());
140-                            break;

src/executor/lookup/impl_.rs
357-            .streaming_metrics
358-            .lookup_total_query_cache_count
359:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
360-            .inc();
361-        if let Some(result) = self.lookup_cache.lookup(&lookup_row) {
--
367-            .streaming_metrics
368-            .lookup_cache_miss_count
369:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
370-            .inc();
371-
--
416-            .streaming_metrics
417-            .lookup_cached_entry_count
418:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
419-            .set(self.lookup_cache.len() as i64);
420-

src/executor/merge.rs
120-            self.metrics
121-                .actor_input_buffer_blocking_duration_ns
122:                .with_label_values(&[&actor_id_str, &fragment_id_str, &upstream_fragment_id_str])
123-                .inc_by(start_time.elapsed().as_nanos() as u64);
124-            let mut msg: Message = msg?;
--
131-                    self.metrics
132-                        .actor_in_record_cnt
133:                        .with_label_values(&[
134-                            &actor_id_str,
135-                            &fragment_id_str,

src/executor/over_window/general.rs
606-                        this.metrics
607-                            .over_window_cached_entry_count
608:                            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
609-                            .set(vars.cached_partitions.len() as _);
610-                        this.metrics
611-                            .over_window_cache_lookup_count
612:                            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
613-                            .inc_by(std::mem::take(&mut vars.stats.cache_lookup));
614-                        this.metrics
615-                            .over_window_cache_miss_count
616:                            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
617-                            .inc_by(std::mem::take(&mut vars.stats.cache_miss));
618-                    }

src/executor/backfill/cdc/cdc_backfill.rs
269-                                    self.metrics
270-                                        .cdc_backfill_snapshot_read_row_count
271:                                        .with_label_values(&[
272-                                            upstream_table_id.to_string().as_str(),
273-                                            self.actor_ctx.id.to_string().as_str(),
--
277-                                    self.metrics
278-                                        .cdc_backfill_upstream_output_row_count
279:                                        .with_label_values(&[
280-                                            upstream_table_id.to_string().as_str(),
281-                                            self.actor_ctx.id.to_string().as_str(),

src/executor/managed_state/join/mod.rs
199-        self.metrics
200-            .join_lookup_total_count
201:            .with_label_values(&[
202-                (self.side),
203-                &self.join_table_id,
--
209-        self.metrics
210-            .join_lookup_miss_count
211:            .with_label_values(&[
212-                (self.side),
213-                &self.join_table_id,
--
219-        self.metrics
220-            .join_insert_cache_miss_count
221:            .with_label_values(&[
222-                (self.side),
223-                &self.join_table_id,

src/executor/backfill/arrangement_backfill.rs
401-                self.metrics
402-                    .arrangement_backfill_snapshot_read_row_count
403:                    .with_label_values(&[
404-                        upstream_table_id.to_string().as_str(),
405-                        self.actor_id.to_string().as_str(),
--
409-                self.metrics
410-                    .arrangement_backfill_upstream_output_row_count
411:                    .with_label_values(&[
412-                        upstream_table_id.to_string().as_str(),
413-                        self.actor_id.to_string().as_str(),

src/executor/top_n/group_top_n.rs
181-                .streaming_metrics
182-                .group_top_n_total_query_cache_count
183:                .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
184-                .inc();
185-            // If 'self.caches' does not already have a cache for the current group, create a new
--
189-                    .streaming_metrics
190-                    .group_top_n_cache_miss_count
191:                    .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
192-                    .inc();
193-                let mut topn_cache =
--
226-            .streaming_metrics
227-            .group_top_n_cached_entry_count
228:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
229-            .set(self.caches.len() as i64);
230-        generate_output(res_rows, res_ops, &self.info().schema)

src/executor/top_n/group_top_n_appendonly.rs
179-                .streaming_metrics
180-                .group_top_n_appendonly_total_query_cache_count
181:                .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
182-                .inc();
183-            // If 'self.caches' does not already have a cache for the current group, create a new
--
187-                    .streaming_metrics
188-                    .group_top_n_appendonly_cache_miss_count
189:                    .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
190-                    .inc();
191-                let mut topn_cache = TopNCache::new(self.offset, self.limit, data_types.clone());
--
210-            .streaming_metrics
211-            .group_top_n_appendonly_cached_entry_count
212:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
213-            .set(self.caches.len() as i64);
214-        generate_output(res_rows, res_ops, &self.info().schema)

src/executor/backfill/no_shuffle_backfill.rs
404-                self.metrics
405-                    .backfill_snapshot_read_row_count
406:                    .with_label_values(&[
407-                        upstream_table_id.to_string().as_str(),
408-                        self.actor_id.to_string().as_str(),
--
412-                self.metrics
413-                    .backfill_upstream_output_row_count
414:                    .with_label_values(&[
415-                        upstream_table_id.to_string().as_str(),
416-                        self.actor_id.to_string().as_str(),

src/executor/temporal_join.rs
158-            .streaming_metrics
159-            .temporal_join_total_query_cache_count
160:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
161-            .inc();
162-
--
169-                .streaming_metrics
170-                .temporal_join_cache_miss_count
171:                .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
172-                .inc();
173-
--
412-                .streaming_metrics
413-                .temporal_join_cached_entry_count
414:                .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
415-                .set(self.right_table.cache.len() as i64);
416-            match msg? {

src/executor/mview/materialize.rs
138-                        .streaming_metrics
139-                        .mview_input_row_count
140:                        .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
141-                        .inc_by(chunk.cardinality() as u64);
142-
--
550-                .metrics
551-                .materialize_cache_total_count
552:                .with_label_values(&[&self.metrics_info.table_id, &self.metrics_info.actor_id])
553-                .inc();
554-            if self.data.contains(key) {
--
556-                    .metrics
557-                    .materialize_cache_hit_count
558:                    .with_label_values(&[&self.metrics_info.table_id, &self.metrics_info.actor_id])
559-                    .inc();
560-                continue;

src/executor/hash_join.rs
703-            self.metrics
704-                .join_actor_input_waiting_duration_ns
705:                .with_label_values(&[&actor_id_str, &fragment_id_str])
706-                .inc_by(start_time.elapsed().as_nanos() as u64);
707-            match msg? {
--
743-                    self.metrics
744-                        .join_match_duration_ns
745:                        .with_label_values(&[&actor_id_str, &fragment_id_str, "left"])
746-                        .inc_by(left_time.as_nanos() as u64);
747-                    self.try_flush_data().await?;
--
770-                    self.metrics
771-                        .join_match_duration_ns
772:                        .with_label_values(&[&actor_id_str, &fragment_id_str, "right"])
773-                        .inc_by(right_time.as_nanos() as u64);
774-                    self.try_flush_data().await?;
--
797-                        self.metrics
798-                            .join_cached_entry_count
799:                            .with_label_values(&[&actor_id_str, &fragment_id_str, side])
800-                            .set(ht.entry_count() as i64);
801-                    }
--
803-                    self.metrics
804-                        .join_match_duration_ns
805:                        .with_label_values(&[&actor_id_str, &fragment_id_str, "barrier"])
806-                        .inc_by(barrier_start_time.elapsed().as_nanos() as u64);
807-                    yield Message::Barrier(barrier);
--
1012-            .streaming_metrics
1013-            .join_matched_join_keys
1014:            .with_label_values(&[
1015-                &ctx.id.to_string(),
1016-                &ctx.fragment_id.to_string(),

src/executor/hash_agg.rs
426-        this.metrics
427-            .agg_dirty_groups_count
428:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
429-            .set(vars.dirty_groups.len() as i64);
430-        this.metrics
431-            .agg_dirty_groups_heap_size
432:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
433-            .set(vars.dirty_groups.estimated_heap_size() as i64);
434-
--
540-        this.metrics
541-            .agg_lookup_miss_count
542:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
543-            .inc_by(std::mem::take(&mut vars.stats.lookup_miss_count));
544-        this.metrics
545-            .agg_total_lookup_count
546:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
547-            .inc_by(std::mem::take(&mut vars.stats.total_lookup_count));
548-        this.metrics
549-            .agg_cached_entry_count
550:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
551-            .set(vars.agg_group_cache.len() as i64);
552-        this.metrics
553-            .agg_chunk_lookup_miss_count
554:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
555-            .inc_by(std::mem::take(&mut vars.stats.chunk_lookup_miss_count));
556-        this.metrics
557-            .agg_chunk_total_lookup_count
558:            .with_label_values(&[&table_id_str, &actor_id_str, &fragment_id_str])
559-            .inc_by(std::mem::take(&mut vars.stats.chunk_total_lookup_count));
560-    }
```

</details>

**Comment by fuyufjh** [comment]
Let's review this first? @wenym1 This PR is totally independent with #13948.

**Comment by wenym1** [comment]
> Let's review this first?

I just pushed a commit https://github.com/risingwavelabs/risingwave/commit/d1fedcb1e5c61c7ac974bfb6c1e3206a22cdaea4 in my own branch [yiming/add_target_source_to_actor_input_output_rows](https://github.com/risingwavelabs/risingwave/compare/yiming/add_target_source_to_actor_input_output_rows) to apply the recommended way to report the metrics modified in this PR. The two metrics in this PR can still use the label guarded counter to prevent label leak after actors are dropped. 

If it looks good we can rebase this branch on my branch and get it merged.

**Review by wenym1 — APPROVED** [review]
Sad about it🥵

Let's get the current PR merged first. I will investigate the cause later.

**Pull request merged**
