### PR TITLE
test(source): add csv format test for Kafka

### LINKED ISSUE #9858: feat: support CSV format for Kafka source
### Is your feature request related to a problem? Please describe.

As requested from the community:
https://github.com/risingwavelabs/risingwave/discussions/9849#discussion-5201761

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #9858 

## Checklist For Contributors

~- [ ] I have written necessary rustdoc comments~
~- [ ] I have added necessary unit tests and integration tests~
~- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~
~- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Connector (sources & sinks)

### Release note

</details>

### CODE REVIEW

**Comment by lmatz** [comment]
But I don't know how we should deal with the "header"

**Review by tabVersion — APPROVED** [review]

**Review by idx0-dev — APPROVED** [review]

**Comment by idx0-dev** [comment]
> But I don't know how we should deal with the "header"

I suggest not support headers in kafka csv.

**Comment by lmatz** [comment]
> > But I don't know how we should deal with the "header"
> 
> I suggest not support headers in kafka csv.

Sure, let me disable it in the frontend and pop a proper error message.

**Comment by CharlieSYH** [comment]
Is this an experimental feature? Is it ready to be documented in 0.19.0? @lmatz

**Pull request merged**
