### PR TITLE
chore: add a docker compose file for standalone mode

### LINKED ISSUE #12538: Use standalone mode in docker-compose.yml
### Is your feature request related to a problem? Please describe.

As title. This makes it more compact and light-weighted.

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

add a docker-compose file for standalone mode. Will update the docs.

resolve #12538 

## Documentation

- [x] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by fuyufjh — APPROVED** [review]
LGTM

Actually, I think we can go one step further and use standalone mode in Docker by default. That is, instead of adding a new `docker-compose-standalone.yaml`, I think we can place the existing `docker-compose.yaml`, because that a user preferring docker-compose than k8s must want to deploy RW in a single machine.

But this may involve some modifications to test pipeline as well. Since the v1.4 is coming soon, we may do it later.

**Review by kwannoel — APPROVED** [review]

**Comment by kwannoel** [comment]
Thanks!

**Comment by hengm3467** [comment]
> LGTM
> 
> Actually, I think we can go one step further and use standalone mode in Docker by default. That is, instead of adding a new `docker-compose-standalone.yaml`, I think we can place the existing `docker-compose.yaml`, because that a user preferring docker-compose than k8s must want to deploy RW in a single machine.
> 
> But this may involve some modifications to test pipeline as well. Since the v1.4 is coming soon, we may do it later.

@lmatz Was this PR included in v1.4? I don't see it in the comparison list (1.3-rc - 1.4-rc). And I assume using the standalone mode in Docker by default is not done yet. Correct? Thanks.

**Comment by lmatz** [comment]
> > LGTM
> > Actually, I think we can go one step further and use standalone mode in Docker by default. That is, instead of adding a new `docker-compose-standalone.yaml`, I think we can place the existing `docker-compose.yaml`, because that a user preferring docker-compose than k8s must want to deploy RW in a single machine.
> > But this may involve some modifications to test pipeline as well. Since the v1.4 is coming soon, we may do it later.
> 
> @lmatz Was this PR included in v1.4? I don't see it in the comparison list (1.3-rc - 1.4-rc). And I assume using the standalone mode in Docker by default is not done yet. Correct? Thanks.

Hi @hengm3467,
It is not ready yet, and not included in v1.4. The default deployment of `docker compose` is still non-standalone mode.

We will need to do some tests first, details in
https://github.com/risingwavelabs/risingwave-docs/issues/1187

**Pull request merged**
