### PR TITLE
perf(stream): add simple strategy for if the stream project compact the chunk

### PR DESCRIPTION
**Pull request by st1page**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

              I mean for q0, there can be no compact at all. The existing compact is done in the first project right after the filter, taking 10% of the flame graph.

_Originally posted by @lmatz in https://github.com/risingwavelabs/risingwave/issues/8742#issuecomment-1482308867_
            
https://github.com/risingwavelabs/risingwave/issues/8712

add some very simple strategy to not compact the chunk all the time.
I introduce a magic `materialize_selectivity_threshold` in this PR, but I do **NOT** think we should do any fine-tuning on the parameter now.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by lmatz** [comment]
Good 👍 

For q0, no compaction is strictly better as long as the sink can iterate through all the visible rows only.
This is a general case where an uncompacted chunk is going to be output directly. That's why I was considering doing it in the frontend.

**Comment by st1page** [comment]
> Good +1
> 
> For q0, no compaction is strictly better as long as the sink can iterate through all the visible rows only. This is a general case where an uncompacted chunk is going to be output directly. That's why I was considering doing it in the frontend.

If our frontend can do more analysis, we can expose this `materialize_selectivity_threshold` to the frontend in the project's plan proto. If the optimizer can analyze the cost of the expressions, it even can calculate a specific `threshold`. But I think these optimizations are too early for us

**Review by lmatz — APPROVED** [review]

**Comment by BugenZhao** [comment]
It's worth noting that there's still `compact` before sinking the chunk, even for `Blackhole`. 🤣 Seems nonsense here.

https://github.com/risingwavelabs/risingwave/blob/1c6b2465e6848deddfb4490e09de757df00defc2/src/stream/src/executor/sink.rs#L120-L128

**Comment by st1page** [comment]
> It's worth noting that there's still compact before sinking the chunk, even for Blackhole. rofl Seems nonsense here.

We need to do further optimization for it. actually, I think the visibility should be handled when serializing. c.c @lmatz

**Pull request merged**
