### PR TITLE
feat(stream): support non-append-only  process time temporal join

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Resolve https://github.com/risingwavelabs/risingwave/issues/15218
- Support non-append-only process time temporal join which will introduce a state called  `memo_table` to the temporal join.
- `memo_table`'s pk is `join_key` + `left_pk` + `right_pk`. And its columns are almost the same as the right table.
-  Write pattern:
    for each left input row (with insert op), construct the memo table pk and insert the row.
    Read pattern:
    for each left input row (with delete op), construct pk prefix (`join_key` + `left_pk`) to fetch rows.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

- Support non-append-only temporal join, that is the outer side of the temporal join doesn't require to be append-only anymore.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
This looks good.

Correct me if I'm wrong: we face the exactly same issue with indeterministic UDFs. Is it possible to make the memoization(materialization) into a separate operator? So that we can reuse it for these similar cases.

**Comment by TennyZhuang** [comment]
> we face the exactly same issue with indeterministic UDFs. Is it possible to make the memoization(materialization) into a separate operator

There should be an abstraction for the logic, but IMO it shouldn’t be a separate operator.

**Comment by chenzl25** [comment]
> This looks good.
> 
> Correct me if I'm wrong: we face the exactly same issue with indeterministic UDFs. Is it possible to make the memoization(materialization) into a separate operator? So that we can reuse it for these similar cases.

Even though deterministic UDFs also need a memo table, I don't think we can use a shared operator to handle both cases. Because the memo table access pattern and the way how to reconstruct rows from the memo table are totally different.

**Comment by BugenZhao** [comment]
> Because the memo table access pattern and the way how to reconstruct rows from the memo table are totally different.

You're right. I was solely focused on using temporal join for point-lookup. 😄

**Review by st1page — APPROVED** [review]
LGTM, maybe we can notice user their will be a memo table state for non-append-only temporal join to prevent silently generating a stream plan with bad performance.(One case I can come up with is https://github.com/risingwavelabs/risingwave/pull/13549)

**Pull request merged**
