### PR TITLE
feat(expr): add `_pg_expandarray` function

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Added a new table function `_pg_expandarray`.

fix https://github.com/risingwavelabs/risingwave/issues/12204

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [x] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

Add a new table function:
```
_pg_expandarray(array anyarray) → record(x anyelement, n int)
```
Returns the input array as a set of rows with an index.

### CODE REVIEW

**Comment by wangrunji0408** [comment]
Is there a way to ignore the lint?
```
expr.proto:250:5:Enum value name "_PG_EXPANDARRAY" should be UPPER_SNAKE_CASE, such as "PG_EXPANDARRAY".
```

**Review by TennyZhuang — APPROVED** [review]
LGTM
It seems that `buf lint` does not support fine-grained ignoring. The only way is to name it as PG_EXPANDARRAY and rewrite it in the frontend.

**Comment by TennyZhuang** [comment]
I found this.

https://buf.build/docs/lint/overview#ignore_only

**Comment by TennyZhuang** [comment]
Will https://buf.build/docs/lint/overview#allow_comment_ignores be better?

**Pull request merged**
