### PR TITLE
test(streaming): make epoch.inc works in tests

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Currently, many of our usage on `Epoch` in test uses `epoch.inc()`, for which we intend to advance the epoch to the next one. However, `epoch.inc()` will not touch the original `epoch`, but rather create a new epoch, which we didn't use in most tests, so in most streaming unit tests, the `epoch` is not changed, and many corner cases cannot be tested. 

In this PR, we change to update the `epoch` when `epoch.inc()` is called. And the `commit_for_test` in state table, which bypass the epoch sanity check, is removed.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Review by wcy-fdu — APPROVED** [review]
This PR is all unit test changes, LGTM!

**Review by wcy-fdu — APPROVED** [review]
This PR is all unit test changes, LGTM!

**Comment by BugenZhao** [comment]
> However, epoch.inc() will not touch the original epoch, but rather create a new epoch, which we didn't use in most tests

For this case, we'd better have a `#[must_use]` attribute on `inc`.

**Comment by wenym1** [comment]
> For this case, we'd better have a #[must_use] attribute on inc.

Since `epoch.inc()` has the semantic of in place update, I have made the `inc` method to return void.

**Pull request merged**
