### PR TITLE
feat(streaming): limit concurrent barriers in exchange based on permits

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Proposed by @fuyufjh: we can limit the overall barrier latency to a bounded value by limiting the number of concurrent barriers in an exchange channel. In this PR, we add a separate category of permits (`barriers`) to achieve this.

The reason why the barrier latency is related to the back-pressure mechanism has been explained in #8654. In some sense, this PR is a more deterministic way to reduce the barrier latency.

Benchmarked [here](https://buildkite.com/risingwave-test/nexmark-benchmark/builds/881) and no regression found.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

### CODE REVIEW

**Review by fuyufjh — APPROVED** [review]
LGTM!

**Review by lmatz — APPROVED** [review]

**Comment by BugenZhao** [comment]
> Is this protobuf breaking-change check necessary? This message type is purely internal and used at runtime 🤔 

I believe we can safely ignore it.

**Comment by lmatz** [comment]
> > Is this protobuf breaking-change check necessary? This message type is purely internal and used at runtime 🤔
> 
> I believe we can safely ignore it.

Oh, I thought this check prevents the PR from being merged

**Comment by BugenZhao** [comment]
> Oh, I thought this check prevents the PR from being merged

It should be a soft failure. The deterministic e2e fails due to timeout (a little bit, which is expected by tweaking the back-pressure).

**Pull request merged**
