### PR TITLE
feat(sink): support new syntax `FORMAT ... ENCODE ...` similar to source

### PR DESCRIPTION
**Pull request by xiangjinwu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

#11451

Old syntax:
```
create sink snk from mv with (
  connector = 'kafka',
  properties.bootstrap.server = 'localhost:9092',
  topic = 'test_topic',
  type = 'append-only');
```
New syntax (similar to source):
```
create sink snk from mv with (
  connector = 'kafka',
  properties.bootstrap.server = 'localhost:9092',
  topic = 'test_topic')
format plain encode json;

create sink snk from mv with (
  connector = 'kafka',
  properties.bootstrap.server = 'localhost:9092',
  topic = 'test_topic')
format upsert encode protobuf (
  schema.location = 'location',
  message = 'main_message');
```

* Updated sqlparser to parse the new syntax.
* Introduce `SinkFormatDesc` in rust and proto to pass around this info.
* Extend `SinkDesc`/`SinkCatalog`/`SinkParam` in rust and `SinkDesc`/`Sink`/`SinkParam` in proto with an extra optional field `format_desc`.
* Replace `SinkType` and `SINK_TYPE_OPTION` with `SinkFormatDesc` in kafka/kinesis/pulsar using `SinkFormatterImpl`.

### Next step
In `SinkFormatterImpl::new`, convert `param.format_desc` to `ProtobufProperties`/`AvroProperties` and reuse `ProtobufParserConfig::new`/`AvroParserConfig::new` to get `prost_reflect::MessageDescriptor`/`apache_avro::Schema` needed by encoders #12425

### Compatibility
* The new syntax is only enabled when `connector` is kafka/kinesis/pulsar. We will test other connectors and migrate them one by one.
* The sqlparser and handler still accepts both syntax. It will derive `SinkFormatDesc` for the old syntax.
* When decoding proto `SinkDesc`/`Sink`/`SinkParam`, `SinkFormatDesc` will also be derived from old syntax.

### Limitations
Some refactor / reuse is possible but not done here to limit the scope:
* In sqlparser, `SourceSchemaV2` is same as `SinkSchema` (easy to rename).
* Common fields in `SinkDesc`/`SinkCatalog`/`SinkParam` may be extracted to a struct.
* `SourceStruct` may be absorbed into `SpecificParserConfig`, then consolidated with `SinkFormatDesc`.
* `SinkType` is similar to `SinkFormat` but cannot be replaced yet:

|SinkType|properties.get(SINK_TYPE_OPTION)|SinkFormat|
|-|-|-|
|AppendOnly|SINK_TYPE_APPEND_ONLY|AppendOnly|
|**_ForceAppendOnly_**|SINK_TYPE_APPEND_ONLY|AppendOnly|
|Upsert|SINK_TYPE_UPSERT|Upsert|
|**_Upsert_**|SINK_TYPE_DEBEZIUM|Debezium|

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [x] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

For kafka/kinesis/pulsar sink, the preferred syntax is now `FORMAT [PLAIN | UPSERT | DEBEZIUM] ENCODE JSON` rather than `type = ['append-only' | 'upsert' | 'debezium']`. This reads similar to source and enables support of different encodings later. Other connectors (clickhouse, jdbc, etc) still use the old `type = ` syntax as of now.

### CODE REVIEW

**Review by st1page — APPROVED** [review]
LGTM. Maybe some parser test is needed?
And should we notice user when they are using legacy syntax? https://github.com/risingwavelabs/risingwave/pull/12373

**Review by tabVersion — APPROVED** [review]
LGTM
but we still need a `connector x format x encode` table for compatibility check
https://github.com/singularity-data/risingwave/blob/fff6d47d897b859e1128029a3fe19b5d41a029f8/src/frontend/src/handler/create_source.rs#L853

**Comment by xiangjinwu** [comment]
> And should we notice user when they are using legacy syntax? #12373

Good point. But the new syntax is not actually effective yet. So maybe we can add them when it actually works.

> but we still need a `connector x format x encode` table for compatibility check https://github.com/singularity-data/risingwave/blob/fff6d47d897b859e1128029a3fe19b5d41a029f8/src/frontend/src/handler/create_source.rs#L853

As of today the old syntax compatibility check happens in compute node (`build_sink` linked above) rather than in frontend. This is different from source for 2 reasons (as far as I can tell):
* No SourceExecutor is created immediately on `create source` (not `create table`).
* Protobuf/avro need to fetch column names and data types immediately in frontend

That being said, we could move/add the check to frontend as a refactor later if appropriate.

**Comment by xiangjinwu** [comment]
Major changes since the reviewed 3c0cfc9:
* The new syntax is now limited to only kafka/kinesis/pulsar, which is using `SinkFormatterImpl`. Other connecters will be tested and migrated later one by one. For example, clickhouse sink does not take an encode today, and elasticsearch sink does not even require `type = `.
* Kafka/kinesis/pulsar is now fully functioning with the new syntax, and does not rely on legacy `SinkType` or `SINK_TYPE_OPTION`. This made the PR more complete, and user-facing, but also doubled the lines.

**Review by tabVersion — APPROVED** [review]

**Pull request merged**
