### PR TITLE
fix: use ring as default provider

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

The original aws_lc_rs provider may default to FIPS mode in certain situations, where FIPS may not be available, leading to panic due to `error:12800067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/x86_64-linux-gnu/ossl-modules/fips.so): /usr/lib/x86_64-linux-gnu/ossl-modules/fips.so: cannot open shared object file: No such file or directory, error:12800067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:152:, error:07880025:common libcrypto routines:provider_init:reason(524325):../crypto/provider_core.c:912:name=fips`

This PR changes the provider to `ring`.

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  My PR contains critical fixes that are necessary to be merged into the latest release. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

**Comment by arkbriar** [comment]
Several questions:
- What's the difference between `aws_lc_rs` and `ring`?
- Shall we also bundle the fips share lib in our image?

**Comment by arkbriar** [comment]
+ @lmatz

**Comment by zwang28** [comment]
> What's the difference between aws_lc_rs and ring?

[aws_lc does not appear to be actively tested on BSD systems.](https://github.com/aws/aws-lc?tab=readme-ov-file#other-platforms)

**Review by hzxa21 — APPROVED** [review]
LGTM

Have we tested that using `ring` can also prevent the google-pub-sub issue mentioned in #19136?

**Pull request merged**
