### PR TITLE
fix(ci): fix standalone tests startup

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

They need to wait for the `minio` service to start, before they can run. Otherwise the meta node just panics and we cannot start.

Honestly, this is a quick fix, rather than a proper fix. We should do #16601, but I don't have time recently..

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by yezizp2012** [comment]
@wcy-fdu we need a proper fix to allow meta starts before minio in standalone mode. Please help to fix it.

**Comment by kwannoel** [comment]
Can we merge this in first? Let the main-cron pass.

**Review by yezizp2012 — APPROVED** [review]

**Comment by wcy-fdu** [comment]
I'm trying to decouple minio and standalone startup, but I found it a bit difficult. If you have any ideas, please let me know.

**Comment by kwannoel** [comment]
> I'm trying to decouple minio and standalone startup, but I found it a bit difficult. If you have any ideas, please let me know.

https://github.com/risingwavelabs/risingwave/issues/16601#issuecomment-2227935760

**Pull request merged**
