### PR TITLE
feat(storage): support box dynamic dispatch state store impl

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

After we introduced `HummockStorageV1` and added a new `StateStoreImpl` variant in https://github.com/risingwavelabs/risingwave/pull/6153, it is reported that the compile time increases significantly. The reason for this might be, we use static dispatch in streaming executor for `StateStore`, and the compiler has to generate code and do optimization for all variants in `StateStoreImpl`, which is time consuming.

In this PR, we add a new cargo feature named `generic_state_store_impl`, and when this feature is enabled, all variants of `StateStoreImpl` will hold a `Box<dyn GenericStateStore>`, which uses dynamic dispatch, and the streaming executor will only take such `Box<dyn ...>` as `StateStore`, and we can speed up the compilation.

In my test, 
Without `generic_state_store_impl` compile feature ,
```
cargo clean
cargo build --profile dev
...
Finished dev [unoptimized + debuginfo] target(s) in 4m 47s
```

With `generic_state_store_impl` compile feature ,
```
cargo clean
cargo build --profile dev --features=generic_state_store_impl
...
Finished dev [unoptimized + debuginfo] target(s) in 3m 06s
```

Since the state store related trait uses GAT, and it seems unable to be made object safe, we introduce a new set of `GenericStateStoreXxx` trait with `async_trait`, and these traits are object safe, and can be used with `Box<dyn ...>`

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
https://github.com/risingwavelabs/risingwave/pull/6153

### CODE REVIEW

**Comment by skyzh** [comment]
I think it's okay to enable this by default in debug mode. Tokio did similar things (spawn will create Box future instead of in-place in debug mode)

**Comment by BugenZhao** [comment]
`generic` gives me an intuition of monomorphism and static dispatch, while it's actually the opposite. 🤔 `box` or `boxed` sounds better to me.

**Comment by hzxa21** [comment]
>> I think it's okay to enable this by default in debug mode.

> +1. We can make it default when debug_assertion is off. Using a feature makes it harder to maintain and we should also enable it manually and carefully.

I think you mean enabling it by default when debug_assertion if **on**. +1 for this.

**Comment by wenym1** [comment]
@skyzh @hzxa21 @BugenZhao I have changed to enable it by default when debug_assertions is enabled. The names have also been changed to `DynamicDispatchStateStoreXxx`. PTAL

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
I guess this will also partially solve the compile regression of toolchain bump (part of it is caused by MergeIterator). Probably we can revert some workarounds.

**Review by BugenZhao — APPROVED** [review]

**Comment by BugenZhao** [comment]
Looks like the compiling is speeded up a lot. 🤩

**Pull request merged**
