### PR TITLE
fix(frontend): accept `READ WRITE` transaction as no-op

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Psycopg will [implicitly execute `START TRANSACTION`](https://www.psycopg.org/psycopg3/docs/basic/transactions.html#transactions-management). After #10735, we use `READ ONLY` as the default access mode, which breaks its functionality. Our [main-cron CI failed](https://buildkite.com/risingwavelabs/main-cron/builds/653) due to this.

In this PR, we make `READ WRITE` the default access mode again, and allow executing `START TRANSACTION READ WRITE` as a no-op.

https://github.com/risingwavelabs/risingwave/blob/a1302563e651f1370dd7c6925122e7ef4178bf7e/src/frontend/src/handler/transaction.rs#L49-L59

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [x] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- SQL commands, functions, and operators

### Release note

- Users must specify `READ ONLY` explicitly for starting a read-only transaction. For compatibility with drivers, `START TRANSACTION` or `START TRANSACTION READ WRITE` is a no-op statement that will still succeed but no transaction is actually started.

</details>

### CODE REVIEW

**Review by kwannoel — APPROVED** [review]
LGTM. I have triggered `main-cron` again to test the fix.

**Comment by BugenZhao** [comment]
> LGTM. I have triggered `main-cron` again to test the fix.

Thanks for that. Let's wait for the result to see if there're any other issues.

**Comment by hzxa21** [comment]
cc @sushantgupta Let's rerun chaos mesh test after this PR is included in the image. It should fix the Psycopg issue.

**Comment by BugenZhao** [comment]
> LGTM. I have triggered `main-cron` again to test the fix.

Passed. https://buildkite.com/risingwavelabs/main-cron/builds/655

**Comment by hzxa21** [comment]
@sushantgupta still faced the same issue after using a image with this PR included: https://buildkite.com/risingwave-test/longevity-chaos-mesh/builds/307#018962f8-717e-4c93-954c-d6ea9ee14ede

cc @BugenZhao

**Comment by hzxa21** [comment]
@sushantgupta I think you are not using the right image. Log shows that the test is running with git commit "f888886656294328608b04bdb39d14704807ff4b", which is the commit in Jul 15.
https://grafana.test.risingwave-cloud.xyz/explore?orgId=1&left=%7B%22datasource%22:%22PE59595AED52CF917%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PE59595AED52CF917%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22longcmkf-20230717-083134%5C%22%7D%20%7C%3D%20%60%3E%20version%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

**Pull request merged**
