### PR TITLE
chore(streaming): log at trace level - `actor` <-> MV definition 

### PR DESCRIPTION
**Pull request by jon-chuang**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
debug actor_id <-> MV definition correspondence.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
https://github.com/risingwavelabs/risingwave/issues/6092

### CODE REVIEW

**Comment by BugenZhao** [comment]
I'm afraid this will yield too many lines in e2e tests. 🤔

**Comment by jon-chuang** [comment]
Hmm weird, `RUST_LOG=info` in this script: https://github.com/risingwavelabs/risingwave/blob/main/ci/scripts/run-e2e-test.sh

**Comment by jon-chuang** [comment]
I see, on further inspection, it seems that the default does not get overriden by a lower log level. Do you think this is the correct behaviour? @BugenZhao @wangrunji0408

**Review by fuyufjh — DISMISSED** [review]

**Comment by jon-chuang** [comment]
Some observations:
1. This recent PR overrides the level: https://github.com/risingwavelabs/risingwave/pull/7016. However, e2e tests generally use the default settings, i.e. DEBUG. 
2. Not sure what the default is for release mode, seems like it is still DEBUG. (compactor and compute node logs in release mode enabled via risedev still contain `DEBUG` level logs.

**Comment by BugenZhao** [comment]
> However, `RUST_LOG` variable should in theory override those defaults:

Seems we don't set the env var for normal e2e tests. 🤔

**Comment by jon-chuang** [comment]
Agreed its quite verbose. Not sure if it will be useful, but I guess it will just be trace.

**Comment by zwang28** [comment]
> However, RUST_LOG variable should in theory override those defaults:

`RUST_LOG=info` won't override any already configured specific setting, like [risingwave_stream](https://github.com/risingwavelabs/risingwave/blob/cf2f7ec85cfd466f73d937a1cdb39ca879a5203b/src/utils/runtime/src/lib.rs#L48). Instead, it overrides [this line](https://github.com/risingwavelabs/risingwave/blob/cf2f7ec85cfd466f73d937a1cdb39ca879a5203b/src/utils/runtime/src/lib.rs#L141).

To override risingwave_stream's filter level, we can use `RUST_LOG=risingwave_stream=info`.

**Comment by lmatz** [comment]
How about adding some extra `log` related documentation into  https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#logging in this PR?

**Pull request closed without merging**
