### PR TITLE
feat(frontend): support struct cast

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao 2 <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR adds support for struct casting and passes all struct tests from duckdb plus our new tests.

The implementation is like we convert the existing type into an enum { Infer, Type, Struct }, and then use implicit cast rules to infer the correct cast type.

* If both left and right are concrete struct types (i.e. in schema, not row expression), recursively resolve two types.
* If either side is concrete struct type and the other side is row expression, recursively resolve one type and one expression.
* If both sides are row expression, recursively resolve two expressions.
* The base case: we've got two type|expression, and we match them. 

The cast is not the same as Postgres. I feel Postgres's struct casting is too restrictive and users might not like it. For example, all of the following queries will error in Postgres:

```
?=> create type t3 as (v1 int, v2 int);
CREATE TYPE
?=> create type t4 as (v1 varchar, v2 varchar);
CREATE TYPE
?=> create table t5(v1 t3, v2 t4);
CREATE TABLE
?=> insert into t5 values (row(1, 1), row(1, 1));
INSERT 0 1

select v1 = v2 from t5;
ERROR:  cannot compare dissimilar column types integer and character varying at record column 1
select v1 = row('1', '1') from t5;
ERROR:  cannot compare dissimilar column types integer and unknown at record column 1
select v2 = row('1', '1') from t5;
ERROR:  cannot compare dissimilar column types character varying and unknown at record column 1
select v2 = row(1, 1) from t5;
ERROR:  cannot compare dissimilar column types character varying and integer at record column 1
```

Therefore, we took a different approach (comments welcomed): if we can assign one field to another, we will do the cast. This makes the struct type more flexible.

The code might need some refactors if we can finalize the struct comparison approach in RisingWave. If we allow implicit assign casts, the logic can be greatly simplified.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)

close https://github.com/risingwavelabs/risingwave/issues/3692

### CODE REVIEW

**Comment by fuyufjh** [comment]
> Therefore, we took a different approach (comments welcomed): if we can assign one field to another, we will do the cast. This makes the struct type more flexible.

LGTM, since `1 = '1'` is true. 

PATL @xiangjinwu

**Comment by xiangjinwu** [comment]
I am also leaning towards relaxing the restrictions from PostgreSQL, which does not contain a literal unnamed definition of `struct<>` type at all.

> if we can assign one field to another, we will do the cast. This makes the struct type more flexible.
> If we allow implicit assign casts

My idea is to only allow `implicit` cast but not `assignment` or `explicit` cast. The reverse of an `implicit` cast (e.g. `int -> bigint`) is always `assignment` (e.g. `bigint -> int`), but there are some extra `assignment` casts (`timestamp -> time`) that should not be allowed during comparison.

I am still looking at the details of type inference of comparison.

**Comment by skyzh** [comment]
In this case it’s easier to implement. I’ll do a refactor before requesting for review then.

**Comment by skyzh** [comment]
The logic is much more simplified. PTAL thanks!

**Review by xiangjinwu — APPROVED** [review]

**Pull request merged**
