### PR TITLE
fix(expr): cast untyped `start` and `step` when inferring type for `generate_series`

### LINKED ISSUE #18729: Streaming `generate_series` should work with `unknown` as `start`
Seems we cannot correctly infer streaming `generate_series` with `now()` when the `start` argument is an `unknown`, as found by @kwannoel here: https://github.com/risingwavelabs/risingwave-docs/pull/2637#issuecomment-2373942740

```sql
dev=> create materialized view m1 as SELECT time::timestamptz FROM generate_series(
  '2020-01-01 00:00:00',
  now(),
  interval '1 hour'
) t(time);
ERROR:  Failed to run the query

Caused by:
  function generate_series(unknown, timestamp with time zone, interval) does not exist
```

Users have to do casting like `'2020-01-01 00:00:00'::timestamptz`.

This is not intended, should be fixed.

### PR DESCRIPTION
**Pull request by stdrc**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix #18729.

## Checklist

- [ ] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by stdrc** [comment]
* **#18786** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/18786?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stdrc and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by kwannoel — APPROVED** [review]
Thanks!

**Comment by kwannoel** [comment]
Can you add a batch plan test as well?

**Comment by kwannoel** [comment]
> > Can you add a batch plan test as well?
> 
> In batch, we won't throw error until the query is executed by backend. So we can't test it in planner test.🤪

An slt test would be good then, to make sure the type checking behaviour is consistent between batch and streaming.

Won't block this PR on it.

**Review by xiangjinwu — APPROVED** [review]

**Pull request merged**
