### PR TITLE
chore(deps): bump rdkafka to v0.34.0 and librdkafka to v2.2.0

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

As title. Please also review the change in https://github.com/madsim-rs/madsim/pull/173, and see what's changed from the original rdkafka in [this commit](https://github.com/madsim-rs/madsim/pull/173/commits/05dc6619df762c9b9ee57c4d02d000472e7d0edd).

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by StrikeW — APPROVED** [review]

**Review by xxchan — COMMENTED** [review]
> Note that the upstream [rust-rdkafka](https://docs.rs/rdkafka/0.33.2/rdkafka/index.html) is still using librdkafka v1.9.2. But we require a newer version since we depend on [the DNS resolution callback feature](https://github.com/MaterializeInc/rust-rdkafka/commit/8ea07c4d2b96636ff093e670bc921892aee0d56a) from Materialize, which has been included in the upstream librdkafka since v2.0.0. So we forked [rdkafka-sys](https://github.com/madsim-rs/rust-rdkafka/tree/librdkafka-2.2.0/rdkafka-sys?rgh-link-date=2023-07-26T06%3A34%3A12Z) and updated its librdkafka to the latest v2.2.0, then [switched](https://github.com/madsim-rs/madsim/pull/161/files#diff-d218f34d3f6d01ecb5c9021c698296967f36e46e26ef369e1bc248c41c6873ca) rdkafka-sys from Mz's fork to our fork.

The story is a little long. Basically it means we switched to latest versions, and applied the same patch as the MZ fork?

Another question is what's the motivation to upgrade (besides keeping it up to date)? Since it's a critical dependency, and the upgrade is across multiple versions (v0.29.0->v0.33.2, v1.9.2->v2.2.0), has anyone went through the CHANGELOG, and/or tested it?

**Comment by wangrunji0408** [comment]
> Basically it means we switched to latest versions, and applied the same patch as the MZ fork?

Yes. The Mz's patch has been included in the latest version.

> Another question is what's the motivation to upgrade (besides keeping it up to date)? Since it's a critical dependency, and the upgrade is across multiple versions (v0.29.0->v0.33.2, v1.9.2->v2.2.0), has anyone went through the CHANGELOG, and/or tested it?

The original motivation was to fix potential memory leak in rdkafka according to @shanicky. But it looks like we have found the reason from another source (see #10888). So this upgrade is not critical at this time. We can pause it until every change has been reviewed and test passed. 

The failure of e2e source/sink tests shows there's might be problems somewhere :(

**Comment by xxchan** [comment]
> we were relying on a version from eight months ago, so we asked Runji if we could upgrade

IMO 8 months isn’t that old but is also quite old. 🤣

Btw, I would recommend update regularly and one version at a time. Then we can review the changes much more easily. Also we can avoid cases like we upgrade it to fix a problem, but didn’t noticed the changes and introduced another problems..

> the upgrade didn’t seem as urgent. If there is an issue, it feels like we can delay it

According to the reasons above, I think it’s a good time to begin reviewing the changes now. 😁(Although not urgent)

**Comment by xxchan** [comment]
Well, but we have a PR depending on the upgrade now.  🤣 #11203

**Comment by fuyufjh** [comment]
> Well, but we have a PR depending on the upgrade now. 🤣 https://github.com/risingwavelabs/risingwave/pull/11203

Don't mind. I can remove this option from that PR if you need to delay this.

**Comment by fuyufjh** [comment]
I tried to merge this into my branch and it doesn't seem to work:

```
dev=> create table s25 (v1 int, v2 varchar) with (
  connector = 'kafka',
  ...
) FORMAT PLAIN ENCODE JSON;
ERROR:  QueryError: internal error: error trying to connect: tcp connect error: Connection refused (os error 111)
dev=>
```

By the way, `risedev` also act wierdly. On my local Mac, it hangs forever

image

**Comment by fuyufjh** [comment]
Just a reminder: please help to update

**Comment by fuyufjh** [comment]
Reminder: please help to update 

https://github.com/risingwavelabs/risingwave/pull/11203/files#diff-851782ccb1f1b4dfb7b42b85cbc605f6f74fe1e5f957b5293ef0e345f4ee7fc1R65-R68

and 

https://github.com/risingwavelabs/risingwave/pull/11203/files#diff-851782ccb1f1b4dfb7b42b85cbc605f6f74fe1e5f957b5293ef0e345f4ee7fc1R160-R162

after this PR gets merged

**Comment by wangrunji0408** [comment]
Seems there are some problems in this madsim-rdkafka update. An unit test is blocking https://github.com/madsim-rs/madsim/pull/161/commits/6932616a56a7b54611927cf013bff10584a73faa. Needs more investigation.

**Comment by wangrunji0408** [comment]
I found the reason why previous update was blocking. The `resolve_cb` function cherry-picked from Materialize didn't consider null pointer input, which lead to invalid memory access. I've added a check to fix this problem.

https://github.com/madsim-rs/madsim/blob/95d4a63a2e4d3572964e7c72df38cc010e81f24c/madsim-rdkafka/src/std/client.rs#L554-L557

**Review by xxchan — APPROVED** [review]
Since 1.3 already branches off and will soon be published, and seemingly no one is going to really review the CHANGELOG in depth, I'm OK to merge this into main now, and just let it go through tests of time.. 🤡

**Pull request merged**
