### PR TITLE
fix(meta): add worker to cluster after able to resolve worker dns

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Related
- https://github.com/risingwavelabs/risingwave/issues/15730
- https://github.com/risingwavelabs/risingwave/issues/15650

There might be latency in dns propagation in cluster. In this PR we change to add the worker to cluster only after meta succeeds to resolve the address of the newly register CN. It will keep retrying for up to approximately 1 minute.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
May I ask why we didn't encounter such issue previously?

**Comment by wenym1** [comment]
> Hmmm, does it mean that if all compute nodes fail to register themselves in a short time, we may also encounter e2e pipeline failure with the error `No available parallel units to schedule`. Because at that time, the cluster is not ready to accept any DDLs. Btw we have encountered it in single-node test of yesterday's main-cron. https://risingwave-labs.slack.com/archives/C03N6EP8ZA7/p1710730547470329?thread_ts=1710729368.555349&cid=C03N6EP8ZA7

It seems that the problem that this PR tries to resolve is not the one mentioned in the link. The problem to be resolved in this PR is that, when CN send a request with its own host address to register itself to meta, meta cannot reach the CN with the host address in the request because of latency in dns propagation.

**Comment by wenym1** [comment]
> May I ask why we didn't encounter such issue previously?

Previously the meta node made the first request to CN on the first DDL. After https://github.com/risingwavelabs/risingwave/pull/15653, we will make the first request when CN registers itself to meta, which is earlier than previously.

**Comment by yezizp2012** [comment]
> It seems that the problem that this PR tries to resolve is not the one mentioned in the link. The problem to be resolved in this PR is that, when CN send a request with its own host address to register itself to meta, meta cannot reach the CN with the host address in the request because of latency in dns propagation.

I see, then the dns propagation delay isn't too high, so e2e pipelines are fine until now.

**Comment by wenym1** [comment]
> > It seems that the problem that this PR tries to resolve is not the one mentioned in the link. The problem to be resolved in this PR is that, when CN send a request with its own host address to register itself to meta, meta cannot reach the CN with the host address in the request because of latency in dns propagation.
> 
> I see, then the dns propagation delay isn't too high, so e2e pipelines are fine until now.

Yes. Actually for e2e test in CI there may not be such problem, because it used 127.0.0.1 or localhost as the address. The problem happened frequently in nexmark, sysbench or longevity that use kubernetes for deployment and node is discovered via resolving the node name dns.

**Review by hzxa21 — APPROVED** [review]

**Review by yezizp2012 — APPROVED** [review]

**Pull request merged**
