### PR TITLE
fix: column index mapping bug of stream_delta_join

### PR DESCRIPTION
**Pull request by yufansong**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

In #9843, when enable delta join, the join will cause panic because of the data type mismatch. For delta join, the input data may come from the upstream or from the storage table. The data from the upstream has already been filtered. But for data from storage table, it is not filtered. 

Root cause: 
When building the `StorageTable`, the input `column_ids` directly using the full table column ids. 

Example:
* create table A (c1, c2, c3, _row_id), table B(c1,c2,c3, _row_id)
* join key c1, select c3
* Error result: row A (c1, c3, _row_id), row B (c1,c2,c3, _row_id)
* Reason: index map A is correct, but index map B should map (c1, c3, _row_id)，rather than (c1, c2, c3, _row_id)

Solution:
Add extra info of `output_col_id` into `ArrangementInfo` and use it when build `StorageTable`.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by kwannoel — APPROVED** [review]
LGTM, thanks! Can we also add a test for it?

**Review by chenzl25 — APPROVED** [review]
LGTM

**Comment by yufansong** [comment]
> LGTM, thanks! Can we also add a test for it?

I added one test. Does it looks good to you?

**Comment by kwannoel** [comment]
> > LGTM, thanks! Can we also add a test for it?
> 
> I added one test. Does it looks good to you?

Lgtm, thanks

**Pull request merged**
