### PR TITLE
fix(storage): assert vnode existence in state table

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

We encode vnode in the mem-table now, so the original implementation of `iter_with_prefix` only applies to iterating with a superset of the distribution key, which meets the pattern of streaming executors for now.

We should not use `unwrap_or` to give it a default value, instead, we should assert its existence.

This PR also improves code styles and removes some code duplication.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- Blocked by #5012

### CODE REVIEW

**Comment by BugenZhao** [comment]
e2e fails. 😕 Is the distribution of the local agg state table correct? cc @xxchan @st1page 

image
image

**Comment by BugenZhao** [comment]
> e2e fails. 😕

Blocked by #5012.

**Comment by wcy-fdu** [comment]
> > e2e fails. 😕
> 
> Blocked by #5012.

fixing...

**Review by st1page — APPROVED** [review]
LGTM

**Pull request merged**
