### PR TITLE
fix(frontend): Allow join key alignment on `IS NOT DISTINCT FROM`, check that eq key types are aligned in frontend

### PR DESCRIPTION
**Pull request by jon-chuang**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
Allow join key alignment on `IS NOT DISTINCT FROM`.

Previously join key is not aligned. This resulted in failure to create a hash join on unequal but implicitly castable types when using `IS NOT DISTINCT FROM`.

Catch error earlier when eq keys are not type aligned when converting join to batch/stream.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
https://github.com/risingwavelabs/risingwave/issues/7399

### CODE REVIEW

**Comment by jon-chuang** [comment]
let me add a planner test. Maybe e2e test is unnecessary.

**Comment by jon-chuang** [comment]
Blocked on: https://github.com/risingwavelabs/risingwave/issues/7401 (affects main)

**Comment by chenzl25** [comment]
> @chenzl25 seems `EqJoinPredicate` is also used in delta join, lookup join. Do these require equality of types on equal join keys as well? I assume yes and added a checks when deriving them from `LogicalJoin`

Yes, we require equality of types on equal join keys of any physical join operator.

**Review by chenzl25 — APPROVED** [review]
LGTM.

**Pull request merged**
