### PR TITLE
test: add endless NexMark e2e test (based on NexMark source)

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

None

## Refer to a related PR or issue link (optional)

related #132

### CODE REVIEW

**Comment by fuyufjh** [comment]
Blocked by #4829

**Comment by fuyufjh** [comment]
> If we just want to include the nexmark source into e2e_test, maybe we can use the nexmark source with an event number limit instead of introducing an endless test.

Yes, I'd like to test the endless source. Setting limited events is helpful to test the result, but I think this is already tested in the table-based cases (nexmark_upstream & nexmark_snapshot)

**Review by KeXiangWang — APPROVED** [review]
LGTM!

**Review by Li0k — APPROVED** [review]

**Comment by fuyufjh** [comment]
blocked by #4817

**Pull request merged**
