### PR TITLE
feat(compaction): do not split compaction output by size in L0 and Lbase

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Do not split compaction output by size when the output is already split by state table in L0 and Lbase to make code more clear.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by soundOfDestiny** [comment]
nexmark q8 blackhole benchmark result:

avg source output rows/s
this PR: 829,966.03
nightnly-20230505: 829,652.22

**Review by Little-Wallace — COMMENTED** [review]
Do we need to `generate_splits` for task which set `is_target_l0_or_lbase` true?

**Comment by soundOfDestiny** [comment]
> Do we need to `generate_splits` for task which set `is_target_l0_or_lbase` true?

I think we need split to compact parallel. cc @Li0k

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Pull request merged**
