### PR TITLE
chore: update to openjdk17 for packaging with hdfs

### PR DESCRIPTION
**Pull request by wcy-fdu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
as title, https://github.com/risingwavelabs/risingwave/pull/17013 upgrade the Dockerfile but forget to update the package shell. 

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by StrikeW — APPROVED** [review]

**Review by hzxa21 — APPROVED** [review]
LGTM.

**Comment by hzxa21** [comment]
We have been spotted and fixed several bugs and misses in the codes, `Dockerfile.hdfs` and `docker-hdfs.sh`. I suspect there will be more. The root cause is because we rely on manual effort to maintain the HDFS related codes and it is hard for developer to remember to update the hdfs related parts during daily development. For example, I saw that the [`nvm` installation](https://github.com/risingwavelabs/risingwave/blob/496d3a3e087307ad8a133b99f358c69b7d338dae/docker/Dockerfile#L14) is missing in `Dockerfile.hdfs.

Given that we saw more and more requests on HDFS build, I start thinking about the following things:
1. Shall we have a CI, at least per release, for the hdfs feature?
2. Based on 1, should we publish a HDFS build image as well for each release?
3. Should we unify the dockerfile and the build script for HDFS and non-HDFS build given that they share a lot of things in common?

**Comment by wcy-fdu** [comment]
New update: 
- remove `atomic_write_dir` for hdfs engine.
- remove `--features all-udf` as it cause` /risingwave/bin/risingwave: error while loading shared libraries: libpython3.12.so.1.0: cannot open shared object file: No such file or directory`

cc @hzxa21

**Comment by wcy-fdu** [comment]
> We have been spotted and fixed several bugs and misses in the codes, `Dockerfile.hdfs` and `docker-hdfs.sh`. I suspect there will be more. The root cause is because we rely on manual effort to maintain the HDFS related codes and it is hard for developer to remember to update the hdfs related parts during daily development. For example, I saw that the [`nvm` installation](https://github.com/risingwavelabs/risingwave/blob/496d3a3e087307ad8a133b99f358c69b7d338dae/docker/Dockerfile#L14) is missing in `Dockerfile.hdfs.
> 
> Given that we saw more and more requests on HDFS build, I start thinking about the following things:
> 
> 1. Shall we have a CI, at least per release, for the hdfs feature?
> 2. Based on 1, should we publish a HDFS build image as well for each release?
> 3. Should we unify the dockerfile and the build script for HDFS and non-HDFS build given that they share a lot of things in common?

Discussed offline, create an issue to track this.

> We have been spotted and fixed several bugs and misses in the codes, `Dockerfile.hdfs` and `docker-hdfs.sh`. I suspect there will be more. The root cause is because we rely on manual effort to maintain the HDFS related codes and it is hard for developer to remember to update the hdfs related parts during daily development. For example, I saw that the [`nvm` installation](https://github.com/risingwavelabs/risingwave/blob/496d3a3e087307ad8a133b99f358c69b7d338dae/docker/Dockerfile#L14) is missing in `Dockerfile.hdfs.
> 
> Given that we saw more and more requests on HDFS build, I start thinking about the following things:
> 
> 1. Shall we have a CI, at least per release, for the hdfs feature?
> 2. Based on 1, should we publish a HDFS build image as well for each release?
> 3. Should we unify the dockerfile and the build script for HDFS and non-HDFS build given that they share a lot of things in common?

SGTM, tracked in https://github.com/risingwavelabs/risingwave/issues/17604

**Pull request merged**
