### PR TITLE
fix(datatype): change the occurence of timestampz to timestamptz

### PR DESCRIPTION
**Pull request by ArshErgon**
for the issue: #6475 I have change the occurence of timestampz to timestamptz

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

**This section will be used as the commit message. Please do not leave this empty!**

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
Fix: https://github.com/risingwavelabs/risingwave/issues/6475

### CODE REVIEW

**Review by wangrunji0408 — CHANGES_REQUESTED** [review]
Seems that there're still other occurrence need to be changed. You can check the CI result for more examples.

**Comment by ArshErgon** [comment]
hope now it wouldn't fail

**Comment by jon-chuang** [comment]
Seems there are over 40 files w/ timestampz in them. Could you account for them? 

There is also some code generation that needs to be run (`./risedev do-apply-planner-tests`, script to generate proto in the dashboard dir)

https://github.com/risingwavelabs/risingwave/search?p=2&q=timestampz&type=

**Comment by ArshErgon** [comment]
Hi @jon-chuang the test `./risedev do-apply-planner-tests`  is giving me error, same error for the `./risedev Test`, am I doing something or missing a step?
```
= note: collect2: fatal error: cannot find 'ld'
          compilation terminated.
          

error: could not compile `syn` due to previous error
error: could not compile `proc-macro2` due to previous error
[cargo-make] ERROR - Unable to execute script.
[cargo-make] WARN - Build Failed.
[cargo-make] INFO - cargo make 0.36.3
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: do-apply-planner-tests
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task do-apply-planner-tests not found
[cargo-make] WARN - Build Failed.
```

**Comment by jon-chuang** [comment]
Try `sudo apt install --reinstall binutils`

**Comment by ArshErgon** [comment]
@jon-chuang that didn't work
All I have to do is `sudo apt install lld` [source](https://stackoverflow.com/questions/70272393/cargo-build-failed-with-note-collect2-fatal-error-cannot-find-ld)
So, I get this in return, do I have edit the `risedev.yml` file?
```
Using default config
=== Enabled Components ===
[Component] Hummock: MinIO + MinIO-CLI: disabled
[Component] Metrics: Prometheus + Grafana: disabled
[Component] Etcd: disabled
[Component] Kafka: disabled
[Component] Google Pubsub: disabled
[Component] Redis: disabled
[Component] RisingWave Connector: disabled
[Component] Tracing: Jaeger: disabled
[Build] Rust components: enabled
[Build] Dashboard v2: disabled
[Build] Enable release mode: disabled
[Build] Enable all-in-one binary: disabled
[Build] Enable sanitizer: disabled
Configuration saved at /home/arshergon/openSource/risingwave/risedev-components.user.env
=========================
RiseDev will only download the components you've enabled.
If you want to use these components, please modify the cluster config in risedev.yml to start that component.
See CONTRIBUTING.md or RiseDev's readme for more information.
[cargo-make] INFO - Build Done in 686.59 seconds.
[cargo-make] INFO - cargo make 0.36.3
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: do-apply-planner-tests
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task do-apply-planner-tests not found
[cargo-make] WARN - Build Failed.

```

**Comment by jon-chuang** [comment]
sry, it's `./risedev do-apply-planner-test`

**Review by jon-chuang — APPROVED** [review]
LGTM, thanks! 

Do contribute again on other issues.

**Review by wangrunji0408 — APPROVED** [review]

**Review by TennyZhuang — APPROVED** [review]

**Comment by ArshErgon** [comment]
@jon-chuang sure I will contribute to other after my exams, thank you so much for guiding me

**Pull request merged**
