### PR TITLE
chore(udf): attach parent pom to java udf and enable formatting

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

As titled.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

## Documentation

- [x] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by StrikeW — APPROVED** [review]
LGTM

**Review by wangrunji0408 — APPROVED** [review]
LGTM.

By the way, what formatting tool are you using? It looks like it has a different format with my tool. (VSCode plugin: Language Support for Java(TM) by Red Hat)

**Comment by StrikeW** [comment]
The spotless-maven-plugin. You can run it by `mvn spotless:apply` in the `java/` folder.

**Comment by wenym1** [comment]
Just added a doc for setting up Intellij IDEA with checkstyle configuration. The setting for VSCode in the doc is following the guide in the plugin description, but it seems not working, added to the doc anyway.

**Pull request merged**
