### PR TITLE
feat(streaming): weighted hash join cache by `moka`

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by yuhao-su** [comment]
I think we should hold this until having an agreement on memory management.

Unless we really need this now for benching purposes.

**Comment by BugenZhao** [comment]
> we really need this now for benching purposes.

I believe it's true.

> I think we should hold this until having an agreement on memory management.

Most management strategies require a basic mechanism of memory-usage bounded LRU cache. This could be a refinement of the current entry-count bounded one, so always be better. If there're some fancy ideas in the future, It's okay to refactor this completely.

**Comment by BugenZhao** [comment]
If the cache size is small enough, the state table panics. Fix in #5020.

```
thread 'risingwave-streaming-actor' panicked at 'internal error: entered unreachable code: memtable update should always be paired with a storage key', /Users/bugenzhao/Developer/S/risingwave-opensource/src/storage/src/table/streaming_table/state_table.rs:734:53
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::table::streaming_table::state_table::StateTableRowIter<M,C>::into_stream::{{closure}}
             at ./src/storage/src/table/streaming_table/state_table.rs:734:53
   3: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   4: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   5: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   6: <&mut S as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:104:9
   7: <futures_async_stream::stream::next::Next<S> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:386:17
   8: risingwave_stream::executor::managed_state::join::JoinHashMap<K,S>::fetch_cached_state::{{closure}}
             at ./src/stream/src/executor/managed_state/join/mod.rs:325:9
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  10: risingwave_stream::executor::managed_state::join::JoinHashMap<K,S>::remove_state::{{closure}}
             at ./src/stream/src/executor/managed_state/join/mod.rs:308:45
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  12: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::hash_eq_match::{{closure}}
             at ./src/stream/src/executor/hash_join.rs:635:33
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  14: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::eq_join_oneside::{{closure}}
             at ./src/stream/src/executor/hash_join.rs:715:62
  15: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  16: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::into_stream::{{closure}}
```

**Comment by BugenZhao** [comment]
Looks that the moka's eviction & admission strategy does not meet our use cases. Will close this PR and open another for estimate sizes and metrics.

**Pull request closed without merging**
