### PR TITLE
feat(sink): set parallelism of iceberg sink to 1

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Currently, our iceberg sink will fail easily with multiple concurrency, because iceberg support poorly on concurrent commit on metadata. Therefore, we may temporarily enforce the parallelism of iceberg sink to 1. 

We shall have a plan to support a centralized coordinator or committer for sinks like iceberg that requires communication between different sink parallelism.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by chenzl25 — APPROVED** [review]
LGTM.

**Review by hzxa21 — APPROVED** [review]

**Review by st1page — APPROVED** [review]

**Review by tabVersion — APPROVED** [review]

**Comment by tabVersion** [comment]
approve. but we need to leave a todo. we cannot use parallelism 1 forever

**Comment by lmatz** [comment]
> approve. but we need to leave a todo. we cannot use parallelism 1 forever

https://github.com/risingwavelabs/risingwave/issues/8496

**Comment by tabVersion** [comment]
unfortunately, I am afraid that jdbc sink also needs to limit parallelism to 1 to prevent concurrent committing.
tested on #8457

**Pull request merged**
