### PR TITLE
chore: bump mimimal glibc version to 2.28 for linux binary release

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

In #4556, we switched to the `manylinux2014` Linux distro to ensure that the released artifact can run on systems with GLIBC versions as old as 2.17. However, this is becoming troublesome as the toolchain is also affected as described in #15749.

After some consideration and discussion with @xxchan, I think it's the time to bump the minimal GLIBC version to 2.28. Reasons:

- Originally, Amazon Linux 2 with GLIBC 2.26 was set to reach its EOL in June 2023 but was later postponed to June 2025. However, the default image used for launching a new EC2 instance is now Amazon Linux 2023, which has GLIBC 2.34. So problems similar to #4566 is unlikely to happen anymore.

- The Linux binary release is not designed to use in production. For the cases that users want to play around with RisingWave (e.g. standalone mode) on their own Linux machines, I believe it's okay to assume they're on a relatively new system.

See the comments on `release-env-x86` to find the updated reference of GLIBC version.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by huangjw806 — APPROVED** [review]
LGTM! Please run the docker build pipeline before merging.

**Comment by BugenZhao** [comment]
> LGTM! Please run the docker build pipeline before merging.

I think I need to run `release.sh`. How should I trigger that?

**Comment by huangjw806** [comment]
> I think I need to run `release.sh`. How should I trigger that?

Docker build pipeline will build binary, I have triggered a build on your branch.

https://buildkite.com/risingwavelabs/docker/builds/15436

**Review by xxchan — APPROVED** [review]
It's arguable that whether Amazon Linux 2 should be supported. But the fact that https://github.com/risingwavelabs/risingwave/issues/4556 dates back to 2022 changed my mind a little. And also the user profile of the users using released binary. (Who will play around with an old EC2?)

I still feel the motivation to change this at this timing isn't large enough. But anyway LGTM now.

**Comment by BugenZhao** [comment]
> buildkite.com/risingwavelabs/docker/builds/15437

It looks good. BTW, where can I find the artifact? Didn't find it in bucket `risingwave-nightly-pre-built-binary`. 😕

**Comment by huangjw806** [comment]
> BTW, where can I find the artifact? Didn't find it in bucket `risingwave-nightly-pre-built-binary`.

We migrated the bucket to the new AWS account, new bucket name `rw-nightly-pre-built-binary`

**Review by fuyufjh — APPROVED** [review]
LGTM. The PR description is convincing.

**Pull request merged**
