### PR TITLE
fix(stream agg): fix agg backwards compatibility issue introduced by #13376

### LINKED ISSUE #13465: hash_join panic in backwards compat test
See compute node logs in https://buildkite.com/risingwavelabs/main-cron/builds/1145#018bd497-981d-4ac5-be67-459c89247f68

```
thread 'risingwave-streaming-actor' panicked at src/stream/src/executor/managed_state/join/join_entry_state.rs:51:13:
pk [0, 128, 0, 0, 0, 85, 165, 162, 158, 0, 0, 0, 0] should be in the cache
thread 'risingwave-streaming-actor' panicked at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.5.0/src/buf/buf_impl.rs:289:9:
assertion failed: self.remaining() >= 1
thread 'risingwave-streaming-actor' panicked at src/storage/src/mem_table.rs:368:49:
internal error: entered unreachable code: memtable update should always be paired with a storage key
stack backtrace:
2023-11-15T20:37:24.363039515Z ERROR risingwave_stream::task::stream_manager: actor exit actor=184 error=Executor error: Storage error: MemTable error: Inconsistent operation
  backtrace of `StreamExecutorError`:
   0: from
             at ./src/stream/src/executor/error.rs:39:10
   1: into<risingwave_stream::executor::error::ErrorKind, risingwave_stream::executor::error::Inner>
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/convert/mod.rs:757:9
   2: from
             at ./src/stream/src/executor/error.rs:173:34
```

### PR DESCRIPTION
**Pull request by stdrc**
Signed-off-by: Richard Chien <stdrc@outlook.com>

I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fixes backwards compatibility issue caused by #13376. Closes #13465.

See https://github.com/risingwavelabs/risingwave/issues/13559#issuecomment-1820945754 and https://github.com/risingwavelabs/risingwave/issues/13465#issuecomment-1821016508 for more details.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by KeXiangWang — APPROVED** [review]
Thanks a lot for this fix. 🥲

**Comment by kwannoel** [comment]
Can keep `ci/main-cron/skip-ci`. Only `ci/skip-ci` should be removed. This is because we just want to test backwards compatibility in `main-cron` (otherwise the full main-cron workflow will run).

**Review by kwannoel — APPROVED** [review]
LGTM, thanks! Are there any improvements which can be made to backwards compatibility test? Seems like it found an error, but not at the precise commit.

**Comment by stdrc** [comment]
> Seems like it found an error, but not at the precise commit. Wonder why.

I guess it's a tiny mistake or some extend of non-deterministic execution.

**Pull request merged**
