### PR TITLE
feat(SqlSmith): gen Table Subquery `EXISTS`

### LINKED ISSUE #4296: feat(sqlsmith): Implement Table subqueries in where statement
This is specifically for EXISTS & NOT EXISTS

### PR DESCRIPTION
**Pull request by marvenlee2486**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

EXISTS implement

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #4296

### CODE REVIEW

**Comment by marvenlee2486** [comment]
There is 1 out of 1024 query that I run have this issue https://github.com/singularity-data/risingwave/issues/4434 . Need to fix this first

**Comment by marvenlee2486** [comment]
> There is 1 out of 1024 query that I run have this issue #4434 . Need to fix this first

alright, I think it is nothing related to exists, we can merge it. Because the problem occur in subquery with aggregate. Probably this probability is very low, until now it is notice.

**Review by lmatz — COMMENTED** [review]
For some `exists` query, e.g.
> SELECT t1.* FROM t1
WHERE EXISTS (SELECT * FROM t3 WHERE t1.c1 = t3.c1)

It can be transformed into a hash join, not necessarily a nested loop join.
> SELECT t1.* FROM t1, t3 WHERE t1.c1 = t3.c1

So we can probably do more than this.

**Comment by kwannoel** [comment]
> For some `exists` query, e.g.
> 
> > SELECT t1.* FROM t1
> > WHERE EXISTS (SELECT * FROM t3 WHERE t1.c1 = t3.c1)
> 
> It can be transformed into a hash join, not necessarily a nested loop join.
> 
> > SELECT t1.* FROM t1, t3 WHERE t1.c1 = t3.c1
> 
> So we can probably do more than this.

Clarification: Do you mean that exists can be transformed into something we already test (hash join), so we probably don't need to generate it, there are other more important things to generate?

**Comment by lmatz** [comment]
We still need to generate in these cases as we can test the `transformed into something`. 
I mean, we can generate correlated subqueries in the `exists` clause.

**Comment by kwannoel** [comment]
Any updates?

**Comment by marvenlee2486** [comment]
Currently a few feature not yet implemented
1) Local subquery inside Aggregate
2) Correlated subquery in HAVING or SELECT with agg is not implemented

so I decided to workaround, as such
If currently the subquery is inside an aggregate function, then it won't generate EXISTS subquery

With this, when I want to generate correlated subquery. The following problem shown up https://github.com/risingwavelabs/risingwave/issues/6350

As for Imatz comment on the possible EXISTS subquery generated by materialised view. I will look into what I can do in a later time.

**Comment by marvenlee2486** [comment]
The problem I facing is  "Feature is not yet implemented: correlated subquery in HAVING or SELECT with agg,"

This show that if I would want to generate correlated query (Not the local query), I need to pass the information about "Cannot have agg" all the way until gen_expr which is too much of parameter passing.

I am planning to refactor some code to able to workaround unsupported feature.
1. put the two variable 'inside_agg' and 'can_agg' as internal state instead of passing around gen_expr. Meaning that the variable will become global to all the methods (functions).
2. To ensure correctness, the same way as how the gen_local_query done is, saving all the state and restoring the state upon leaving the function. (This may be quite a some refactor).
3. By doing so, we can actually think of a few more internal state that can help us with workaround for example, if it is mv, then we avoid generating Nested Loop Join.

Since this PR is not about correlated query, and it is about EXISTS, would it be alright if I dun generate correlated query and have another PR about generating correlated query.

I need some advise on this.

**Comment by kwannoel** [comment]
> Since this PR is not about correlated query, and it is about EXISTS, would it be alright if I dun generate correlated query (meaning I generate local context) and have another PR about generating correlated query.

Sounds good.

**Comment by kwannoel** [comment]
> This show that if I would want to generate correlated query (Not the local query), I need to pass the information about "Cannot have agg" all the way until gen_expr which is too much of parameter passing.

This is a good point, I think the way we workaround unsupported features have added complexity to the code.
I think an alternative to your suggestion is to handle by matching on the error `unimplemented!()`. I think this will handle a class of errors without having to manually check `can_agg`, `inside_agg` depending on the unsupported expression.

This is similar to our approach for runtime errors: https://github.com/risingwavelabs/risingwave/blob/7a12a6ba0d6977d1363888952e4b7d46bb65cc20/src/tests/sqlsmith/src/runner.rs#L139-L145

**Review by kwannoel — APPROVED** [review]

**Comment by marvenlee2486** [comment]
Lets continue discussion under this issue https://github.com/risingwavelabs/risingwave/issues/6592

**Pull request merged**
