### PR TITLE
fix(batch): fix the wrong range when scan with ranges

### LINKED ISSUE #7390: Wrong query result on mviews with descent orders
### Describe the bug

Query over mviews with `ORDER BY ? DESC` with a simple prediction will produce wrong results.

### To Reproduce

```sql
create table t (id int,v1 int,v2 int);
insert into t values(1,1,1),(2,2,2),(3,3,3);
create materialized view mv11 as select * from t order by id desc;
```

```
select * from mv11 where id > 2;
 id | v1 | v2
----+----+----
  1 |  1 |  1
(1 row)
select * from mv11 where id < 2;
 id | v1 | v2
----+----+----
  3 |  3 |  3
(1 row)
```

### Expected behavior

```
select * from mv11 where id > 2;
 id | v1 | v2
----+----+----
  3 |  3 |  3
(1 row)
select * from mv11 where id < 2;
 id | v1 | v2
----+----+----
  1 |  1 |  1
(1 row)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by st1page**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
fix #7390 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- ~[ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]

**Review by chenzl25 — APPROVED** [review]

**Comment by BugenZhao** [comment]
Does the Backfill executor encounter a similar issue? cc @chenzl25. I guess we need to find a more robust interface design to explicitly notice that the orders matter here. 🤔

**Comment by chenzl25** [comment]
> Does the Backfill executor encounter a similar issue? cc @chenzl25. I guess we need to find a more robust interface design to explicitly notice that the orders matter here. 🤔

You really remind me of the `BackfillExecutor`. I am wondering how do we store the pk in descending order?

**Comment by st1page** [comment]
https://github.com/singularity-data/risingwave/blob/main/src/stream/src/executor/backfill.rs#L300-L314
it seems ok.

**Comment by chenzl25** [comment]
Backfill also relies on a comparison between `current_pos` and upstream message storage order key. We need to handle it properly.

**Pull request merged**
