### PR TITLE
fix(join): inequality may be reversed (close #8747)

### LINKED ISSUE #8747: inequality might be reversed in join condition
### Describe the bug

as title

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

inequality may be reversed in join condition

## Checklist For Contributors

- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by xxchan — COMMENTED** [review]
add a test case for it?😄

**Comment by soundOfDestiny** [comment]
> add a test case for it?😄

added a planner test

**Comment by lmatz** [comment]
Shall we merge it soon? Reverse in this case could lead to wrong results, right?

**Comment by soundOfDestiny** [comment]
> Shall we merge it soon? Reverse in this case could lead to wrong results, right?

ok I can close it because it has been resolved in my another PR https://github.com/risingwavelabs/risingwave/pull/8749

**Pull request closed without merging**
