### PR TITLE
feat(ci): more meta backend agnostic e2e tests in `main-cron`

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Use `meta-backend: env` for all CI RiseDev profiles.
  * use a persisted SQLite database as a fallback when env var is not set, behaving as if `meta-backend: sqlite` is specified, ensuring compatibility with the behavior prior to this PR.

- Extend coverage for PG/MySQL meta backends on `main-cron` to
  * slow e2e test
  * parallel e2e test
  * e2e source test
  * e2e sink test

Note that although there are many other steps for specific connectors, I suppose it may not be necessary to cover them all, as the execution path on the meta node should not differ significantly.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19595?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#19595** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19595?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19595?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#19568** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19568?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#19560** <a href="https://app.graphite.dev/github/pr/risingwavelabs/risingwave/19560?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by kwannoel — APPROVED** [review]

**Comment by kwannoel** [comment]
Seems like `main-cron` tests still fail. Let's make it pass before merging. Or disable the failing tests first.

**Review by xxchan — APPROVED** [review]
cool!

**Comment by xxchan** [comment]
failure looks strange

image

**Comment by BugenZhao** [comment]
> failure looks strange

See #19783.

**Comment by BugenZhao** [comment]
Disabled MySQL backend for now as there are some more unresolved issues.

**Pull request merged**
