### PR TITLE
fix(connector): make kinesis work again

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

as title, add kinesis properties, allowing start consuming from the given position, earliest and latest. 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Connector (sources & sinks)

### Release note

add two fields in WITH options

* `scan.startup.mode`: specify the position for start consuming. accept values: `latest`, `earliest`, `sequence_number`, default `earliest`
* `scan.startup.sequence_number`: specify a offset to start consuming. This field is only available and required when setting `scan.startup.mode` to `sequence_number`

### CODE REVIEW

**Review by waruto210 — APPROVED** [review]
LGTM

**Review by WingsUpete — APPROVED** [review]
Seems clear for me to understand

**Comment by neverchanje** [comment]
LGTM. But the title is somewhat mismatched with the content. I feel it's more of a "feat" rather than a "fix". And without this PR I think kinesis can still "work".

"feat(connector): support options to specify offsets for kinesis" would be more appropriate.

**Comment by tabVersion** [comment]
> But the title is somewhat mismatched with the content. I feel it's more of a "feat" rather than a "fix". 

I insist the pr be a fix. we would get into an `unreachable` arm before this. 🤣

**Pull request merged**
