### PR TITLE
feat(storage): use http instead of encryption connection for S3

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Resolve https://github.com/risingwavelabs/risingwave/issues/13053

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by chenzl25** [comment]
Maybe we need to bench the CPU usage cost by the encryption connection.

**Review by fuyufjh — APPROVED** [review]
LGTM

**Comment by hzxa21** [comment]
> Maybe we need to bench the CPU usage cost by the encryption connection.

+1. We can use [s3-bench](https://github.com/risingwavelabs/risingwave/blob/73dcbc2701a22530f698ed03ac1613bc70cab797/src/bench/s3_bench/main.rs#L625) to do so.

**Comment by chenzl25** [comment]
HTTPS flame graph, we can see function `tlsl_enc` would consume CPU to encrypt and decrypt messages.
image

image

**Comment by chenzl25** [comment]
While HTTP no encryption and decryption here:

image

**Comment by chenzl25** [comment]
However, I found that the aws sdk default will construct the s3 endpoint URL in https way e.g. `https://s3-ap-southeast-1.amazonaws.com`. If we just change the connector implementation to HTTP, it is not enough. We need the cloud to provide the correct HTTP endpoint by specifying environment variable `RW_S3_ENDPOINT` e.g. `http://s3-ap-southeast-1.amazonaws.com`. So I recommend we only enable HTTP when `RW_S3_ENDPOINT` is configured with a HTTP URL. cc @arkbriar

**Comment by chenzl25** [comment]
Just found that we don't need to modify any code, since `hyper_tls::HttpsConnector` has already handled the HTTP case. The only thing we need to do is to pass an HTTP endpoint to the compute node.

**Comment by arkbriar** [comment]
> However, I found that the aws sdk by default constructa the s3 endpoint URL in HTTPS way e.g. https://s3-ap-southeast-1.amazonaws.com. If we just change the connector implementation to HTTP, it is not enough. We need the cloud to provide the correct HTTP endpoint by specifying environment variable RW_S3_ENDPOINT e.g. http://s3-ap-southeast-1.amazonaws.com. So I recommend we only enable HTTP when RW_S3_ENDPOINT is configured with a HTTP URL. cc @arkbriar

Since the CPU overhead is not much (~4%), the cloud won't disable the HTTPs as suggested by @wjf3121 for the following reason that

> Encryption in transit within AWS VPC is based on the assumption that your VPC is not compromised. Otherwise, an attacker can still get your data unencrypted.

**Pull request closed without merging**
