### PR TITLE
chore(ci): fix buildkite main-cron notification

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Some test failures doesn't get notified. Still testing.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by kwannoel — COMMENTED** [review]
Hi Eric, I'll take over it.

**Comment by fuyufjh** [comment]
> Hi Eric, I'll take over it.

Thank you! The motivation is here: https://risingwave-labs.slack.com/archives/C03N6EP8ZA7/p1729048187787349?thread_ts=1729048114.857709&cid=C03N6EP8ZA7


Btw, what's the purpose of `"test-notify"` and `"test-notify-2"`?

**Comment by kwannoel** [comment]
> > Hi Eric, I'll take over it.
> 
> Thank you! The motivation is here: https://risingwave-labs.slack.com/archives/C03N6EP8ZA7/p1729048187787349?thread_ts=1729048114.857709&cid=C03N6EP8ZA7
> 
> Btw, what's the purpose of `"test-notify"` and `"test-notify-2"`?

It's to test:
1. Test notifications for failing test steps can be pushed. Both tests will always fail.
2. We can push notifications for multiple steps.

**Comment by kwannoel** [comment]
Fixed here: https://github.com/risingwavelabs/risingwave/pull/18962

**Pull request closed without merging**
