### PR TITLE
fix(cdc): fix postgres privilege check for AWS RDS

### PR DESCRIPTION
**Pull request by StrikeW**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Check whether postgres user is granted as `rds_superuser` or `rds_replication`;

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by lmatz** [comment]
Is it necessary to add an integration test with AWS RDS via Local Stack: https://docs.localstack.cloud/user-guide/aws/rds/

**Comment by StrikeW** [comment]
I think it is necessary to have integration test for RDS, right now we don't have such environment and @neverchanje is working on it. I am not sure whether the localstack could simulate an exact environment as AWS, do you have any experience with it?

**Comment by lmatz** [comment]
We have kinesis test based on local stack: https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/kinesis-s3-source/docker-compose.yml#L36-L61

**Comment by yufansong** [comment]
Will we have the same issue in GCP?

**Comment by StrikeW** [comment]
> Will we have the same issue in GCP?

We don't support RDS on GCP yet..

**Review by lmatz — APPROVED** [review]

**Review by yufansong — APPROVED** [review]

**Pull request merged**
