### PR TITLE
chore(build): workaround for toolchain upgrade

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao 2 <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR mainly removes some unnecessary generics in the storage code.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- #5977 
- #5119

### CODE REVIEW

**Comment by skyzh** [comment]
specifically `unsafe_boxed_static_future`, I feel we won't wait long before the upstream resolves this issue.

**Comment by skyzh** [comment]
cc @Li0k @wenym1 @hzxa21 PTAL thanks. There should be no performance regression for this PR.

**Comment by skyzh** [comment]
write anytime broken by a wrong refactor in merge iterator. will fix tomorrow 🥵

**Comment by skyzh** [comment]
Really ready for review

**Review by Li0k — APPROVED** [review]
LGTM. @wenym1 @hzxa21 PTAL

**Review by xxchan — APPROVED** [review]

**Review by hzxa21 — APPROVED** [review]

**Pull request merged**
