### PR TITLE
feat(sink): add metrics to monitor sink back pressure

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Resolve https://github.com/risingwavelabs/risingwave/issues/15473

Sink back-pressure is measured as `total_wait_new_future_time / total_time`, where `wait_new_future_time` means the time between the a `next_item` future returns ready and a next `next_item` future is created.

Metrics on grafana. Barrier interval is 1s. We manually inject a sleep in blackhole sink for 200ms, 500ms and 2000ms, and get sink back pressure as 20%, 50% and 100%, which is as expected.
image

The `truncate` method is unnecessary to be async, and to make the backpressure measurement easier, we make `truncate` method non-async by the way.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by BugenZhao — COMMENTED** [review]
There's similar stuff for monitoring the back-pressure rate of dispatchers, where we simply keep a counter to track the total blocking time accumulated, then visualize the `rate` of it over time as the back-pressure rate.

Can we also follow that style, which looks simpler and more consistent?

https://github.com/risingwavelabs/risingwave/blob/88cfb55b4713cc21f13ee962526fa17febba1338/src/stream/src/executor/dispatch.rs#L144-L149

**Comment by wenym1** [comment]
> There's similar stuff for monitoring the back-pressure rate of dispatchers, where we simply keep a counter to track the total blocking time accumulated, then visualize the `rate` of it over time as the back-pressure rate.
> 
> Can we also follow that style, which looks simpler and more consistent?
> 
> https://github.com/risingwavelabs/risingwave/blob/88cfb55b4713cc21f13ee962526fa17febba1338/src/stream/src/executor/dispatch.rs#L144-L149

It's different. The dispatcher is like monitoring backpressure from the sender side of a channel, but here we only have `LogReader`, which is similar to channel receiver rather than sender.

**Comment by BugenZhao** [comment]
> It's different. The dispatcher is like monitoring backpressure from the sender side of a channel, but here we only have `LogReader`, which is similar to channel receiver rather than sender.

You're right. I meant directly replace `self.total_wait_new_future_micro_secs` with a counter metric. Will this work?

**Comment by wenym1** [comment]
> > It's different. The dispatcher is like monitoring backpressure from the sender side of a channel, but here we only have `LogReader`, which is similar to channel receiver rather than sender.
> 
> You're right. I meant directly replace `self.total_wait_new_future_micro_secs` with a counter metric. Will this work?

Do you mean measure and report the two time separately, and reflect

> > It's different. The dispatcher is like monitoring backpressure from the sender side of a channel, but here we only have `LogReader`, which is similar to channel receiver rather than sender.
> 
> You're right. I meant directly replace `self.total_wait_new_future_micro_secs` with a counter metric. Will this work?

Oh, I get what you mean. Let me have a try.

**Comment by wenym1** [comment]
> > > It's different. The dispatcher is like monitoring backpressure from the sender side of a channel, but here we only have `LogReader`, which is similar to channel receiver rather than sender.
> > 
> > 
> > You're right. I meant directly replace `self.total_wait_new_future_micro_secs` with a counter metric. Will this work?
> 
> Do you mean measure and report the two time separately, and reflect
> 
> > > It's different. The dispatcher is like monitoring backpressure from the sender side of a channel, but here we only have `LogReader`, which is similar to channel receiver rather than sender.
> > 
> > 
> > You're right. I meant directly replace `self.total_wait_new_future_micro_secs` with a counter metric. Will this work?
> 
> Oh, I get what you mean. Let me have a try.

It works! Though the curve is not as sharp as before, but looks good to me, given that it's much easier.

image

**Review by BugenZhao — APPROVED** [review]
LGTM

**Pull request merged**
