### PR TITLE
chore(common): use RPITIT for Row trait and add Slice adapter

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR uses the unstable feature return-position-impl-trait-in-trait to avoid explicit iterator types in the `Row` trait.
In addition, it adds a `slice` method to `RowExt`.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] ~~I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).~~
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

### CODE REVIEW

**Comment by BugenZhao** [comment]
> This PR uses the unstable feature return-position-impl-trait-in-trait to avoid explicit iterator types in the `Row` trait.

I once used TAIT with GAT for the iter type and found it not friendly to the Rust Analyzer: the auto-completion doesn't work after `row.iter()`. I'm not sure whether RPITIT survives this. 🥵

BTW, I'm not sure whether someone want to explicitly write the type `R::Iter` in the future, though there seems no such usage currently.

**Comment by wangrunji0408** [comment]
> I once used TAIT with GAT for the iter type and found it not friendly to the Rust Analyzer: the auto-completion doesn't work after row.iter(). I'm not sure whether RPITIT survives this. 🥵

It seems to be working well on my environment.

WX20230626-162919@2x

> BTW, I'm not sure whether someone want to explicitly write the type R::Iter in the future, though there seems no such usage currently.

Explicit types are also acceptable in function signatures.

```rust
impl<D: ToDatumRef> Row for Once<D> {
    ...
    #[inline]
    fn iter(&self) -> std::iter::Once<DatumRef<'_>> {
        std::iter::once(self.0.to_datum_ref())
    }
}
```

**Comment by BugenZhao** [comment]
Oops, I mean something like...

```rust
struct MyRowIter<R: Row> {
  iter: R::Iter,
}
```

**Review by BugenZhao — APPROVED** [review]
LGTM!

**Pull request merged**
