### PR TITLE
fix(storage): replace vector with BytesMut in sstable writer

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

If we use vector as buf, we must convert it to `Bytes` before write it to objectstorage. But the method `Bytes::From::<Vec<u8>>` would re-allocate memory if the capacity of vector is larger than size. So we use BytesMut to reduce memory allocation.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by yuhao-su** [comment]
Seems the `freeze` will still call a function that convert a vec to Bytes. Not sure if this will be better than just use a vec rather than bufmut.
https://docs.rs/bytes/latest/src/bytes/bytes_mut.rs.html#247

**Review by Li0k — APPROVED** [review]
This change has no negative impact, consistent with su's point of view, not sure if it will bring benefits rather than use vec<u8>

https://docs.rs/bytes/latest/src/bytes/bytes_mut.rs.html#247
https://docs.rs/bytes/latest/src/bytes/bytes.rs.html#832

From the source code, it still needs to convert from vec to bytes, and into_boxed_slice will not bring the allocation

**Comment by yuhao-su** [comment]
Is it possible to use the exact size of the buffer when calling `with_capacity`? It's probably the only way to avoid the shink.

**Comment by Little-Wallace** [comment]
It seems that we need another method to avoid allocation.

**Pull request closed without merging**
