### PR TITLE
refactor(config): make PROCESSING_WINDOW_SIZE configurable

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
#5249, `The maximum size of the chunk produced by executor at a time.`.
And also `K_PROCESSING_WINDOW_SIZE` used in `MergeSortExchangeExecutor`.

`BatchConfig` is needed for `FrontendBatchTaskContext` because `MergeSortExchangeExecutor` can be used for local execution and thus require a configurable parameter `batch_chunk_size` under `BatchConfig`.

## Checklist

- [x] I have written necessary rustdoc comments
~- [ ] I have added necessary unit tests and integration tests~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#5249.

### CODE REVIEW

**Review by liurenjie1024 — COMMENTED** [review]
Another use of chunk size is https://github.com/risingwavelabs/risingwave/blob/d13809b7626b809ffb8b0faae888656b98cddf11/src/common/src/util/chunk_coalesce.rs#L44

We should eliminate all of this.

**Comment by lmatz** [comment]
> Another use of chunk size is
> 
> https://github.com/risingwavelabs/risingwave/blob/d13809b7626b809ffb8b0faae888656b98cddf11/src/common/src/util/chunk_coalesce.rs#L44
> 
> We should eliminate all of this.

Do you suggest removing this `with_default_size` function and always requiring callers to pass in a `chunk_size`, or we have some sort of `DataChunkBuilder`'s builder and use this builder's builder every time when we want to initialize a `DataChunkBuilder`?

**Comment by liurenjie1024** [comment]
> Do you suggest removing this `with_default_size` function and always requiring callers to pass in a `chunk_size`, or we have some sort of `DataChunkBuilder`'s builder and use this builder's builder every time when we want to initialize a `DataChunkBuilder`?

I think eliminate `with_default_size` and always requiring callers to pass in a `chunk_size` is enough for now.

**Comment by lmatz** [comment]
`DEFAULT_CHUNK_BUFFER_SIZE` is now also removed.

**Review by liurenjie1024 — APPROVED** [review]
LGTM

**Pull request merged**
