### PR TITLE
feat(optimizer): change stream join mv distribution key

### PR DESCRIPTION
**Pull request by chenzl25**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Change the stream join mv distribution key to be the same as the stream key to avoid slow backfilling caused by data skew of the dimension table join key.
- Resolve https://github.com/risingwavelabs/risingwave/issues/12824

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
Sorry, can you take a look on https://github.com/risingwavelabs/risingwave/issues/12824#issuecomment-1776521330

**Comment by chenzl25** [comment]
> Sorry, can you take a look on [#12824 (comment)](https://github.com/risingwavelabs/risingwave/issues/12824#issuecomment-1776521330)

Currently, we just have `stream_key`. After we have the `unique_key` property we can change the distribution to it. It would be more elegant I think.

**Comment by fuyufjh** [comment]
> > Sorry, can you take a look on [#12824 (comment)](https://github.com/risingwavelabs/risingwave/issues/12824#issuecomment-1776521330)
> 
> Currently, we just have `stream_key`. After we have the `unique_key` property we can change the distribution to it. It would be more elegant I think.

Okay. Make sense to me. 

But `unique_key` sounds ambiguous with the `unique key` in relation DB. Even though sharing some similarity, they seem to be different things to me.

**Review by fuyufjh — APPROVED** [review]
The code LGTM.

Needs to run a benchmark test before merging.

**Comment by chenzl25** [comment]
> But `unique_key` sounds ambiguous with the `unique key` in relation DB. Even though sharing some similarity, they seem to be different things to me.

The `unique_key` should be exactly what it means in a relational Database. While `stream_key` is also a unique key, it might contain more redundant columns.

**Pull request merged**
