### PR TITLE
fix(dynamic_filter): let executor write correct data upon scaling change

### PR DESCRIPTION
**Pull request by soundOfDestiny**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

- Summarize your change (**mandatory**)
let executor write correct data upon change in dynamic filter
- How does this PR work? Need a brief introduction for the changed logic (optional)
maintain `last_comitted_row`

## Checklist

- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
#6470

### CODE REVIEW

**Comment by jon-chuang** [comment]
Hmm, this is unnecessary. The last_commited_epoch_row is only necessary for when vnode 0 is set. See e.g. https://github.com/risingwavelabs/risingwave/pull/3783

**Comment by BugenZhao** [comment]
> Hmm, this is unnecessary. The last_commited_epoch_row is only necessary for when vnode 0 is set. See e.g. #3783

Is it possible if an executor starts to take charge of vnode 0 after scaling? 🤔

**Comment by jon-chuang** [comment]
Yes, indeed. Actually, we also need to properly handle the pause and update barriers correctly. I will make the corrections in a new PR.

**Comment by soundOfDestiny** [comment]
> Yes, indeed. Actually, we also need to properly handle the pause and update barriers correctly.
> 
> ~I will make the corrections in a new PR. I will also add some regression unit tests.~ No regression test as its hard to test scaling in unit tests for now... Anw, I've added some changes and comments. (actually no drastic changes needed as the code block handling the barrier is actually idempotent just like in hash agg).

Your changes are perfect! Thank you very much!

**Review by BugenZhao — APPROVED** [review]

**Pull request merged**
