### PR TITLE
feat(telemetry): mark a test message

### PR DESCRIPTION
**Pull request by tabVersion**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

add an `is_test` field in the `ReportBase` message body, marking the request is from the CI and will not be recorded

related pr https://github.com/risingwavelabs/telemetry-backend/pull/30

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by fuyufjh** [comment]
May I ask the motivation? Why reporting a test message?

**Comment by tabVersion** [comment]
> May I ask the motivation? Why reporting a test message? 

Then we can use the online service to validate if the report is compatible with the latest proto def. I use the field to mark if the message is from CI env and it will not be recorded into the db.

**Comment by fuyufjh** [comment]
> > May I ask the motivation? Why reporting a test message?
> 
> Then we can use the online service to validate if the report is compatible with the latest proto def. I use the field to mark if the message is from CI env and it will not be recorded into the db.

I see. IIUC, it's supposed to be enabled only for **testing telemetry**, rather than enabling for all tests.

**Review by fuyufjh — APPROVED** [review]
LGTM

**Comment by tabVersion** [comment]
> > > May I ask the motivation? Why reporting a test message?
> > 
> > 
> > Then we can use the online service to validate if the report is compatible with the latest proto def. I use the field to mark if the message is from CI env and it will not be recorded into the db.
> 
> I see. IIUC, it's supposed to be enabled only for **testing telemetry**, rather than enabling for all tests.

Yes, it ought to only be enabled when `telemetry.proto` changes but requiring changing the workflow and re-compile the whole project in that case. I think running the test in every CI is a more economic way.

**Pull request merged**
