### PR TITLE
feat: validate input references are consistent with the input schema

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

So that bugs like #7158 can be found earlier in frontend instead of backend.

### CODE REVIEW

**Review by chenzl25 — APPROVED** [review]
LGTM. Should we only enable these checks in debug mode?

**Comment by xxchan** [comment]
> Should we only enable these checks in debug mode?

I was also thinking about this problem and was not sure whether to add `cfg!(debug_assertions)`. Are you mainly worried about performance or safety or other things?

IMHO: 
- Overhead is acceptable.
- Violation of the assertion causes bugs. And frontend panic is better than backend panic. 

BTW there are already many other assertions and we havn't systematically considered how to use assertions 🤔

**Comment by chenzl25** [comment]
> IMHO

My concern is about performance, because we need to visit the entire plan exprs several times. Most of our CI tests run in debug mode and once some bugs are found we can still catch them.

**Comment by xxchan** [comment]
> My concern is about performance, because we need to visit the entire plan exprs several times.

If so do we also change these to `debug_assert` 🫣:
```rust
        assert!(*plan.distribution() == Distribution::Single, "{}", plan);
        assert!(!has_batch_exchange(plan.clone()), "{}", plan);
```

**Pull request merged**
