### PR TITLE
chore(object store): add log for s3 timeout retry

### PR DESCRIPTION
**Pull request by wcy-fdu**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
Report warning when the http connection limitation is triggered, in order to let upper layer be aware of the increasing of latency.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by lmatz** [comment]
How about also putting it into the Grafana dashboard?
similar to the `user streaming errors` panel
SCR-20230511-iy5

I suppose we may want to observe the frequency of this type of error, but it's up to you

**Comment by wcy-fdu** [comment]
> streaming

It's ok, and besides we can monitor `object_store_failure_count` metrics.

**Comment by zwang28** [comment]
> I suppose we may want to observe the frequency of this type of error, but it's up to you

+1

> Maybe we can add a object store error type pannel, including object not found, get object timeout, etc.

-1, because it is a failure only when max retry still fail. Call it a failure can be misleading if it eventually succeed.
BTW "object not found" is not a failure, because the we call `get` to check a object that is fine to not exist.

**Comment by zwang28** [comment]
> We can monitor object_store_failure_count metrics.
It's not recorded in `object_store_failure_count` if it succeeds before max retry.

> Maybe we can add a object store error type pannel, including object not found, get object timeout, etc.

+1. 
- We also want to monitor error that is auto retried by S3 SDK, because retry-until-succeed can increase the latency significantly and upper layer want to be aware of it, at least knowing there is more retry happening. But it seems not easy to expose this info from S3 SDK.
- But not for "object not found" because sometimes we call get for a object that is OK to not exist by intention.

**Comment by wcy-fdu** [comment]
> dd a object store error type pannel

Tracked [here](https://github.com/risingwavelabs/risingwave/issues/9764)

**Review by zwang28 — APPROVED** [review]

**Pull request merged**
