### PR TITLE
fix(connector): s3 source up to 1k objects

### PR DESCRIPTION
**Pull request by idx0-dev**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Our S3 connector uses `list_objects_v2` API to list objects of a bucket, but this API returns up to 1000 objects once. I have improved it to break the limit.

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by lmatz** [comment]
Thanks!

How about also increasing the test data size, e.g. more than 1000 objects, in the main-cron s3 source test?

**Review by lmatz — APPROVED** [review]
Thanks!

**Comment by idx0-dev** [comment]
Test passes. https://buildkite.com/risingwavelabs/main-cron/builds/503#0188285c-abfe-48da-8daf-06626ae19f27

**Review by tabVersion — APPROVED** [review]

**Review by waruto210 — APPROVED** [review]
Good job, LGTM.

**Pull request merged**
