### PR TITLE
feat(dashboard): add diagnose command

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Add `/api/monitor/diagnose` in dashboard service that returns a diagnostic report in text.
Also add a button for it in dashboard UI, under the Debug button group.

I anticipate this report being useful in scenarios where the developer lacks direct access to the problematic cluster, and the user can provide it as an initial troubleshooting reference. It's kind like a troubleshooting knowledge base.

The major structure `DiagnoseCommand` gathers info from both meta service and prometheus. Many lines of code but most of them are simple read/format/write. Perhaps in the future we can define both prometheus queries and meta store SQL (after SQL backend) in an external config file, to get rid of most LOC of `DiagnoseCommand`.

A sample report: [report.txt](https://github.com/risingwavelabs/risingwave/files/13699122/report.txt)

#12826

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
For metrics, I believe it works only if we specify `--prometheus-endpoint` (and also `--prometheus-selector`, if applied). Currently, they are not available in most deployments but local development.

**Comment by zwang28** [comment]
> For metrics, I believe it works only if we specify `--prometheus-endpoint` (and also `--prometheus-selector`, if applied). Currently, they are not available in most deployments but local development.

I think helping on-prem user setup `RW_PROMETHEUS_ENDPOINT` and `RW_PROMETHEUS_SELECTOR` once is unavoidable.

**Comment by fuyufjh** [comment]
- Instead of printing the number of tables/materialized views/sinks/indexes/etc., how about print the definition of them as well?
- Additionally, may also print the scheduling - the table that being printed on `risedev meta cluster-info`

I think the diagnosis output should include as much information as possible, to avoid the ping-pong between us and the user.

**Comment by fuyufjh** [comment]
> > For metrics, I believe it works only if we specify `--prometheus-endpoint` (and also `--prometheus-selector`, if applied). Currently, they are not available in most deployments but local development.
> 
> I think helping on-prem user setup `RW_PROMETHEUS_ENDPOINT` and `RW_PROMETHEUS_SELECTOR` once is unavoidable.
> 
> The diagnose report will skip PromQL if `RW_PROMETHEUS_ENDPOINT` is not set.

Relate #13830 which proposed to store some critical metrics in Meta's memory.

**Review by fuyufjh — APPROVED** [review]
The framework LGTM. We may add/modify the content of diagnosis in the future.

**Review by BugenZhao — APPROVED** [review]

**Comment by zwang28** [comment]
> Instead of printing the number of tables/materialized views/sinks/indexes/etc., how about print the definition of them as well?

Not included in this PR, because the dashboard api may be public so I think removing sensitive data from table definition is required, which need be done in dedicated PR.

> Additionally, may also print the scheduling - the table that being printed on risedev meta cluster-info

Not included in this PR. It can be added along with above-mentioned catalog definition, because we need the definition to interpret cluster-info . Currently the report tells the number of actors in each worker node.

> And the await tree dump, too... and anything else that might be helpful for us.

Added.

**Pull request merged**
