### PR TITLE
style(batch): rename OrderByExecutor to SortExecutor

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

## What's changed and what's your intention?

`SortExecutor` is a better name.

And keep consistent with StreamSort. #6085 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

# Refer to a related PR or issue link (optional)

### CODE REVIEW

**Comment by TennyZhuang** [comment]
@skyzh PTAL the changes in dashboard, I regenerated plans, but seems it's not up-to-date before the PR.

**Review by skyzh — APPROVED** [review]
Looks great. The large stub code is expected.

**Review by xxchan — APPROVED** [review]

**Comment by TennyZhuang** [comment]
> Looks great. The large stub code is expected.



> Looks great. The large stub code is expected.

Seems dashboard is broken

**Comment by skyzh** [comment]
Column property is removed some days before 😭

**Pull request merged**
