### PR TITLE
fix(kafka): the issue of not setting the group id correctly when creating KafkaSplitReader.

### PR DESCRIPTION
**Pull request by artorias1024**
Fix: the issue of not setting the group id correctly when creating KafkaSplitReader.

I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [x] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Comment by artorias1024** [comment]
@BugenZhao Please help review this PR, thank you!

**Comment by artorias1024** [comment]
@shanicky @tabVersion  Hi，Please help review this PR, thank you!  ：）

**Comment by tabVersion** [comment]
First and foremost, we truly appreciate your interest in the RisingWave community, and we are grateful for your contributions. Unfortunately, we are unable to merge your first Pull Request at this time. The primary reason is that RisingWave's Split Reader uses Kafka's low-level API for data consumption. In this level of abstraction, the concept of Consumer Group does not exist, so we have not set a `group id`. If we were to set this parameter here, it would affect the proper consumption progress tracking within RisingWave. We have reserved the `group id` in an attempt to commit consumption progress back to the Kafka Broker, but we have not yet found a suitable way to achieve this goal.
If you are interested in this topic, we would be more than happy to discuss potential solutions together.

**Comment by artorias1024** [comment]
> First and foremost, we truly appreciate your interest in the RisingWave community, and we are grateful for your contributions. Unfortunately, we are unable to merge your first Pull Request at this time. The primary reason is that RisingWave's Split Reader uses Kafka's low-level API for data consumption. In this level of abstraction, the concept of Consumer Group does not exist, so we have not set a `group id`. If we were to set this parameter here, it would affect the proper consumption progress tracking within RisingWave. We have reserved the `group id` in an attempt to commit consumption progress back to the Kafka Broker, but we have not yet found a suitable way to achieve this goal. If you are interested in this topic, we would be more than happy to discuss potential solutions together.

[https://www.risingwave.dev/docs/current/create-source-cdc/]()
I have been following the instructions in this document to use the Kafka source, and based on the previous response, I am more puzzled now: should users set the group.id?

**Comment by tabVersion** [comment]
> > First and foremost, we truly appreciate your interest in the RisingWave community, and we are grateful for your contributions. Unfortunately, we are unable to merge your first Pull Request at this time. The primary reason is that RisingWave's Split Reader uses Kafka's low-level API for data consumption. In this level of abstraction, the concept of Consumer Group does not exist, so we have not set a `group id`. If we were to set this parameter here, it would affect the proper consumption progress tracking within RisingWave. We have reserved the `group id` in an attempt to commit consumption progress back to the Kafka Broker, but we have not yet found a suitable way to achieve this goal. If you are interested in this topic, we would be more than happy to discuss potential solutions together.
> 
> https://www.risingwave.dev/docs/current/create-source-cdc/ I have been following the instructions in this document to use the Kafka source, and based on the previous response, I am more puzzled now: should users set the group.id?

sorry for your confusion, we have discussed removing `group.id` in the parameters and users should not set it.

**Pull request closed without merging**
