### PR TITLE
feat: process metric for macos

### LINKED ISSUE #5129: metrics: report correct process metrics under macOS
Currently, the process metrics, i.e., CPU and memory usage, are dummy values under macOS. Considering that most of our developers are working on a Mac and may do some small tests or benchmarks directly on the local machine, it would be better to report correct process metrics under macOS.

https://github.com/risingwavelabs/risingwave/blob/d574cf586ab5e96696a445e82d69d2323848b79b/src/common/src/monitor/process_linux.rs#L113-L137

### PR DESCRIPTION
**Pull request by tabVersion**
Signed-off-by: tabVersion <tabvision@bupt.icu>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

as title, this pr can help collect stats for current process on macos

inspired by https://github.com/robotty/simple-process-stats

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

~~- [ ] I have written necessary rustdoc comments~~
~~- [ ] I have added necessary unit tests and integration tests~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

close #5129

### CODE REVIEW

**Comment by tabVersion** [comment]
image

when I do clippy check on my M1 mac, I get the dependency warning. I don't know if it matters.

**Comment by BugenZhao** [comment]
Looks like https://github.com/robotty/simple-process-stats is cross-platform. Can we use a single library (like this) to collect metrics for all platforms? cc @Little-Wallace @skyzh

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
> Looks like https://github.com/robotty/simple-process-stats is cross-platform. Can we use a single library (like this) to collect metrics for all platforms? cc @Little-Wallace @skyzh

I'd prefer using some unified crates instead of implementing everything on our own 🤣

**Comment by BugenZhao** [comment]
> image
> 
> 
> 
> when I do clippy check on my M1 mac, I get the dependency warning. I don't know if it matters. 

Has this been resolved?

**Comment by tabVersion** [comment]
> > image
> > when I do clippy check on my M1 mac, I get the dependency warning. I don't know if it matters.
> 
> Has this been resolved?

I almost forgot the issue. Will look into this

**Comment by BugenZhao** [comment]
> > > image
> 
> > > when I do clippy check on my M1 mac, I get the dependency warning. I don't know if it matters.
> 
> > 
> 
> > Has this been resolved?
> 
> 
> 
> I almost forgot the issue. Will look into this

cc @skyzh Could you please help to take a look?

**Comment by skyzh** [comment]
You've got a typo.

```
recv = "a502be24bd0971463f5bcbfe035a248d8ba503b7"
```
should be
```
rev = "a502be24bd0971463f5bcbfe035a248d8ba503b7"
```

**Comment by skyzh** [comment]
Feel like drunk-coding 🤣

**Pull request merged**
