### PR TITLE
test: workaround a flaky source test

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?
This test becomes flaky. e.g., https://buildkite.com/risingwavelabs/pull-request/builds/63945

Probable reason: After https://github.com/risingwavelabs/risingwave/pull/19467, `CREATE SOURCE` returns earlier than before (previously, it will wait for source reader created, i.e., connection established). Now it doesn't wait for that.
See also https://github.com/risingwavelabs/risingwave/issues/19681#issuecomment-2527123971

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Review by stdrc — APPROVED** [review]

**Comment by xxchan** [comment]
still failed...

**Review by StrikeW — APPROVED** [review]
Previously I increased sleep to 6s and also add `flush` to `release-2.1`, but the main-cron for v2.1 still failed in release test. Rerun again it can pass.
Actually I didn't sure where the race condition exist, would appreciate any insight from you.

**Comment by xxchan** [comment]
sleep6s + flush can still fail

**Comment by xxchan** [comment]
In this run. it takes ~1.2s to receive msg
```
#first log
2024-12-10T09:10:08.602685725Z DEBUG risingwave_connector::source::reader::reader: spawning connector split reader for multiple splits [Kafka(KafkaSplit { topic: "test-topic-19563", partition: 1, start_offset: Some(-1), stop_offset: None })]
...
#last log
2024-12-10T09:10:09.784461512Z  INFO risingwave_connector::source::kafka::source::reader: [KAFKA] MESSAGE RECEIVED: [Ok(Message { ptr: 0x7f00b2811f78 }), Ok(Message { ptr: 0x7f00b28120b8 }), Ok(Message { ptr: 0x7f00b28121f8 }), Ok(Message { ptr: 0x7f00b2812338 }), Ok(Message { ptr: 0x7f00b2812478 })] self.splits=[KafkaSplit { topic: "test-topic-19563", partition: 3, start_offset: Some(-1), stop_offset: None }, KafkaSplit { topic: "test-topic-19563", partition: 4, start_offset: Some(-1), stop_offset: None }]
```

**Comment by xxchan** [comment]
Cannot trigger the failure any more after adding logs..

**Comment by xxchan** [comment]
Great, this time it failed 

it takes 1min14s. And no message consumed at all.
```
2024-12-10T10:10:40.638303204Z
...
2024-12-10T10:11:54.516867539Z
```

**Comment by xxchan** [comment]
Strange. We can see the state table has latest offsets, but no data emited.

**Pull request merged**
