### PR TITLE
feat(metrics): add source throughput in bytes

### PR DESCRIPTION
**Pull request by lmatz**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
Currently, we only have source throughput in `rows/s`. If there is `varchar` as one of the columns, hard to say `rows` still means anything.
This PR adds source throughput in `bytes(MB)/s`.

For the `rows/s` source throughput, we can also sum it up over all the partitions instead of using two different metrcis in the system. Not sure if it is intentional or not?

## Checklist

- [x] ~I have written necessary rustdoc comments~
- [x] ~I have added necessary unit tests and integration tests~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by lmatz** [comment]
SCR-20221226-mn2

**Comment by tabVersion** [comment]
> For the rows/s source throughput, we can also sum it up over all the partitions instead of using two different metrcis in the system. Not sure if it is intentional or not?

These two metrics are from different places, one from the source executor and another from the connector source. feel free to remove the metrics.

**Comment by lmatz** [comment]
> > For the rows/s source throughput, we can also sum it up over all the partitions instead of using two different metrcis in the system. Not sure if it is intentional or not?
> 
> These two metrics are from different places, one from the source executor and another from the connector source. feel free to remove the metrics.

thanks, I see! 

Let's remove or decide in another PR. 

The thing is that the metric of total rows has `source_name`, i.e. `Table_1001`, while if we sum the partition ones up, we will lose that name, although we can also pass the name down to the connector source.

I am not sure if anyone is depending on that `name` to do any analysis, etc?

**Comment by tabVersion** [comment]
> > > For the rows/s source throughput, we can also sum it up over all the partitions instead of using two different metrcis in the system. Not sure if it is intentional or not?
> > 
> > 
> > These two metrics are from different places, one from the source executor and another from the connector source. feel free to remove the metrics.
> 
> thanks, I see!
> 
> Let's remove or decide in another PR.
> 
> The thing is that the metric of total rows has `source_name`, i.e. `Table_1001`, while if we sum the partition ones up, we will lose that name, although we can also pass the name down to the connector source.

let's do this refactoring after #7032 is done to prevent conflicts. 
 
> I am not sure if anyone is depending on that `name` to do any analysis, etc?

The metric from the connector source is added for Orchestra, is there any dependency? @KeXiangWang

**Review by tabVersion — APPROVED** [review]
LGTM

**Pull request merged**
