### PR TITLE
ci: fix dashboard ci down by setup-protoc@v3

### PR DESCRIPTION
**Pull request by yihong0618**
This patch fix the version mismatch for setup-protoc that make ci happy.

I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This PR fix arduino/setup-protoc@v3 version is mismatch caused by #18710 by set the right version for it.

Wrong action: https://github.com/yihong0618/risingwave/actions/runs/11090307344
Right action by set it to the right version https://github.com/yihong0618/risingwave/actions/runs/11090308904/job/30812486809

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

### CODE REVIEW

**Comment by yuhao-su** [comment]
This action will not be triggered in ci unless proto files are modified. Please make sure it passes the CI.

Also out release script is using protoc 3.15.8. Please be careful if you want bump it to 23.x

**Comment by BugenZhao** [comment]
> Also out release script is using protoc 3.15.8.

Shall we use `26` instead? According to this:

https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/src/Makefile.am#L21

**Comment by yihong0618** [comment]
> > Also out release script is using protoc 3.15.8.
> 
> Shall we use `26` instead? According to this:
> 
> https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/src/Makefile.am#L21

not exactly, seems we need to set the version to latest
according to this issue: https://github.com/arduino/setup-protoc/issues/99

**Review by BugenZhao — APPROVED** [review]

**Comment by yihong0618** [comment]
> https://github.com/arduino/setup-protoc/releases/tag/v2.0.0 Start from v2.0.0, setup-protoc only supports new protobuf version schema. That's why it does work with 3.x

Thanks

**Pull request closed without merging**
