### PR TITLE
revert: chore tag user facing issues

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

This reverts commit #8053. I misunderstood the intention. 

> Otherwise, remove the checkbox above and write a release note below.

That line should be removed rather than leaving unchecked

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

### CODE REVIEW

**Review by xxchan — APPROVED** [review]

**Comment by BugenZhao** [comment]
Is it possible to get a negative match on this line?

**Comment by lmatz** [comment]
auto-tagging is great though, don't think people including myself always remember doing so

**Comment by fuyufjh** [comment]
> Is it possible to get a negative match on this line?

Not supported yet. https://github.com/srvaroa/labeler/issues/31 But I guess it won't be hard

**Comment by fuyufjh** [comment]
Oops. What a coincidence! https://github.com/srvaroa/labeler/pull/67

**Comment by srvaroa** [comment]
Hi! I noticed the reference to the issue as I was pushing a PR for this.  I will release this in a few minutes, if you want to give it a try and let me know if it works well for you that'll be very appreciated!

**Comment by fuyufjh** [comment]
> Hi! I noticed the reference to the issue as I was pushing a PR for this. I will release this in a few minutes, if you want to give it a try and let me know if it works well for you that'll be very appreciated!

Sure. Let me try it right now!

**Comment by srvaroa** [comment]
Thanks @fuyufjh, v1.3 is already released. Let me know how that goes.

**Pull request merged**
