### PR TITLE
feat(state_table): add `upsert` method for `StateTable`, and use it in managed value state

### PR DESCRIPTION
**Pull request by richardchien**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Managed value state view state table as a one-row table, it update the single row in `flush` previously with `state_table.insert`. However, two problems exist, 1) insertion is not correct in term of semantics, 2) `insert` disallows multiple insertion with the same pk within one epoch, which prevent us from insert the output into state table during `apply_chunk`.

In this PR, `upsert` method is added to solve these problems.

This is a step towards the removal of `is_dirty` and `flush`.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

#4035

### CODE REVIEW

**Review by BowenXiao1999 — APPROVED** [review]
LGTM

**Comment by BugenZhao** [comment]
Would you please give a simple benchmark of the performance degradation?

**Comment by BowenXiao1999** [comment]
> Would you please give a simple benchmark of the performance degradation?

Agreed. That will be better

**Review by st1page — COMMENTED** [review]
Maybe we should also add a upsert `RowOp` in Memtable and do not do the SANITY_CHECK in `StateTable::batch_write_rows`

**Comment by BugenZhao** [comment]
> Maybe we should also add a upsert `RowOp` in Memtable and do not do the SANITY_CHECK in `StateTable::batch_write_rows`

As the sanity check for aggregation is not enabled yet, I think we may do this later.

**Comment by richardchien** [comment]
Benchmark

Running `create materialized view mv as select count(*) as c from person group by city;` on NexMark schema, gives the following results:

**main branch**

main

**this branch**

pr

The throughput is not stable on main branch, but for average throughput, this PR faces a slight degradation.

**Comment by BugenZhao** [comment]
Based on some offline discussions, we may hold this PR for a while as the strategy introducing in #5290 will guarantee that states updated in current epoch won't be evicted.

**Comment by wcy-fdu** [comment]
Can we close this PR as https://github.com/risingwavelabs/risingwave/pull/5565 merged?

**Comment by richardchien** [comment]
As #5565, which simply adds `upsert`, has been merged, and we are doing a new refactoring on branch [sts/refactor_proto_stream_agg](https://github.com/risingwavelabs/risingwave/tree/sts/refactor_proto_stream_agg) that can remove `is_dirty` and `flush` without performance impacts, this PR can be closed.

**Pull request closed without merging**
