### PR TITLE
refactor: `Row::serialize()` does not need to return `Result`

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title:

```diff
-    pub fn serialize(&self) -> value_encoding::Result<Vec<u8>> {
+    pub fn serialize(&self) -> Vec<u8> {
```

Other changes are consequent. 😇

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

None

## Refer to a related PR or issue link (optional)

None

### CODE REVIEW

**Review by yuhao-su — APPROVED** [review]

**Review by st1page — APPROVED** [review]
LGTM

**Review by wcy-fdu — APPROVED** [review]
LGTM

**Comment by BugenZhao** [comment]
Parallel e2e timed out. 👀

**Comment by BugenZhao** [comment]
@mergifyio requeue

**Pull request merged**
